--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['gym']['talent_tree'] = {
	[1] = {
		id = 1,
		name = 'Attack',
		name_vn = 'Hướng tấn công',
		name_en = 'Attack',
		name_th = 'สายโจมตี',
		name_in = 'Jalur Serangan',
		name_ph = 'Landas ng Opensa',
		name_ma = 'Laluan Serangan'
	},
	[2] = {
		id = 2,
		name = 'Defence',
		name_vn = 'Hướng Phòng Thủ',
		name_en = 'Defence',
		name_th = 'สายป้องกัน',
		name_in = 'Jalur Pertahanan',
		name_ph = 'Landas ng Depensa',
		name_ma = 'Laluan Pertahanan'
	},
	[3] = {
		id = 3,
		name = 'Assist',
		name_vn = 'Hướng phụ trợ',
		name_en = 'Assist',
		name_th = 'สายสนับสนุน',
		name_in = 'Jalur Dukungan',
		name_ph = 'Landas ng Suporta',
		name_ma = 'Laluan Sokongan'
	},

	__size = 3,
	__default = {
		__index = {
			name = '',
			name_vn = '',
			name_en = '',
			name_th = '',
			name_in = '',
			name_ph = '',
			name_ma = '',
			desc = '',
			desc_tw = '',
			desc_en = '',
			desc_vn = '',
			desc_kr = '',
			preTreeID = {},
			prePointNum = 0
		}
	}
}
return csv.gym.talent_tree