--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {'game.dev.1'}, 
	[3] = {'game.vn.1', 'game.vn.2', 'game.vn.3'}, __size = 2}
local __data_t__servers = {
	[21001] = __predefine_t__[3],
	[102] = __predefine_t__[2],
	[6001] = __predefine_t__[2],
	[4001] = __predefine_t__[2],
	[1] = __predefine_t__[2],
	[3] = __predefine_t__[2],
	[13001] = __predefine_t__[2],
	[9] = __predefine_t__[2],
	[8] = __predefine_t__[2],
	[5001] = __predefine_t__[2],
	[30001] = __predefine_t__[2],
	[31001] = __predefine_t__[2],
	[20001] = __predefine_t__[3],
	[22001] = __predefine_t__[3],
	[101] = __predefine_t__[2],
	[32001] = __predefine_t__[2],
	[2002] = __predefine_t__[2],
	[2001] = __predefine_t__[2],
	[1102] = __predefine_t__[2],
	[1103] = __predefine_t__[2],
	[1101] = __predefine_t__[2],
	[1001] = __predefine_t__[2]
}

csv['cross']['service'] = {
	[1] = {
		id = 1,
		service = 'crosscraft',
		date = 20230403,
		servers = __data_t__servers[1],
		-- {'game.dev.1'}
		cross = 'crosscraft.dev.1'
	},
	[3] = {
		id = 3,
		service = 'crossarena',
		date = 20230403,
		servers = __data_t__servers[3],
		-- {'game.dev.1'}
		cross = 'crossarena.dev.1'
	},
	[8] = {
		id = 8,
		service = 'crossfishing',
		date = 20230403,
		servers = __data_t__servers[8],
		-- {'game.dev.1'}
		cross = 'crossfishing.dev.1'
	},
	[9] = {
		id = 9,
		service = 'skyscraper',
		date = 20250821,
		endDate = 20250830,
		servers = __data_t__servers[9],
		-- {'game.dev.1'}
		cross = 'skyscraper.dev.1'
	},
	[101] = {
		id = 101,
		service = 'crosscraft',
		date = 20250419,
		servers = __data_t__servers[101],
		-- {'game.dev.1'}
		cross = 'crosscraft.dev.1'
	},
	[102] = {
		id = 102,
		service = 'crossarena',
		date = 20250419,
		servers = __data_t__servers[102],
		-- {'game.dev.1'}
		cross = 'crossarena.dev.1'
	},
	[1001] = {
		id = 1001,
		service = 'onlinefight',
		date = 20250524,
		endDate = 20250725,
		servers = __data_t__servers[1001],
		-- {'game.dev.1'}
		cross = 'onlinefight.dev.1'
	},
	[1101] = {
		id = 1101,
		service = 'crosscraft',
		date = 20250901,
		servers = __data_t__servers[1101],
		-- {'game.dev.1'}
		cross = 'crosscraft.dev.1'
	},
	[1102] = {
		id = 1102,
		service = 'crossarena',
		date = 20250901,
		servers = __data_t__servers[1102],
		-- {'game.dev.1'}
		cross = 'crossarena.dev.1'
	},
	[1103] = {
		id = 1103,
		service = 'crossmine',
		date = 20250901,
		servers = __data_t__servers[1103],
		-- {'game.dev.1'}
		cross = 'crossmine.dev.1'
	},
	[2001] = {
		id = 2001,
		service = 'crosscraft',
		date = 20250524,
		endDate = 20250524,
		servers = __data_t__servers[2001],
		-- {'game.dev.1'}
		cross = 'crosscraft.dev.1'
	},
	[2002] = {
		id = 2002,
		service = 'crossarena',
		date = 20250524,
		endDate = 20250524,
		servers = __data_t__servers[2002],
		-- {'game.dev.1'}
		cross = 'crossarena.dev.1'
	},
	[4001] = {
		id = 4001,
		service = 'crosscraft',
		date = 20250901,
		servers = __data_t__servers[4001],
		-- {'game.dev.1'}
		cross = 'crosscraft.dev.1'
	},
	[5001] = {
		id = 5001,
		service = 'crossarena',
		date = 20250901,
		servers = __data_t__servers[5001],
		-- {'game.dev.1'}
		cross = 'crossarena.dev.1'
	},
	[6001] = {
		id = 6001,
		service = 'crossmine',
		date = 20250901,
		servers = __data_t__servers[6001],
		-- {'game.dev.1'}
		cross = 'crossmine.dev.1'
	},
	[13001] = {
		id = 13001,
		service = 'skyscraper',
		date = 20250824,
		endDate = 20250831,
		servers = __data_t__servers[13001],
		-- {'game.dev.1'}
		cross = 'skyscraper.th.1'
	},
	[20001] = {
		id = 20001,
		service = 'crosscraft',
		date = 20230203,
		servers = __data_t__servers[20001],
		-- {'game.vn.1', 'game.vn.2', 'game.vn.3'}
		cross = 'crosscraft.vn.1'
	},
	[21001] = {
		id = 21001,
		service = 'crossarena',
		date = 20230203,
		endDate = 20230303,
		servers = __data_t__servers[21001],
		-- {'game.vn.1', 'game.vn.2', 'game.vn.3'}
		cross = 'crossarena.vn.1'
	},
	[22001] = {
		id = 22001,
		service = 'crossmine',
		date = 20230203,
		servers = __data_t__servers[22001],
		-- {'game.vn.1', 'game.vn.2', 'game.vn.3'}
		cross = 'crossmine.vn.1'
	},
	[23001] = {
		id = 23001,
		service = 'skyscraper',
		date = 20230203,
		endDate = 20230210,
		servers = {'game.en.1', 'game.en.2', 'game.en.3', 'game.en.4', 'game.en.5', 'game.en.6', 'game.en.7', 'game.en.8', 'game.en.9', 'game.en.10', 'game.en.10', 'game.en.11', 'game.en.12', 'game.en.13', 'game.en.14', 'game.en.15', 'game.en.16', 'game.en.17'},
		cross = 'skyscraper.en.1'
	},
	[30001] = {
		id = 30001,
		service = 'crossarena',
		date = 20251026,
		endDate = 20251122,
		servers = __data_t__servers[30001],
		-- {'game.dev.1'}
		cross = 'crossarena.dev.1'
	},
	[31001] = {
		id = 31001,
		service = 'crosscraft',
		date = 20251026,
		servers = __data_t__servers[31001],
		-- {'game.dev.1'}
		cross = 'crosscraft.dev.1'
	},
	[32001] = {
		id = 32001,
		service = 'crossmine',
		date = 20251026,
		servers = __data_t__servers[32001],
		-- {'game.dev.1'}
		cross = 'crossmine.dev.1'
	},

	__size = 23,
	__default = {
		__index = {
			service = '',
			date = 20170120,
			endDate = 0,
			servers = {},
			cross = '',
			version = 0
		}
	}
}
return csv.cross.service