--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[4] = {[521] = 2, ['gold'] = 800000, [529] = 320, [6017] = 12, [20712] = 2, __size = 5}, __size = 1}
local __data_t__award = {
	[3] = __predefine_t__[4],
	[4] = __predefine_t__[4]
}

csv['cross']['craft']['rank'] = {
	[1] = {
		id = 1,
		rankMax = 1,
		award = {[521] = 4, ['gold'] = 1000000, [529] = 400, [6017] = 16, [20712] = 3, __size = 5}
	},
	[2] = {
		id = 2,
		rankMax = 2,
		award = {[521] = 4, ['gold'] = 900000, [529] = 360, [6017] = 14, [20712] = 2, __size = 5}
	},
	[3] = {
		id = 3,
		rankMax = 3,
		award = __data_t__award[3]
		-- {[521] = 2, ['gold'] = 800000, [529] = 320, [6017] = 12, [20712] = 2, __size = 5}
	},
	[4] = {
		id = 4,
		rankMax = 4,
		award = __data_t__award[4]
		-- {[521] = 2, ['gold'] = 800000, [529] = 320, [6017] = 12, [20712] = 2, __size = 5}
	},
	[5] = {
		id = 5,
		rankMax = 8,
		award = {[521] = 2, ['gold'] = 760000, [529] = 290, [6017] = 10, [20712] = 1, __size = 5}
	},
	[6] = {
		id = 6,
		rankMax = 16,
		award = {[6018] = 2, ['gold'] = 720000, [521] = 2, [6017] = 8, [529] = 260, __size = 5}
	},
	[7] = {
		id = 7,
		rankMax = 32,
		award = {[6018] = 4, ['gold'] = 680000, [502] = 2, [529] = 240, [6017] = 6, __size = 5}
	},
	[8] = {
		id = 8,
		rankMax = 64,
		award = {[6018] = 6, ['gold'] = 640000, [502] = 2, [529] = 220, [6017] = 4, __size = 5}
	},
	[9] = {
		id = 9,
		rankMax = 100,
		award = {[6018] = 8, ['gold'] = 600000, [529] = 200, [6017] = 2, __size = 4}
	},
	[10] = {
		id = 10,
		rankMax = 200,
		award = {[6018] = 10, ['gold'] = 560000, [529] = 190, __size = 3}
	},
	[11] = {
		id = 11,
		rankMax = 300,
		award = {[6018] = 10, ['gold'] = 520000, [529] = 180, __size = 3}
	},
	[12] = {
		id = 12,
		rankMax = 500,
		award = {[6018] = 10, ['gold'] = 480000, [529] = 170, __size = 3}
	},
	[13] = {
		id = 13,
		rankMax = 1000,
		award = {[6018] = 10, ['gold'] = 440000, [529] = 160, __size = 3}
	},
	[14] = {
		id = 14,
		rankMax = 2000,
		award = {[6018] = 10, ['gold'] = 400000, [529] = 150, __size = 3}
	},
	[15] = {
		id = 15,
		rankMax = 99999,
		award = {[6018] = 10, ['gold'] = 360000, [529] = 140, __size = 3}
	},

	__size = 15,
	__default = {
		__index = {
			award = {__size = 0},
			version = 0
		}
	}
}
return csv.cross.craft.rank