
--
-- Copyright (c) 2014 YouMi Information Technology Inc.
-- Copyright (c) 2020 TianJi Information Technology Inc.
--
return {
    "ăn cặc",
    "ăncặc",
    "ba may",
    "bà mày",
    "ba mày",
    "bàmay",
    "bamày",
    "bàmày",
    "bac_ho",
    "bamay",
    "ban_đam",
    "ban_hoa",
    "bandam",
    "banhoa",
    "bánhoa",
    "bitch",
    "bo_may",
    "bomay",
    "bon_cho",
    "bon_khon_nan",
    "boncho",
    "bonkhonnan",
    "breast",
    "bucac",
    "buoi",
    "buồi",
    "buom",
    "bướm",
    "c_san",
    "cạc",
    "cặc",
    "cai_buoi",
    "cai_chim",
    "cai_cu",
    "cai_lon",
    "caibuoi",
    "caichim",
    "caicu",
    "cailon",
    "cave",
    "chim",
    "chim_to",
    "chimto",
    "chó",
    "cho_chet",
    "cho kin ",
    "chochct",
    "chokin",
    "con_cho",
    "con_cu",
    "bac_ho",
    "Bac_ho",
    "bac_Ho",
    "Bac_Ho",
    "Bác Hồ",
    "bác Hồ",
    "Bác hồ",
    "bác hồ",
    "bÁcHồ",
    "bÁc hồ",
    "bác Hồ",
    "b4c Hồ",
    "b4c hồ",
    "b'4c Hồ",
    "b’4c hồ",
    "b4’c Hồ",
    "b4'c hồ",
    "bac ho",
    "Bac ho",
    "bacHO",
    "BacHO",
    "bitch",
    "BITCH",
    "Bitch",
    "buoi",
    "Buoi",
    "buoi'",
    "Buoi'",
    "buồi",
    "Buồi",
    "buO'i",
    "BuO'i",
    "buồi",
    "Buồi",
    "congsan",
    "cong san",
    "Cong san",
    "cong San",
    "Cong San",
    "cộng sản",
    "cộng Sản",
    "Cộng sản",
    "cong_san",
    "Congsan",
    "CongSan",
    "cuho",
    "Cuho",
    "cuHo",
    "CuHo",
    "cuhO",
    "CuhO",
    "cuHO",
    "CuHO",
    "cu_ho",
    "tổng bí thư",
    "Tổng Bí Thư",
    "tongbithu",
    "tong bi thu",
    "vietcong",
    "Vietcong",
    "dis_me",
    "disme",
    "dit",
    "dịt",
    "đít",
    "địt",
    "dit_bo",
    "dit_con_cu",
    "dit_conjne",
    "dit_concu",
    "dit_conme",
    "đit_cu",
    "ditjeu may",
    "đit_me",
    "dit_me",
    "dit_ong",
    "ditba",
    "ditbo",
    "ditme",
    "ditme",
    "ditmemay",
    "ditong",
    "dm",
    "đm",
    "doconcho",
    "dokhon",
    "drug",
    "dụ",
    "đụ",
    "du_ma",
    "dục",
    "duma",
    "dume",
    "f_u_c_k",
    "fuck",
    "gai_ban_hoa",
    "gai_diem",
    "mut cac",
    "Gaidiem",
    "ham_hiep",
    "Hamhiep",
    "hanh_kinh",
    "Hanhkinh",
    "Hiếp",
    "hiep_dam",
    "Hiepdam",
    "ho_chi_minh",
    "hồ_chí_minh",
    "ho_chiminh",
    "hochi_minh",
    "dÂm",
    "sex",
    "shit",
    "sinh_duc",
    "sinhduc",
    "slut",
    "so_lon",
    "solon",
    "su_bo_may",
    "suboraay",
    "thang_cho",
    "thangcho",
    "tien_su",
    "tiensu",
    "tinh_duc",
    "tinhduc",
    "to su",
    "tosu",
    "v_cong",
    "vai_dai",
    "vai_leu",
    "vai_lin",
    "vai_lon",
    "vaiđai",
    "vaileu",
    "vailin",
    "vai lon",
    "vcong",
    "viet_cong",
    "vietcong",
    "Yên Báĩ",
    "Đại La",
    "Cổ Loa ",
    "Vạn Xuân",
    "Thành Hồ",
    "Thanh Ho",
    "Vua Đinh",
    "Vua Lê",
    "Cổ Đô Huế",
    "lồn",
    "lỏn",
    "1ỒN",
    "lOn",
    "10 n",
    "1'On",
    "lo'n",
    "1ÒN",
    "_BacHo_",
    "_BAcHo_",
    "_Bacho_",
    "_bacHo_",
    "ho chi minh",
    "Ho Chi Minh",
    "HO cm",
    "MỊNH",
    "hiếp",
    "Hiep",
    "HffiP",
    "lo'n",
    "Lo'n",
    "lon'",
    "Lon'",
    "lồn",
    "Lồn",
    "lôn",
    "Lôn",
    "LÔN",
    "LỒN",
    "lồn",
    "Dmm",
    "Đmm",
    "DMM",
    "ĐMM",
    "Đcm",
    "ĐcM",
    "đCM",
    "đcmm",
    "dkm",
    "đkm",
    "dcm",
    "đcm",
    "dkmm",
    "đkmm",
    "đụ",
    "đự",
    "Đu",
    "ĐỤ",
    "đu.",
    "Đu.",
    "ĐU.",
    "fuck",
    "Fuck",
    "FUCK",
    "fuck",
    "F_U_C_K",
    "G4meMaster",
    "G4meM4ster",
    "G4me_Master",
    "G4me_M4ster",
    "G4me*Master",
    "G4me*M4ster",
    "GameMaster",
    "Game_Master",
    "[Game]Master",
    "Game*Master",
    "Game [Master]",
    "GM",
    "[G]M",
    "G[M]",
    "G M",
    "G*M",
    "Hồ chí minh",
    "HO chí minh",
    "hồ Chí minh",
    "ho chí Minh",
    "Hồ chí Minh",
    "hồ Chí minh",
    "hồ chí minh",
    "ad",
    "admin",
    "ca.c",
    "cAc",
    "cạc",
    "Cặc",
    "Cac.",
    "cac.",
    "cai dis",
    "cai’ dis",
    "cái dis",
    "cAi DKM",
    "cai’ loz",
    "cailoz",
    "caj dis",
    "caj djjt me",
    "caj DKM",
    "caj loz",
    "caj lozl",
    "caj...Địf",
    "cak",
    "CAMIỒN",
    "cav3",
    "cave",
    "căc",
    "cặc",
    "cặẹ",
    }