--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[6] = {1, 2, 3, 4, 5}, __size = 1}
local __data_t__natureLimit = {
	[5] = __predefine_t__[6],
	[6] = __predefine_t__[6]
}

csv['union_fight']['nature_limit'] = {
	[1] = {
		id = 1,
		weekDay = 2,
		natureLimit = {1, 2}
	},
	[2] = {
		id = 2,
		weekDay = 3,
		natureLimit = {3, 4}
	},
	[3] = {
		id = 3,
		weekDay = 4,
		natureLimit = {1, 3, 5}
	},
	[4] = {
		id = 4,
		weekDay = 5,
		natureLimit = {2, 4, 5}
	},
	[5] = {
		id = 5,
		weekDay = 6,
		natureLimit = __data_t__natureLimit[5]
		-- {1, 2, 3, 4, 5}
	},
	[6] = {
		id = 6,
		weekDay = 7,
		natureLimit = __data_t__natureLimit[6]
		-- {1, 2, 3, 4, 5}
	},
	[7] = {
		id = 7,
		weekDay = 1,
		natureLimit = {2, 3}
	},

	__size = 7,
	__default = {
		__index = {
			weekDay = 0,
			natureLimit = {}
		}
	}
}
return csv.union_fight.nature_limit