--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[2] = {'2.4%', '2.8%', '3.2%', '3.6%', '4%', '4.4%', '4.8%', '5.2%', '5.6%', '6%', '6.4%', '6.8%', '7.2%', '7.6%', '8%', '8.4%', '8.8%', '9.2%', '9.6%', '10%'}, 
	[3] = {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}, 
	[4] = {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}, 
	[5] = {250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200}, 
	[6] = {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}, 
	[7] = {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}, 
	[8] = {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}, 
	[9] = {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}, 
	[10] = {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}, 
	[11] = {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}, 
	[12] = {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}, 
	[13] = {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}, __size = 13}
local __data_t__attrNum6 = {
	[77] = __predefine_t__[10],
	[14] = __predefine_t__[6],
	[49] = __predefine_t__[10],
	[63] = __predefine_t__[10],
	[42] = __predefine_t__[8],
	[56] = __predefine_t__[10],
	[28] = __predefine_t__[6],
	[35] = __predefine_t__[8],
	["default"] = __predefine_t__[1],
	[2] = __predefine_t__[3],
	[70] = __predefine_t__[10],
	[8] = __predefine_t__[3],
	[84] = __predefine_t__[12],
	[21] = __predefine_t__[6]
}
local __data_t__attrNum4 = {
	[77] = __predefine_t__[10],
	[14] = __predefine_t__[6],
	[49] = __predefine_t__[10],
	[63] = __predefine_t__[10],
	[42] = __predefine_t__[8],
	[56] = __predefine_t__[10],
	[28] = __predefine_t__[6],
	[35] = __predefine_t__[8],
	["default"] = __predefine_t__[1],
	[2] = __predefine_t__[3],
	[70] = __predefine_t__[10],
	[8] = __predefine_t__[3],
	[84] = __predefine_t__[12],
	[21] = __predefine_t__[6]
}
local __data_t__attrNum5 = {
	[77] = __predefine_t__[10],
	[14] = __predefine_t__[6],
	[49] = __predefine_t__[10],
	[63] = __predefine_t__[10],
	[42] = __predefine_t__[8],
	[56] = __predefine_t__[10],
	[28] = __predefine_t__[6],
	[35] = __predefine_t__[8],
	["default"] = __predefine_t__[1],
	[2] = __predefine_t__[3],
	[70] = __predefine_t__[10],
	[8] = __predefine_t__[3],
	[84] = __predefine_t__[12],
	[21] = __predefine_t__[6]
}
local __data_t__attrNum2 = {
	[11] = __predefine_t__[4],
	[10] = __predefine_t__[4],
	[12] = __predefine_t__[4],
	[77] = __predefine_t__[10],
	[14] = __predefine_t__[6],
	[49] = __predefine_t__[10],
	[63] = __predefine_t__[10],
	[42] = __predefine_t__[8],
	[56] = __predefine_t__[10],
	[28] = __predefine_t__[6],
	[35] = __predefine_t__[8],
	["default"] = __predefine_t__[1],
	[2] = __predefine_t__[3],
	[7] = __predefine_t__[2],
	[70] = __predefine_t__[10],
	[9] = __predefine_t__[4],
	[8] = __predefine_t__[3],
	[84] = __predefine_t__[12],
	[21] = __predefine_t__[6]
}
local __data_t__attrNum3 = {
	[77] = __predefine_t__[10],
	[14] = __predefine_t__[6],
	[49] = __predefine_t__[10],
	[63] = __predefine_t__[10],
	[42] = __predefine_t__[8],
	[56] = __predefine_t__[10],
	[28] = __predefine_t__[6],
	[35] = __predefine_t__[8],
	["default"] = __predefine_t__[1],
	[2] = __predefine_t__[3],
	[70] = __predefine_t__[10],
	[8] = __predefine_t__[3],
	[84] = __predefine_t__[12],
	[21] = __predefine_t__[6]
}
local __data_t__attrNum1 = {
	[56] = __predefine_t__[10],
	[77] = __predefine_t__[10],
	[54] = __predefine_t__[11],
	[42] = __predefine_t__[8],
	[43] = __predefine_t__[9],
	["default"] = __predefine_t__[1],
	[61] = __predefine_t__[11],
	[88] = __predefine_t__[13],
	[63] = __predefine_t__[10],
	[64] = __predefine_t__[11],
	[49] = __predefine_t__[10],
	[66] = __predefine_t__[11],
	[67] = __predefine_t__[11],
	[68] = __predefine_t__[11],
	[80] = __predefine_t__[11],
	[81] = __predefine_t__[11],
	[86] = __predefine_t__[13],
	[53] = __predefine_t__[11],
	[84] = __predefine_t__[12],
	[85] = __predefine_t__[13],
	[24] = __predefine_t__[7],
	[25] = __predefine_t__[7],
	[26] = __predefine_t__[7],
	[27] = __predefine_t__[5],
	[20] = __predefine_t__[5],
	[21] = __predefine_t__[6],
	[22] = __predefine_t__[7],
	[23] = __predefine_t__[7],
	[46] = __predefine_t__[9],
	[47] = __predefine_t__[9],
	[44] = __predefine_t__[9],
	[45] = __predefine_t__[9],
	[28] = __predefine_t__[6],
	[29] = __predefine_t__[7],
	[40] = __predefine_t__[9],
	[87] = __predefine_t__[13],
	[1] = __predefine_t__[2],
	[82] = __predefine_t__[11],
	[3] = __predefine_t__[4],
	[2] = __predefine_t__[3],
	[5] = __predefine_t__[4],
	[4] = __predefine_t__[4],
	[7] = __predefine_t__[2],
	[6] = __predefine_t__[4],
	[9] = __predefine_t__[4],
	[8] = __predefine_t__[3],
	[78] = __predefine_t__[11],
	[51] = __predefine_t__[11],
	[89] = __predefine_t__[13],
	[39] = __predefine_t__[9],
	[60] = __predefine_t__[11],
	[65] = __predefine_t__[11],
	[75] = __predefine_t__[11],
	[38] = __predefine_t__[9],
	[73] = __predefine_t__[11],
	[72] = __predefine_t__[11],
	[71] = __predefine_t__[11],
	[70] = __predefine_t__[10],
	[59] = __predefine_t__[11],
	[79] = __predefine_t__[11],
	[58] = __predefine_t__[11],
	[11] = __predefine_t__[4],
	[10] = __predefine_t__[4],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[4],
	[15] = __predefine_t__[7],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[7],
	[16] = __predefine_t__[7],
	[19] = __predefine_t__[7],
	[18] = __predefine_t__[7],
	[31] = __predefine_t__[7],
	[30] = __predefine_t__[7],
	[37] = __predefine_t__[9],
	[36] = __predefine_t__[9],
	[35] = __predefine_t__[8],
	[52] = __predefine_t__[11],
	[33] = __predefine_t__[7],
	[74] = __predefine_t__[11],
	[32] = __predefine_t__[7],
	[57] = __predefine_t__[11],
	[90] = __predefine_t__[13],
	[50] = __predefine_t__[11]
}
local __data_t__target = {
	["default"] = __predefine_t__[1]
}

csv['explorer']['explorer_effect'] = {
	[1] = {
		id = 1,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[1],
		-- {'2.4%', '2.8%', '3.2%', '3.6%', '4%', '4.4%', '4.8%', '5.2%', '5.6%', '6%', '6.4%', '6.8%', '7.2%', '7.6%', '8%', '8.4%', '8.8%', '9.2%', '9.6%', '10%'}
		effectDesc = '#C0x5B545B##F40#All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan%s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani%s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira%s meningkat#F50##C0x5C9970#%s'
	},
	[2] = {
		id = 2,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[2],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[2],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[2],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[2],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[2],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[2],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attribute#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attribute#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkat atribut dasar#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkat atribut asas#F50##C0x5C9970#%s'
	},
	[3] = {
		id = 3,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[3],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s'
	},
	[4] = {
		id = 4,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[4],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s'
	},
	[5] = {
		id = 5,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[5],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s'
	},
	[6] = {
		id = 6,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[6],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes%s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s'
	},
	[7] = {
		id = 7,
		attrType1 = 7,
		attrNum1 = __data_t__attrNum1[7],
		-- {'2.4%', '2.8%', '3.2%', '3.6%', '4%', '4.4%', '4.8%', '5.2%', '5.6%', '6%', '6.4%', '6.8%', '7.2%', '7.6%', '8%', '8.4%', '8.8%', '9.2%', '9.6%', '10%'}
		attrType2 = 8,
		attrNum2 = __data_t__attrNum2[7],
		-- {'2.4%', '2.8%', '3.2%', '3.6%', '4%', '4.4%', '4.8%', '5.2%', '5.6%', '6%', '6.4%', '6.8%', '7.2%', '7.6%', '8%', '8.4%', '8.8%', '9.2%', '9.6%', '10%'}
		effectDesc = '#C0x5B545B##F40#All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s#C0x5B545B##F40#, %s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani%s tumaas#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s'
	},
	[8] = {
		id = 8,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[8],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[8],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[8],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[8],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[8],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[8],
		-- {'0.1%', '0.2%', '0.3%', '0.4%', '0.5%', '0.6%', '0.7%', '0.8%', '0.9%', '1%', '1.1%', '1.2%', '1.3%', '1.4%', '1.5%', '1.6%', '1.7%', '1.8%', '1.9%', '2%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attribute#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attribute#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkat atribut dasar#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkat atribut asas#F50##C0x5C9970#%s'
	},
	[9] = {
		id = 9,
		attrType1 = 7,
		attrNum1 = __data_t__attrNum1[9],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		attrType2 = 8,
		attrNum2 = __data_t__attrNum2[9],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s#C0x5B545B##F40#, %s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s'
	},
	[10] = {
		id = 10,
		attrType1 = 7,
		attrNum1 = __data_t__attrNum1[10],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		attrType2 = 8,
		attrNum2 = __data_t__attrNum2[10],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s#C0x5B545B##F40#, %s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s'
	},
	[11] = {
		id = 11,
		attrType1 = 7,
		attrNum1 = __data_t__attrNum1[11],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		attrType2 = 8,
		attrNum2 = __data_t__attrNum2[11],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s#C0x5B545B##F40#, %s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s'
	},
	[12] = {
		id = 12,
		attrType1 = 7,
		attrNum1 = __data_t__attrNum1[12],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		attrType2 = 8,
		attrNum2 = __data_t__attrNum2[12],
		-- {'1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%', '1%'}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng%s tăng#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tăng#F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes%s increase#F50##C0x5C9970#%s#C0x5B545B##F40#, %s increase#F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด%s เพิ่มขึ้น#F50##C0x5C9970#%s#C0x5B545B##F40#, %s เพิ่มขึ้น#F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani%s tumaas#F50##C0x5C9970#%s#C0x5B545B##F40#, %s tumaas#F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira%s meningkat#F50##C0x5C9970#%s#C0x5B545B##F40#, %s meningkat#F50##C0x5C9970#%s'
	},
	[13] = {
		id = 13,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[13],
		-- {250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200}
		effectDesc = '#C0x5B545B##F40#All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[14] = {
		id = 14,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[14],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[14],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[14],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[14],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[14],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[14],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkat atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkat atribut asas #F50##C0x5C9970#%s'
	},
	[15] = {
		id = 15,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[15],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[16] = {
		id = 16,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[16],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[17] = {
		id = 17,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[17],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[18] = {
		id = 18,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[18],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[19] = {
		id = 19,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[19],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[20] = {
		id = 20,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[20],
		-- {250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200}
		effectDesc = '#C0x5B545B##F40#All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[21] = {
		id = 21,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[21],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[21],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[21],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[21],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[21],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[21],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkat atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkat atribut asas #F50##C0x5C9970#%s'
	},
	[22] = {
		id = 22,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[22],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[23] = {
		id = 23,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[23],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[24] = {
		id = 24,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[24],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[25] = {
		id = 25,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[25],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[26] = {
		id = 26,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[26],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[27] = {
		id = 27,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[27],
		-- {250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200}
		effectDesc = '#C0x5B545B##F40#All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[28] = {
		id = 28,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[28],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[28],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[28],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[28],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[28],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[28],
		-- {'0.15%', '0.3%', '0.45%', '0.6%', '0.75%', '0.9%', '1.05%', '1.2%', '1.35%', '1.5%', '1.65%', '1.8%', '1.95%', '2.1%', '2.25%', '2.4%', '2.55%', '2.7%', '2.85%', '3%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkat atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkat atribut asas #F50##C0x5C9970#%s'
	},
	[29] = {
		id = 29,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[29],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[30] = {
		id = 30,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[30],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[31] = {
		id = 31,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[31],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[32] = {
		id = 32,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[32],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[33] = {
		id = 33,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[33],
		-- {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[34] = {
		id = 34,
		effectType = 2,
		skillID = 61506,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[35] = {
		id = 35,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[35],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[35],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[35],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[35],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[35],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[35],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attribute #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[36] = {
		id = 36,
		attrType1 = 17,
		attrNum1 = __data_t__attrNum1[36],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[37] = {
		id = 37,
		attrType1 = 19,
		attrNum1 = __data_t__attrNum1[37],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[38] = {
		id = 38,
		attrType1 = 33,
		attrNum1 = __data_t__attrNum1[38],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[39] = {
		id = 39,
		attrType1 = 35,
		attrNum1 = __data_t__attrNum1[39],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[40] = {
		id = 40,
		attrType1 = 16,
		attrNum1 = __data_t__attrNum1[40],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[41] = {
		id = 41,
		effectType = 2,
		skillID = 61509,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[42] = {
		id = 42,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[42],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[42],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[42],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[42],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[42],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[42],
		-- {'0.3%', '0.6%', '0.9%', '1.2%', '1.5%', '1.8%', '2.1%', '2.4%', '2.7%', '3%', '3.3%', '3.6%', '3.9%', '4.2%', '4.5%', '4.8%', '5.1%', '5.4%', '5.7%', '6%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[43] = {
		id = 43,
		attrType1 = 11,
		attrNum1 = __data_t__attrNum1[43],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[44] = {
		id = 44,
		attrType1 = 12,
		attrNum1 = __data_t__attrNum1[44],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[45] = {
		id = 45,
		attrType1 = 32,
		attrNum1 = __data_t__attrNum1[45],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[46] = {
		id = 46,
		attrType1 = 34,
		attrNum1 = __data_t__attrNum1[46],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[47] = {
		id = 47,
		attrType1 = 14,
		attrNum1 = __data_t__attrNum1[47],
		-- {300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[48] = {
		id = 48,
		effectType = 2,
		skillID = 61507,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[49] = {
		id = 49,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[49],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[49],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[49],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[49],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[49],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[49],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[50] = {
		id = 50,
		attrType1 = 93,
		attrNum1 = __data_t__attrNum1[50],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[51] = {
		id = 51,
		attrType1 = 28,
		attrNum1 = __data_t__attrNum1[51],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[52] = {
		id = 52,
		attrType1 = 25,
		attrNum1 = __data_t__attrNum1[52],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[53] = {
		id = 53,
		attrType1 = 16,
		attrNum1 = __data_t__attrNum1[53],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[54] = {
		id = 54,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[54],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[55] = {
		id = 55,
		effectType = 2,
		skillID = 61511,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[56] = {
		id = 56,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[56],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[56],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[56],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[56],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[56],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[56],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[57] = {
		id = 57,
		attrType1 = 92,
		attrNum1 = __data_t__attrNum1[57],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[58] = {
		id = 58,
		attrType1 = 15,
		attrNum1 = __data_t__attrNum1[58],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[59] = {
		id = 59,
		attrType1 = 24,
		attrNum1 = __data_t__attrNum1[59],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[60] = {
		id = 60,
		attrType1 = 14,
		attrNum1 = __data_t__attrNum1[60],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[61] = {
		id = 61,
		attrType1 = 22,
		attrNum1 = __data_t__attrNum1[61],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[62] = {
		id = 62,
		effectType = 2,
		skillID = 61521,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[63] = {
		id = 63,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[63],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[63],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[63],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[63],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[63],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[63],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มค่าพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng bayani tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[64] = {
		id = 64,
		attrType1 = 14,
		attrNum1 = __data_t__attrNum1[64],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[65] = {
		id = 65,
		attrType1 = 15,
		attrNum1 = __data_t__attrNum1[65],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[66] = {
		id = 66,
		attrType1 = 22,
		attrNum1 = __data_t__attrNum1[66],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[67] = {
		id = 67,
		attrType1 = 93,
		attrNum1 = __data_t__attrNum1[67],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[68] = {
		id = 68,
		attrType1 = 16,
		attrNum1 = __data_t__attrNum1[68],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 activation: Lahat ng bayani %s tumaas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[69] = {
		id = 69,
		effectType = 2,
		skillID = 61522,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[70] = {
		id = 70,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[70],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[70],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[70],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[70],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[70],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[70],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มคุณสมบัติพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มคุณสมบัติพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng mga bayani ay tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[71] = {
		id = 71,
		attrType1 = 16,
		attrNum1 = __data_t__attrNum1[71],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[72] = {
		id = 72,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[72],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[73] = {
		id = 73,
		attrType1 = 25,
		attrNum1 = __data_t__attrNum1[73],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[74] = {
		id = 74,
		attrType1 = 90,
		attrNum1 = __data_t__attrNum1[74],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[75] = {
		id = 75,
		attrType1 = 92,
		attrNum1 = __data_t__attrNum1[75],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[76] = {
		id = 76,
		effectType = 2,
		skillID = 61523,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[77] = {
		id = 77,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[77],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[77],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[77],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[77],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[77],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[77],
		-- {'0.6%', '1.2%', '1.8%', '2.4%', '3%', '3.6%', '4.2%', '4.8%', '5.4%', '6%', '6.9%', '7.8%', '8.7%', '9.6%', '10.5%', '11.4%', '12.3%', '13.2%', '14.1%', '15%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng mga bayani ay tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[78] = {
		id = 78,
		attrType1 = 20,
		attrNum1 = __data_t__attrNum1[78],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[79] = {
		id = 79,
		attrType1 = 21,
		attrNum1 = __data_t__attrNum1[79],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[80] = {
		id = 80,
		attrType1 = 26,
		attrNum1 = __data_t__attrNum1[80],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[81] = {
		id = 81,
		attrType1 = 28,
		attrNum1 = __data_t__attrNum1[81],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[82] = {
		id = 82,
		attrType1 = 91,
		attrNum1 = __data_t__attrNum1[82],
		-- {500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[83] = {
		id = 83,
		effectType = 2,
		skillID = 61524,
		effectDesc = '%s',
		effectDesc_vn = '%s',
		effectDesc_en = '%s',
		effectDesc_th = '%s',
		effectDesc_in = '%s',
		effectDesc_ph = '%s',
		effectDesc_ma = '%s'
	},
	[84] = {
		id = 84,
		attrType1 = 1,
		attrNum1 = __data_t__attrNum1[84],
		-- {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}
		attrType2 = 13,
		attrNum2 = __data_t__attrNum2[84],
		-- {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}
		attrType3 = 7,
		attrNum3 = __data_t__attrNum3[84],
		-- {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}
		attrType4 = 8,
		attrNum4 = __data_t__attrNum4[84],
		-- {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}
		attrType5 = 9,
		attrNum5 = __data_t__attrNum5[84],
		-- {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}
		attrType6 = 10,
		attrNum6 = __data_t__attrNum6[84],
		-- {'1%', '2%', '3%', '4%', '5%', '6%', '7%', '8%', '9%', '10%', '11%', '12%', '13%', '14%', '15%', '16%', '17%', '18%', '19%', '20%'}
		effectDesc = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#Toàn bộ anh hùng tăng thuộc tính cơ bản #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#All heroes increase basic attributes #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#ฮีโร่ทั้งหมดเพิ่มคุณสมบัติพื้นฐาน #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#Semua pahlawan meningkatkan atribut dasar #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#Lahat ng mga bayani ay tumataas ang pangunahing katangian #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#Semua wira meningkatkan atribut asas #F50##C0x5C9970#%s'
	},
	[85] = {
		id = 85,
		attrType1 = 16,
		attrNum1 = __data_t__attrNum1[85],
		-- {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}
		effectDesc = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+3 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+3 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+3 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+3 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+3 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+3 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[86] = {
		id = 86,
		attrType1 = 17,
		attrNum1 = __data_t__attrNum1[86],
		-- {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}
		effectDesc = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+6 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+6 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+6 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+6 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+6 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+6 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[87] = {
		id = 87,
		attrType1 = 20,
		attrNum1 = __data_t__attrNum1[87],
		-- {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}
		effectDesc = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+9 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+9 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+9 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+9 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+9 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+9 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[88] = {
		id = 88,
		attrType1 = 23,
		attrNum1 = __data_t__attrNum1[88],
		-- {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}
		effectDesc = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+12 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+12 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+12 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+12 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+12 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+12 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[89] = {
		id = 89,
		attrType1 = 25,
		attrNum1 = __data_t__attrNum1[89],
		-- {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}
		effectDesc = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+15 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+15 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+15 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+15 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+15 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+15 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},
	[90] = {
		id = 90,
		attrType1 = 25,
		attrNum1 = __data_t__attrNum1[90],
		-- {1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000}
		effectDesc = '#C0x5B545B##F40#+20 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_vn = '#C0x5B545B##F40#+20 kích hoạt: Toàn bộ anh hùng %s tăng #F50##C0x5C9970#%s',
		effectDesc_en = '#C0x5B545B##F40#+20 activation: All heroes %s increase #F50##C0x5C9970#%s',
		effectDesc_th = '#C0x5B545B##F40#+20 การเปิดใช้งาน: ฮีโร่ทั้งหมด %s เพิ่มขึ้น #F50##C0x5C9970#%s',
		effectDesc_in = '#C0x5B545B##F40#+20 aktivasi: Semua pahlawan %s meningkat #F50##C0x5C9970#%s',
		effectDesc_ph = '#C0x5B545B##F40#+20 pag-activate: Lahat ng mga bayani %s tumataas #F50##C0x5C9970#%s',
		effectDesc_ma = '#C0x5B545B##F40#+20 pengaktifan: Semua wira %s meningkat #F50##C0x5C9970#%s'
	},

	__size = 90,
	__default = {
		__index = {
			effectType = 1,
			target = __data_t__target["default"]	--[[ {}]],
			attrNum1 = __data_t__attrNum1["default"]	--[[ {}]],
			attrNum2 = __data_t__attrNum2["default"]	--[[ {}]],
			attrNum3 = __data_t__attrNum3["default"]	--[[ {}]],
			attrNum4 = __data_t__attrNum4["default"]	--[[ {}]],
			attrNum5 = __data_t__attrNum5["default"]	--[[ {}]],
			attrNum6 = __data_t__attrNum6["default"]	--[[ {}]]
		}
	}
}
return csv.explorer.explorer_effect