--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[2] = {[4000] = 20, __size = 1}, 
	[3] = {[4000] = 50, __size = 1}, 
	[4] = {[4000] = 105, __size = 1}, 
	[5] = {[4000] = 240, __size = 1}, 
	[7] = {[4000] = 720, __size = 1}, 
	[8] = {[4000] = 40, __size = 1}, 
	[9] = {[4000] = 100, __size = 1}, 
	[13] = {[4000] = 60, __size = 1}, 
	[16] = {[4000] = 2160, __size = 1}, 
	[17] = {[4000] = 80, __size = 1}, 
	[26] = {[4000] = 140, __size = 1}, 
	[31] = {[4000] = 180, __size = 1}, 
	[35] = {[4000] = 230, __size = 1}, 
	[40] = {[4000] = 290, __size = 1}, 
	[45] = {[4000] = 370, __size = 1}, 
	[50] = {[4000] = 460, __size = 1}, 
	[55] = {[4000] = 560, __size = 1}, 
	[60] = {[4000] = 670, __size = 1}, 
	[65] = {[4000] = 790, __size = 1}, 
	[70] = {[4000] = 940, __size = 1}, 
	[75] = {[4000] = 1090, __size = 1}, 
	[80] = {[4000] = 1240, __size = 1}, 
	[85] = {[4000] = 1390, __size = 1}, 
	[90] = {[4000] = 1540, __size = 1}, __size = 25}
local __data_t__costItemMap3 = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[9],
	[2] = __predefine_t__[3]
}
local __data_t__costItemMap2 = {
	[11] = __predefine_t__[45],
	[1] = __predefine_t__[2],
	[13] = __predefine_t__[55],
	[12] = __predefine_t__[50],
	[15] = __predefine_t__[65],
	[14] = __predefine_t__[60],
	[17] = __predefine_t__[75],
	[10] = __predefine_t__[40],
	[19] = __predefine_t__[85],
	[18] = __predefine_t__[80],
	[16] = __predefine_t__[70],
	[20] = __predefine_t__[90],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[8],
	[2] = __predefine_t__[2],
	[5] = __predefine_t__[17],
	[4] = __predefine_t__[13],
	[7] = __predefine_t__[26],
	[6] = __predefine_t__[9],
	[9] = __predefine_t__[35],
	[8] = __predefine_t__[31]
}
local __data_t__costItemMap1 = {
	[11] = __predefine_t__[45],
	[1] = __predefine_t__[2],
	[13] = __predefine_t__[55],
	[12] = __predefine_t__[50],
	[15] = __predefine_t__[65],
	[14] = __predefine_t__[60],
	[17] = __predefine_t__[75],
	[10] = __predefine_t__[40],
	[19] = __predefine_t__[85],
	[18] = __predefine_t__[80],
	[16] = __predefine_t__[70],
	[20] = __predefine_t__[90],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[8],
	[2] = __predefine_t__[2],
	[5] = __predefine_t__[17],
	[4] = __predefine_t__[13],
	[7] = __predefine_t__[26],
	[6] = __predefine_t__[9],
	[9] = __predefine_t__[35],
	[8] = __predefine_t__[31]
}
local __data_t__costItemMap6 = {
	["default"] = __predefine_t__[1],
	[2] = __predefine_t__[7],
	[4] = __predefine_t__[16]
}
local __data_t__costItemMap5 = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[5],
	[2] = __predefine_t__[5],
	[4] = __predefine_t__[7],
	[8] = __predefine_t__[16]
}
local __data_t__costItemMap4 = {
	["default"] = __predefine_t__[1],
	[1] = __predefine_t__[4],
	[2] = __predefine_t__[4]
}

csv['explorer']['explorer_advance'] = {
	[1] = {
		id = 1,
		costItemMap1 = __data_t__costItemMap1[1],
		-- {[4000] = 20, __size = 1}
		costItemMap2 = __data_t__costItemMap2[1],
		-- {[4000] = 20, __size = 1}
		costItemMap3 = __data_t__costItemMap3[1],
		-- {[4000] = 50, __size = 1}
		costItemMap4 = __data_t__costItemMap4[1],
		-- {[4000] = 105, __size = 1}
		costItemMap5 = __data_t__costItemMap5[1],
		-- {[4000] = 240, __size = 1}
		costItemMap6 = {[4000] = 360, __size = 1}
	},
	[2] = {
		id = 2,
		costItemMap1 = __data_t__costItemMap1[2],
		-- {[4000] = 20, __size = 1}
		costItemMap2 = __data_t__costItemMap2[2],
		-- {[4000] = 20, __size = 1}
		costItemMap3 = __data_t__costItemMap3[2],
		-- {[4000] = 50, __size = 1}
		costItemMap4 = __data_t__costItemMap4[2],
		-- {[4000] = 105, __size = 1}
		costItemMap5 = __data_t__costItemMap5[2],
		-- {[4000] = 240, __size = 1}
		costItemMap6 = __data_t__costItemMap6[2]
		-- {[4000] = 720, __size = 1}
	},
	[3] = {
		id = 3,
		costItemMap1 = __data_t__costItemMap1[3],
		-- {[4000] = 40, __size = 1}
		costItemMap2 = __data_t__costItemMap2[3],
		-- {[4000] = 40, __size = 1}
		costItemMap3 = __data_t__costItemMap3[3],
		-- {[4000] = 100, __size = 1}
		costItemMap4 = {[4000] = 210, __size = 1},
		costItemMap5 = {[4000] = 480, __size = 1},
		costItemMap6 = {[4000] = 1440, __size = 1}
	},
	[4] = {
		id = 4,
		costItemMap1 = __data_t__costItemMap1[4],
		-- {[4000] = 60, __size = 1}
		costItemMap2 = __data_t__costItemMap2[4],
		-- {[4000] = 60, __size = 1}
		costItemMap3 = {[4000] = 150, __size = 1},
		costItemMap4 = {[4000] = 315, __size = 1},
		costItemMap5 = __data_t__costItemMap5[4],
		-- {[4000] = 720, __size = 1}
		costItemMap6 = __data_t__costItemMap6[4]
		-- {[4000] = 2160, __size = 1}
	},
	[5] = {
		id = 5,
		costItemMap1 = __data_t__costItemMap1[5],
		-- {[4000] = 80, __size = 1}
		costItemMap2 = __data_t__costItemMap2[5],
		-- {[4000] = 80, __size = 1}
		costItemMap3 = {[4000] = 200, __size = 1},
		costItemMap4 = {[4000] = 420, __size = 1},
		costItemMap5 = {[4000] = 960, __size = 1},
		costItemMap6 = {[4000] = 2880, __size = 1}
	},
	[6] = {
		id = 6,
		costItemMap1 = __data_t__costItemMap1[6],
		-- {[4000] = 100, __size = 1}
		costItemMap2 = __data_t__costItemMap2[6],
		-- {[4000] = 100, __size = 1}
		costItemMap3 = {[4000] = 250, __size = 1},
		costItemMap4 = {[4000] = 525, __size = 1},
		costItemMap5 = {[4000] = 1200, __size = 1},
		costItemMap6 = {[4000] = 3600, __size = 1}
	},
	[7] = {
		id = 7,
		costItemMap1 = __data_t__costItemMap1[7],
		-- {[4000] = 140, __size = 1}
		costItemMap2 = __data_t__costItemMap2[7],
		-- {[4000] = 140, __size = 1}
		costItemMap3 = {[4000] = 350, __size = 1},
		costItemMap4 = {[4000] = 735, __size = 1},
		costItemMap5 = {[4000] = 1680, __size = 1},
		costItemMap6 = {[4000] = 5040, __size = 1}
	},
	[8] = {
		id = 8,
		costItemMap1 = __data_t__costItemMap1[8],
		-- {[4000] = 180, __size = 1}
		costItemMap2 = __data_t__costItemMap2[8],
		-- {[4000] = 180, __size = 1}
		costItemMap3 = {[4000] = 450, __size = 1},
		costItemMap4 = {[4000] = 945, __size = 1},
		costItemMap5 = __data_t__costItemMap5[8],
		-- {[4000] = 2160, __size = 1}
		costItemMap6 = {[4000] = 6480, __size = 1}
	},
	[9] = {
		id = 9,
		costItemMap1 = __data_t__costItemMap1[9],
		-- {[4000] = 230, __size = 1}
		costItemMap2 = __data_t__costItemMap2[9],
		-- {[4000] = 230, __size = 1}
		costItemMap3 = {[4000] = 575, __size = 1},
		costItemMap4 = {[4000] = 1215, __size = 1},
		costItemMap5 = {[4000] = 2760, __size = 1},
		costItemMap6 = {[4000] = 8280, __size = 1}
	},
	[10] = {
		id = 10,
		costItemMap1 = __data_t__costItemMap1[10],
		-- {[4000] = 290, __size = 1}
		costItemMap2 = __data_t__costItemMap2[10],
		-- {[4000] = 290, __size = 1}
		costItemMap3 = {[4000] = 725, __size = 1},
		costItemMap4 = {[4000] = 1530, __size = 1},
		costItemMap5 = {[4000] = 3480, __size = 1},
		costItemMap6 = {[4000] = 10440, __size = 1}
	},
	[11] = {
		id = 11,
		costItemMap1 = __data_t__costItemMap1[11],
		-- {[4000] = 370, __size = 1}
		costItemMap2 = __data_t__costItemMap2[11],
		-- {[4000] = 370, __size = 1}
		costItemMap3 = {[4000] = 925, __size = 1},
		costItemMap4 = {[4000] = 1950, __size = 1},
		costItemMap5 = {[4000] = 4440, __size = 1},
		costItemMap6 = {[4000] = 13320, __size = 1}
	},
	[12] = {
		id = 12,
		costItemMap1 = __data_t__costItemMap1[12],
		-- {[4000] = 460, __size = 1}
		costItemMap2 = __data_t__costItemMap2[12],
		-- {[4000] = 460, __size = 1}
		costItemMap3 = {[4000] = 1150, __size = 1},
		costItemMap4 = {[4000] = 2415, __size = 1},
		costItemMap5 = {[4000] = 5520, __size = 1},
		costItemMap6 = {[4000] = 16560, __size = 1}
	},
	[13] = {
		id = 13,
		costItemMap1 = __data_t__costItemMap1[13],
		-- {[4000] = 560, __size = 1}
		costItemMap2 = __data_t__costItemMap2[13],
		-- {[4000] = 560, __size = 1}
		costItemMap3 = {[4000] = 1400, __size = 1},
		costItemMap4 = {[4000] = 2940, __size = 1},
		costItemMap5 = {[4000] = 6720, __size = 1},
		costItemMap6 = {[4000] = 20160, __size = 1}
	},
	[14] = {
		id = 14,
		costItemMap1 = __data_t__costItemMap1[14],
		-- {[4000] = 670, __size = 1}
		costItemMap2 = __data_t__costItemMap2[14],
		-- {[4000] = 670, __size = 1}
		costItemMap3 = {[4000] = 1675, __size = 1},
		costItemMap4 = {[4000] = 3525, __size = 1},
		costItemMap5 = {[4000] = 8040, __size = 1},
		costItemMap6 = {[4000] = 24120, __size = 1}
	},
	[15] = {
		id = 15,
		costItemMap1 = __data_t__costItemMap1[15],
		-- {[4000] = 790, __size = 1}
		costItemMap2 = __data_t__costItemMap2[15],
		-- {[4000] = 790, __size = 1}
		costItemMap3 = {[4000] = 1975, __size = 1},
		costItemMap4 = {[4000] = 4155, __size = 1},
		costItemMap5 = {[4000] = 9480, __size = 1},
		costItemMap6 = {[4000] = 28440, __size = 1}
	},
	[16] = {
		id = 16,
		costItemMap1 = __data_t__costItemMap1[16],
		-- {[4000] = 940, __size = 1}
		costItemMap2 = __data_t__costItemMap2[16],
		-- {[4000] = 940, __size = 1}
		costItemMap3 = {[4000] = 2325, __size = 1},
		costItemMap4 = {[4000] = 4890, __size = 1},
		costItemMap5 = {[4000] = 11070, __size = 1},
		costItemMap6 = {[4000] = 33210, __size = 1}
	},
	[17] = {
		id = 17,
		costItemMap1 = __data_t__costItemMap1[17],
		-- {[4000] = 1090, __size = 1}
		costItemMap2 = __data_t__costItemMap2[17],
		-- {[4000] = 1090, __size = 1}
		costItemMap3 = {[4000] = 2675, __size = 1},
		costItemMap4 = {[4000] = 5625, __size = 1},
		costItemMap5 = {[4000] = 12660, __size = 1},
		costItemMap6 = {[4000] = 37980, __size = 1}
	},
	[18] = {
		id = 18,
		costItemMap1 = __data_t__costItemMap1[18],
		-- {[4000] = 1240, __size = 1}
		costItemMap2 = __data_t__costItemMap2[18],
		-- {[4000] = 1240, __size = 1}
		costItemMap3 = {[4000] = 3025, __size = 1},
		costItemMap4 = {[4000] = 6360, __size = 1},
		costItemMap5 = {[4000] = 14250, __size = 1},
		costItemMap6 = {[4000] = 42750, __size = 1}
	},
	[19] = {
		id = 19,
		costItemMap1 = __data_t__costItemMap1[19],
		-- {[4000] = 1390, __size = 1}
		costItemMap2 = __data_t__costItemMap2[19],
		-- {[4000] = 1390, __size = 1}
		costItemMap3 = {[4000] = 3375, __size = 1},
		costItemMap4 = {[4000] = 7095, __size = 1},
		costItemMap5 = {[4000] = 15840, __size = 1},
		costItemMap6 = {[4000] = 47520, __size = 1}
	},
	[20] = {
		id = 20,
		costItemMap1 = __data_t__costItemMap1[20],
		-- {[4000] = 1540, __size = 1}
		costItemMap2 = __data_t__costItemMap2[20],
		-- {[4000] = 1540, __size = 1}
		costItemMap3 = {[4000] = 3725, __size = 1},
		costItemMap4 = {[4000] = 7830, __size = 1},
		costItemMap5 = {[4000] = 17430, __size = 1},
		costItemMap6 = {[4000] = 52290, __size = 1}
	},

	__size = 20,
	__default = {
		__index = {
			costItemMap1 = __data_t__costItemMap1["default"]	--[[ {__size = 0}]],
			costItemMap2 = __data_t__costItemMap2["default"]	--[[ {__size = 0}]],
			costItemMap3 = __data_t__costItemMap3["default"]	--[[ {__size = 0}]],
			costItemMap4 = __data_t__costItemMap4["default"]	--[[ {__size = 0}]],
			costItemMap5 = __data_t__costItemMap5["default"]	--[[ {__size = 0}]],
			costItemMap6 = __data_t__costItemMap6["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.explorer.explorer_advance