//////////////////// FUNC_STRING BEGIN
#define setPvrCczKey            	lua_cocos2dx_ui_Button_setScale9Enabled__Peripheral
#define setXXTEAKeyAndSign      	lua_cocos2dx_ui_ScrollView_getScrollBarColor__Remote
#define getFileData             	lua_cocos2dx_ui_Scale9Sprite_getSprite__Union
#define getDataFromFile         	lua_cocos2dx_ui_RelativeBox_finalize__Spyware
#define getRawDataFromFile      	lua_cocos2dx_ui_EditBox_setPlaceholderFontName__Uncountable
#define isTJCompressed          	lua_cocos2dx_ui_PageView_setIndicatorSpaceBetweenIndexNodes__Location
#define tjDecompress            	lua_cocos2dx_ui_RichText_createWithXML__Overloading
#define tjzBufRead              	lua_cocos2dx_ui_Widget_getWorldPosition__Vertical
#define tjXXTEAKey              	lua_cocos2dx_ui_RichElement_equalType__Terminology
#define luaLoadBuffer           	lua_cocos2dx_ui_Text_setFontNameAndSize__Apparently
#define tjGetDataFromFile       	lua_cocos2dx_ui_EditBox_setCapInsetsDisabledRenderer__Script
#define tj_malloc               	lua_cocos2dx_ui_RichText_isAnchorTextDelEnabled__Profit
#define tj_calloc               	lua_cocos2dx_ui_TabControl_getHeaderHeight__Supercomputer
#define tj_realloc              	lua_cocos2dx_ui_RichElementImage_setWidth__Monopoly
#define tj_free                 	lua_cocos2dx_ui_Widget_clone__Formidable
#define tj_small_malloc         	lua_cocos2dx_ui_Slider_getProgressBarFile__Multiple
#define tj_small_calloc         	lua_cocos2dx_ui_EditBox_getInputFlag__Recursive
#define tj_small_realloc        	lua_cocos2dx_ui_Layout_getClippingType__Turbocharger
//////////////////// FUNC_STRING END

//////////////////// CLASS_STRING BEGIN
#define TJAllocator             	DisplayManagerNegotiation
#define TJBuddyAllocator        	GridBaseCorrelation
#define TJSmallAllocator        	EventListenerControllerExtended
#define TJFixedMem              	Grid3DActionMail
#define HierarchyDraw           	EaseBouncePreemptive
#define HierarchyDrawManager    	ActionManagerExResponse
#define HierarchySiblings       	ParallaxNodeDisguise
//////////////////// CLASS_STRING END
