--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[2] = {1, 1, 1, 1, 1, 1}, __size = 2}
local __data_t__damageFix_en = {
	["default"] = __predefine_t__[2]
}
local __data_t__defenceFix_kr = {
	["default"] = __predefine_t__[2]
}
local __data_t__defenceFix_vn = {
	["default"] = __predefine_t__[2]
}
local __data_t__defenceFix_tw = {
	["default"] = __predefine_t__[2]
}
local __data_t__storys = {
	["default"] = __predefine_t__[1]
}
local __data_t__speedFix_tw = {
	["default"] = __predefine_t__[2]
}
local __data_t__defenceFix_en = {
	["default"] = __predefine_t__[2]
}
local __data_t__speedFix = {
	["default"] = __predefine_t__[2]
}
local __data_t__hpFix_tw = {
	["default"] = __predefine_t__[2]
}
local __data_t__speedFix_en = {
	["default"] = __predefine_t__[2]
}
local __data_t__cards = {
	["default"] = __predefine_t__[1]
}
local __data_t__hpFix_vn = {
	["default"] = __predefine_t__[2]
}
local __data_t__speedFix_kr = {
	["default"] = __predefine_t__[2]
}
local __data_t__hpFix_en = {
	["default"] = __predefine_t__[2]
}
local __data_t__speedFix_vn = {
	["default"] = __predefine_t__[2]
}
local __data_t__damageFix_vn = {
	["default"] = __predefine_t__[2]
}
local __data_t__cards_en = {
	["default"] = __predefine_t__[1]
}
local __data_t__damageFix_tw = {
	["default"] = __predefine_t__[2]
}
local __data_t__cards_kr = {
	["default"] = __predefine_t__[1]
}
local __data_t__hpFix_kr = {
	["default"] = __predefine_t__[2]
}
local __data_t__damageFix_kr = {
	["default"] = __predefine_t__[2]
}
local __data_t__cards_tw = {
	["default"] = __predefine_t__[1]
}
local __data_t__cards_vn = {
	["default"] = __predefine_t__[1]
}
local __data_t__defenceFix = {
	["default"] = __predefine_t__[2]
}
local __data_t__damageFix = {
	["default"] = __predefine_t__[2]
}
local __data_t__hpFix = {
	["default"] = __predefine_t__[2]
}

csv['summer_challenge']['monsters'] = {
	[101] = {
		id = 101,
		gateID = 101
	},
	[102] = {
		id = 102,
		gateID = 101,
		sceneCount = 2
	},
	[103] = {
		id = 103,
		gateID = 101,
		sceneCount = 3
	},
	[111] = {
		id = 111,
		gateID = 102
	},
	[112] = {
		id = 112,
		gateID = 102,
		sceneCount = 2
	},
	[113] = {
		id = 113,
		gateID = 102,
		sceneCount = 3
	},
	[121] = {
		id = 121,
		gateID = 103
	},
	[122] = {
		id = 122,
		gateID = 103,
		sceneCount = 2
	},
	[123] = {
		id = 123,
		gateID = 103,
		sceneCount = 3
	},
	[131] = {
		id = 131,
		gateID = 104
	},
	[132] = {
		id = 132,
		gateID = 104,
		sceneCount = 2
	},
	[133] = {
		id = 133,
		gateID = 104,
		sceneCount = 3
	},
	[141] = {
		id = 141,
		gateID = 105
	},
	[142] = {
		id = 142,
		gateID = 105,
		sceneCount = 2
	},
	[143] = {
		id = 143,
		gateID = 105,
		sceneCount = 3
	},
	[151] = {
		id = 151,
		gateID = 106
	},
	[152] = {
		id = 152,
		gateID = 106,
		sceneCount = 2
	},
	[153] = {
		id = 153,
		gateID = 106,
		sceneCount = 3
	},
	[161] = {
		id = 161,
		gateID = 107
	},
	[162] = {
		id = 162,
		gateID = 107,
		sceneCount = 2
	},
	[163] = {
		id = 163,
		gateID = 107,
		sceneCount = 3
	},
	[171] = {
		id = 171,
		gateID = 108
	},
	[172] = {
		id = 172,
		gateID = 108,
		sceneCount = 2
	},
	[173] = {
		id = 173,
		gateID = 108,
		sceneCount = 3
	},
	[181] = {
		id = 181,
		gateID = 109
	},
	[182] = {
		id = 182,
		gateID = 109,
		sceneCount = 2
	},
	[183] = {
		id = 183,
		gateID = 109,
		sceneCount = 3
	},
	[191] = {
		id = 191,
		gateID = 110
	},
	[192] = {
		id = 192,
		gateID = 110,
		sceneCount = 2
	},
	[193] = {
		id = 193,
		gateID = 110,
		sceneCount = 3
	},
	[1001] = {
		id = 1001,
		gateID = 1001,
		storys = {{1001, 100001}, {98, 100011}}
	},
	[1011] = {
		id = 1011,
		gateID = 1011,
		storys = {{1001, 100101}, {98, 100109}}
	},
	[1021] = {
		id = 1021,
		gateID = 1021,
		storys = {{1001, 100201}, {98, 100206}}
	},
	[1031] = {
		id = 1031,
		gateID = 1031,
		storys = {{1001, 100301}, {98, 100303}}
	},
	[1041] = {
		id = 1041,
		gateID = 1041,
		storys = {{1001, 100401}, {98, 100403}}
	},
	[1051] = {
		id = 1051,
		gateID = 1051,
		storys = {{1001, 100501}, {98, 100503}, {1, 100511}, {1, 100512}, {1, 100513}, {1, 100514}, {1, 100515}, {1, 100516}}
	},
	[1061] = {
		id = 1061,
		gateID = 1061,
		storys = {{1001, 100601}, {98, 100616}}
	},
	[1071] = {
		id = 1071,
		gateID = 1071,
		storys = {{1001, 100701}, {98, 100703}}
	},
	[1081] = {
		id = 1081,
		gateID = 1081,
		storys = {{1001, 100801}, {98, 100819}}
	},
	[1091] = {
		id = 1091,
		gateID = 1091,
		storys = {{1001, 100901}, {98, 100912}}
	},

	__size = 40,
	__default = {
		__index = {
			gateID = 0,
			sceneCount = 1,
			cards = __data_t__cards["default"]	--[[ {}]],
			cards_tw = __data_t__cards_tw["default"]	--[[ {}]],
			cards_en = __data_t__cards_en["default"]	--[[ {}]],
			cards_vn = __data_t__cards_vn["default"]	--[[ {}]],
			cards_kr = __data_t__cards_kr["default"]	--[[ {}]],
			hpFix = __data_t__hpFix["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			hpFix_tw = __data_t__hpFix_tw["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			hpFix_en = __data_t__hpFix_en["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			hpFix_vn = __data_t__hpFix_vn["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			hpFix_kr = __data_t__hpFix_kr["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			damageFix = __data_t__damageFix["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			damageFix_tw = __data_t__damageFix_tw["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			damageFix_en = __data_t__damageFix_en["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			damageFix_vn = __data_t__damageFix_vn["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			damageFix_kr = __data_t__damageFix_kr["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			defenceFix = __data_t__defenceFix["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			defenceFix_tw = __data_t__defenceFix_tw["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			defenceFix_en = __data_t__defenceFix_en["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			defenceFix_vn = __data_t__defenceFix_vn["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			defenceFix_kr = __data_t__defenceFix_kr["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			speedFix = __data_t__speedFix["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			speedFix_tw = __data_t__speedFix_tw["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			speedFix_en = __data_t__speedFix_en["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			speedFix_vn = __data_t__speedFix_vn["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			speedFix_kr = __data_t__speedFix_kr["default"]	--[[ {1, 1, 1, 1, 1, 1}]],
			storys = __data_t__storys["default"]	--[[ {}]]
		}
	}
}
return csv.summer_challenge.monsters