--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['union_qa']['qa_game'] = {
	[1] = {
		id = 1,
		name = 'Vanished Spirit',
		name_vn = 'Tinh linh biến mất',
		name_en = 'Vanished Spirit',
		name_th = 'วิญญาณที่หายไป',
		name_in = 'Roh yang Menghilang',
		name_ph = 'Espiritung Nawala',
		name_ma = 'Roh yang Hilang',
		type = 1,
		weight = 100,
		desc = 'Huấn luyện viên, hãy cùng chơi một trò chơi nhé!Khi bắt đầu, sẽ có ba thẻ tinh linh xuất hiện, bạn cần ghi nhớ diện mạo của chúng. Sau đó, một nhóm tinh linh sẽ xuất hiện phía trên kèm theo hiệu ứng đặc biệt.Nhiệm vụ của bạn là tìm ra tinh linh nào KHÔNG xuất hiện trong nhóm đó.',
		desc_vn = 'Trainer, let’s play a game! At the beginning, three spirit cards will appear, and you need to remember their appearance. After that, a group of spirits will appear above with special effects. Your task is to find out which spirit did NOT appear in that group.',
		desc_en = 'Trainer, let’s play a game! At the beginning, three spirit cards will appear, and you need to remember their appearance. After that, a group of spirits will appear above with special effects. Your task is to find out which spirit did NOT appear in that group.',
		desc_th = 'เทรนเนอร์ มาร่วมเล่นเกมกันเถอะ! เมื่อเริ่มเกม จะมีการ์ดวิญญาณสามใบปรากฏขึ้น และคุณต้องจดจำรูปลักษณ์ของพวกมันให้ดี จากนั้นจะมีวิญญาณกลุ่มหนึ่งปรากฏด้านบนพร้อมเอฟเฟกต์พิเศษ หน้าที่ของคุณคือหาว่าวิญญาณตัวไหนที่ "ไม่" ปรากฏในกลุ่มนั้น',
		desc_in = 'Pelatih, ayo main permainan! Di awal, tiga kartu roh akan muncul, dan kamu harus mengingat penampilannya. Setelah itu, sekelompok roh akan muncul di atas dengan efek khusus. Tugasmu adalah menemukan roh mana yang TIDAK muncul dalam kelompok tersebut.',
		desc_ph = 'Trainer, tara’t maglaro tayo! Sa simula, tatlong card ng espiritu ang lalabas, at kailangan mong tandaan ang itsura nila. Pagkatapos, may lilitaw na grupo ng mga espiritu sa itaas na may espesyal na epekto. Ang misyon mo ay tukuyin kung aling espiritu ang HINDI lumitaw sa grupong iyon.',
		desc_ma = 'Jurulatih, mari kita main satu permainan! Pada permulaan, tiga kad roh akan muncul, dan anda perlu ingat rupa mereka. Selepas itu, sekumpulan roh akan muncul di atas dengan kesan khas. Tugas anda ialah mencari roh yang TIDAK muncul dalam kumpulan tersebut.'
	},

	__size = 1,
	__default = {
		__index = {
			name = '',
			name_vn = '',
			name_tw = '',
			name_en = '',
			name_th = '',
			name_in = '',
			name_ph = '',
			name_ma = '',
			weight = 0,
			desc = '',
			desc_vn = '',
			desc_tw = '',
			desc_en = '',
			desc_th = '',
			desc_in = '',
			desc_ph = '',
			desc_ma = ''
		}
	}
}
return csv.union_qa.qa_game