--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['random_tower']['can_jump'] = {
	[1] = {
		id = 1,
		canJump = 0
	},
	[2] = {
		id = 2,
		level = 50
	},
	[3] = {
		id = 3,
		level = 60
	},
	[4] = {
		id = 4,
		level = 70,
		canJump = 35
	},
	[5] = {
		id = 5,
		level = 80,
		canJump = 40
	},
	[6] = {
		id = 6,
		level = 90,
		canJump = 45
	},
	[7] = {
		id = 7,
		vip = 3,
		canJump = 0
	},
	[8] = {
		id = 8,
		vip = 4,
		canJump = 0
	},
	[9] = {
		id = 9,
		level = 75,
		vip = 10,
		canJump = 50
	},
	[10] = {
		id = 10,
		level = 75,
		vip = 13,
		canJump = 55
	},
	[11] = {
		id = 11,
		level = 75,
		vip = 16,
		canJump = 55
	},
	[12] = {
		id = 12,
		level = 75,
		vip = 18,
		canJump = 60
	},

	__size = 12,
	__default = {
		__index = {
			level = 1,
			vip = 0,
			canJump = 30,
			canJump_en = 30,
			canJump_kr = 30,
			canJump_tw = 30
		}
	}
}
return csv.random_tower.can_jump