<?xml version="1.0" encoding="UTF-8"?>
<data version="1.0">
    <struct type="Settings">
        <key>fileFormatVersion</key>
        <int>1</int>
        <key>variation</key>
        <string>main</string>
        <key>verbose</key>
        <false/>
        <key>autoSDSettings</key>
        <array/>
        <key>allowRotation</key>
        <false/>
        <key>quiet</key>
        <false/>
        <key>premultiplyAlpha</key>
        <true/>
        <key>shapeDebug</key>
        <false/>
        <key>dpi</key>
        <uint>72</uint>
        <key>dataFormat</key>
        <string>cocos2d</string>
        <key>textureFileName</key>
        <filename>buffs0.pvr.ccz</filename>
        <key>flipPVR</key>
        <false/>
        <key>ditherType</key>
        <enum type="SettingsBase::DitherType">Linear</enum>
        <key>backgroundColor</key>
        <uint>0</uint>
        <key>libGdx</key>
        <struct type="LibGDX">
            <key>filtering</key>
            <struct type="LibGDXFiltering">
                <key>x</key>
                <enum type="LibGDXFiltering::Filtering">Linear</enum>
                <key>y</key>
                <enum type="LibGDXFiltering::Filtering">Linear</enum>
            </struct>
        </struct>
        <key>shapePadding</key>
        <uint>2</uint>
        <key>jpgQuality</key>
        <uint>80</uint>
        <key>pngOptimizationLevel</key>
        <uint>0</uint>
        <key>textureSubPath</key>
        <string></string>
        <key>textureFormat</key>
        <enum type="SettingsBase::TextureFormat">pvr2ccz</enum>
        <key>borderPadding</key>
        <uint>2</uint>
        <key>maxTextureSize</key>
        <QSize>
            <key>width</key>
            <int>1024</int>
            <key>height</key>
            <int>1024</int>
        </QSize>
        <key>fixedTextureSize</key>
        <QSize>
            <key>width</key>
            <int>-1</int>
            <key>height</key>
            <int>-1</int>
        </QSize>
        <key>reduceBorderArtifacts</key>
        <false/>
        <key>algorithmSettings</key>
        <struct type="AlgorithmSettings">
            <key>algorithm</key>
            <enum type="AlgorithmSettings::AlgorithmId">MaxRects</enum>
            <key>freeSizeMode</key>
            <enum type="AlgorithmSettings::AlgorithmFreeSizeMode">Best</enum>
            <key>sizeConstraints</key>
            <enum type="AlgorithmSettings::SizeConstraints">AnySize</enum>
            <key>forceSquared</key>
            <false/>
            <key>forceWordAligned</key>
            <true/>
            <key>maxRects</key>
            <struct type="AlgorithmMaxRectsSettings">
                <key>heuristic</key>
                <enum type="AlgorithmMaxRectsSettings::Heuristic">Best</enum>
            </struct>
            <key>basic</key>
            <struct type="AlgorithmBasicSettings">
                <key>sortBy</key>
                <enum type="AlgorithmBasicSettings::SortBy">Best</enum>
                <key>order</key>
                <enum type="AlgorithmBasicSettings::Order">Ascending</enum>
            </struct>
        </struct>
        <key>andEngine</key>
        <struct type="AndEngine">
            <key>minFilter</key>
            <enum type="AndEngine::MinFilter">Linear</enum>
            <key>packageName</key>
            <string>Texture</string>
            <key>javaFileName</key>
            <filename>buffs0.java</filename>
            <key>wrap</key>
            <struct type="AndEngineWrap">
                <key>s</key>
                <enum type="AndEngineWrap::Wrap">Clamp</enum>
                <key>t</key>
                <enum type="AndEngineWrap::Wrap">Clamp</enum>
            </struct>
            <key>magFilter</key>
            <enum type="AndEngine::MagFilter">MagLinear</enum>
        </struct>
        <key>dataFileName</key>
        <filename>buffs0.plist</filename>
        <key>mainExtension</key>
        <string></string>
        <key>forceIdenticalLayout</key>
        <false/>
        <key>outputFormat</key>
        <enum type="SettingsBase::OutputFormat">RGBA5551</enum>
        <key>contentProtection</key>
        <struct type="ContentProtection">
            <key>key</key>
            <string></string>
        </struct>
        <key>autoAliasEnabled</key>
        <true/>
        <key>trimSpriteNames</key>
        <false/>
        <key>globalSpriteSettings</key>
        <struct type="SpriteSettings">
            <key>scale</key>
            <double>1</double>
            <key>scaleMode</key>
            <enum type="ScaleMode">Smooth</enum>
            <key>innerPadding</key>
            <uint>0</uint>
            <key>extrude</key>
            <uint>0</uint>
            <key>trimThreshold</key>
            <uint>1</uint>
            <key>trimMode</key>
            <enum type="SpriteSettings::TrimMode">Trim</enum>
            <key>heuristicMask</key>
            <false/>
        </struct>
        <key>fileList</key>
        <array>
            <filename>logo_mh2.png</filename>
            <filename>logo_ly.png</filename>
            <filename>logo_ldhy.png</filename>
            <filename>logo_ldfx.png</filename>
            <filename>logo_jdc.png</filename>
            <filename>logo_cd.png</filename>
            <filename>logo_zy.png</filename>
            <filename>logo_rh1.png</filename>
            <filename>logo_gmys.png</filename>
            <filename>logo_gnhw.png</filename>
            <filename>logo_yjqc.png</filename>
            <filename>logo_ryzt.png</filename>
            <filename>logo_ryzs.png</filename>
            <filename>logo_rhzx.png</filename>
            <filename>logo_ll.png</filename>
            <filename>logo_hyms.png</filename>
            <filename>logo_ddfy.png</filename>
            <filename>logo_jgzd.png</filename>
            <filename>logo_gtsp.png</filename>
            <filename>logo_mm.png</filename>
            <filename>icon_zhdjs3.png</filename>
            <filename>icon_zhdjs2.png</filename>
            <filename>icon_zhdjs1.png</filename>
            <filename>icon_xxz.png</filename>
            <filename>icon_swyj.png</filename>
            <filename>icon_sbshts.png</filename>
            <filename>icon_sb.png</filename>
            <filename>icon_ptzt.png</filename>
            <filename>icon_dxz.png</filename>
            <filename>logo_zzzd3.png</filename>
            <filename>logo_zzzd2.png</filename>
            <filename>logo_zzzd1.png</filename>
            <filename>logo_sjll2.png</filename>
            <filename>logo_sjll1.png</filename>
            <filename>logo_sjky.png</filename>
            <filename>logo_sjbd2.png</filename>
            <filename>logo_sjbd1.png</filename>
            <filename>logo_yzwl.png</filename>
            <filename>logo_tkmj.png</filename>
            <filename>logo_snzf.png</filename>
            <filename>logo_wjsl.png</filename>
            <filename>logo_smzz.png</filename>
            <filename>logo_swlj.png</filename>
            <filename>logo_phzj.png</filename>
            <filename>logo_zjwj.png</filename>
            <filename>logo_xglq.png</filename>
            <filename>logo_wzbh.png</filename>
            <filename>logo_tw.png</filename>
            <filename>logo_xyx.png</filename>
            <filename>logo_xy1.png</filename>
            <filename>logo_xlswjh.png</filename>
            <filename>logo_xls.png</filename>
            <filename>logo_qyzs.png</filename>
            <filename>logo_fd.png</filename>
            <filename>logo_ls2.png</filename>
            <filename>logo_jy.png</filename>
            <filename>logo_xh.png</filename>
            <filename>logo_jd.png</filename>
            <filename>logo_hbhd.png</filename>
            <filename>box_selected.png</filename>
            <filename>logo_te.png</filename>
            <filename>logo_cxy.png</filename>
            <filename>logo_zdh.png</filename>
            <filename>logo_fdh.png</filename>
            <filename>logo_qyzs1.png</filename>
            <filename>logo_sd.png</filename>
            <filename>logo_cpms.png</filename>
            <filename>logo_xd1.png</filename>
            <filename>logo_gl.png</filename>
            <filename>logo_mz_down.png</filename>
            <filename>logo_xzge.png</filename>
            <filename>logo_tkzh.png</filename>
            <filename>logo_hszz.png</filename>
            <filename>logo_ymgh.png</filename>
            <filename>logo_gy.png</filename>
            <filename>logo_zzyj.png</filename>
            <filename>logo_zz1.png</filename>
            <filename>logo_zz.png</filename>
            <filename>logo_zsqdtg.png</filename>
            <filename>logo_zs.png</filename>
            <filename>logo_zm1.png</filename>
            <filename>logo_zm.png</filename>
            <filename>logo_zlxg_up.png</filename>
            <filename>logo_zll_up.png</filename>
            <filename>logo_ze.png</filename>
            <filename>logo_zd.png</filename>
            <filename>logo_ys.png</filename>
            <filename>logo_yn.png</filename>
            <filename>logo_yh.png</filename>
            <filename>logo_xy.png</filename>
            <filename>logo_xx.png</filename>
            <filename>logo_xd.png</filename>
            <filename>logo_wsmy.png</filename>
            <filename>logo_ws.png</filename>
            <filename>logo_wg_up.png</filename>
            <filename>logo_wg_down.png</filename>
            <filename>logo_wf_up.png</filename>
            <filename>logo_wf_down.png</filename>
            <filename>logo_tx.png</filename>
            <filename>logo_tsmy.png</filename>
            <filename>logo_tl.png</filename>
            <filename>logo_tg_up.png</filename>
            <filename>logo_tg_down.png</filename>
            <filename>logo_tf_up.png</filename>
            <filename>logo_tf_down.png</filename>
            <filename>logo_sxys.png</filename>
            <filename>logo_smsx_up.png</filename>
            <filename>logo_smsx_down.png</filename>
            <filename>logo_smsh.png</filename>
            <filename>logo_sm1.png</filename>
            <filename>logo_sm.png</filename>
            <filename>logo_sl.png</filename>
            <filename>logo_shjm_up.png</filename>
            <filename>logo_shjm_down.png</filename>
            <filename>logo_shjc_up.png</filename>
            <filename>logo_shjc_down.png</filename>
            <filename>logo_sh.png</filename>
            <filename>logo_sf.png</filename>
            <filename>logo_sd_up.png</filename>
            <filename>logo_sd_down.png</filename>
            <filename>logo_rh.png</filename>
            <filename>logo_pdy_up.png</filename>
            <filename>logo_pdy_down.png</filename>
            <filename>logo_ny.png</filename>
            <filename>logo_nqsxtg.png</filename>
            <filename>logo_nqsxjd.png</filename>
            <filename>logo_nqhf_up.png</filename>
            <filename>logo_nqhf_down.png</filename>
            <filename>logo_mysh.png</filename>
            <filename>logo_my.png</filename>
            <filename>logo_mht.png</filename>
            <filename>logo_mh.png</filename>
            <filename>logo_mb.png</filename>
            <filename>logo_lx1.png</filename>
            <filename>logo_lx.png</filename>
            <filename>logo_ls.png</filename>
            <filename>logo_llbshd.png</filename>
            <filename>logo_kzmy.png</filename>
            <filename>logo_kj.png</filename>
            <filename>logo_jszz.png</filename>
            <filename>logo_jl2.png</filename>
            <filename>logo_jl1.png</filename>
            <filename>logo_hxys.png</filename>
            <filename>logo_hnsh.png</filename>
            <filename>logo_hl2.png</filename>
            <filename>logo_hl.png</filename>
            <filename>logo_hh.png</filename>
            <filename>logo_hd.png</filename>
            <filename>logo_hbxj.png</filename>
            <filename>logo_gd.png</filename>
            <filename>logo_fs.png</filename>
            <filename>logo_fn.png</filename>
            <filename>logo_dyqd_up.png</filename>
            <filename>logo_dyqd_down.png</filename>
            <filename>logo_dyl_up.png</filename>
            <filename>logo_dyl_down.png</filename>
            <filename>logo_dxys.png</filename>
            <filename>logo_cxzl.png</filename>
            <filename>logo_cxhfnq.png</filename>
            <filename>logo_cs.png</filename>
            <filename>logo_cr.png</filename>
            <filename>logo_cm.png</filename>
            <filename>logo_cf1.png</filename>
            <filename>logo_cf.png</filename>
            <filename>logo_bz.png</filename>
            <filename>logo_bxys.png</filename>
            <filename>logo_bssh_up.png</filename>
            <filename>logo_bssh_down.png</filename>
            <filename>logo_bskx_up.png</filename>
            <filename>logo_bskx_down.png</filename>
            <filename>logo_bq.png</filename>
            <filename>logo_bn.png</filename>
            <filename>logo_bjsh_up.png</filename>
            <filename>logo_bjsh_down.png</filename>
            <filename>logo_bjl_up.png</filename>
            <filename>logo_bjl_down.png</filename>
            <filename>logo_bjkx_up.png</filename>
            <filename>logo_bjkx_down.png</filename>
            <filename>logo_bfx.png</filename>
            <filename>logo_bdqdtg.png</filename>
            <filename>logo_bd.png</filename>
            <filename>logo_jl.png</filename>
            <filename>logo_jf1.png</filename>
            <filename>logo_jf.png</filename>
            <filename>logo_shsz.png</filename>
            <filename>logo_mkl.png</filename>
            <filename>logo_nlfs.png</filename>
            <filename>logo_slhz.png</filename>
            <filename>logo_yj.png</filename>
            <filename>logo_yl.png</filename>
            <filename>logo_ch.png</filename>
            <filename>logo_bz1.png</filename>
            <filename>logo_sgdj.png</filename>
            <filename>logo_xb.png</filename>
            <filename>logo_df.png</filename>
            <filename>icon_lsg.png</filename>
            <filename>icon_zlg.png</filename>
            <filename>icon_lyzl.png</filename>
            <filename>icon_mzg.png</filename>
            <filename>icon_ccg.png</filename>
            <filename>logo_sd1.png</filename>
            <filename>logo_szll.png</filename>
            <filename>logo_hxcf.png</filename>
            <filename>logo_zy2.png</filename>
            <filename>logo_zh.png</filename>
            <filename>logo_xianx.png</filename>
            <filename>logo_jidu.png</filename>
            <filename>logo_huax.png</filename>
            <filename>logo_yqw.png</filename>
            <filename>logo_huans.png</filename>
            <filename>logo_haipa.png</filename>
            <filename>icon_jc.png</filename>
            <filename>icon_qy1.png</filename>
            <filename>icon_qy2.png</filename>
            <filename>logo_msdxd.png</filename>
            <filename>logo_zsxd.png</filename>
            <filename>logo_srm.png</filename>
            <filename>logo_spp.png</filename>
            <filename>logo_rdy.png</filename>
            <filename>logo_rdyq.png</filename>
            <filename>logo_sh1.png</filename>
            <filename>logo_lx2.png</filename>
            <filename>logo_sg.png</filename>
            <filename>logo_jw.png</filename>
            <filename>logo_zdh2.png</filename>
            <filename>logo_fdh2.png</filename>
            <filename>logo_yz.png</filename>
            <filename>icon_yqtc.png</filename>
            <filename>logo_hyzl.png</filename>
            <filename>logo_sl2.png</filename>
            <filename>logo_ylht.png</filename>
            <filename>logo_ym.png</filename>
            <filename>logo_jbzl.png</filename>
            <filename>logo_lb.png</filename>
            <filename>logo_sslj2.png</filename>
            <filename>logo_sslj1.png</filename>
            <filename>logo_syfs.png</filename>
            <filename>logo_my2.png</filename>
            <filename>logo_sslj3.png</filename>
            <filename>logo_xrzt.png</filename>
            <filename>logo_mh3.png</filename>
            <filename>logo_lyk.png</filename>
            <filename>logo_dq.png</filename>
            <filename>logo_zyjz.png</filename>
            <filename>logo_jx.png</filename>
            <filename>logo_tcdk.png</filename>
            <filename>logo_pz.png</filename>
            <filename>logo_gjydzz.png</filename>
            <filename>logo_glzz.png</filename>
            <filename>logo_hx.png</filename>
            <filename>logo_jsymzz.png</filename>
            <filename>logo_qr.png</filename>
            <filename>logo_ylzhzz.png</filename>
            <filename>logo_kn.png</filename>
            <filename>logo_bl.png</filename>
            <filename>logo_tb.png</filename>
            <filename>logo_hm.png</filename>
            <filename>logo_sx.png</filename>
            <filename>logo_zqnw.png</filename>
            <filename>logo_zqnl.png</filename>
            <filename>logo_zqdl.png</filename>
            <filename>logo_zf.png</filename>
            <filename>logo_ssxshts.png</filename>
            <filename>logo_rlyj.png</filename>
            <filename>logo_hsxshts.png</filename>
            <filename>logo_lwsxts.png</filename>
            <filename>logo_rygd.png</filename>
            <filename>logo_ryfb.png</filename>
            <filename>logo_sk.png</filename>
            <filename>logo_sbbpl.png</filename>
            <filename>logo_sbb.png</filename>
            <filename>logo_byzs.png</filename>
            <filename>logo_rmy.png</filename>
            <filename>logo_yh2.png</filename>
            <filename>logo_bd1.png</filename>
            <filename>logo_guyue.png</filename>
            <filename>logo_manyue.png</filename>
            <filename>logo_myzt.png</filename>
            <filename>logo_shangxian.png</filename>
            <filename>logo_xiaxian.png</filename>
            <filename>logo_xinyue.png</filename>
            <filename>logo_ylyj.png</filename>
            <filename>logo_yueyin.png</filename>
            <filename>logo_hh2.png</filename>
            <filename>logo_ymhh.png</filename>
            <filename>logo_mh4.png</filename>
            <filename>logo_cy.png</filename>
            <filename>logo_tl1.png</filename>
            <filename>logo_sm2.png</filename>
            <filename>logo_bh.png</filename>
            <filename>icon_yayf.png</filename>
            <filename>logo_yc.png</filename>
            <filename>logo_eyzz.png</filename>
            <filename>logo_bx.png</filename>
            <filename>logo_yd.png</filename>
            <filename>logo_ym1.png</filename>
            <filename>logo_jscz.png</filename>
            <filename>logo_sjds.png</filename>
            <filename>logo_panxuan.png</filename>
            <filename>logo_fengshi.png</filename>
            <filename>logo_gtyz.png</filename>
            <filename>logo_sj.png</filename>
            <filename>logo_gj.png</filename>
            <filename>logo_zslj.png</filename>
            <filename>logo_xzd.png</filename>
            <filename>logo_zsfy.png</filename>
            <filename>logo_zhongzhao.png</filename>
            <filename>logo_duiqi.png</filename>
            <filename>logo_zhenya.png</filename>
            <filename>logo_bt.png</filename>
            <filename>logo_bzzt.png</filename>
            <filename>logo_cj.png</filename>
            <filename>logo_fkjs.png</filename>
            <filename>logo_sb.png</filename>
            <filename>logo_xwyk.png</filename>
            <filename>icon_jinfu.png</filename>
            <filename>icon_shiheng.png</filename>
            <filename>icon_wudi.png</filename>
            <filename>icon_yinghua.png</filename>
            <filename>logo_duoqu.png</filename>
            <filename>logo_guangneng.png</filename>
            <filename>box_commandeer.png</filename>
            <filename>icon_gy.png</filename>
            <filename>icon_ltzl.png</filename>
            <filename>logo_jd1.png</filename>
            <filename>icon_sbfh.png</filename>
            <filename>icon_caiying.png</filename>
            <filename>logo_ghpp.png</filename>
            <filename>logo_bx1.png</filename>
            <filename>logo_xxsys.png</filename>
            <filename>logo_xxhys.png</filename>
            <filename>logo_xxdys1.png</filename>
            <filename>logo_xxdys.png</filename>
            <filename>logo_xxctgx.png</filename>
            <filename>logo_xxbys.png</filename>
            <filename>icon_zhenshe.png</filename>
            <filename>logo_jjwy.png</filename>
            <filename>logo_jjxj.png</filename>
            <filename>logo_qingxin.png</filename>
            <filename>logo_flm.png</filename>
            <filename>logo_czh.png</filename>
            <filename>logo_czw.png</filename>
            <filename>icon_hysd.png</filename>
            <filename>icon_hznl.png</filename>
            <filename>icon_nm.png</filename>
            <filename>icon_df.png</filename>
            <filename>icon_zqd.png</filename>
            <filename>icon_czn.png</filename>
            <filename>logo_zmpz.png</filename>
            <filename>logo_wuwo.png</filename>
            <filename>logo_smpz.png</filename>
            <filename>logo_judun.png</filename>
            <filename>logo_cmpz.png</filename>
            <filename>logo_zhouyuan.png</filename>
            <filename>logo_xu.png</filename>
            <filename>logo_wei.png</filename>
            <filename>icon_xg2.png</filename>
            <filename>icon_xg1.png</filename>
            <filename>icon_gjdy.png</filename>
        </array>
        <key>ignoreFileList</key>
        <array/>
        <key>replaceList</key>
        <array/>
        <key>ignoredWarnings</key>
        <array/>
        <key>commonDivisorX</key>
        <uint>1</uint>
        <key>commonDivisorY</key>
        <uint>1</uint>
    </struct>
</data>
