--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {['rmb'] = 1000, __size = 1}, 
	[3] = {['gold'] = 500000, __size = 1}, 
	[5] = {['gold'] = 2000000, __size = 1}, 
	[6] = {['gold'] = 3000000, __size = 1}, 
	[7] = {['gold'] = 5000000, __size = 1}, 
	[8] = {['gold'] = 1000000, __size = 1}, 
	[9] = {['gold'] = 8000000, __size = 1}, 
	[11] = {['gold'] = 12000000, __size = 1}, 
	[16] = {['rmb'] = 5000, __size = 1}, __size = 9}
local __data_t__totalVal = {
	[116] = __predefine_t__[2],
	[113] = __predefine_t__[2],
	[51] = __predefine_t__[2],
	[60] = __predefine_t__[5],
	[61] = __predefine_t__[6],
	[62] = __predefine_t__[6],
	[63] = __predefine_t__[7],
	[64] = __predefine_t__[7],
	[65] = __predefine_t__[9],
	[66] = __predefine_t__[11],
	[112] = __predefine_t__[2],
	[118] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[7],
	[26] = __predefine_t__[7],
	[27] = __predefine_t__[9],
	[20] = __predefine_t__[2],
	[21] = __predefine_t__[8],
	[22] = __predefine_t__[5],
	[23] = __predefine_t__[6],
	[29] = __predefine_t__[11],
	[40] = __predefine_t__[2],
	[41] = __predefine_t__[2],
	[1] = __predefine_t__[2],
	[2] = __predefine_t__[3],
	[5] = __predefine_t__[6],
	[4] = __predefine_t__[5],
	[7] = __predefine_t__[7],
	[6] = __predefine_t__[7],
	[9] = __predefine_t__[2],
	[8] = __predefine_t__[2],
	[105] = __predefine_t__[2],
	[117] = __predefine_t__[2],
	[39] = __predefine_t__[2],
	[108] = __predefine_t__[2],
	[38] = __predefine_t__[2],
	[241] = __predefine_t__[2],
	[242] = __predefine_t__[2],
	[102] = __predefine_t__[2],
	[103] = __predefine_t__[2],
	[115] = __predefine_t__[2],
	[101] = __predefine_t__[2],
	[106] = __predefine_t__[2],
	[107] = __predefine_t__[2],
	[104] = __predefine_t__[2],
	[58] = __predefine_t__[16],
	[11] = __predefine_t__[2],
	[10] = __predefine_t__[2],
	[13] = __predefine_t__[2],
	[12] = __predefine_t__[2],
	[15] = __predefine_t__[2],
	[14] = __predefine_t__[2],
	[17] = __predefine_t__[2],
	[16] = __predefine_t__[2],
	[19] = __predefine_t__[2],
	[18] = __predefine_t__[2],
	[31] = __predefine_t__[3],
	[56] = __predefine_t__[16],
	[37] = __predefine_t__[2],
	[36] = __predefine_t__[2],
	[35] = __predefine_t__[7],
	[34] = __predefine_t__[6],
	[33] = __predefine_t__[5],
	[55] = __predefine_t__[16],
	[109] = __predefine_t__[2],
	[32] = __predefine_t__[8],
	[114] = __predefine_t__[2],
	[111] = __predefine_t__[2],
	[57] = __predefine_t__[16],
	[110] = __predefine_t__[2]
}

csv['union']['red_packet'] = {
	[1] = {
		id = 1,
		name = 'การแข่งขันสนามประลองจบลงและได้รับชัยชนะ',
		showType = 2,
		sortVal = 30,
		totalVal = __data_t__totalVal[1],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 44,
		tipText = 'ต้องการอันดับที่ 1 ในการแข่งขันสนามประลอง'
	},
	[2] = {
		id = 2,
		name = 'การไต่ระดับพลังถึง 50,000',
		sortVal = 14,
		totalVal = __data_t__totalVal[2],
		-- {['gold'] = 500000, __size = 1}
		conditionType = 97,
		conditionNum = 50000,
		tipText = 'ต้องการพลังต่อสู้ถึง 50,000'
	},
	[3] = {
		id = 3,
		name = 'การไต่ระดับพลังถึง 100,000',
		sortVal = 15,
		totalVal = {['gold'] = 750000, __size = 1},
		conditionType = 97,
		conditionNum = 100000,
		tipText = 'ต้องการพลังต่อสู้ถึง 100,000'
	},
	[4] = {
		id = 4,
		name = 'การไต่ระดับพลังถึง 300,000',
		sortVal = 16,
		totalVal = __data_t__totalVal[4],
		-- {['gold'] = 2000000, __size = 1}
		conditionType = 97,
		conditionNum = 300000,
		tipText = 'ต้องการพลังต่อสู้ถึง 300,000'
	},
	[5] = {
		id = 5,
		name = 'การไต่ระดับพลังถึง 500,000',
		sortVal = 17,
		totalVal = __data_t__totalVal[5],
		-- {['gold'] = 3000000, __size = 1}
		conditionType = 97,
		conditionNum = 500000,
		tipText = 'ต้องการพลังต่อสู้ถึง 500,000'
	},
	[6] = {
		id = 6,
		name = 'การไต่ระดับพลังถึง 7,500,000',
		sortVal = 18,
		totalVal = __data_t__totalVal[6],
		-- {['gold'] = 5000000, __size = 1}
		conditionType = 97,
		conditionNum = 750000,
		tipText = 'ต้องการพลังต่อสู้ถึง 7,500,000'
	},
	[7] = {
		id = 7,
		name = 'การไต่ระดับพลังถึง 1,000,000',
		sortVal = 19,
		totalVal = __data_t__totalVal[7],
		-- {['gold'] = 5000000, __size = 1}
		conditionType = 97,
		conditionNum = 1000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 1,000,000'
	},
	[8] = {
		id = 8,
		name = 'การไต่ระดับพลังถึง 2,000,000',
		sortVal = 20,
		totalVal = __data_t__totalVal[8],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 2000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 2,000,000'
	},
	[9] = {
		id = 9,
		name = 'การไต่ระดับพลังถึง 3,000,000',
		sortVal = 21,
		totalVal = __data_t__totalVal[9],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 3000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 3,000,000'
	},
	[10] = {
		id = 10,
		name = 'การไต่ระดับพลังถึง 4,000,000',
		sortVal = 22,
		totalVal = __data_t__totalVal[10],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 4000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 4,000,000'
	},
	[11] = {
		id = 11,
		name = 'การไต่ระดับพลังถึง 5,000,000',
		sortVal = 23,
		totalVal = __data_t__totalVal[11],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 5000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 5,000,000'
	},
	[12] = {
		id = 12,
		name = 'การไต่ระดับพลังถึง 6,000,000',
		sortVal = 24,
		totalVal = __data_t__totalVal[12],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 6000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 6,000,000'
	},
	[13] = {
		id = 13,
		name = 'การไต่ระดับพลังถึง 8,000,000',
		sortVal = 25,
		totalVal = __data_t__totalVal[13],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 8000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 8,000,000'
	},
	[14] = {
		id = 14,
		name = 'การไต่ระดับพลังถึง 10,000,000',
		sortVal = 26,
		totalVal = __data_t__totalVal[14],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 10000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 10,000,000'
	},
	[15] = {
		id = 15,
		name = 'การไต่ระดับพลังถึง 12,000,000',
		sortVal = 27,
		totalVal = __data_t__totalVal[15],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 12000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 12,000,000'
	},
	[16] = {
		id = 16,
		name = 'การไต่ระดับพลังถึง 14,000,000',
		sortVal = 28,
		totalVal = __data_t__totalVal[16],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 14000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 14,000,000'
	},
	[17] = {
		id = 17,
		name = 'การไต่ระดับพลังถึง 16,000,000',
		sortVal = 29,
		totalVal = __data_t__totalVal[17],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 16000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 16,000,000'
	},
	[18] = {
		id = 18,
		name = 'การไต่ระดับพลังถึง 18,000,000',
		sortVal = 30,
		totalVal = __data_t__totalVal[18],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 18000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 18,000,000'
	},
	[19] = {
		id = 19,
		name = 'การไต่ระดับพลังถึง 20,000,000',
		sortVal = 31,
		totalVal = __data_t__totalVal[19],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 20000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 20,000,000'
	},
	[20] = {
		id = 20,
		name = 'การไต่ระดับพลังถึง 22,000,000',
		sortVal = 32,
		totalVal = __data_t__totalVal[20],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 22000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 22,000,000'
	},
	[21] = {
		id = 21,
		name = 'ระดับทีมถึง 60',
		sortVal = 8,
		totalVal = __data_t__totalVal[21],
		-- {['gold'] = 1000000, __size = 1}
		conditionNum = 60,
		tipText = 'ต้องการระดับทีมถึง 60'
	},
	[22] = {
		id = 22,
		name = 'ระดับทีมถึง 70',
		sortVal = 9,
		totalVal = __data_t__totalVal[22],
		-- {['gold'] = 2000000, __size = 1}
		conditionNum = 70,
		tipText = 'ต้องการระดับทีมถึง 70'
	},
	[23] = {
		id = 23,
		name = 'ระดับทีมถึง 80',
		sortVal = 10,
		totalVal = __data_t__totalVal[23],
		-- {['gold'] = 3000000, __size = 1}
		conditionNum = 80,
		tipText = 'ต้องการระดับทีมถึง 80'
	},
	[24] = {
		id = 24,
		name = 'ระดับทีมถึง 90',
		sortVal = 11,
		totalVal = __data_t__totalVal[24],
		-- {['gold'] = 3000000, __size = 1}
		conditionNum = 90,
		tipText = 'ต้องการระดับทีมถึง 90'
	},
	[25] = {
		id = 25,
		name = 'ระดับทีมถึง 100',
		sortVal = 12,
		totalVal = __data_t__totalVal[25],
		-- {['gold'] = 5000000, __size = 1}
		conditionNum = 100,
		tipText = 'ต้องการระดับทีมถึง 100'
	},
	[26] = {
		id = 26,
		name = 'ระดับทีมถึง 110',
		sortVal = 13,
		totalVal = __data_t__totalVal[26],
		-- {['gold'] = 5000000, __size = 1}
		conditionNum = 110,
		tipText = 'ต้องการระดับทีมถึง 110'
	},
	[27] = {
		id = 27,
		name = 'ระดับทีมถึง 120',
		sortVal = 14,
		totalVal = __data_t__totalVal[27],
		-- {['gold'] = 8000000, __size = 1}
		conditionNum = 120,
		tipText = 'ต้องการระดับทีมถึง 120'
	},
	[28] = {
		id = 28,
		name = 'ระดับทีมถึง 130',
		sortVal = 15,
		totalVal = {['gold'] = 10000000, __size = 1},
		conditionNum = 130,
		tipText = 'ต้องการระดับทีมถึง 130'
	},
	[29] = {
		id = 29,
		name = 'ระดับทีมถึง 140',
		sortVal = 16,
		totalVal = __data_t__totalVal[29],
		-- {['gold'] = 12000000, __size = 1}
		conditionNum = 140,
		tipText = 'ต้องการระดับทีมถึง 140'
	},
	[31] = {
		id = 31,
		name = 'จบดันเจี้ยนหลัก 1-6',
		sortVal = 1,
		totalVal = __data_t__totalVal[31],
		-- {['gold'] = 500000, __size = 1}
		conditionType = 2,
		conditionNum = 10105,
		goto = '10105'
	},
	[32] = {
		id = 32,
		name = 'จบดันเจี้ยนหลัก 3-8',
		sortVal = 2,
		totalVal = __data_t__totalVal[32],
		-- {['gold'] = 1000000, __size = 1}
		conditionType = 2,
		conditionNum = 10308,
		goto = '10308'
	},
	[33] = {
		id = 33,
		name = 'จบดันเจี้ยนหลัก 5-10',
		sortVal = 3,
		totalVal = __data_t__totalVal[33],
		-- {['gold'] = 2000000, __size = 1}
		conditionType = 2,
		conditionNum = 10510,
		goto = '10510'
	},
	[34] = {
		id = 34,
		name = 'จบดันเจี้ยนหลัก 7-10',
		sortVal = 4,
		totalVal = __data_t__totalVal[34],
		-- {['gold'] = 3000000, __size = 1}
		conditionType = 2,
		conditionNum = 10710,
		goto = '10710'
	},
	[35] = {
		id = 35,
		name = 'จบดันเจี้ยนหลัก 9-10',
		sortVal = 5,
		totalVal = __data_t__totalVal[35],
		-- {['gold'] = 5000000, __size = 1}
		conditionType = 2,
		conditionNum = 10910,
		goto = '10910'
	},
	[36] = {
		id = 36,
		name = 'จบดันเจี้ยนหลัก 11-10',
		sortVal = 6,
		totalVal = __data_t__totalVal[36],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 11110,
		goto = '11110'
	},
	[37] = {
		id = 37,
		name = 'จบดันเจี้ยนหลัก 13-10',
		sortVal = 7,
		totalVal = __data_t__totalVal[37],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 11310,
		goto = '11310'
	},
	[38] = {
		id = 38,
		name = 'จบดันเจี้ยนหลัก 15-10',
		sortVal = 7,
		totalVal = __data_t__totalVal[38],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 11510,
		goto = '11510'
	},
	[39] = {
		id = 39,
		name = 'จบดันเจี้ยนหลัก 17-10',
		sortVal = 7,
		totalVal = __data_t__totalVal[39],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 11710,
		goto = '11710'
	},
	[40] = {
		id = 40,
		name = 'จบดันเจี้ยนหลัก 19-10',
		sortVal = 7,
		totalVal = __data_t__totalVal[40],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 11910,
		goto = '11910'
	},
	[41] = {
		id = 41,
		name = 'เติมเงินวันนี้ 328 บาท',
		type = 3,
		showType = 2,
		sortVal = 0,
		totalVal = __data_t__totalVal[41],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 22,
		conditionNum = 3280,
		goto = 'recharge'
	},
	[42] = {
		id = 42,
		name = 'เติมเงินวันนี้ 648 บาท',
		type = 3,
		showType = 2,
		sortVal = 0,
		totalVal = {['rmb'] = 1500, __size = 1},
		conditionType = 22,
		conditionNum = 6480,
		goto = 'recharge'
	},
	[51] = {
		id = 51,
		name = 'ระดับ VIP ถึง 20',
		showType = 2,
		sortVal = 0,
		totalVal = __data_t__totalVal[51],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 5,
		conditionNum = 20,
		goto = 'recharge'
	},
	[52] = {
		id = 52,
		name = 'ระดับ VIP ถึง 21',
		showType = 2,
		sortVal = 0,
		totalVal = {['rmb'] = 2000, __size = 1},
		conditionType = 5,
		conditionNum = 21,
		goto = 'recharge'
	},
	[53] = {
		id = 53,
		name = 'ระดับ VIP ถึง 22',
		showType = 2,
		sortVal = 0,
		totalVal = {['rmb'] = 3000, __size = 1},
		conditionType = 5,
		conditionNum = 22,
		goto = 'recharge'
	},
	[54] = {
		id = 54,
		name = 'ระดับ VIP ถึง 23',
		showType = 2,
		sortVal = 0,
		totalVal = {['rmb'] = 4000, __size = 1},
		conditionType = 5,
		conditionNum = 23,
		goto = 'recharge'
	},
	[55] = {
		id = 55,
		name = 'ระดับ VIP ถึง 24',
		showType = 2,
		sortVal = 0,
		totalVal = __data_t__totalVal[55],
		-- {['rmb'] = 5000, __size = 1}
		conditionType = 5,
		conditionNum = 24,
		goto = 'recharge'
	},
	[56] = {
		id = 56,
		name = 'ระดับ VIP ถึง 25',
		showType = 2,
		sortVal = 0,
		totalVal = __data_t__totalVal[56],
		-- {['rmb'] = 5000, __size = 1}
		conditionType = 5,
		conditionNum = 25,
		goto = 'recharge'
	},
	[57] = {
		id = 57,
		name = 'ระดับ VIP ถึง 26',
		showType = 2,
		sortVal = 0,
		totalVal = __data_t__totalVal[57],
		-- {['rmb'] = 5000, __size = 1}
		conditionType = 5,
		conditionNum = 26,
		goto = 'recharge'
	},
	[58] = {
		id = 58,
		name = 'ระดับ VIP ถึง 27',
		showType = 2,
		sortVal = 0,
		totalVal = __data_t__totalVal[58],
		-- {['rmb'] = 5000, __size = 1}
		conditionType = 5,
		conditionNum = 27,
		goto = 'recharge'
	},
	[60] = {
		id = 60,
		name = 'จบดันเจี้ยนฝันร้าย 3-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[60],
		-- {['gold'] = 2000000, __size = 1}
		conditionType = 2,
		conditionNum = 30301,
		goto = '30301'
	},
	[61] = {
		id = 61,
		name = 'จบดันเจี้ยนฝันร้าย 6-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[61],
		-- {['gold'] = 3000000, __size = 1}
		conditionType = 2,
		conditionNum = 30601,
		goto = '30601'
	},
	[62] = {
		id = 62,
		name = 'จบดันเจี้ยนฝันร้าย 9-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[62],
		-- {['gold'] = 3000000, __size = 1}
		conditionType = 2,
		conditionNum = 30901,
		goto = '30901'
	},
	[63] = {
		id = 63,
		name = 'จบดันเจี้ยนฝันร้าย 12-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[63],
		-- {['gold'] = 5000000, __size = 1}
		conditionType = 2,
		conditionNum = 31201,
		goto = '31201'
	},
	[64] = {
		id = 64,
		name = 'จบดันเจี้ยนฝันร้าย 15-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[64],
		-- {['gold'] = 5000000, __size = 1}
		conditionType = 2,
		conditionNum = 31501,
		goto = '31501'
	},
	[65] = {
		id = 65,
		name = 'จบดันเจี้ยนฝันร้าย 18-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[65],
		-- {['gold'] = 8000000, __size = 1}
		conditionType = 2,
		conditionNum = 31801,
		goto = '31801'
	},
	[66] = {
		id = 66,
		name = 'จบดันเจี้ยนฝันร้าย 21-1',
		sortVal = 1,
		totalVal = __data_t__totalVal[66],
		-- {['gold'] = 12000000, __size = 1}
		conditionType = 2,
		conditionNum = 32101,
		goto = '32101'
	},
	[67] = {
		id = 67,
		name = 'จบดันเจี้ยนฝันร้าย 22-1',
		sortVal = 1,
		totalVal = {['gold'] = 16000000, __size = 1},
		conditionType = 2,
		conditionNum = 32201,
		goto = '32201'
	},
	[101] = {
		id = 101,
		name = 'การไต่ระดับพลังถึง 24,000,000',
		sortVal = 33,
		totalVal = __data_t__totalVal[101],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 24000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 24,000,000'
	},
	[102] = {
		id = 102,
		name = 'การไต่ระดับพลังถึง 26,000,000',
		sortVal = 34,
		totalVal = __data_t__totalVal[102],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 26000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 26,000,000'
	},
	[103] = {
		id = 103,
		name = 'การไต่ระดับพลังถึง 28,000,000',
		sortVal = 35,
		totalVal = __data_t__totalVal[103],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 28000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 28,000,000'
	},
	[104] = {
		id = 104,
		name = 'การไต่ระดับพลังถึง 30,000,000',
		sortVal = 36,
		totalVal = __data_t__totalVal[104],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 30000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 30,000,000'
	},
	[105] = {
		id = 105,
		name = 'การไต่ระดับพลังถึง 35,000,000',
		sortVal = 37,
		totalVal = __data_t__totalVal[105],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 35000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 35,000,000'
	},
	[106] = {
		id = 106,
		name = 'การไต่ระดับพลังถึง 40,000,000',
		sortVal = 38,
		totalVal = __data_t__totalVal[106],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 40000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 40,000,000'
	},
	[107] = {
		id = 107,
		name = 'การไต่ระดับพลังถึง 45,000,000',
		sortVal = 39,
		totalVal = __data_t__totalVal[107],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 45000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 45,000,000'
	},
	[108] = {
		id = 108,
		name = 'การไต่ระดับพลังถึง 50,000,000',
		sortVal = 40,
		totalVal = __data_t__totalVal[108],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 50000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 50,000,000'
	},
	[109] = {
		id = 109,
		name = 'การไต่ระดับพลังถึง 55,000,000',
		sortVal = 41,
		totalVal = __data_t__totalVal[109],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 55000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 55,000,000'
	},
	[110] = {
		id = 110,
		name = 'การไต่ระดับพลังถึง 60,000,000',
		sortVal = 42,
		totalVal = __data_t__totalVal[110],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 60000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 60,000,000'
	},
	[111] = {
		id = 111,
		name = 'การไต่ระดับพลังถึง 65,000,000',
		sortVal = 43,
		totalVal = __data_t__totalVal[111],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 65000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 65,000,000'
	},
	[112] = {
		id = 112,
		name = 'การไต่ระดับพลังถึง 70,000,000',
		sortVal = 44,
		totalVal = __data_t__totalVal[112],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 70000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 70,000,000'
	},
	[113] = {
		id = 113,
		name = 'การไต่ระดับพลังถึง 75,000,000',
		sortVal = 45,
		totalVal = __data_t__totalVal[113],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 75000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 75,000,000'
	},
	[114] = {
		id = 114,
		name = 'การไต่ระดับพลังถึง 80,000,000',
		sortVal = 46,
		totalVal = __data_t__totalVal[114],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 80000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 80,000,000'
	},
	[115] = {
		id = 115,
		name = 'การไต่ระดับพลังถึง 85,000,000',
		sortVal = 47,
		totalVal = __data_t__totalVal[115],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 85000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 85,000,000'
	},
	[116] = {
		id = 116,
		name = 'การไต่ระดับพลังถึง 90,000,000',
		sortVal = 48,
		totalVal = __data_t__totalVal[116],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 90000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 90,000,000'
	},
	[117] = {
		id = 117,
		name = 'การไต่ระดับพลังถึง 95,000,000',
		sortVal = 49,
		totalVal = __data_t__totalVal[117],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 95000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 95,000,000'
	},
	[118] = {
		id = 118,
		name = 'การไต่ระดับพลังถึง 100,000,000',
		sortVal = 50,
		totalVal = __data_t__totalVal[118],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 97,
		conditionNum = 100000000,
		tipText = 'ต้องการพลังต่อสู้ถึง 100,000,000'
	},
	[241] = {
		id = 241,
		name = 'จบดันเจี้ยนหลัก 21-10',
		sortVal = 7,
		totalVal = __data_t__totalVal[241],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 12110,
		goto = '12110'
	},
	[242] = {
		id = 242,
		name = 'จบดันเจี้ยนหลัก 22-10',
		sortVal = 7,
		totalVal = __data_t__totalVal[242],
		-- {['rmb'] = 1000, __size = 1}
		conditionType = 2,
		conditionNum = 12210,
		goto = '12210'
	},

	__size = 77,
	__default = {
		__index = {
			name = '',
			type = 1,
			showType = 1,
			totalCount = 10,
			totalVal = {['gold'] = 60000, __size = 1},
			date = 7,
			conditionType = 1,
			conditionNum = 1,
			tipText = ''
		}
	}
}
return csv.union.red_packet