--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['union']['union_skill'] = {
	[1] = {
		id = 1,
		name = 'พลังชีวิตต้นกำเนิด',
		icon = 'common/icon/union_skill/icon_sm.png'
	},
	[2] = {
		id = 2,
		name = 'ฝึกฝนพลังโจมตีกายภาพ',
		icon = 'common/icon/union_skill/icon_bs.png',
		sort = 2,
		attrType = 7
	},
	[3] = {
		id = 3,
		name = 'ฝึกฝนพลังโจมตีพิเศษ',
		icon = 'common/icon/union_skill/icon_bj.png',
		sort = 3,
		attrType = 8
	},
	[4] = {
		id = 4,
		name = 'เพิ่มพลังป้องกันกายภาพ',
		icon = 'common/icon/union_skill/icon_wf.png',
		sort = 4,
		attrType = 9
	},
	[5] = {
		id = 5,
		name = 'เพิ่มพลังป้องกันพิเศษ',
		icon = 'common/icon/union_skill/icon_tf.png',
		sort = 5,
		attrType = 10
	},
	[6] = {
		id = 6,
		name = 'ฝึกฝนสมรรถภาพ',
		icon = 'common/icon/union_skill/icon_sm.png',
		sort = 6,
		preSkill = {1, 10},
		needGuildLv = 6
	},
	[7] = {
		id = 7,
		name = 'หล่อหลอมพลังโจมตี',
		icon = 'common/icon/union_skill/icon_bs.png',
		sort = 7,
		preSkill = {2, 10},
		needGuildLv = 6,
		attrType = 7
	},
	[8] = {
		id = 8,
		name = 'ขัดเกลาจิตใจ',
		icon = 'common/icon/union_skill/icon_bj.png',
		sort = 8,
		preSkill = {3, 10},
		needGuildLv = 6,
		attrType = 8
	},
	[9] = {
		id = 9,
		name = 'ออกกำลังกายเสริมร่างกาย',
		icon = 'common/icon/union_skill/icon_wf.png',
		sort = 9,
		preSkill = {4, 10},
		needGuildLv = 6,
		attrType = 9
	},
	[10] = {
		id = 10,
		name = 'ฝึกจิตวิญญาณ',
		icon = 'common/icon/union_skill/icon_tf.png',
		sort = 10,
		preSkill = {5, 10},
		needGuildLv = 6,
		attrType = 10
	},
	[11] = {
		id = 11,
		name = 'ฝึกฝนการต้านทาน',
		icon = 'common/icon/union_skill/icon_tg.png',
		sort = 11,
		needGuildLv = 8,
		attrType = 17
	},
	[12] = {
		id = 12,
		name = 'เสริมความแข็งแกร่งในการต้านทาน',
		icon = 'common/icon/union_skill/icon_tg.png',
		sort = 12,
		needGuildLv = 8,
		attrType = 19
	},
	[13] = {
		id = 13,
		name = 'พัฒนาประสิทธิภาพการฟื้นฟู',
		icon = 'common/icon/union_skill/icon_sm.png',
		sort = 14,
		needGuildLv = 8,
		attrType = 28
	},
	[14] = {
		id = 14,
		name = 'เพิ่มพลังคริติคอล',
		icon = 'common/icon/union_skill/icon_wg.png',
		sort = 15,
		needGuildLv = 8,
		attrType = 14
	},
	[15] = {
		id = 15,
		name = 'เสริมความแรงของคริติคอล',
		icon = 'common/icon/union_skill/icon_wg.png',
		sort = 16,
		needGuildLv = 8,
		attrType = 15
	},
	[16] = {
		id = 16,
		name = 'เสริมต้านทานคริติคอล',
		icon = 'common/icon/union_skill/icon_tf.png',
		sort = 17,
		needGuildLv = 8,
		attrType = 16
	},
	[17] = {
		id = 17,
		name = 'ทำลายการต้านทาน',
		icon = 'common/icon/union_skill/icon_bs.png',
		sort = 13,
		needGuildLv = 8,
		attrType = 18
	},

	__size = 17,
	__default = {
		__index = {
			name = '',
			icon = 'config/item/icon_bsdmz.png',
			sort = 1,
			preSkill = {},
			needGuildLv = 0,
			attrNatureType = 0,
			attrType = 1
		}
	}
}
return csv.union.union_skill