--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[9] = {['flip'] = true, __size = 1}, 
	[13] = {['height'] = 4, ['width'] = 6, __size = 2}, 
	[20] = {['right'] = true, ['flip'] = true, __size = 2}, 
	[21] = {['height'] = 2, ['width'] = 4, __size = 2}, 
	[24] = {['left'] = true, ['flip'] = true, __size = 2}, 
	[25] = {['height'] = 2, ['width'] = 2, __size = 2}, 
	[28] = {['height'] = 5, ['width'] = 3, __size = 2}, 
	[36] = {['height'] = 2, ['width'] = 1, __size = 2}, 
	[50] = {['y'] = 20, ['x'] = -40, __size = 2}, 
	[53] = {['height'] = 1, ['width'] = 3, __size = 2}, __size = 10}
local __data_t__size = {
	[75004] = __predefine_t__[25],
	[75001] = __predefine_t__[53],
	[76002] = __predefine_t__[13],
	[75002] = __predefine_t__[53],
	[75501] = __predefine_t__[25],
	[75503] = __predefine_t__[36],
	[75504] = __predefine_t__[36],
	[74003] = __predefine_t__[25],
	[77003] = __predefine_t__[36],
	[72501] = __predefine_t__[36],
	[71501] = __predefine_t__[21],
	[71502] = __predefine_t__[25],
	[72001] = __predefine_t__[28],
	[72002] = __predefine_t__[28],
	[70502] = __predefine_t__[13],
	[74001] = __predefine_t__[21]
}
local __data_t__attr = {
	[76501] = __predefine_t__[9],
	[76502] = __predefine_t__[9],
	[72501] = __predefine_t__[24],
	[74002] = __predefine_t__[9],
	[74003] = __predefine_t__[9],
	[74001] = __predefine_t__[24],
	[76001] = __predefine_t__[9],
	[76002] = __predefine_t__[9],
	[70503] = __predefine_t__[9],
	[70502] = __predefine_t__[9],
	[70501] = __predefine_t__[9],
	[75501] = __predefine_t__[9],
	[75502] = __predefine_t__[9],
	[75503] = __predefine_t__[9],
	[75504] = __predefine_t__[9],
	[74503] = __predefine_t__[9],
	[74502] = __predefine_t__[9],
	[74501] = __predefine_t__[9],
	[75004] = __predefine_t__[9],
	[75001] = __predefine_t__[9],
	[75003] = __predefine_t__[9],
	[75002] = __predefine_t__[9],
	[71501] = __predefine_t__[20],
	[71502] = __predefine_t__[24],
	[72001] = __predefine_t__[20],
	[72002] = __predefine_t__[20],
	[72003] = __predefine_t__[24]
}
local __data_t__startPos = {
	[74502] = __predefine_t__[50],
	[75504] = __predefine_t__[50]
}

csv['town']['home_furniture'] = {
	[70001] = {
		id = 70001,
		name = '湖蓝格子',
		name_tw = '湖藍格子',
		name_en = 'Lake Blue Plaid',
		name_vn = 'Hồ sọc xanh',
		name_kr = '푸른 칸',
		desc = '平日里最稀松平常的样式，充满了生活气息',
		desc_tw = '平日里最稀松平常的样式，充满了生活气息',
		desc_vn = 'Phong cách thường ngày nhất. tràn đầy hơi thở cuộc sống',
		type = 101,
		stackMax = 1,
		series = 101,
		icon = 'config/item/furniture/icon_diban.png',
		res = 'city/town/furniture/floor70001.tmx',
		attr = {['maxNum'] = 30, ['maxScale'] = 0.9, ['minScale'] = 0.4, ['k'] = 0.5, __size = 4},
		size = {['y'] = 6, ['wallHeight'] = 5, ['x'] = 6, ['height'] = 18, ['width'] = 18, __size = 5}
	},
	[70501] = {
		id = 70501,
		name = '简约格子-蓝',
		name_vn = 'Lưới đơn giản - màu xanh',
		desc = '以静谧而清新的蓝色为主调，棉麻的材料给地毯带来柔软的触感',
		desc_vn = 'Với tông màu xanh trầm lắng và tươi mát làm chủ đạo. chất liệu cotton và linen mang đến nét mềm mại cho tấm thảm',
		series = 102,
		icon = 'config/item/furniture/icon_ditan.png',
		res = 'city/town/furniture/img_ditan.png',
		attr = __data_t__attr[70501],
		-- {['flip'] = true, __size = 1}
		size = {['height'] = 4, ['width'] = 5, __size = 2},
		touchSize = {{1, 121}, {200, 220}, {434, 101}, {241, 2}},
		startPos = {['y'] = 0, ['x'] = -480, __size = 2}
	},
	[70502] = {
		id = 70502,
		name = '简约格子-白',
		name_vn = 'Lưới đơn giản - trắng',
		desc = '以简单的纯白色为主调，棉麻的材料给地毯带来柔软的触感',
		desc_vn = 'Với tông màu trắng tinh khôi đơn giản làm chủ đạo. chất liệu cotton và linen mang lại nét mềm mại cho tấm thảm',
		series = 104,
		icon = 'config/item/furniture/icon_ditan2.png',
		res = 'city/town/furniture/img_ditan2.png',
		attr = __data_t__attr[70502],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[70502],
		-- {['height'] = 4, ['width'] = 6, __size = 2}
		touchSize = {{0, 110}, {222, 1}, {366, 76}, {145, 183}},
		startPos = {['y'] = 16, ['x'] = -447, __size = 2}
	},
	[70503] = {
		id = 70503,
		name = '精灵球地毯',
		name_vn = 'Thảm bóng chọc',
		desc = '是一张圆形地毯，样式和训练家们用的精灵球一模一样',
		desc_vn = 'Đó là một tấm thảm hình tròn. kiểu dáng giống hệt như những quả bóng Ninja mà các Nhẫn Giả sử dụng',
		icon = 'config/item/furniture/icon_ditan1.png',
		res = 'city/town/furniture/img_ditan1.png',
		attr = __data_t__attr[70503],
		-- {['flip'] = true, __size = 1}
		size = {['height'] = 4, ['width'] = 4, __size = 2},
		touchSize = {{118, 112}, {4, 73}, {43, 14}, {189, 15}, {214, 78}},
		startPos = {['y'] = 48, ['x'] = -225, __size = 2}
	},
	[71001] = {
		id = 71001,
		name = '湖蓝墙纸',
		name_tw = '湖藍牆紙',
		name_vn = 'Hình nền hồ xanh',
		name_kr = '푸른 벽지',
		desc = '平日里最稀松平常的样式，充满了生活气息',
		desc_tw = '平日里最稀松平常的样式，充满了生活气息',
		desc_vn = 'Phong cách thường ngày nhất. tràn đầy hơi thở cuộc sống',
		type = 201,
		stackMax = 1,
		series = 102,
		icon = 'config/item/furniture/icon_qiangzhi.png',
		res = 'city/town/furniture/wall71001.tmx',
		size = {['height'] = 5, ['width'] = 12, __size = 2}
	},
	[71501] = {
		id = 71501,
		name = '碗碟放置柜',
		name_vn = 'Tủ đựng bát đĩa',
		desc = '采用壁挂的方式，更方便拿取，也节省了空间',
		desc_vn = 'Phương pháp treo tường thuận tiện hơn để lấy và tiết kiệm không gian',
		type = 202,
		series = 108,
		icon = 'config/item/furniture/icon_chugui2.png',
		res = 'city/town/furniture/img_chugui2.png',
		attr = __data_t__attr[71501],
		-- {['right'] = true, ['flip'] = true, __size = 2}
		size = __data_t__size[71501],
		-- {['height'] = 2, ['width'] = 4, __size = 2}
		touchSize = {{5, 68}, {0, 114}, {42, 128}, {158, 91}, {182, 51}, {164, 4}},
		startPos = {['y'] = 0, ['x'] = -385, __size = 2}
	},
	[71502] = {
		id = 71502,
		name = '杂物壁挂柜',
		name_vn = 'Tủ âm tường đựng đồ lặt vặt',
		desc = '小小的柜子，可是能容纳不少东西的',
		desc_vn = 'Tủ nhỏ nhưng đựng được rất nhiều đồ',
		type = 202,
		series = 108,
		icon = 'config/item/furniture/icon_chugui3.png',
		res = 'city/town/furniture/img_chugui3.png',
		attr = __data_t__attr[71502],
		-- {['left'] = true, ['flip'] = true, __size = 2}
		size = __data_t__size[71502],
		-- {['height'] = 2, ['width'] = 2, __size = 2}
		touchSize = {{0, 57}, {3, 10}, {65, 9}, {97, 28}, {96, 73}, {66, 86}},
		startPos = {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[72001] = {
		id = 72001,
		name = '阳光窗台',
		name_vn = 'Bậu cửa sổ đầy nắng',
		desc = '皮卡丘表示很喜欢站在这里晒太阳',
		desc_vn = 'Pikachu nói rằng nó thích đứng đây và tắm nắng',
		type = 203,
		series = 107,
		icon = 'config/item/furniture/icon_chuanghu1.png',
		res = 'city/town/furniture/img_chuanghu1.png',
		attr = __data_t__attr[72001],
		-- {['right'] = true, ['flip'] = true, __size = 2}
		size = __data_t__size[72001],
		-- {['height'] = 5, ['width'] = 3, __size = 2}
		touchSize = {{0, 50}, {108, 7}, {114, 178}, {2, 232}},
		startPos = {['y'] = 12, ['x'] = -240, __size = 2}
	},
	[72002] = {
		id = 72002,
		name = '铁质大门',
		name_vn = 'cổng sắt',
		desc = '非常厚实的铁质大门，门上还用了精灵贴纸进行装饰',
		desc_vn = 'Một cánh cổng sắt rất dày được trang trí bằng hình dán yêu tinh',
		type = 203,
		icon = 'config/item/furniture/icon_damen.png',
		res = 'city/town/furniture/img_damen.png',
		attr = __data_t__attr[72002],
		-- {['right'] = true, ['flip'] = true, __size = 2}
		size = __data_t__size[72002],
		-- {['height'] = 5, ['width'] = 3, __size = 2}
		touchSize = {{4, 43}, {86, 3}, {87, 180}, {24, 216}, {0, 200}},
		startPos = {['y'] = 17, ['x'] = -222, __size = 2}
	},
	[72003] = {
		id = 72003,
		name = '木质窗户',
		name_vn = 'Cửa sổ bằng gỗ',
		desc = '一扇小窗户，不带窗帘的设计可以使阳光更好的透进小屋内',
		desc_vn = 'Một ô cửa sổ nhỏ. được thiết kế không có rèm che để ánh nắng xuyên vào cabin tốt hơn',
		type = 203,
		series = 104,
		icon = 'config/item/furniture/icon_chuanghu.png',
		res = 'city/town/furniture/img_chuanghu.png',
		attr = __data_t__attr[72003],
		-- {['left'] = true, ['flip'] = true, __size = 2}
		size = {['height'] = 3, ['width'] = 2, __size = 2},
		touchSize = {{5, 4}, {2, 100}, {30, 131}, {55, 120}, {57, 30}},
		startPos = {['y'] = 18, ['x'] = 20, __size = 2}
	},
	[72501] = {
		id = 72501,
		name = '手绘小智挂像',
		name_vn = 'Tượng treo Xiaozhi vẽ tay',
		desc = '这可能是小智实现梦想之后笑容满面的样子吧',
		desc_vn = 'Đây có thể là khuôn mặt tươi cười của Xiaozhi sau khi thực hiện được ước mơ của mình',
		type = 204,
		series = 101,
		icon = 'config/item/furniture/icon_xiangkuang.png',
		res = 'city/town/furniture/img_xiangkuang.png',
		attr = __data_t__attr[72501],
		-- {['left'] = true, ['flip'] = true, __size = 2}
		size = __data_t__size[72501],
		-- {['height'] = 2, ['width'] = 1, __size = 2}
		touchSize = {{25, 8}, {1, 6}, {1, 52}, {23, 50}},
		startPos = {['y'] = 40, ['x'] = -13, __size = 2}
	},
	[74001] = {
		id = 74001,
		name = '聚餐长桌',
		name_vn = 'Bàn ăn dài',
		desc = '是一张很长长长的餐桌，可以容纳你的所有好友',
		desc_vn = 'Đó là một bàn ăn rất dài có thể chứa tất cả bạn bè của bạn',
		type = 301,
		series = 102,
		icon = 'config/item/furniture/icon_zhuozi.png',
		res = 'city/town/furniture/img_zhuozi.png',
		attr = __data_t__attr[74001],
		-- {['left'] = true, ['flip'] = true, __size = 2}
		size = __data_t__size[74001],
		-- {['height'] = 2, ['width'] = 4, __size = 2}
		touchSize = {{168, 9}, {187, 81}, {121, 130}, {34, 139}, {2, 67}, {112, 10}},
		startPos = {['y'] = 25, ['x'] = -280, __size = 2}
	},
	[74002] = {
		id = 74002,
		name = '实木茶几',
		name_vn = 'Bàn cà phê gỗ nguyên khối',
		desc = '款式非常大气，适合大区域的小屋摆放使用',
		desc_vn = 'Phong cách rất khí chất. thích hợp sử dụng cho nhà nhỏ diện tích lớn',
		type = 301,
		series = 107,
		icon = 'config/item/furniture/icon_chugui.png',
		res = 'city/town/furniture/img_chugui.png',
		attr = __data_t__attr[74002],
		-- {['flip'] = true, __size = 1}
		size = {['height'] = 2, ['width'] = 5, __size = 2},
		touchSize = {{64, 159}, {194, 103}, {242, 49}, {171, 3}, {5, 118}},
		startPos = {['y'] = 20, ['x'] = -363, __size = 2}
	},
	[74003] = {
		id = 74003,
		name = '实木圆桌',
		name_vn = 'Bàn tròn gỗ nguyên khối',
		desc = '围着圆桌吃火锅，大概是最幸福的事情了',
		desc_vn = 'Ăn lẩu quanh chiếc bàn tròn có lẽ là điều hạnh phúc nhất',
		type = 301,
		icon = 'config/item/furniture/icon_chaji.png',
		res = 'city/town/furniture/img_chaji.png',
		attr = __data_t__attr[74003],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[74003],
		-- {['height'] = 2, ['width'] = 2, __size = 2}
		touchSize = {{8, 18}, {1, 62}, {45, 101}, {88, 59}, {81, 10}},
		startPos = {['y'] = 28, ['x'] = -88, __size = 2}
	},
	[74501] = {
		id = 74501,
		name = '可爱布艺沙发',
		name_vn = 'Sofa vải dễ thương',
		desc = '买胖丁附赠一张柔软舒适的沙发喽',
		desc_vn = 'Một chiếc ghế sofa mềm mại và thoải mái sẽ được tặng kèm khi bạn mua một cậu bé béo',
		type = 302,
		series = 103,
		icon = 'config/item/furniture/icon_shafa1.png',
		res = 'city/town/furniture/img_shafa1.png',
		attr = __data_t__attr[74501],
		-- {['flip'] = true, __size = 1}
		size = {['height'] = 3, ['width'] = 1, __size = 2},
		touchSize = {{45, 2}, {4, 21}, {4, 123}, {122, 127}, {147, 84}, {141, 51}},
		startPos = {['y'] = 13, ['x'] = -81, __size = 2}
	},
	[74502] = {
		id = 74502,
		name = '软萌小凳子',
		name_vn = 'Phân mềm dễ thương',
		desc = '体积小，又轻便，放在哪个角落都是一抹靓丽的装饰',
		desc_vn = 'Kích thước nhỏ và trọng lượng nhẹ. nó là một vật trang trí đẹp mắt ở bất kỳ góc nào',
		type = 302,
		series = 101,
		icon = 'config/item/furniture/icon_xiaodengzi.png',
		res = 'city/town/furniture/img_xiaodengzi.png',
		attr = __data_t__attr[74502],
		-- {['flip'] = true, __size = 1}
		touchSize = {{1, 3}, {34, 4}, {35, 37}, {2, 39}},
		startPos = __data_t__startPos[74502]
		-- {['y'] = 20, ['x'] = -40, __size = 2}
	},
	[74503] = {
		id = 74503,
		name = '时尚软椅',
		name_vn = 'Ghế mềm thời trang',
		desc = '是舒服到可以在上边小睡的程度',
		desc_vn = 'Nó đủ thoải mái để chợp mắt trên đó',
		type = 302,
		icon = 'config/item/furniture/icon_xiaodengzi2.png',
		res = 'city/town/furniture/img_xiaodengzi2.png',
		attr = __data_t__attr[74503],
		-- {['flip'] = true, __size = 1}
		touchSize = {{7, 15}, {48, 15}, {47, 49}, {20, 88}, {1, 76}},
		startPos = {['y'] = 15, ['x'] = -60, __size = 2}
	},
	[75001] = {
		id = 75001,
		name = '欧式屏风',
		name_vn = 'Màn phong cách châu âu',
		desc = '严密而厚实的设计，可以遮挡你所有的小秘密',
		desc_vn = 'Thiết kế nghiêm ngặt và dày dặn. có thể che đi tất cả những bí mật nhỏ của bạn',
		type = 303,
		series = 109,
		icon = 'config/item/furniture/icon_pinfeng.png',
		res = 'city/town/furniture/img_pinfeng.png',
		attr = __data_t__attr[75001],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[75001],
		-- {['height'] = 1, ['width'] = 3, __size = 2}
		touchSize = {{3, 43}, {94, 6}, {96, 152}, {6, 196}},
		startPos = {['y'] = 26, ['x'] = -190, __size = 2}
	},
	[75002] = {
		id = 75002,
		name = '超薄电视',
		name_vn = 'Tivi siêu mỏng',
		desc = '超薄的设计，看起来科技感满满',
		desc_vn = 'Thiết kế siêu mỏng. vẻ ngoài đầy công nghệ',
		type = 303,
		series = 109,
		icon = 'config/item/furniture/icon_dianshi.png',
		res = 'city/town/furniture/img_dianshi.png',
		attr = __data_t__attr[75002],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[75002],
		-- {['height'] = 1, ['width'] = 3, __size = 2}
		touchSize = {{4, 48}, {14, 94}, {32, 134}, {105, 94}, {120, 27}, {93, 5}},
		startPos = {['y'] = 18, ['x'] = -200, __size = 2}
	},
	[75003] = {
		id = 75003,
		name = '实木小床',
		name_vn = 'Cũi gỗ rắn',
		desc = '有大而厚的挂帘遮挡住刺眼的光线，舒适更好眠',
		desc_vn = 'Có rèm cửa dày và to để cản ánh sáng chói giúp bạn có giấc ngủ thoải mái',
		type = 303,
		series = 109,
		icon = 'config/item/furniture/icon_chuang.png',
		res = 'city/town/furniture/img_chuang.png',
		attr = __data_t__attr[75003],
		-- {['flip'] = true, __size = 1}
		size = {['height'] = 3, ['width'] = 4, __size = 2},
		touchSize = {{4, 60}, {2, 192}, {93, 234}, {117, 130}, {215, 85}, {212, 41}, {135, 2}},
		startPos = {['y'] = 48, ['x'] = -293, __size = 2}
	},
	[75004] = {
		id = 75004,
		name = '暖黄软垫',
		name_vn = 'Bọc đệm màu vàng ấm áp',
		desc = '垫在硬硬的地面上，坐上去也会觉得软乎舒服',
		desc_vn = 'Đệm trên nền đất cứng. ngồi lên sẽ có cảm giác mềm mại. dễ chịu',
		type = 303,
		icon = 'config/item/furniture/icon_dianzi.png',
		res = 'city/town/furniture/img_dianzi.png',
		attr = __data_t__attr[75004],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[75004],
		-- {['height'] = 2, ['width'] = 2, __size = 2}
		touchSize = {{7, 15}, {12, 44}, {61, 48}, {78, 16}, {41, 3}},
		startPos = {['y'] = 34, ['x'] = -83, __size = 2}
	},
	[75501] = {
		id = 75501,
		name = '转角橱柜',
		name_vn = 'Tủ góc',
		desc = '空间收纳大师的设计，连转角都不放过可以收纳的部分',
		desc_vn = 'Thiết kế của các bậc thầy lưu trữ không gian. ngay cả các góc không bỏ lỡ phần có thể được lưu trữ',
		type = 304,
		series = 105,
		icon = 'config/item/furniture/icon_guizi.png',
		res = 'city/town/furniture/img_guizi.png',
		attr = __data_t__attr[75501],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[75501],
		-- {['height'] = 2, ['width'] = 2, __size = 2}
		touchSize = {{1, 31}, {16, 92}, {65, 92}, {66, 7}},
		startPos = {['y'] = 18, ['x'] = -120, __size = 2}
	},
	[75502] = {
		id = 75502,
		name = '简约花架',
		name_vn = 'Kệ hoa đơn giản',
		desc = '随手放置植物即可以点缀室内的布局',
		desc_vn = 'Đặt cây theo ý muốn để tô điểm cho bố cục trong nhà',
		type = 304,
		series = 103,
		icon = 'config/item/furniture/icon_huajia.png',
		res = 'city/town/furniture/img_huajia.png',
		attr = __data_t__attr[75502],
		-- {['flip'] = true, __size = 1}
		size = {['height'] = 1, ['width'] = 2, __size = 2},
		touchSize = {{23, 129}, {66, 100}, {59, 8}, {2, 18}},
		startPos = {['y'] = 21, ['x'] = -110, __size = 2}
	},
	[75503] = {
		id = 75503,
		name = '玄关储物柜',
		name_vn = 'Tủ đựng đồ ở lối vào',
		desc = '友好的高度，适合接住回到家的你的所有疲惫',
		desc_vn = 'Chiều cao thân thiện. phù hợp để đánh bay mọi mệt mỏi mỗi khi về đến nhà',
		type = 304,
		series = 106,
		icon = 'config/item/furniture/icon_shugui.png',
		res = 'city/town/furniture/img_shugui.png',
		attr = __data_t__attr[75503],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[75503],
		-- {['height'] = 2, ['width'] = 1, __size = 2}
		touchSize = {{1, 87}, {26, 124}, {69, 127}, {86, 89}, {70, 28}, {4, 16}},
		startPos = {['y'] = 15, ['x'] = -45, __size = 2}
	},
	[75504] = {
		id = 75504,
		name = '实木床头柜',
		name_vn = 'Bàn đầu giường bằng gỗ nguyên khối',
		desc = '简单而温馨的配色，还有一个巨大的抽屉，看起来特别实用',
		desc_vn = 'Phối màu đơn giản và ấm áp. và một ngăn kéo lớn. trông rất thiết thực',
		type = 304,
		series = 107,
		icon = 'config/item/furniture/icon_chuangtougui.png',
		res = 'city/town/furniture/img_chuangtougui.png',
		attr = __data_t__attr[75504],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[75504],
		-- {['height'] = 2, ['width'] = 1, __size = 2}
		touchSize = {{1, 51}, {56, 92}, {73, 58}, {64, 20}, {17, 13}},
		startPos = __data_t__startPos[75504]
		-- {['y'] = 20, ['x'] = -40, __size = 2}
	},
	[76001] = {
		id = 76001,
		name = '皮神定制冰箱',
		name_vn = 'Tủ lạnh tùy chỉnh Pishen',
		desc = '简单的小体积冰箱，跳跃的配色与皮神特别搭配',
		desc_vn = 'Tủ lạnh cỡ nhỏ đơn giản phối màu nhảy Pishen',
		type = 305,
		series = 108,
		icon = 'config/item/furniture/icon_bingxiang.png',
		res = 'city/town/furniture/img_bingxiang.png',
		attr = __data_t__attr[76001],
		-- {['flip'] = true, __size = 1}
		touchSize = {{3, 17}, {13, 146}, {33, 179}, {68, 137}, {61, 12}},
		startPos = {['y'] = 7, ['x'] = -72, __size = 2}
	},
	[76002] = {
		id = 76002,
		name = '一体式灶台',
		name_vn = 'Bếp từ tích hợp',
		desc = '功能非常齐全的灶台集柜设计，是时下最流行的款式',
		desc_vn = 'Thiết kế tủ bếp với đầy đủ công năng là phong cách được ưa chuộng nhất hiện nay',
		type = 305,
		series = 108,
		icon = 'config/item/furniture/icon_chugui1.png',
		res = 'city/town/furniture/img_chugui1.png',
		attr = __data_t__attr[76002],
		-- {['flip'] = true, __size = 1}
		size = __data_t__size[76002],
		-- {['height'] = 4, ['width'] = 6, __size = 2}
		touchSize = {{1, 112}, {149, 182}, {380, 68}, {353, 2}, {147, 73}, {37, 52}, {7, 59}},
		startPos = {['y'] = 133, ['x'] = -453, __size = 2}
	},
	[76501] = {
		id = 76501,
		name = '天堂鸟盆栽',
		name_vn = 'chậu cây chim thiên đường',
		desc = '是一个大件的植物，可以保证室内的清新',
		desc_vn = 'Là một loại cây lớn có thể giữ cho nội thất tươi mát',
		type = 306,
		series = 105,
		icon = 'config/item/furniture/icon_zhiwu.png',
		res = 'city/town/furniture/img_zhiwu.png',
		attr = __data_t__attr[76501],
		-- {['flip'] = true, __size = 1}
		touchSize = {{11, 14}, {2, 99}, {63, 94}, {42, 9}},
		startPos = {['y'] = 21, ['x'] = -60, __size = 2}
	},
	[76502] = {
		id = 76502,
		name = '超大软萌皮卡丘',
		name_vn = 'Pikachu siêu mềm dễ thương',
		desc = '非常巨大的皮卡丘玩偶，摸上去软乎乎的，抱起来很舒服',
		desc_vn = 'Búp bê Pikachu rất lớn. mềm khi chạm vào và thoải mái khi cầm',
		type = 306,
		series = 109,
		icon = 'config/item/furniture/icon_wanou2.png',
		res = 'city/town/furniture/img_wanou2.png',
		attr = __data_t__attr[76502],
		-- {['flip'] = true, __size = 1}
		touchSize = {{4, 56}, {29, 123}, {89, 67}, {83, 14}, {33, 11}},
		startPos = {['y'] = 8, ['x'] = -108, __size = 2}
	},
	[77001] = {
		id = 77001,
		name = '解锁区域1',
		name_vn = 'Mở khóa khu vực 1',
		desc = '解锁区域',
		desc_vn = 'Khu vực mở khóa',
		type = 0,
		icon = 'config/item/furniture/img_kzqy1.png',
		res = 'city/town/furniture/img_kzqy1.png',
		size = {['height'] = 6, ['width'] = 12, __size = 2},
		touchSize = {{6, 457}, {4, 254}, {509, 8}, {754, 132}, {275, 375}, {272, 578}},
		startPos = {['y'] = -20, ['x'] = -1020, __size = 2}
	},
	[77002] = {
		id = 77002,
		name = '解锁区域2',
		name_vn = 'Mở khóa khu vực 2',
		desc = '解锁区域',
		desc_vn = 'Khu vực mở khóa',
		type = 0,
		icon = 'config/item/furniture/img_kzqy2.png',
		res = 'city/town/furniture/img_kzqy2.png',
		size = {['height'] = 18, ['width'] = 6, __size = 2},
		touchSize = {{720, 698}, {719, 507}, {3, 134}, {246, 8}, {997, 377}, {994, 588}},
		startPos = {['y'] = -35, ['x'] = -480, __size = 2}
	},
	[77003] = {
		id = 77003,
		name = '装修图标',
		name_vn = 'Biểu tượng đổi mới',
		desc = '解锁区域',
		desc_vn = 'Khu vực mở khóa',
		type = 0,
		icon = 'config/item/furniture/icon_sgz.png',
		res = 'city/town/furniture/icon_sgz.png',
		size = __data_t__size[77003],
		-- {['height'] = 2, ['width'] = 1, __size = 2}
		touchSize = {{49, 140}, {30, 83}, {61, 19}, {190, 84}, {161, 157}, {132, 160}},
		startPos = {['y'] = -70, ['x'] = -140, __size = 2}
	},
	[77004] = {
		id = 77004,
		name = '内墙',
		name_vn = 'Tường nội thất',
		desc = '未解锁时候的内墙',
		desc_vn = 'Các bức tường bên trong khi được mở khóa',
		type = 0,
		icon = 'config/item/furniture/img_neiqiang.png',
		res = 'city/town/furniture/img_neiqiang.png',
		size = {['height'] = 1, ['width'] = 12, __size = 2},
		touchSize = {{1, 241}, {476, 2}, {475, 5}, {476, 55}, {10, 292}},
		startPos = {['y'] = 20, ['x'] = -900, __size = 2}
	},
	[77005] = {
		id = 77005,
		name = '外墙',
		name_vn = 'Bức tường bên ngoài',
		desc = '外墙',
		desc_vn = 'Bức tường bên ngoài',
		type = 0,
		icon = 'config/item/furniture/img_waiqiang.png',
		res = 'city/town/furniture/img_waiqiang.png',
		size = {['height'] = 1, ['width'] = 6, __size = 2},
		touchSize = {{0, 177}, {0, 130}, {247, 2}, {258, 8}, {257, 55}, {9, 179}},
		startPos = {['y'] = 20, ['x'] = -420, __size = 2}
	},

	__size = 34,
	__default = {
		__index = {
			name = '',
			name_tw = '',
			name_en = '',
			name_vn = '',
			name_kr = '',
			desc = '',
			desc_tw = '',
			desc_en = '',
			desc_vn = '',
			desc_kr = '',
			type = 102,
			stackMax = 10,
			expAdd = 5,
			series = 0,
			icon = '',
			res = '',
			startResScale = 2,
			attr = {__size = 0},
			size = {['height'] = 1, ['width'] = 1, __size = 2},
			touchSize = {},
			relSize = {['off'] = {['offWidth'] = 0, ['offHeight'] = 0, __size = 2}, ['height'] = 1, ['width'] = 1, __size = 3},
			startPos = {['y'] = 0, ['y2'] = 0, ['x'] = 0, ['x2'] = 0, __size = 4},
			position = 5,
			quality = 0,
			currentNum = false,
			languages = {'cn', 'in', 'tw', 'en', 'kr', 'vn', 'th', 'ma', 'ph'}
		}
	}
}
return csv.town.home_furniture