--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['server']['merge'] = {
	[1] = {
		id = 1,
		destServer = 'gamemerge.dev.1',
		servers = {'game.dev.1', 'game.dev.2'},
		serverID = 1,
		pwAwardVer = 101,
		randomTowerAwardVer = 101,
		craftAwardVer = 101,
		realityMerge = 1
	},
	[2] = {
		id = 2,
		destServer = 'gamemerge.th.1',
		servers = {'game.th.1', 'game.th.2', 'game.th.3', 'game.th.4', 'game.th.5'},
		serverID = 1,
		pwAwardVer = 101,
		randomTowerAwardVer = 101,
		craftAwardVer = 101,
		realityMerge = 1
	},
	[3] = {
		id = 3,
		destServer = 'gamemerge.th.2',
		servers = {'game.th.6', 'game.th.7', 'game.th.8', 'game.th.9', 'game.th.10'},
		serverID = 1,
		pwAwardVer = 101,
		randomTowerAwardVer = 101,
		craftAwardVer = 101,
		realityMerge = 1
	},

	__size = 3,
	__default = {
		__index = {
			servers = {},
			pwAwardVer = 0,
			randomTowerAwardVer = 0,
			craftAwardVer = 0,
			realityMerge = 0
		}
	}
}
return csv.server.merge