--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['achievement']['achievement'] = {
	[1] = {
		id = 1,
		name = 'เติมโต',
		icon = 'city/task/achievement/icon_rucz.png'
	},
	[2] = {
		id = 2,
		name = 'สะสม',
		icon = 'city/task/achievement/icon_jlsj.png'
	},
	[3] = {
		id = 3,
		name = 'ฝึกฝน',
		icon = 'city/task/achievement/icon_jlpy.png'
	},
	[4] = {
		id = 4,
		name = 'ดันเจี้ยน',
		icon = 'city/task/achievement/icon_fbhd.png'
	},
	[5] = {
		id = 5,
		name = 'อารีน่า',
		icon = 'city/task/achievement/icon_jjtz.png'
	},
	[6] = {
		id = 6,
		name = 'โซเซียล',
		icon = 'city/task/achievement/icon_sj.png'
	},
	[7] = {
		id = 7,
		name = 'ความสำเร็จ'
	},

	__size = 7,
	__default = {
		__index = {
			name = '',
			icon = ''
		}
	}
}
return csv.achievement.achievement