--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, __size = 1}
local __data_t__clothCost = {
	["default"] = __predefine_t__[1]
}
local __data_t__videoattr = {
	["default"] = __predefine_t__[1]
}
local __data_t__clothattr = {
	["default"] = __predefine_t__[1]
}
local __data_t__videoCost = {
	["default"] = __predefine_t__[1]
}

csv['banlvxiaowu'] = {
	[1] = {
		id = 1,
		name = 'Tứ Phong Viện Dạ Nhất',
		clothattr = {[1] = '2%', [2] = '2%', __size = 2},
		videoattr = {[1] = '2%', [3] = '2%', [2] = '2%', __size = 3},
		chipnum = 28,
		blessing = 'Vật công',
		attrType = 7,
		attrNum = '5%',
		cardID = 1293,
		clothCost = {[31] = 10, __size = 1},
		videoCost = {[30] = 10, __size = 1},
		sort = 1,
		randLib = 130,
		chattext1 = 'So với Thi Hồn Giới, nơi này cũng không tệ lắm nhỉ~',
		chattext2 = 'Hôm nay có nhớ chị không nào~',
		chattext3 = '? (??o? ?)????',
		roleConfig = {['y'] = 365, ['x'] = 620, ['offsety'] = 30, __size = 3},
		chtaTextConfig = {['y'] = 140, ['scale'] = 1, ['x'] = -100, __size = 3}
	},

	__size = 1,
	__default = {
		__index = {
			clothattr = __data_t__clothattr["default"]	--[[ {__size = 0}]],
			videoattr = __data_t__videoattr["default"]	--[[ {__size = 0}]],
			clothCost = __data_t__clothCost["default"]	--[[ {__size = 0}]],
			videoCost = __data_t__videoCost["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.banlvxiaowu