--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['character'] = {
	[1] = {
		id = 1,
		name = 'Impulsive',
		name_vn = 'Nông nổi',
		name_ma = 'Gopoh',
		name_en = 'Impulsive',
		name_th = 'ใจร้อน',
		name_in = 'Ceroboh',
		name_ph = 'Padalos-dalos'
	},
	[2] = {
		id = 2,
		name = 'Diligent',
		name_vn = 'Siêng năng',
		name_ma = 'Rajin',
		name_en = 'Diligent',
		name_th = 'ขยัน',
		name_in = 'Rajin',
		name_ph = 'Masipag'
	},
	[3] = {
		id = 3,
		name = 'Shy',
		name_vn = 'Nhút nhát',
		name_ma = 'Pemalu',
		name_en = 'Shy',
		name_th = 'ขี้อาย',
		name_in = 'Pemalu',
		name_ph = 'Mahiyain'
	},
	[4] = {
		id = 4,
		name = 'Straightforward',
		name_vn = 'Thẳng thắn',
		name_ma = 'Terus terang',
		name_en = 'Straightforward',
		name_th = 'ตรงไปตรงมา',
		name_in = 'Terus terang',
		name_ph = 'Diretsahan'
	},
	[5] = {
		id = 5,
		name = 'Serious',
		name_vn = 'Nghiêm túc',
		name_ma = 'Serius',
		name_en = 'Serious',
		name_th = 'จริงจัง',
		name_in = 'Serius',
		name_ph = 'Seryoso'
	},
	[6] = {
		id = 6,
		name = 'Cowardly',
		name_vn = 'Nhát gan',
		name_ma = 'Penakut',
		name_en = 'Cowardly',
		name_th = 'ขี้ขลาด',
		name_in = 'Pengecut',
		name_ph = 'Duwag',
		attrMap = {[13] = '110%', [7] = '90%', __size = 2}
	},
	[7] = {
		id = 7,
		name = 'Short-tempered',
		name_vn = 'Nóng nảy',
		name_ma = 'Cepat marah',
		name_en = 'Short-tempered',
		name_th = 'หงุดหงิดง่าย',
		name_in = 'Pemarah',
		name_ph = 'Mainitin ang ulo',
		attrMap = {[9] = '90%', [13] = '110%', __size = 2}
	},
	[8] = {
		id = 8,
		name = 'Cheerful',
		name_vn = 'Sảng khoái',
		name_ma = 'Ceria',
		name_en = 'Cheerful',
		name_th = 'สดใส',
		name_in = 'Ceria',
		name_ph = 'Masigla',
		attrMap = {[8] = '90%', [13] = '110%', __size = 2}
	},
	[9] = {
		id = 9,
		name = 'Naive',
		name_vn = 'Ngây thơ',
		name_ma = 'Naif',
		name_en = 'Naive',
		name_th = 'ไร้เดียงสา',
		name_in = 'Naif',
		name_ph = 'Walang muwang',
		attrMap = {[10] = '90%', [13] = '110%', __size = 2}
	},
	[10] = {
		id = 10,
		name = 'Afraid of being alone',
		name_vn = 'Sợ cô đơn',
		name_ma = 'Takut keseorangan',
		name_en = 'Afraid of being alone',
		name_th = 'กลัวความเหงา',
		name_in = 'Takut kesepian',
		name_ph = 'Takot sa kalungkutan',
		attrMap = {[9] = '90%', [7] = '110%', __size = 2}
	},
	[11] = {
		id = 11,
		name = 'Brave',
		name_vn = 'Dũng cảm',
		name_ma = 'Berani',
		name_en = 'Brave',
		name_th = 'กล้าหาญ',
		name_in = 'Berani',
		name_ph = 'Matapang',
		attrMap = {[13] = '90%', [7] = '110%', __size = 2}
	},
	[12] = {
		id = 12,
		name = 'Stubborn',
		name_vn = 'Cứng đầu',
		name_ma = 'Degil',
		name_en = 'Stubborn',
		name_th = 'ดื้อรั้น',
		name_in = 'Keras kepala',
		name_ph = 'Matigas ang ulo',
		attrMap = {[8] = '90%', [7] = '110%', __size = 2}
	},
	[13] = {
		id = 13,
		name = 'Mischievous',
		name_vn = 'Nghịch ngợm',
		name_ma = 'Nakal',
		name_en = 'Mischievous',
		name_th = 'ซุกซน',
		name_in = 'Nakal',
		name_ph = 'Pilyo',
		attrMap = {[10] = '90%', [7] = '110%', __size = 2}
	},
	[14] = {
		id = 14,
		name = 'Bold',
		name_vn = 'Táo bạo',
		name_ma = 'Berani mencuba',
		name_en = 'Bold',
		name_th = 'กล้าหาญ',
		name_in = 'Berani',
		name_ph = 'Mapangahas',
		attrMap = {[9] = '110%', [7] = '90%', __size = 2}
	},
	[15] = {
		id = 15,
		name = 'Relaxed',
		name_vn = 'Thư thả',
		name_ma = 'Santai',
		name_en = 'Relaxed',
		name_th = 'สบาย ๆ',
		name_in = 'Santai',
		name_ph = 'Relax lang',
		attrMap = {[9] = '110%', [13] = '90%', __size = 2}
	},
	[16] = {
		id = 16,
		name = 'Playful',
		name_vn = 'Tinh nghịch',
		name_ma = 'Nak nakal',
		name_en = 'Playful',
		name_th = 'ขี้เล่น',
		name_in = 'Usil',
		name_ph = 'Malikot',
		attrMap = {[9] = '110%', [8] = '90%', __size = 2}
	},
	[17] = {
		id = 17,
		name = 'Optimistic',
		name_vn = 'Lạc quan',
		name_ma = 'Optimis',
		name_en = 'Optimistic',
		name_th = 'มองโลกในแง่ดี',
		name_in = 'Optimis',
		name_ph = 'Optimistiko',
		attrMap = {[9] = '110%', [10] = '90%', __size = 2}
	},
	[18] = {
		id = 18,
		name = 'Reserved',
		name_vn = 'Kín đáo',
		name_ma = 'Pendiam',
		name_en = 'Reserved',
		name_th = 'เก็บตัว',
		name_in = 'Tertutup',
		name_ph = 'Tahimik',
		attrMap = {[8] = '110%', [7] = '90%', __size = 2}
	},
	[19] = {
		id = 19,
		name = 'Slow',
		name_vn = 'Chậm chạp',
		name_ma = 'Perlahan',
		name_en = 'Slow',
		name_th = 'เชื่องช้า',
		name_in = 'Lambat',
		name_ph = 'Mabagal',
		attrMap = {[9] = '90%', [8] = '110%', __size = 2}
	},
	[20] = {
		id = 20,
		name = 'Calm',
		name_vn = 'Bình tĩnh',
		name_ma = 'Tenang',
		name_en = 'Calm',
		name_th = 'ใจเย็น',
		name_in = 'Tenang',
		name_ph = 'Kalmado',
		attrMap = {[8] = '110%', [13] = '90%', __size = 2}
	},
	[21] = {
		id = 21,
		name = 'Careless',
		name_vn = 'Cẩu thả',
		name_ma = 'Cuai',
		name_en = 'Careless',
		name_th = 'สะเพร่า',
		name_in = 'Sembrono',
		name_ph = 'Pabaya',
		attrMap = {[8] = '110%', [10] = '90%', __size = 2}
	},
	[22] = {
		id = 22,
		name = 'Gentle',
		name_vn = 'Ôn hòa',
		name_ma = 'Lemah lembut',
		name_en = 'Gentle',
		name_th = 'อ่อนโยน',
		name_in = 'Lembut',
		name_ph = 'Maamo',
		attrMap = {[10] = '110%', [7] = '90%', __size = 2}
	},
	[23] = {
		id = 23,
		name = 'Obedient',
		name_vn = 'Ngoan ngoãn',
		name_ma = 'Patuh',
		name_en = 'Obedient',
		name_th = 'เชื่อฟัง',
		name_in = 'Patuh',
		name_ph = 'Masunurin',
		attrMap = {[9] = '90%', [10] = '110%', __size = 2}
	},
	[24] = {
		id = 24,
		name = 'Arrogant',
		name_vn = 'Tự cao',
		name_ma = 'Sombong',
		name_en = 'Arrogant',
		name_th = 'หยิ่งยโส',
		name_in = 'Sombong',
		name_ph = 'Mayabang',
		attrMap = {[10] = '110%', [13] = '90%', __size = 2}
	},
	[25] = {
		id = 25,
		name = 'Cautious',
		name_vn = 'Thận trọng',
		name_ma = 'Berhati-hati',
		name_en = 'Cautious',
		name_th = 'รอบคอบ',
		name_in = 'Hati-hati',
		name_ph = 'Maingat',
		attrMap = {[8] = '90%', [10] = '110%', __size = 2}
	},

	__size = 25,
	__default = {
		__index = {
			name = '',
			name_vn = '',
			name_ma = '',
			name_en = '',
			name_th = '',
			name_in = '',
			name_ph = '',
			attrMap = {__size = 0},
			res = ''
		}
	}
}
return csv.character