--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {2}, __size = 1}
local __data_t__tab = {
	[24] = __predefine_t__[2],
	[25] = __predefine_t__[2],
	[23] = __predefine_t__[2],
	[27] = __predefine_t__[2],
	[20] = __predefine_t__[2],
	[21] = __predefine_t__[2],
	[17] = __predefine_t__[2],
	[16] = __predefine_t__[2],
	[19] = __predefine_t__[2],
	[18] = __predefine_t__[2],
	[22] = __predefine_t__[2],
	[28] = __predefine_t__[2],
	[26] = __predefine_t__[2],
	[29] = __predefine_t__[2],
	[30] = __predefine_t__[2]
}

csv['chat_emoji'] = {
	[1] = {
		id = 1,
		key = 'emo1',
		text = 'Yeah~',
		text_vn = 'Yeah~',
		text_ma = 'Yeah~',
		text_en = 'Yeah~',
		text_th = 'เย้~',
		text_ph = 'Yeah~',
		text_in = 'Yeah~',
		resource = 'config/chatemoji/emoji_1.png'
	},
	[2] = {
		id = 2,
		key = 'emo2',
		text = 'Thank you',
		text_vn = 'Cảm ơn',
		text_ma = 'Terima kasih',
		text_en = 'Thank you',
		text_th = 'ขอบคุณ',
		text_ph = 'Salamat',
		text_in = 'Terima kasih',
		resource = 'config/chatemoji/emoji_2.png'
	},
	[3] = {
		id = 3,
		key = 'emo3',
		text = 'Ok',
		text_vn = 'Ok',
		text_ma = 'Ok',
		text_en = 'Ok',
		text_th = 'โอเค',
		text_ph = 'Ok',
		text_in = 'Oke',
		resource = 'config/chatemoji/emoji_3.png'
	},
	[4] = {
		id = 4,
		key = 'emo4',
		text = 'Got it',
		text_vn = 'Hiểu rồi',
		text_ma = 'Faham dah',
		text_en = 'Got it',
		text_th = 'เข้าใจแล้ว',
		text_ph = 'Naiintindihan na',
		text_in = 'Mengerti',
		resource = 'config/chatemoji/emoji_4.png'
	},
	[5] = {
		id = 5,
		key = 'emo5',
		text = 'Check the punch / Throw a punch',
		text_vn = 'Xem quyền (hoặc ra đòn quyền)',
		text_ma = 'Lihat tumbukan / Bagi tumbukan',
		text_en = 'Check the punch / Throw a punch',
		text_th = 'ดูหมัด / ปล่อยหมัด',
		text_ph = 'Tingnan ang suntok / Suntok na',
		text_in = 'Lihat pukulan / Lontarkan pukulan',
		resource = 'config/chatemoji/emoji_5.png'
	},
	[6] = {
		id = 6,
		key = 'emo6',
		text = 'Speechless',
		text_vn = 'Nghẹn lời',
		text_ma = 'Terdiam',
		text_en = 'Speechless',
		text_th = 'พูดไม่ออก',
		text_ph = 'Walang masabi',
		text_in = 'Bisu',
		resource = 'config/chatemoji/emoji_6.png'
	},
	[7] = {
		id = 7,
		key = 'emo7',
		text = 'Sorry…',
		text_vn = 'Xin lỗi…',
		text_ma = 'Maaf…',
		text_en = 'Sorry…',
		text_th = 'ขอโทษนะ…',
		text_ph = 'Pasensya na…',
		text_in = 'Maaf ya…',
		resource = 'config/chatemoji/emoji_7.png'
	},
	[8] = {
		id = 8,
		key = 'emo8',
		text = 'Congrats',
		text_vn = 'Chúc mừng',
		text_ma = 'Tahniah',
		text_en = 'Congrats',
		text_th = 'ยินดีด้วย',
		text_ph = 'Congrats',
		text_in = 'Selamat',
		resource = 'config/chatemoji/emoji_8.png'
	},
	[9] = {
		id = 9,
		key = 'emo9',
		text = 'Do I even have to say it',
		text_vn = 'Còn phải nói sao',
		text_ma = 'Perlu ke cakap lagi',
		text_en = 'Do I even have to say it',
		text_th = 'ต้องพูดด้วยเหรอ',
		text_ph = 'Kailangan pa bang i-memorize yan',
		text_in = 'Masih perlu ditanya?',
		resource = 'config/chatemoji/emoji_9.png'
	},
	[10] = {
		id = 10,
		key = 'emo10',
		text = 'No way~!',
		text_vn = 'Không thể nào~!',
		text_ma = 'Tak mungkin~!',
		text_en = 'No way~!',
		text_th = 'เป็นไปไม่ได้~!',
		text_ph = 'Imposible~!',
		text_in = 'Tidak mungkin~!',
		resource = 'config/chatemoji/emoji_10.png'
	},
	[11] = {
		id = 11,
		key = 'emo11',
		text = 'Shocked',
		text_vn = 'Sốc',
		text_ma = 'Terkedu',
		text_en = 'Shocked',
		text_th = 'ช็อก',
		text_ph = 'Shookt',
		text_in = 'Kaget',
		resource = 'config/chatemoji/emoji_11.png'
	},
	[12] = {
		id = 12,
		key = 'emo12',
		text = 'So good~',
		text_vn = 'Tốt quá đi~',
		text_ma = 'Terbaik sangat~',
		text_en = 'So good~',
		text_th = 'ดีเกินไป~',
		text_ph = 'Ang saya~',
		text_in = 'Bagus banget~',
		resource = 'config/chatemoji/emoji_12.png'
	},
	[13] = {
		id = 13,
		key = 'emo13',
		text = 'Happy',
		text_vn = 'Vui vẻ',
		text_ma = 'Gembira',
		text_en = 'Happy',
		text_th = 'สนุกสนาน',
		text_ph = 'Masaya',
		text_in = 'Senang',
		resource = 'config/chatemoji/emoji_13.png'
	},
	[14] = {
		id = 14,
		key = 'emo14',
		text = 'Smile',
		text_vn = 'Mỉm cười',
		text_ma = 'Senyum',
		text_en = 'Smile',
		text_th = 'ยิ้ม',
		text_ph = 'Ngiti',
		text_in = 'Senyum',
		resource = 'config/chatemoji/emoji_14.png'
	},
	[15] = {
		id = 15,
		key = 'emo15',
		text = 'Hahaha',
		text_vn = 'Hahaha',
		text_ma = 'Hahaha',
		text_en = 'Hahaha',
		text_th = 'ฮ่าๆๆ',
		text_ph = 'Hahaha',
		text_in = 'Hahaha',
		resource = 'config/chatemoji/emoji_15.png'
	},
	[16] = {
		id = 16,
		key = 'emo16',
		text = 'Feeling sad',
		text_vn = 'Tủi thân',
		text_ma = 'Sedih',
		text_en = 'Feeling sad',
		text_th = 'เสียใจ',
		text_ph = 'Nalulungkot',
		text_in = 'Sedih',
		tab = __data_t__tab[16],
		-- {2}
		resource = 'config/chatemoji/emoji_16.png'
	},
	[17] = {
		id = 17,
		key = 'emo17',
		text = 'Awesome!!!',
		text_vn = 'Đỉnh!!!',
		text_ma = 'Padu!!!',
		text_en = 'Awesome!!!',
		text_th = 'สุดยอด!!!',
		text_ph = 'Angas!!!',
		text_in = 'Keren!!!',
		tab = __data_t__tab[17],
		-- {2}
		resource = 'config/chatemoji/emoji_18.png'
	},
	[18] = {
		id = 18,
		key = 'emo18',
		text = 'Thank you',
		text_vn = 'Cảm ơn',
		text_ma = 'Terima kasih',
		text_en = 'Thank you',
		text_th = 'ขอบคุณ',
		text_ph = 'Salamat',
		text_in = 'Terima kasih',
		tab = __data_t__tab[18],
		-- {2}
		resource = 'config/chatemoji/emoji_19.png'
	},
	[19] = {
		id = 19,
		key = 'emo19',
		text = 'Want it',
		text_vn = 'Muốn',
		text_ma = 'Mahukan',
		text_en = 'Want it',
		text_th = 'อยากได้',
		text_ph = 'Gusto',
		text_in = 'Ingin',
		tab = __data_t__tab[19],
		-- {2}
		resource = 'config/chatemoji/emoji_20.png'
	},
	[20] = {
		id = 20,
		key = 'emo20',
		text = 'Very good!',
		text_vn = 'Rất ổn!',
		text_ma = 'Bagus sangat!',
		text_en = 'Very good!',
		text_th = 'ดีมาก!',
		text_ph = 'Ayos lang!',
		text_in = 'Sangat bagus!',
		tab = __data_t__tab[20],
		-- {2}
		resource = 'config/chatemoji/emoji_21.png'
	},
	[21] = {
		id = 21,
		key = 'emo21',
		text = 'Delicious',
		text_vn = 'Ngon',
		text_ma = 'Sedap',
		text_en = 'Delicious',
		text_th = 'อร่อย',
		text_ph = 'Masarap',
		text_in = 'Enak',
		tab = __data_t__tab[21],
		-- {2}
		resource = 'config/chatemoji/emoji_22.png'
	},
	[22] = {
		id = 22,
		key = 'emo22',
		text = 'Cheer up',
		text_vn = 'Cổ vũ',
		text_ma = 'Sokong',
		text_en = 'Cheer up',
		text_th = 'ให้กำลังใจ',
		text_ph = 'Suporta',
		text_in = 'Dukung',
		tab = __data_t__tab[22],
		-- {2}
		resource = 'config/chatemoji/emoji_23.png'
	},
	[23] = {
		id = 23,
		key = 'emo23',
		text = 'I\'m hungry',
		text_vn = 'Đói rồi',
		text_ma = 'Lapar dah',
		text_en = 'I\'m hungry',
		text_th = 'หิวแล้ว',
		text_ph = 'Nagugutom na ako',
		text_in = 'Lapar nih',
		tab = __data_t__tab[23],
		-- {2}
		resource = 'config/chatemoji/emoji_24.png'
	},
	[24] = {
		id = 24,
		key = 'emo24',
		text = 'Like it',
		text_vn = 'Thích',
		text_ma = 'Suka',
		text_en = 'Like it',
		text_th = 'ชอบ',
		text_ph = 'Gusto ko',
		text_in = 'Suka',
		tab = __data_t__tab[24],
		-- {2}
		resource = 'config/chatemoji/emoji_25.png'
	},
	[25] = {
		id = 25,
		key = 'emo25',
		text = 'Let me see',
		text_vn = 'Để tôi xem nào',
		text_ma = 'Biar saya tengok dulu',
		text_en = 'Let me see',
		text_th = 'ขอดูก่อนนะ',
		text_ph = 'Tingnan ko nga',
		text_in = 'Biar saya lihat dulu',
		tab = __data_t__tab[25],
		-- {2}
		resource = 'config/chatemoji/emoji_26.png'
	},
	[26] = {
		id = 26,
		key = 'emo26',
		text = 'Send heart',
		text_vn = 'Thả tim',
		text_ma = 'Hantar hati',
		text_en = 'Send heart',
		text_th = 'ส่งหัวใจ',
		text_ph = 'Pusuan',
		text_in = 'Kirim hati',
		tab = __data_t__tab[26],
		-- {2}
		resource = 'config/chatemoji/emoji_27.png'
	},
	[27] = {
		id = 27,
		key = 'emo27',
		text = 'Kneel down',
		text_vn = 'Quỳ xuống',
		text_ma = 'Berlutut',
		text_en = 'Kneel down',
		text_th = 'คุกเข่า',
		text_ph = 'Lumuhod',
		text_in = 'Berlutut',
		tab = __data_t__tab[27],
		-- {2}
		resource = 'config/chatemoji/emoji_28.png'
	},
	[28] = {
		id = 28,
		key = 'emo28',
		text = 'Cold',
		text_vn = 'Lạnh nhạt',
		text_ma = 'Dingin',
		text_en = 'Cold',
		text_th = 'เฉยชา',
		text_ph = 'Walang pakialam',
		text_in = 'Dingin',
		tab = __data_t__tab[28],
		-- {2}
		resource = 'config/chatemoji/emoji_29.png'
	},
	[29] = {
		id = 29,
		key = 'emo29',
		text = 'No words',
		text_vn = 'Cạn lời',
		text_ma = 'Tak tahu nak cakap apa',
		text_en = 'No words',
		text_th = 'พูดไม่ออกเลย',
		text_ph = 'Walang masabi',
		text_in = 'Bingung mau ngomong apa',
		tab = __data_t__tab[29],
		-- {2}
		resource = 'config/chatemoji/emoji_30.png'
	},
	[30] = {
		id = 30,
		key = 'emo30',
		text = 'Send me 50',
		text_vn = 'Chuyển tôi 50 (vnd)',
		text_ma = 'Hantar saya RM0.50',
		text_en = 'Send me 50',
		text_th = 'โอนให้ฉัน 50',
		text_ph = 'Pasa mo 50',
		text_in = 'Kirim saya 50',
		tab = __data_t__tab[30],
		-- {2}
		resource = 'config/chatemoji/emoji_31.png'
	},

	__size = 30,
	__default = {
		__index = {
			key = '',
			text = '',
			text_vn = '',
			text_ma = '',
			text_en = '',
			text_th = '',
			text_ph = '',
			text_in = '',
			tab = {1},
			resource = ''
		}
	}
}
return csv.chat_emoji