--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['citysound'] = {
	[1] = {
		id = 1,
		path = 'city.mp3',
		name = 'Default',
		name = 'Mặc định',
		name_ma = 'Lalai',
		name_ph = 'Default',
		name_th = 'ค่าเริ่มต้น',
		name_en = 'Default',
		name_in = 'Default'
	},
	[2] = {
		id = 2,
		path = 'city2.mp3',
		name = 'Lively',
		name = 'Sôi động',
		name_ma = 'Meriah',
		name_ph = 'Masigla',
		name_th = 'คึกคัก',
		name_en = 'Lively',
		name_in = 'Meriah'
	},
	[3] = {
		id = 3,
		path = 'city3.mp3',
		name = 'Gentle',
		name = 'Nhẹ nhàng',
		name_ma = 'Lembut',
		name_ph = 'Banayad',
		name_th = 'นุ่มนวล',
		name_en = 'Gentle',
		name_in = 'Lembut'
	},

	__size = 3,
	__default = {
		__index = {
			path = '',
			name = '默认场景',
			name = '默认场景',
			name_ma = '默認場景',
			name_ph = '默认场景',
			name_th = '默认场景',
			name_en = '默认场景',
			name_in = '默认场景'
		}
	}
}
return csv.citysound