--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {['y'] = 0, ['x'] = 0, __size = 2}, 
	[8] = {['y'] = 80, ['x'] = 240, __size = 2}, 
	[12] = {['y'] = 60, ['x'] = -90, __size = 2}, 
	[14] = {100105}, 
	[16] = {['y'] = 50, ['x'] = -130, __size = 2}, 
	[17] = {['y'] = 40, ['x'] = -140, __size = 2}, 
	[23] = {2485}, 
	[26] = {['libs'] = {136}, __size = 1}, 
	[29] = {['height'] = 80, ['width'] = 70, __size = 2}, 
	[33] = {['height'] = 120, ['width'] = 80, __size = 2}, 
	[51] = {['height'] = 120, ['width'] = 120, __size = 2}, __size = 11}
local __data_t__activityPosition = {
	["default"] = __predefine_t__[1]
}
local __data_t__touchSize = {
	[25] = __predefine_t__[33],
	[26] = __predefine_t__[33],
	[20] = __predefine_t__[33],
	[21] = __predefine_t__[29],
	[18] = __predefine_t__[29],
	[1002] = __predefine_t__[51],
	[1001] = __predefine_t__[51]
}
local __data_t__offPos = {
	[1] = __predefine_t__[8],
	[12] = __predefine_t__[16],
	[15] = __predefine_t__[12],
	[17] = __predefine_t__[8],
	["default"] = __predefine_t__[1],
	[5] = __predefine_t__[12],
	[7] = __predefine_t__[16],
	[9] = __predefine_t__[17],
	[8] = __predefine_t__[17]
}
local __data_t__activityIds = {
	[24] = __predefine_t__[23],
	[10] = __predefine_t__[14],
	[15] = __predefine_t__[23],
	[22] = __predefine_t__[23],
	[23] = __predefine_t__[23],
	[6] = __predefine_t__[14]
}
local __data_t__position = {
	["default"] = __predefine_t__[1]
}
local __data_t__unfreezeAward = {
	[19] = __predefine_t__[26],
	[18] = __predefine_t__[26],
	[20] = __predefine_t__[26],
	[21] = __predefine_t__[26],
	[16] = __predefine_t__[26]
}

csv['city_sprites'] = {
	[1] = {
		id = 1,
		group = 11,
		res = 'zhuchangjing/zjm_kbs.skel',
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[1],
		-- {['y'] = 80, ['x'] = 240, __size = 2}
		overture = true,
		active = false
	},
	[2] = {
		id = 2,
		type = 2,
		group = 21,
		res = 'zhuchangjing/zjm_zdpp.skel',
		zOrder = 15,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 30, ['x'] = -200, __size = 2}
	},
	[3] = {
		id = 3,
		type = 2,
		group = 21,
		res = 'zhuchangjing/zjm_sb_br.skel',
		zOrder = 12,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 140, ['x'] = -180, __size = 2}
	},
	[4] = {
		id = 4,
		type = 2,
		group = 21,
		res = 'zhuchangjing/zjm_fdpp.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 30, ['x'] = 180, __size = 2},
		overture = true
	},
	[5] = {
		id = 5,
		type = 2,
		group = 21,
		res = 'zhuchangjing/shadiao.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[5]
		-- {['y'] = 60, ['x'] = -90, __size = 2}
	},
	[6] = {
		id = 6,
		type = 3,
		group = 31,
		res = 'zhuchangjing/zjm_kdy.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 0, ['x'] = 120, __size = 2},
		overture = true,
		activityIds = __data_t__activityIds[6],
		-- {100105}
		activityPosition = {['y'] = 620, ['x'] = 3400, __size = 2},
		activityScale = 3
	},
	[7] = {
		id = 7,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_qqhs.skel',
		zOrder = 14,
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[7]
		-- {['y'] = 50, ['x'] = -130, __size = 2}
	},
	[8] = {
		id = 8,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_pkq.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[8]
		-- {['y'] = 40, ['x'] = -140, __size = 2}
	},
	[9] = {
		id = 9,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_mmx.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[9]
		-- {['y'] = 40, ['x'] = -140, __size = 2}
	},
	[10] = {
		id = 10,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_pqlz.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 0, ['x'] = 80, __size = 2},
		overture = true,
		activityIds = __data_t__activityIds[10],
		-- {100105}
		activityPosition = {['y'] = 372, ['x'] = 3617, __size = 2},
		activityScale = 4
	},
	[11] = {
		id = 11,
		type = 5,
		group = 51,
		res = 'zhuchangjing/zjm_dds.skel',
		zOrder = 12,
		randLib = 130,
		baibianRandLib = 131
	},
	[12] = {
		id = 12,
		type = 6,
		group = 61,
		res = 'zhuchangjing/zjm_scg.skel',
		zOrder = 12,
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[12]
		-- {['y'] = 50, ['x'] = -130, __size = 2}
	},
	[13] = {
		id = 13,
		type = 6,
		group = 61,
		res = 'zhuchangjing/zjm_trq.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = -100, ['x'] = -100, __size = 2}
	},
	[14] = {
		id = 14,
		type = 6,
		group = 61,
		res = 'zhuchangjing/zjm_xbb.skel',
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[15] = {
		id = 15,
		type = 7,
		group = 71,
		res = 'zhuchangjing/bitixiong.skel',
		zOrder = 15,
		touchSize = {['height'] = 100, ['width'] = 80, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[15],
		-- {['y'] = 60, ['x'] = -90, __size = 2}
		activityIds = __data_t__activityIds[15],
		-- {2485}
		activityPosition = {['y'] = 230, ['x'] = 2266, __size = 2},
		active = false
	},
	[16] = {
		id = 16,
		type = 8,
		group = 81,
		res = 'zhuchangjing/bojiaman.skel',
		zOrder = 13,
		touchSize = {['height'] = 100, ['width'] = 90, __size = 2},
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[16],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		offPos = {['y'] = 80, ['x'] = 80, __size = 2},
		overture = true,
		active = false
	},
	[17] = {
		id = 17,
		type = 9,
		group = 91,
		res = 'zhuchangjing/chuanzhuoxiong.skel',
		touchSize = {['height'] = 150, ['width'] = 160, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		offPos = __data_t__offPos[17],
		-- {['y'] = 80, ['x'] = 240, __size = 2}
		overture = true,
		active = false
	},
	[18] = {
		id = 18,
		type = 10,
		group = 101,
		res = 'zhuchangjing/daidaishou.skel',
		zOrder = 11,
		touchSize = __data_t__touchSize[18],
		-- {['height'] = 80, ['width'] = 70, __size = 2}
		scale = 2.4,
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[18],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		offPos = {['y'] = 40, ['x'] = 130, __size = 2},
		overture = true,
		active = false
	},
	[19] = {
		id = 19,
		type = 8,
		group = 81,
		res = 'zhuchangjing/haibaoqiu.skel',
		zOrder = 14,
		touchSize = {['height'] = 70, ['width'] = 70, __size = 2},
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[19],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		offPos = {['y'] = 40, ['x'] = 126, __size = 2},
		overture = true,
		active = false
	},
	[20] = {
		id = 20,
		type = 8,
		group = 81,
		res = 'zhuchangjing/kabishou2.skel',
		zOrder = 13,
		touchSize = __data_t__touchSize[20],
		-- {['height'] = 120, ['width'] = 80, __size = 2}
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[20],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		offPos = {['y'] = 30, ['x'] = 170, __size = 2},
		overture = true,
		active = false
	},
	[21] = {
		id = 21,
		type = 10,
		group = 101,
		res = 'zhuchangjing/kedaya.skel',
		zOrder = 12,
		touchSize = __data_t__touchSize[21],
		-- {['height'] = 80, ['width'] = 70, __size = 2}
		scale = 2.4,
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[21],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		offPos = {['y'] = 60, ['x'] = -74, __size = 2},
		active = false
	},
	[22] = {
		id = 22,
		type = 7,
		group = 71,
		res = 'zhuchangjing/minibing.skel',
		zOrder = 13,
		touchSize = {['height'] = 60, ['width'] = 60, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 44, ['x'] = -82, __size = 2},
		activityIds = __data_t__activityIds[22],
		-- {2485}
		activityPosition = {['y'] = 481, ['x'] = 2303, __size = 2},
		active = false
	},
	[23] = {
		id = 23,
		type = 7,
		group = 71,
		res = 'zhuchangjing/moqiangrenou.skel',
		zOrder = 14,
		touchSize = {['height'] = 170, ['width'] = 100, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 144, ['x'] = 56, __size = 2},
		overture = true,
		activityIds = __data_t__activityIds[23],
		-- {2485}
		activityPosition = {['y'] = 233, ['x'] = 2670, __size = 2},
		active = false
	},
	[24] = {
		id = 24,
		type = 7,
		group = 71,
		res = 'zhuchangjing/suannaixian.skel',
		zOrder = 13,
		touchSize = {['height'] = 130, ['width'] = 100, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = 120, ['x'] = -90, __size = 2},
		activityIds = __data_t__activityIds[24],
		-- {2485}
		activityPosition = {['y'] = 243, ['x'] = 2435, __size = 2},
		active = false
	},
	[25] = {
		id = 25,
		type = 11,
		group = 111,
		res = 'zhuchangjing/pikaqiu.skel',
		zOrder = 13,
		touchSize = __data_t__touchSize[25],
		-- {['height'] = 120, ['width'] = 80, __size = 2}
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = -20, ['x'] = -154, __size = 2},
		active = false
	},
	[26] = {
		id = 26,
		type = 11,
		group = 111,
		res = 'zhuchangjing/miaomiao.skel',
		zOrder = 13,
		touchSize = __data_t__touchSize[26],
		-- {['height'] = 120, ['width'] = 80, __size = 2}
		randLib = 130,
		baibianRandLib = 131,
		offPos = {['y'] = -40, ['x'] = -74, __size = 2},
		active = false
	},
	[27] = {
		id = 27,
		type = 12,
		group = 121,
		res = 'zhuchangjingpokmon/wsjzh.skel',
		touchSize = {['height'] = 200, ['width'] = 200, __size = 2},
		randLib = 130,
		shape_shifter = false
	},
	[1000] = {
		id = 1000,
		type = 1000,
		group = 10001,
		res = 'zhuchangjing/zjm_mnq1.skel',
		zOrder = 2,
		touchSize = {['height'] = 80, ['width'] = 120, __size = 2},
		action = false,
		randLib = 132,
		activityIds = {2320},
		activityPosition = {['y'] = 551, ['x'] = 463, __size = 2}
	},
	[1001] = {
		id = 1001,
		type = 1000,
		group = 10002,
		res = 'zhuchangjing/zjm_mnq2.skel',
		zOrder = 2,
		touchSize = __data_t__touchSize[1001],
		-- {['height'] = 120, ['width'] = 120, __size = 2}
		action = false,
		randLib = 132
	},
	[1002] = {
		id = 1002,
		weight = 0,
		type = 1000,
		group = 10003,
		res = 'zhuchangjing/zjm_mnq3.skel',
		zOrder = 2,
		touchSize = __data_t__touchSize[1002],
		-- {['height'] = 120, ['width'] = 120, __size = 2}
		action = false,
		randLib = 132
	},
	[1003] = {
		id = 1003,
		type = 1000,
		group = 10004,
		res = 'zhuchangjing/zjm_mnq3.skel',
		zOrder = 2,
		touchSize = {['height'] = 200, ['width'] = 100, __size = 2},
		action = false,
		randLib = 132
	},

	__size = 31,
	__default = {
		__index = {
			weight = 10,
			type = 1,
			group = 1,
			res = '',
			position = __data_t__position["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			position_tw = {['y'] = 1, ['x'] = 0, __size = 2},
			position_en = {['y'] = 2, ['x'] = 0, __size = 2},
			position_vn = {['y'] = 3, ['x'] = 0, __size = 2},
			position_kr = {['y'] = 4, ['x'] = 0, __size = 2},
			zOrder = 10,
			scale = 2,
			action = true,
			randLib = 0,
			unfreezeAward = {__size = 0},
			shape_shifter = true,
			baibianRandLib = 0,
			chattext1 = '',
			chattext1_tw = '',
			chattext1_en = '',
			chattext1_vn = '',
			chattext1_kr = '',
			chattext2 = '',
			chattext2_tw = '',
			chattext2_en = '',
			chattext2_vn = '',
			chattext2_kr = '',
			chattext3 = '',
			chattext3_tw = '',
			chattext3_en = '',
			chattext3_vn = '',
			chattext3_kr = '',
			offPos = __data_t__offPos["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			overture = false,
			activityIds = {},
			activityPosition = __data_t__activityPosition["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			activityScale = 2,
			active = true
		}
	}
}
return csv.city_sprites