--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[4] = {[150] = 1, __size = 1}, 
	[10] = {[150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, [162] = 1, __size = 6}, 
	[11] = {[150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, [162] = 1, __size = 6}, 
	[12] = {[150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, [162] = 1, __size = 6}, 
	[13] = {[151] = 1, [150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, __size = 6}, 
	[14] = {[151] = 1, [150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, __size = 6}, 
	[15] = {[151] = 1, [150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, __size = 6}, 
	[16] = {[150] = 1, [153] = 1, [152] = 4, [160] = 1, [154] = 3, __size = 5}, 
	[25] = {[10022] = 1, __size = 1}, 
	[26] = {[10023] = 1, __size = 1}, 
	[31] = {[10021] = 1, __size = 1}, 
	[32] = {[10021] = 5, __size = 1}, 
	[33] = {[40021] = 1, __size = 1}, 
	[34] = {[40021] = 5, __size = 1}, 
	[35] = {[40022] = 1, __size = 1}, 
	[36] = {[50021] = 1, __size = 1}, 
	[37] = {[50021] = 5, __size = 1}, 
	[38] = {[50022] = 1, __size = 1}, __size = 19}
local __data_t__lotteryType2 = {
	[133] = __predefine_t__[25],
	[132] = __predefine_t__[26],
	[131] = __predefine_t__[25],
	[130] = __predefine_t__[26],
	[137] = __predefine_t__[25],
	[136] = __predefine_t__[26],
	[135] = __predefine_t__[25],
	[134] = __predefine_t__[26],
	[139] = __predefine_t__[25],
	[138] = __predefine_t__[26],
	[344] = __predefine_t__[32],
	[345] = __predefine_t__[25],
	[346] = __predefine_t__[31],
	[347] = __predefine_t__[32],
	[403] = __predefine_t__[31],
	[341] = __predefine_t__[31],
	[342] = __predefine_t__[32],
	[343] = __predefine_t__[31],
	[348] = __predefine_t__[25],
	[349] = __predefine_t__[25],
	[409] = __predefine_t__[31],
	[408] = __predefine_t__[25],
	[454] = __predefine_t__[36],
	[120] = __predefine_t__[26],
	[121] = __predefine_t__[25],
	[122] = __predefine_t__[26],
	[123] = __predefine_t__[25],
	[124] = __predefine_t__[26],
	[125] = __predefine_t__[25],
	[126] = __predefine_t__[26],
	[127] = __predefine_t__[25],
	[128] = __predefine_t__[26],
	[129] = __predefine_t__[25],
	[442] = __predefine_t__[36],
	[457] = __predefine_t__[36],
	[423] = __predefine_t__[25],
	[422] = __predefine_t__[32],
	[54] = __predefine_t__[12],
	[51] = __predefine_t__[12],
	[53] = __predefine_t__[12],
	[52] = __predefine_t__[12],
	[414] = __predefine_t__[25],
	[415] = __predefine_t__[31],
	[416] = __predefine_t__[32],
	[417] = __predefine_t__[25],
	[410] = __predefine_t__[32],
	[411] = __predefine_t__[25],
	[412] = __predefine_t__[31],
	[413] = __predefine_t__[32],
	[371] = __predefine_t__[32],
	[370] = __predefine_t__[31],
	[373] = __predefine_t__[31],
	[372] = __predefine_t__[25],
	[375] = __predefine_t__[25],
	[374] = __predefine_t__[32],
	[312] = __predefine_t__[32],
	[311] = __predefine_t__[31],
	[115] = __predefine_t__[25],
	[114] = __predefine_t__[26],
	[117] = __predefine_t__[25],
	[116] = __predefine_t__[26],
	[111] = __predefine_t__[25],
	[110] = __predefine_t__[26],
	[113] = __predefine_t__[25],
	[112] = __predefine_t__[26],
	[119] = __predefine_t__[25],
	[118] = __predefine_t__[26],
	[429] = __predefine_t__[25],
	[428] = __predefine_t__[32],
	[368] = __predefine_t__[25],
	[369] = __predefine_t__[25],
	[366] = __predefine_t__[32],
	[367] = __predefine_t__[25],
	[364] = __predefine_t__[25],
	[365] = __predefine_t__[31],
	[362] = __predefine_t__[31],
	[363] = __predefine_t__[32],
	[360] = __predefine_t__[32],
	[361] = __predefine_t__[25],
	[449] = __predefine_t__[37],
	[440] = __predefine_t__[37],
	[420] = __predefine_t__[25],
	[443] = __predefine_t__[37],
	[301] = __predefine_t__[31],
	[302] = __predefine_t__[32],
	[421] = __predefine_t__[31],
	[447] = __predefine_t__[25],
	[446] = __predefine_t__[37],
	[445] = __predefine_t__[36],
	[444] = __predefine_t__[25],
	[108] = __predefine_t__[26],
	[109] = __predefine_t__[25],
	[102] = __predefine_t__[25],
	[103] = __predefine_t__[25],
	[106] = __predefine_t__[26],
	[107] = __predefine_t__[25],
	[104] = __predefine_t__[25],
	[105] = __predefine_t__[25],
	[418] = __predefine_t__[31],
	[419] = __predefine_t__[32],
	[438] = __predefine_t__[38],
	[439] = __predefine_t__[36],
	[436] = __predefine_t__[36],
	[437] = __predefine_t__[37],
	[434] = __predefine_t__[37],
	[435] = __predefine_t__[38],
	[432] = __predefine_t__[35],
	[433] = __predefine_t__[36],
	[430] = __predefine_t__[33],
	[431] = __predefine_t__[34],
	[458] = __predefine_t__[37],
	[459] = __predefine_t__[25],
	[450] = __predefine_t__[25],
	[451] = __predefine_t__[36],
	[452] = __predefine_t__[37],
	[453] = __predefine_t__[25],
	[331] = __predefine_t__[31],
	[455] = __predefine_t__[37],
	[456] = __predefine_t__[25],
	[332] = __predefine_t__[32],
	["default"] = __predefine_t__[1],
	[61] = __predefine_t__[15],
	[62] = __predefine_t__[15],
	[63] = __predefine_t__[15],
	[64] = __predefine_t__[15],
	[407] = __predefine_t__[32],
	[406] = __predefine_t__[31],
	[405] = __predefine_t__[25],
	[404] = __predefine_t__[32],
	[402] = __predefine_t__[25],
	[425] = __predefine_t__[32],
	[401] = __predefine_t__[32],
	[400] = __predefine_t__[31],
	[424] = __predefine_t__[31],
	[427] = __predefine_t__[31],
	[426] = __predefine_t__[25],
	[448] = __predefine_t__[36],
	[441] = __predefine_t__[25],
	[322] = __predefine_t__[32],
	[321] = __predefine_t__[31],
	[142] = __predefine_t__[26],
	[143] = __predefine_t__[25],
	[140] = __predefine_t__[26],
	[141] = __predefine_t__[25],
	[357] = __predefine_t__[31],
	[356] = __predefine_t__[32],
	[355] = __predefine_t__[31],
	[354] = __predefine_t__[25],
	[353] = __predefine_t__[25],
	[352] = __predefine_t__[32],
	[351] = __predefine_t__[31],
	[350] = __predefine_t__[25],
	[359] = __predefine_t__[31],
	[358] = __predefine_t__[32]
}
local __data_t__lotteryType8 = {
	["default"] = __predefine_t__[1],
	[65] = __predefine_t__[16]
}
local __data_t__lotteryType9 = {
	["default"] = __predefine_t__[1]
}
local __data_t__lotteryType6 = {
	["default"] = __predefine_t__[1]
}
local __data_t__lotteryType7 = {
	["default"] = __predefine_t__[1]
}
local __data_t__lotteryType4 = {
	["default"] = __predefine_t__[1]
}
local __data_t__lotteryType5 = {
	["default"] = __predefine_t__[1]
}
local __data_t__lotteryType10 = {
	["default"] = __predefine_t__[1]
}
local __data_t__lotteryType3 = {
	[54] = __predefine_t__[10],
	[51] = __predefine_t__[10],
	[53] = __predefine_t__[10],
	[52] = __predefine_t__[10],
	["default"] = __predefine_t__[1],
	[61] = __predefine_t__[13],
	[62] = __predefine_t__[13],
	[63] = __predefine_t__[13],
	[64] = __predefine_t__[13],
	[65] = __predefine_t__[16]
}
local __data_t__lotteryType1 = {
	[133] = __predefine_t__[25],
	[132] = __predefine_t__[26],
	[131] = __predefine_t__[25],
	[130] = __predefine_t__[26],
	[137] = __predefine_t__[25],
	[136] = __predefine_t__[26],
	[135] = __predefine_t__[25],
	[134] = __predefine_t__[26],
	[139] = __predefine_t__[25],
	[138] = __predefine_t__[26],
	[344] = __predefine_t__[32],
	[345] = __predefine_t__[25],
	[346] = __predefine_t__[31],
	[347] = __predefine_t__[32],
	[403] = __predefine_t__[31],
	[341] = __predefine_t__[31],
	[342] = __predefine_t__[32],
	[343] = __predefine_t__[31],
	[348] = __predefine_t__[25],
	[349] = __predefine_t__[25],
	[409] = __predefine_t__[31],
	[408] = __predefine_t__[25],
	[454] = __predefine_t__[36],
	[120] = __predefine_t__[26],
	[121] = __predefine_t__[25],
	[122] = __predefine_t__[26],
	[123] = __predefine_t__[25],
	[124] = __predefine_t__[26],
	[125] = __predefine_t__[25],
	[126] = __predefine_t__[26],
	[127] = __predefine_t__[25],
	[128] = __predefine_t__[26],
	[129] = __predefine_t__[25],
	[442] = __predefine_t__[36],
	[457] = __predefine_t__[36],
	[423] = __predefine_t__[25],
	[422] = __predefine_t__[32],
	[54] = __predefine_t__[11],
	[51] = __predefine_t__[11],
	[53] = __predefine_t__[11],
	[52] = __predefine_t__[11],
	[414] = __predefine_t__[25],
	[415] = __predefine_t__[31],
	[416] = __predefine_t__[32],
	[417] = __predefine_t__[25],
	[410] = __predefine_t__[32],
	[411] = __predefine_t__[25],
	[412] = __predefine_t__[31],
	[413] = __predefine_t__[32],
	[371] = __predefine_t__[32],
	[370] = __predefine_t__[31],
	[373] = __predefine_t__[31],
	[372] = __predefine_t__[25],
	[375] = __predefine_t__[25],
	[374] = __predefine_t__[32],
	[312] = __predefine_t__[32],
	[311] = __predefine_t__[31],
	[115] = __predefine_t__[25],
	[114] = __predefine_t__[26],
	[117] = __predefine_t__[25],
	[116] = __predefine_t__[26],
	[111] = __predefine_t__[25],
	[110] = __predefine_t__[26],
	[113] = __predefine_t__[25],
	[112] = __predefine_t__[26],
	[119] = __predefine_t__[25],
	[118] = __predefine_t__[26],
	[429] = __predefine_t__[25],
	[428] = __predefine_t__[32],
	[368] = __predefine_t__[25],
	[369] = __predefine_t__[25],
	[366] = __predefine_t__[32],
	[367] = __predefine_t__[25],
	[364] = __predefine_t__[25],
	[365] = __predefine_t__[31],
	[362] = __predefine_t__[31],
	[363] = __predefine_t__[32],
	[360] = __predefine_t__[32],
	[361] = __predefine_t__[25],
	[449] = __predefine_t__[37],
	[440] = __predefine_t__[37],
	[420] = __predefine_t__[25],
	[443] = __predefine_t__[37],
	[301] = __predefine_t__[31],
	[302] = __predefine_t__[32],
	[421] = __predefine_t__[31],
	[447] = __predefine_t__[25],
	[446] = __predefine_t__[37],
	[445] = __predefine_t__[36],
	[444] = __predefine_t__[25],
	[108] = __predefine_t__[26],
	[109] = __predefine_t__[25],
	[102] = __predefine_t__[25],
	[103] = __predefine_t__[25],
	[106] = __predefine_t__[26],
	[107] = __predefine_t__[25],
	[104] = __predefine_t__[25],
	[105] = __predefine_t__[25],
	[418] = __predefine_t__[31],
	[419] = __predefine_t__[32],
	[438] = __predefine_t__[38],
	[439] = __predefine_t__[36],
	[436] = __predefine_t__[36],
	[437] = __predefine_t__[37],
	[434] = __predefine_t__[37],
	[435] = __predefine_t__[38],
	[432] = __predefine_t__[35],
	[433] = __predefine_t__[36],
	[430] = __predefine_t__[33],
	[431] = __predefine_t__[34],
	[458] = __predefine_t__[37],
	[459] = __predefine_t__[25],
	[450] = __predefine_t__[25],
	[451] = __predefine_t__[36],
	[452] = __predefine_t__[37],
	[453] = __predefine_t__[25],
	[331] = __predefine_t__[31],
	[455] = __predefine_t__[37],
	[456] = __predefine_t__[25],
	[332] = __predefine_t__[32],
	["default"] = __predefine_t__[1],
	[61] = __predefine_t__[14],
	[62] = __predefine_t__[14],
	[63] = __predefine_t__[14],
	[64] = __predefine_t__[14],
	[407] = __predefine_t__[32],
	[406] = __predefine_t__[31],
	[405] = __predefine_t__[25],
	[404] = __predefine_t__[32],
	[402] = __predefine_t__[25],
	[425] = __predefine_t__[32],
	[401] = __predefine_t__[32],
	[400] = __predefine_t__[31],
	[424] = __predefine_t__[31],
	[13] = __predefine_t__[4],
	[12] = __predefine_t__[4],
	[427] = __predefine_t__[31],
	[426] = __predefine_t__[25],
	[448] = __predefine_t__[36],
	[441] = __predefine_t__[25],
	[322] = __predefine_t__[32],
	[321] = __predefine_t__[31],
	[142] = __predefine_t__[26],
	[143] = __predefine_t__[25],
	[140] = __predefine_t__[26],
	[141] = __predefine_t__[25],
	[357] = __predefine_t__[31],
	[356] = __predefine_t__[32],
	[355] = __predefine_t__[31],
	[354] = __predefine_t__[25],
	[353] = __predefine_t__[25],
	[352] = __predefine_t__[32],
	[351] = __predefine_t__[31],
	[350] = __predefine_t__[25],
	[359] = __predefine_t__[31],
	[358] = __predefine_t__[32]
}

csv['draw_equip'] = {
	[10] = {
		id = 10,
		drawType = 'rmb1',
		startCount = 40,
		effectLimit = 1,
		probLimit = 0.5,
		lotteryType1 = {[151] = 1, __size = 1},
		probInit = 0.1,
		probMiniTimes = 10,
		lotteryWeight1 = 100,
		probEffectInterval = 99999,
		drawTriggerTimes = 40
	},
	[11] = {
		id = 11,
		drawType = 'rmb1',
		startCount = 50,
		effectLimit = 1,
		probLimit = 0.5,
		lotteryType1 = {[162] = 1, __size = 1},
		probInit = 0.1,
		probStep = 0.03,
		probMiniTimes = 10,
		lotteryWeight1 = 100,
		probEffectInterval = 99999,
		drawTriggerTimes = 30
	},
	[12] = {
		id = 12,
		drawType = 'rmb1',
		drawTriggerType = 3,
		lotteryType1 = __data_t__lotteryType1[12],
		-- {[150] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[13] = {
		id = 13,
		drawType = 'rmb1',
		drawTriggerType = 4,
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[13],
		-- {[150] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[14] = {
		id = 14,
		drawType = 'rmb1',
		lotteryWeight5 = 5,
		drawTriggerType = 0,
		lotteryType3 = {[154] = 1, __size = 1},
		lotteryType1 = {[152] = 1, __size = 1},
		lotteryType5 = {[161] = 1, __size = 1},
		lotteryWeight4 = 15,
		lotteryWeight2 = 15,
		lotteryType4 = {[160] = 1, __size = 1},
		lotteryWeight3 = 15,
		lotteryType2 = {[153] = 1, __size = 1},
		lotteryWeight1 = 45,
		drawTriggerTimes = 2
	},
	[51] = {
		id = 51,
		drawType = 'rmb10',
		startCount = 19,
		weightEnd = 0.09,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[51],
		-- {[150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		lotteryType1 = __data_t__lotteryType1[51],
		-- {[150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, [162] = 1, __size = 6}
		weightStart = 0.04,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[51],
		-- {[150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[52] = {
		id = 52,
		drawType = 'rmb10',
		startCount = 11,
		weightEnd = 0.15,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[52],
		-- {[150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[52],
		-- {[150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, [162] = 1, __size = 6}
		weightStart = 0.08,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[52],
		-- {[150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[53] = {
		id = 53,
		drawType = 'rmb10',
		startCount = 5,
		weightEnd = 0.3,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[53],
		-- {[150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[53],
		-- {[150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, [162] = 1, __size = 6}
		weightStart = 0.2,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[53],
		-- {[150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[54] = {
		id = 54,
		drawType = 'rmb10',
		startCount = 4,
		weightEnd = 1,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[54],
		-- {[150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[54],
		-- {[150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, [162] = 1, __size = 6}
		weightStart = 1,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[54],
		-- {[150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, [162] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[61] = {
		id = 61,
		drawType = 'rmb10',
		startCount = 14,
		weightEnd = 0.12,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[61],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, __size = 6}
		lotteryType1 = __data_t__lotteryType1[61],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, __size = 6}
		weightStart = 0.06,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[61],
		-- {[151] = 1, [150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[62] = {
		id = 62,
		drawType = 'rmb10',
		startCount = 7,
		weightEnd = 0.2,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[62],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, __size = 6}
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[62],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, __size = 6}
		weightStart = 0.1,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[62],
		-- {[151] = 1, [150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[63] = {
		id = 63,
		drawType = 'rmb10',
		startCount = 3,
		weightEnd = 0.3,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[63],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, __size = 6}
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[63],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, __size = 6}
		weightStart = 0.2,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[63],
		-- {[151] = 1, [150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[64] = {
		id = 64,
		drawType = 'rmb10',
		startCount = 2,
		weightEnd = 1,
		drawTriggerType = 1,
		lotteryType3 = __data_t__lotteryType3[64],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, __size = 6}
		effectLimit = 1,
		lotteryType1 = __data_t__lotteryType1[64],
		-- {[151] = 1, [150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, __size = 6}
		weightStart = 1,
		lotteryWeight2 = 100,
		lotteryWeight3 = 100,
		lotteryType2 = __data_t__lotteryType2[64],
		-- {[151] = 1, [150] = 1, [153] = 2, [152] = 4, [154] = 1, [160] = 1, __size = 6}
		lotteryWeight1 = 100,
		drawTriggerTimes = 10
	},
	[65] = {
		id = 65,
		drawType = 'rmb10',
		lotteryWeight5 = 100,
		drawTriggerType = 0,
		lotteryType3 = __data_t__lotteryType3[65],
		-- {[150] = 1, [153] = 1, [152] = 4, [160] = 1, [154] = 3, __size = 5}
		lotteryType1 = {[150] = 1, [153] = 2, [152] = 4, [160] = 1, [154] = 2, __size = 5},
		lotteryType5 = {[150] = 1, [153] = 2, [152] = 5, [160] = 1, [154] = 1, __size = 5},
		lotteryType7 = {[150] = 1, [153] = 1, [152] = 5, [154] = 2, [161] = 1, __size = 5},
		lotteryWeight4 = 100,
		lotteryWeight2 = 100,
		lotteryType8 = __data_t__lotteryType8[65],
		-- {[150] = 1, [153] = 1, [152] = 4, [160] = 1, [154] = 3, __size = 5}
		lotteryWeight7 = 100,
		lotteryWeight6 = 100,
		lotteryType6 = {[150] = 1, [153] = 1, [152] = 5, [154] = 1, [160] = 1, [161] = 1, __size = 6},
		lotteryType4 = {[150] = 1, [153] = 1, [152] = 5, [160] = 1, [154] = 2, __size = 5},
		lotteryWeight3 = 100,
		lotteryType2 = {[150] = 1, [153] = 1, [152] = 4, [154] = 2, [160] = 1, [161] = 1, __size = 6},
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[101] = {
		id = 101,
		drawType = 'recharge_wheel_120010',
		drawTriggerType = 0,
		lotteryType1 = {[20001] = 1, __size = 1},
		lotteryWeight2 = 1,
		lotteryType2 = {[20002] = 1, __size = 1},
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[102] = {
		id = 102,
		drawType = 'recharge_wheel_12001',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[102],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[102],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[103] = {
		id = 103,
		drawType = 'recharge_wheel_1277',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[103],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[103],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[104] = {
		id = 104,
		drawType = 'recharge_wheel_1357',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[104],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[104],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[105] = {
		id = 105,
		drawType = 'recharge_wheel_1487',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[105],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[105],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[106] = {
		id = 106,
		drawType = 'recharge_wheel_1540',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[106],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[106],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[107] = {
		id = 107,
		drawType = 'recharge_wheel_1617',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[107],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[107],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[108] = {
		id = 108,
		drawType = 'recharge_wheel_1670',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[108],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[108],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[109] = {
		id = 109,
		drawType = 'recharge_wheel_1737',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[109],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[109],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[110] = {
		id = 110,
		drawType = 'recharge_wheel_1790',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[110],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[110],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[111] = {
		id = 111,
		drawType = 'recharge_wheel_1837',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[111],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[111],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[112] = {
		id = 112,
		drawType = 'recharge_wheel_1870',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[112],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[112],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[113] = {
		id = 113,
		drawType = 'recharge_wheel_1917',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[113],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[113],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[114] = {
		id = 114,
		drawType = 'recharge_wheel_1960',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[114],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[114],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[115] = {
		id = 115,
		drawType = 'recharge_wheel_2007',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[115],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[115],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[116] = {
		id = 116,
		drawType = 'recharge_wheel_2070',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[116],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[116],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[117] = {
		id = 117,
		drawType = 'recharge_wheel_2107',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[117],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[117],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[118] = {
		id = 118,
		drawType = 'recharge_wheel_2130',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[118],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[118],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[119] = {
		id = 119,
		drawType = 'recharge_wheel_2217',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[119],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[119],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[120] = {
		id = 120,
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[120],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[120],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[121] = {
		id = 121,
		drawType = 'recharge_wheel_2287',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[121],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[121],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[122] = {
		id = 122,
		drawType = 'recharge_wheel_2330',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[122],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[122],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[123] = {
		id = 123,
		drawType = 'recharge_wheel_2367',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[123],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[123],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[124] = {
		id = 124,
		drawType = 'recharge_wheel_2410',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[124],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[124],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[125] = {
		id = 125,
		drawType = 'recharge_wheel_2467',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[125],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[125],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[126] = {
		id = 126,
		drawType = 'recharge_wheel_2500',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[126],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[126],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[127] = {
		id = 127,
		drawType = 'recharge_wheel_2567',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[127],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[127],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[128] = {
		id = 128,
		drawType = 'recharge_wheel_2600',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[128],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[128],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[129] = {
		id = 129,
		drawType = 'recharge_wheel_2667',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[129],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[129],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[130] = {
		id = 130,
		drawType = 'recharge_wheel_2690',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[130],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[130],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[131] = {
		id = 131,
		drawType = 'recharge_wheel_2737',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[131],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[131],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[132] = {
		id = 132,
		drawType = 'recharge_wheel_2790',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[132],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[132],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[133] = {
		id = 133,
		drawType = 'recharge_wheel_2847',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[133],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[133],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[134] = {
		id = 134,
		drawType = 'recharge_wheel_2870',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[134],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[134],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[135] = {
		id = 135,
		drawType = 'recharge_wheel_2937',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[135],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[135],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[136] = {
		id = 136,
		drawType = 'recharge_wheel_2960',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[136],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[136],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[137] = {
		id = 137,
		drawType = 'recharge_wheel_3017',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[137],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[137],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[138] = {
		id = 138,
		drawType = 'recharge_wheel_3060',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[138],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[138],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[139] = {
		id = 139,
		drawType = 'recharge_wheel_3107',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[139],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[139],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[140] = {
		id = 140,
		drawType = 'recharge_wheel_3140',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[140],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[140],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[141] = {
		id = 141,
		drawType = 'recharge_wheel_3187',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[141],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[141],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[142] = {
		id = 142,
		drawType = 'recharge_wheel_3260',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[142],
		-- {[10023] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[142],
		-- {[10023] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[143] = {
		id = 143,
		drawType = 'recharge_wheel_20041',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[143],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[143],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[201] = {
		id = 201,
		drawType = 'liveness_wheel1_13001',
		drawTriggerType = 0,
		lotteryType1 = {[20011] = 1, __size = 1},
		lotteryWeight2 = 10,
		lotteryType2 = {[20012] = 1, __size = 1},
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[202] = {
		id = 202,
		drawType = 'liveness_wheel5_13001',
		drawTriggerType = 0,
		lotteryType1 = {[20011] = 5, __size = 1},
		lotteryWeight2 = 1,
		lotteryType2 = {[20011] = 4, [20012] = 1, __size = 2},
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[301] = {
		id = 301,
		drawType = 'liveness_wheel1_20076',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[301],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[301],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[302] = {
		id = 302,
		drawType = 'liveness_wheel5_20076',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[302],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[302],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[311] = {
		id = 311,
		drawType = 'liveness_wheel1_60002',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[311],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[311],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[312] = {
		id = 312,
		drawType = 'liveness_wheel5_60002',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[312],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[312],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[321] = {
		id = 321,
		drawType = 'liveness_wheel1_2052',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[321],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[321],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[322] = {
		id = 322,
		drawType = 'liveness_wheel5_2052',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[322],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[322],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[331] = {
		id = 331,
		drawType = 'liveness_wheel1_2520',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[331],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[331],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[332] = {
		id = 332,
		drawType = 'liveness_wheel5_2520',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[332],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[332],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[341] = {
		id = 341,
		drawType = 'liveness_wheel1_3270',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[341],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[341],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[342] = {
		id = 342,
		drawType = 'liveness_wheel5_3270',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[342],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[342],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[343] = {
		id = 343,
		drawType = 'liveness_wheel1_202309052',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[343],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[343],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[344] = {
		id = 344,
		drawType = 'liveness_wheel5_202309052',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[344],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[344],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[345] = {
		id = 345,
		drawType = 'recharge_wheel_202309049',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[345],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[345],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[346] = {
		id = 346,
		drawType = 'liveness_wheel1_202311008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[346],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[346],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[347] = {
		id = 347,
		drawType = 'liveness_wheel5_202311008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[347],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[347],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[348] = {
		id = 348,
		drawType = 'recharge_wheel_202310035',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[348],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[348],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[349] = {
		id = 349,
		drawType = 'recharge_wheel_202310059',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[349],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[349],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[350] = {
		id = 350,
		drawType = 'recharge_wheel_202311029',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[350],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[350],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[351] = {
		id = 351,
		drawType = 'liveness_wheel1_202312008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[351],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[351],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[352] = {
		id = 352,
		drawType = 'liveness_wheel5_202312008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[352],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[352],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[353] = {
		id = 353,
		drawType = 'recharge_wheel_202312041',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[353],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[353],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[354] = {
		id = 354,
		drawType = 'recharge_wheel_202401024',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[354],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[354],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[355] = {
		id = 355,
		drawType = 'liveness_wheel1_202401032',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[355],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[355],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[356] = {
		id = 356,
		drawType = 'liveness_wheel5_202401032',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[356],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[356],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[357] = {
		id = 357,
		drawType = 'liveness_wheel1_202401062',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[357],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[357],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[358] = {
		id = 358,
		drawType = 'liveness_wheel5_202401062',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[358],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[358],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[359] = {
		id = 359,
		drawType = 'liveness_wheel1_202402008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[359],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[359],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[360] = {
		id = 360,
		drawType = 'liveness_wheel5_202402008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[360],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[360],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[361] = {
		id = 361,
		drawType = 'recharge_wheel_202402014',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[361],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[361],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[362] = {
		id = 362,
		drawType = 'liveness_wheel1_202402061',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[362],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[362],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[363] = {
		id = 363,
		drawType = 'liveness_wheel5_202402061',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[363],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[363],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[364] = {
		id = 364,
		drawType = 'recharge_wheel_202402062',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[364],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[364],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[365] = {
		id = 365,
		drawType = 'liveness_wheel1_202403008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[365],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[365],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[366] = {
		id = 366,
		drawType = 'liveness_wheel5_202403008',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[366],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[366],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[367] = {
		id = 367,
		drawType = 'recharge_wheel_202403011',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[367],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[367],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[368] = {
		id = 368,
		drawType = 'recharge_wheel_202403058',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[368],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[368],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[369] = {
		id = 369,
		drawType = 'recharge_wheel_202403083',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[369],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[369],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[370] = {
		id = 370,
		drawType = 'liveness_wheel1_202404076',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[370],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[370],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[371] = {
		id = 371,
		drawType = 'liveness_wheel5_202404076',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[371],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[371],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[372] = {
		id = 372,
		drawType = 'recharge_wheel_202404078',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[372],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[372],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[373] = {
		id = 373,
		drawType = 'liveness_wheel1_202404127',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[373],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[373],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[374] = {
		id = 374,
		drawType = 'liveness_wheel5_202404127',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[374],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[374],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[375] = {
		id = 375,
		drawType = 'recharge_wheel_202404129',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[375],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[375],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[400] = {
		id = 400,
		drawType = 'liveness_wheel1_80214',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[400],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[400],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[401] = {
		id = 401,
		drawType = 'liveness_wheel5_80214',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[401],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[401],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[402] = {
		id = 402,
		drawType = 'recharge_wheel_80213',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[402],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[402],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[403] = {
		id = 403,
		drawType = 'liveness_wheel1_80222',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[403],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[403],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[404] = {
		id = 404,
		drawType = 'liveness_wheel5_80222',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[404],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[404],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[405] = {
		id = 405,
		drawType = 'recharge_wheel_80221',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[405],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[405],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[406] = {
		id = 406,
		drawType = 'liveness_wheel1_80252',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[406],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[406],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[407] = {
		id = 407,
		drawType = 'liveness_wheel5_80252',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[407],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[407],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[408] = {
		id = 408,
		drawType = 'recharge_wheel_80251',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[408],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[408],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[409] = {
		id = 409,
		drawType = 'liveness_wheel1_80262',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[409],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[409],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[410] = {
		id = 410,
		drawType = 'liveness_wheel5_80262',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[410],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[410],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[411] = {
		id = 411,
		drawType = 'recharge_wheel_80261',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[411],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[411],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[412] = {
		id = 412,
		drawType = 'liveness_wheel1_80285',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[412],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[412],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[413] = {
		id = 413,
		drawType = 'liveness_wheel5_80285',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[413],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[413],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[414] = {
		id = 414,
		drawType = 'recharge_wheel_80284',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[414],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[414],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[415] = {
		id = 415,
		drawType = 'liveness_wheel1_80294',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[415],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[415],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[416] = {
		id = 416,
		drawType = 'liveness_wheel5_80294',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[416],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[416],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[417] = {
		id = 417,
		drawType = 'recharge_wheel_80293',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[417],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[417],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[418] = {
		id = 418,
		drawType = 'liveness_wheel1_80308',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[418],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[418],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[419] = {
		id = 419,
		drawType = 'liveness_wheel5_80308',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[419],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[419],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[420] = {
		id = 420,
		drawType = 'recharge_wheel_80307',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[420],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[420],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[421] = {
		id = 421,
		drawType = 'liveness_wheel1_80323',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[421],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[421],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[422] = {
		id = 422,
		drawType = 'liveness_wheel5_80323',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[422],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[422],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[423] = {
		id = 423,
		drawType = 'recharge_wheel_80322',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[423],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[423],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[424] = {
		id = 424,
		drawType = 'liveness_wheel1_80328',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[424],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[424],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[425] = {
		id = 425,
		drawType = 'liveness_wheel5_80328',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[425],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[425],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[426] = {
		id = 426,
		drawType = 'recharge_wheel_80327',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[426],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[426],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[427] = {
		id = 427,
		drawType = 'liveness_wheel1_80340',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[427],
		-- {[10021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[427],
		-- {[10021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[428] = {
		id = 428,
		drawType = 'liveness_wheel5_80340',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[428],
		-- {[10021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[428],
		-- {[10021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[429] = {
		id = 429,
		drawType = 'recharge_wheel_80339',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[429],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[429],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[430] = {
		id = 430,
		drawType = 'liveness_wheel1_80355',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[430],
		-- {[40021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[430],
		-- {[40021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[431] = {
		id = 431,
		drawType = 'liveness_wheel5_80355',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[431],
		-- {[40021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[431],
		-- {[40021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[432] = {
		id = 432,
		drawType = 'recharge_wheel_80354',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[432],
		-- {[40022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[432],
		-- {[40022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[433] = {
		id = 433,
		drawType = 'liveness_wheel1_80360',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[433],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[433],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[434] = {
		id = 434,
		drawType = 'liveness_wheel5_80360',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[434],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[434],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[435] = {
		id = 435,
		drawType = 'recharge_wheel_80361',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[435],
		-- {[50022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[435],
		-- {[50022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[436] = {
		id = 436,
		drawType = 'liveness_wheel1_80402',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[436],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[436],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[437] = {
		id = 437,
		drawType = 'liveness_wheel5_80402',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[437],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[437],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[438] = {
		id = 438,
		drawType = 'recharge_wheel_80403',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[438],
		-- {[50022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[438],
		-- {[50022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[439] = {
		id = 439,
		drawType = 'liveness_wheel1_80434',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[439],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[439],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[440] = {
		id = 440,
		drawType = 'liveness_wheel5_80434',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[440],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[440],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[441] = {
		id = 441,
		drawType = 'recharge_wheel_80433',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[441],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[441],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[442] = {
		id = 442,
		drawType = 'liveness_wheel1_80471',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[442],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[442],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[443] = {
		id = 443,
		drawType = 'liveness_wheel5_80471',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[443],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[443],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[444] = {
		id = 444,
		drawType = 'recharge_wheel_80470',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[444],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[444],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[445] = {
		id = 445,
		drawType = 'liveness_wheel1_80495',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[445],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[445],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[446] = {
		id = 446,
		drawType = 'liveness_wheel5_80495',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[446],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[446],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[447] = {
		id = 447,
		drawType = 'recharge_wheel_80494',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[447],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[447],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[448] = {
		id = 448,
		drawType = 'liveness_wheel1_80515',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[448],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[448],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[449] = {
		id = 449,
		drawType = 'liveness_wheel5_80515',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[449],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[449],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[450] = {
		id = 450,
		drawType = 'recharge_wheel_80514',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[450],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[450],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[451] = {
		id = 451,
		drawType = 'liveness_wheel1_80550',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[451],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[451],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[452] = {
		id = 452,
		drawType = 'liveness_wheel5_80550',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[452],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[452],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[453] = {
		id = 453,
		drawType = 'recharge_wheel_80549',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[453],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[453],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[454] = {
		id = 454,
		drawType = 'liveness_wheel1_80591',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[454],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[454],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[455] = {
		id = 455,
		drawType = 'liveness_wheel5_80591',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[455],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[455],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[456] = {
		id = 456,
		drawType = 'recharge_wheel_80590',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[456],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[456],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[457] = {
		id = 457,
		drawType = 'liveness_wheel1_80758',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[457],
		-- {[50021] = 1, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[457],
		-- {[50021] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[458] = {
		id = 458,
		drawType = 'liveness_wheel5_80758',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[458],
		-- {[50021] = 5, __size = 1}
		lotteryWeight2 = 100,
		lotteryType2 = __data_t__lotteryType2[458],
		-- {[50021] = 5, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},
	[459] = {
		id = 459,
		drawType = 'recharge_wheel_80757',
		drawTriggerType = 0,
		lotteryType1 = __data_t__lotteryType1[459],
		-- {[10022] = 1, __size = 1}
		lotteryWeight2 = 1,
		lotteryType2 = __data_t__lotteryType2[459],
		-- {[10022] = 1, __size = 1}
		lotteryWeight1 = 100,
		drawTriggerTimes = 1
	},

	__size = 162,
	__default = {
		__index = {
			drawType = 'recharge_wheel_2240',
			startCount = 0,
			weightEnd = 0,
			lotteryWeight5 = 0,
			drawTriggerType = 2,
			lotteryType3 = __data_t__lotteryType3["default"]	--[[ {__size = 0}]],
			effectLimit = 0,
			probLimit = 0.2,
			lotteryWeight10 = 0,
			lotteryType10 = __data_t__lotteryType10["default"]	--[[ {__size = 0}]],
			lotteryWeight9 = 0,
			lotteryType9 = __data_t__lotteryType9["default"]	--[[ {__size = 0}]],
			lotteryType1 = __data_t__lotteryType1["default"]	--[[ {__size = 0}]],
			lotteryWeight8 = 0,
			lotteryType5 = __data_t__lotteryType5["default"]	--[[ {__size = 0}]],
			weightStart = 0,
			lotteryType7 = __data_t__lotteryType7["default"]	--[[ {__size = 0}]],
			lotteryWeight4 = 0,
			lotteryWeight2 = 0,
			probInit = 0,
			lotteryType8 = __data_t__lotteryType8["default"]	--[[ {__size = 0}]],
			lotteryWeight7 = 0,
			lotteryWeight6 = 0,
			lotteryType6 = __data_t__lotteryType6["default"]	--[[ {__size = 0}]],
			probStep = 0.01,
			lotteryType4 = __data_t__lotteryType4["default"]	--[[ {__size = 0}]],
			lotteryWeight3 = 0,
			lotteryType2 = __data_t__lotteryType2["default"]	--[[ {__size = 0}]],
			probMiniTimes = 30,
			lotteryWeight1 = 0,
			probEffectInterval = 50,
			drawTriggerTimes = 0
		}
	}
}
return csv.draw_equip