--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {}, 
	[5] = {60001, 60002, 60003, 60004, 60005, 60006, 60007}, 
	[7] = {510, 511, 512, 513, 514}, 
	[9] = {60101, 60102, 60103, 60104, 60105, 60106, 60107}, 
	[11] = {11, 12, 13, 14}, 
	[13] = {60201, 60202, 60203, 60204, 60205, 60206, 60207}, 
	[14] = {60251, 60252, 60253, 60254, 60255, 60256, 60257}, 
	[15] = {60801, 60802, 60803, 60804, 60805, 60806}, __size = 8}
local __data_t__gateSeq2_en = {
	["default"] = __predefine_t__[2],
	[3] = __predefine_t__[14]
}
local __data_t__gateSeq_en = {
	["default"] = __predefine_t__[2],
	[1] = __predefine_t__[5],
	[3] = __predefine_t__[13],
	[2] = __predefine_t__[9],
	[7] = __predefine_t__[15]
}
local __data_t__gateSeq2_tw = {
	["default"] = __predefine_t__[2]
}
local __data_t__gateSeq_tw = {
	["default"] = __predefine_t__[2]
}
local __data_t__awardDesc = {
	[1] = __predefine_t__[7],
	["default"] = __predefine_t__[2],
	[3] = __predefine_t__[11],
	[2] = __predefine_t__[11],
	[4] = __predefine_t__[11],
	[7] = __predefine_t__[7]
}
local __data_t__gateSeq2_kr = {
	["default"] = __predefine_t__[2]
}
local __data_t__gateSeq_kr = {
	["default"] = __predefine_t__[2]
}
local __data_t__gateLimitSeq = {
	["default"] = __predefine_t__[2]
}
local __data_t__gateSeq = {
	["default"] = __predefine_t__[2],
	[1] = __predefine_t__[5],
	[3] = __predefine_t__[13],
	[2] = __predefine_t__[9],
	[7] = __predefine_t__[15]
}
local __data_t__gateSeq2 = {
	["default"] = __predefine_t__[2],
	[3] = __predefine_t__[14]
}

csv['huodong'] = {
	[1] = {
		id = 1,
		type = 'gold',
		background = 'city/adventure/selectgate/img_bg1.png',
		icon = 'city/adventure/selectgate/img_jbfb@.png',
		rTitle = '00ShuMa/TZFB_res/tz_word_titlejb.png',
		zrTitleBg = '00ShuMa/TZFB_res/tz_bg_btk.png',
		zrTitle = '00ShuMa/TZFB_res/tz_word_titlejb.png',
		ruleJson = 'TZFB_GZ_JB_ui.json',
		huodongType = 1,
		name = 'Daily Gold Event',
		name_vn = 'Sự kiện vàng hàng ngày',
		name_ma = 'Acara emas harian',
		name_en = 'Daily Gold Event',
		name_in = 'Acara emas harian',
		name_th = 'กิจกรรมทองคำประจำวัน',
		name_ph = 'Araw-araw na gintong kaganapan',
		desc = 'Can obtain many gold items',
		desc_vn = 'Có thể nhận được nhiều vật phẩm vàng.',
		desc_ma = 'Boleh memperoleh banyak item emas',
		desc_en = 'Can obtain many gold items',
		desc_in = 'Dapat memperoleh banyak item emas',
		desc_th = 'สามารถรับไอเทมทองจำนวนมาก',
		desc_ph = 'Maaaring makakuha ng maraming gintong item',
		openTimeDesc = 'Open all day',
		openTimeDesc_vn = 'Mở cửa cả ngày',
		openTimeDesc_ma = 'Dibuka sepanjang hari',
		openTimeDesc_en = 'Open all day',
		openTimeDesc_in = 'Buka sepanjang hari',
		openTimeDesc_th = 'เปิดให้บริการทั้งวัน',
		openTimeDesc_ph = 'Bukas buong araw',
		gateSeq = __data_t__gateSeq[1],
		-- {60001, 60002, 60003, 60004, 60005, 60006, 60007}
		gateSeq_en = __data_t__gateSeq_en[1],
		-- {60001, 60002, 60003, 60004, 60005, 60006, 60007}
		gateLimitSeq = {60010, 60011, 60012, 60013, 60014, 60015, 60016, 60017, 60018, 60019, 60020, 60021, 60022, 60023, 60024, 60025, 60026, 60027, 60028, 60029, 60030, 60031, 60032, 60033, 60034, 60035, 60036, 60037, 60038, 60039, 60040, 60041, 60042, 60043, 60044, 60045, 60046, 60047, 60048, 60049, 60050, 60051, 60052, 60053, 60054, 60055, 60056, 60057, 60058, 60059},
		times = 2,
		openLevel = 18,
		openType = 2,
		beginTime = 500,
		endTime = 500,
		endTime_en = 500,
		openDuration = 24,
		awardDesc = __data_t__awardDesc[1],
		-- {510, 511, 512, 513, 514}
		intervalCD = 600,
		sortValue = 2,
		rankShow = {35, 70, 85, 100}
	},
	[2] = {
		id = 2,
		type = 'exp',
		background = 'city/adventure/selectgate/img_bg2.png',
		icon = 'city/adventure/selectgate/img_ds@.png',
		rTitle = '00ShuMa/TZFB_res/tz_word_titlejy.png',
		zrTitleBg = '00ShuMa/TZFB_res/tz_bg_btk.png',
		zrTitle = '00ShuMa/TZFB_res/tz_word_titlejy.png',
		ruleJson = 'TZFB_GZ_JY_ui.json',
		huodongType = 2,
		name = 'Activity Experience Book',
		name_vn = 'Sổ kinh nghiệm hoạt động',
		name_ma = 'Buku pengalaman aktiviti',
		name_en = 'Activity Experience Book',
		name_in = 'Buku pengalaman aktivitas',
		name_th = 'สมุดประสบการณ์กิจกรรม',
		name_ph = 'Aklat ng karanasan sa aktibidad',
		desc = 'Can obtain lots of experience potions',
		desc_vn = 'Có thể nhận được nhiều thuốc kinh nghiệm.',
		desc_ma = 'Boleh memperoleh banyak ubat pengalaman',
		desc_en = 'Can obtain lots of experience potions',
		desc_in = 'Dapat memperoleh banyak ramuan pengalaman',
		desc_th = 'สามารถรับยาฟื้นค่าประสบการณ์จำนวนมาก',
		desc_ph = 'Maaaring makakuha ng maraming potion ng karanasan',
		openTimeDesc = 'Open all day',
		openTimeDesc_vn = 'Mở cửa cả ngày',
		openTimeDesc_ma = 'Dibuka sepanjang hari',
		openTimeDesc_en = 'Open all day',
		openTimeDesc_in = 'Buka sepanjang hari',
		openTimeDesc_th = 'เปิดให้บริการทั้งวัน',
		openTimeDesc_ph = 'Bukas buong araw',
		gateSeq = __data_t__gateSeq[2],
		-- {60101, 60102, 60103, 60104, 60105, 60106, 60107}
		gateSeq_en = __data_t__gateSeq_en[2],
		-- {60101, 60102, 60103, 60104, 60105, 60106, 60107}
		gateLimitSeq = {60110, 60111, 60112, 60113, 60114, 60115, 60116, 60117, 60118, 60119, 60120, 60121, 60122, 60123, 60124, 60125, 60126, 60127, 60128, 60129, 60130, 60131, 60132, 60133, 60134, 60135, 60136, 60137, 60138, 60139, 60140, 60141, 60142, 60143, 60144, 60145, 60146, 60147, 60148, 60149, 60150, 60151, 60152, 60153, 60154, 60155, 60156, 60157, 60158, 60159},
		times = 2,
		openLevel = 26,
		openType = 2,
		beginTime = 500,
		endTime = 500,
		endTime_en = 500,
		openDuration = 24,
		awardDesc = __data_t__awardDesc[2],
		-- {11, 12, 13, 14}
		intervalCD = 600,
		sortValue = 3,
		rankShow = {7, 14, 17, 20}
	},
	[3] = {
		id = 3,
		type = 'gift',
		background = 'city/adventure/selectgate/img_bg3.png',
		icon = 'city/adventure/selectgate/img_lwfb@.png',
		rTitle = '00ShuMa/TZFB_res/huanxiang.png',
		zrTitle = '00ShuMa/TZFB_res/hx_title.png',
		ruleJson = 'TZFB_GZ_HX_ui.json',
		huodongType = 3,
		name = 'Gift Dungeon',
		name_vn = 'Phó bản quà tặng',
		name_ma = 'Penjara hadiah',
		name_en = 'Gift Dungeon',
		name_in = 'Dungeon hadiah',
		name_th = 'ดันเจี้ยนของขวัญ',
		name_ph = 'Dungeon ng regalo',
		desc = 'Gift Dungeon',
		desc_vn = 'Phó bản quà tặng',
		desc_ma = 'Penjara hadiah',
		desc_en = 'Gift Dungeon',
		desc_in = 'Dungeon hadiah',
		desc_th = 'ดันเจี้ยนของขวัญ',
		desc_ph = 'Dungeon ng regalo',
		openTimeDesc = 'Open all day',
		openTimeDesc_vn = 'Mở cửa cả ngày',
		openTimeDesc_ma = 'Dibuka sepanjang hari',
		openTimeDesc_en = 'Open all day',
		openTimeDesc_in = 'Buka sepanjang hari',
		openTimeDesc_th = 'เปิดให้บริการทั้งวัน',
		openTimeDesc_ph = 'Bukas buong araw',
		gateSeq = __data_t__gateSeq[3],
		-- {60201, 60202, 60203, 60204, 60205, 60206, 60207}
		gateSeq2 = __data_t__gateSeq2[3],
		-- {60251, 60252, 60253, 60254, 60255, 60256, 60257}
		gateSeq_en = __data_t__gateSeq_en[3],
		-- {60201, 60202, 60203, 60204, 60205, 60206, 60207}
		gateSeq2_en = __data_t__gateSeq2_en[3],
		-- {60251, 60252, 60253, 60254, 60255, 60256, 60257}
		times = 2,
		openLevel = 30,
		openType = 2,
		beginTime = 500,
		endTime = 500,
		endTime_en = 500,
		openDuration = 24,
		awardDesc = __data_t__awardDesc[3],
		-- {11, 12, 13, 14}
		intervalCD = 600,
		sortValue = 4
	},
	[4] = {
		id = 4,
		type = 'frag',
		background = 'city/adventure/selectgate/img_bg4.png',
		icon = 'city/adventure/selectgate/img_spfb@.png',
		rTitle = '00ShuMa/TZFB_res/gongfang.png',
		zrTitleBg = '00ShuMa/TZFB_res/tz_bg_btk.png',
		zrTitle = '00ShuMa/TZFB_res/gongfang.png',
		ruleJson = 'TZFB_GZ_GFJ_ui.json',
		huodongType = 4,
		name = 'Fragment Dungeon',
		name_vn = 'Phó bản mảnh vỡ',
		name_ma = 'Penjara serpihan',
		name_en = 'Fragment Dungeon',
		name_in = 'Dungeon fragmen',
		name_th = 'ดันเจี้ยนเศษชิ้นส่วน',
		name_ph = 'Dungeon ng piraso',
		desc = 'Fragment Dungeon',
		desc_vn = 'Phó bản mảnh vỡ',
		desc_ma = 'Penjara serpihan',
		desc_en = 'Fragment Dungeon',
		desc_in = 'Dungeon fragmen',
		desc_th = 'ดันเจี้ยนเศษชิ้นส่วน',
		desc_ph = 'Dungeon ng piraso',
		openTimeDesc = 'Open all day',
		openTimeDesc_vn = 'Mở cửa cả ngày',
		openTimeDesc_ma = 'Dibuka sepanjang hari',
		openTimeDesc_en = 'Open all day',
		openTimeDesc_in = 'Buka sepanjang hari',
		openTimeDesc_th = 'เปิดให้บริการทั้งวัน',
		openTimeDesc_ph = 'Bukas buong araw',
		times = 2,
		openLevel = 36,
		openType = 2,
		beginTime = 500,
		endTime = 500,
		endTime_en = 500,
		openDuration = 24,
		awardDesc = __data_t__awardDesc[4],
		-- {11, 12, 13, 14}
		intervalCD = 600,
		sortValue = 5
	},
	[7] = {
		id = 7,
		type = 'event',
		background = 'city/adventure/selectgate/img_bg7.png',
		icon = 'city/adventure/selectgate/img_ldjfb.png',
		huodongType = 5,
		name = 'Lunar New Year Challenge',
		name_vn = 'Thử thách Tết Nguyên Đán',
		name_ma = 'Cabaran Tahun Baru Cina',
		name_en = 'Lunar New Year Challenge',
		name_in = 'Tantangan Tahun Baru Imlek',
		name_th = 'ความท้าทายตรุษจีน',
		name_ph = 'Hamong Bagong Taon ng Tsino',
		desc = 'Can obtain Xiao Mei Yan fragments',
		desc_vn = 'Có thể nhận được mảnh vỡ Hiểu Mỹ Diễm.',
		desc_ma = 'Boleh memperoleh serpihan Xiao Mei Yan',
		desc_en = 'Can obtain Xiao Mei Yan fragments',
		desc_in = 'Dapat memperoleh fragmen Xiao Mei Yan',
		desc_th = 'สามารถรับเศษชิ้นส่วนของเสี่ยวเหม่ยเยี่ยน',
		desc_ph = 'Maaaring makakuha ng piraso ni Xiao Mei Yan',
		openTimeDesc = 'Open during the Chinese New Year event',
		openTimeDesc_vn = 'Mở cửa trong thời gian hoạt động Tết Nguyên Đán',
		openTimeDesc_ma = 'Dibuka semasa acara Tahun Baru Cina',
		openTimeDesc_en = 'Open during the Chinese New Year event',
		openTimeDesc_in = 'Buka selama acara Tahun Baru Imlek',
		openTimeDesc_th = 'เปิดให้บริการในช่วงกิจกรรมตรุษจีน',
		openTimeDesc_ph = 'Bukas lamang sa panahon ng aktibidad ng Chinese New Year',
		gateSeq = __data_t__gateSeq[7],
		-- {60801, 60802, 60803, 60804, 60805, 60806}
		gateSeq_en = __data_t__gateSeq_en[7],
		-- {60801, 60802, 60803, 60804, 60805, 60806}
		times = 3,
		openLevel = 24,
		openType = 0,
		beginDate = 20241226,
		beginTime = 500,
		endDate = 20250102,
		endTime = 500,
		endTime_en = 500,
		openDuration = 168,
		awardDesc = __data_t__awardDesc[7],
		-- {510, 511, 512, 513, 514}
		intervalCD = 600,
		sortValue = 1
	},

	__size = 5,
	__default = {
		__index = {
			type = '',
			background = 'YXKPT/wuseer.png',
			icon = 'ICON/SL-exp.png',
			rTitle = 'ICON/SL-exp.png',
			zrTitleBg = '',
			zrTitle = 'ICON/SL-exp.png',
			ruleJson = 'ICON/SL-exp.png',
			huodongType = 0,
			paramMap = {__size = 0},
			gateSeq = __data_t__gateSeq["default"]	--[[ {}]],
			gateSeq2 = __data_t__gateSeq2["default"]	--[[ {}]],
			gateSeq_tw = __data_t__gateSeq_tw["default"]	--[[ {}]],
			gateSeq2_tw = __data_t__gateSeq2_tw["default"]	--[[ {}]],
			gateSeq_en = __data_t__gateSeq_en["default"]	--[[ {}]],
			gateSeq2_en = __data_t__gateSeq2_en["default"]	--[[ {}]],
			gateSeq_kr = __data_t__gateSeq_kr["default"]	--[[ {}]],
			gateSeq2_kr = __data_t__gateSeq2_kr["default"]	--[[ {}]],
			gateLimitSeq = __data_t__gateLimitSeq["default"]	--[[ {}]],
			times = 1,
			openLevel = 1,
			openType = 1,
			beginDate = 20160101,
			beginTime = 0,
			beginTime_kr = 0,
			beginTime_en = 0,
			endDate = 20300101,
			endTime = 0,
			endTime_kr = 0,
			endTime_en = 0,
			openWeekDay = {1, 2, 3, 4, 5, 6, 7},
			openDuration = 1,
			awardDesc = __data_t__awardDesc["default"]	--[[ {}]],
			intervalCD = 0,
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr', 'in', 'ma', 'ph'}
		}
	}
}
return csv.huodong