--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[3] = {32}, 
	[4] = {['y'] = -150, ['x'] = 0, __size = 2}, __size = 3}
local __data_t__choices = {
	["default"] = __predefine_t__[1]
}
local __data_t__useRoleFigure = {
	[1003] = __predefine_t__[3],
	[1002] = __predefine_t__[3],
	[1001] = __predefine_t__[3]
}
local __data_t__offPos = {
	[1003] = __predefine_t__[4],
	[1002] = __predefine_t__[4],
	[1001] = __predefine_t__[4]
}
local __data_t__tagName = {
	["default"] = __predefine_t__[1]
}

csv['new_guide_local'] = {
	[1] = {
		id = 1,
		stage = 1,
		specialName = 'summerChallenge101',
		showType = 2
	},
	[2] = {
		id = 2,
		stage = 1,
		service = 1,
		showType = 2,
		choices = {11, 21, 31}
	},
	[11] = {
		id = 11,
		stage = 1,
		showType = 2
	},
	[21] = {
		id = 21,
		stage = 1,
		showType = 2
	},
	[31] = {
		id = 31,
		stage = 1,
		showType = 2
	},
	[1001] = {
		id = 1001,
		stage = 2,
		specialName = 'summerChallenge1001',
		showType = 2,
		useRoleFigure = __data_t__useRoleFigure[1001],
		-- {32}
		offPos = __data_t__offPos[1001],
		-- {['y'] = -150, ['x'] = 0, __size = 2}
		talkContent = 'Welcome everyone to the Summer Festival Treasure Hunt activity! We are now standing on a beautiful archipelago, home of Milotic. In the coming time, everyone will join us in uncovering the legend of Milotic through thrilling and exciting games, and venture into the ancient and mysterious temple in the lake to discover Milotic’s secrets...',
		talkContent_vn = 'Chào mừng tất cả mọi người đến với hoạt động thám hiểm kho báu lễ hội mùa hè lần này. Nơi chúng ta đang đứng chính là quần đảo xinh đẹp, nơi sinh sống của Milotic. Trong thời gian tới, mọi người sẽ cùng chúng tôi truy tìm truyền thuyết về Milotic trong những trò chơi đầy mạo hiểm và thú vị, đồng thời tiến vào ngôi đền cổ kính và bí ẩn trong hồ để khám phá những bí mật của Milotic...',
		talkContent_ma = 'Selamat datang semua ke aktiviti Mencari Harta Karun Festival Musim Panas ini! Kita kini berada di kepulauan yang indah, tempat tinggal Milotic. Tidak lama lagi, semua akan bersama kami dalam menjejak legenda Milotic melalui permainan yang mencabar dan menyeronokkan, serta meneroka kuil purba dan misteri di dalam tasik untuk membongkar rahsia Milotic...',
		talkContent_en = 'Welcome everyone to the Summer Festival Treasure Hunt activity! We are now standing on a beautiful archipelago, home of Milotic. In the coming time, everyone will join us in uncovering the legend of Milotic through thrilling and exciting games, and venture into the ancient and mysterious temple in the lake to discover Milotic’s secrets...',
		talkContent_th = 'ขอต้อนรับทุกคนเข้าสู่กิจกรรมล่าขุมทรัพย์ในเทศกาลฤดูร้อน! สถานที่ที่เรายืนอยู่นี้คือหมู่เกาะที่สวยงามซึ่งเป็นถิ่นอาศัยของ Milotic ในช่วงเวลาต่อไป ทุกคนจะร่วมมือกับพวกเราเพื่อค้นหาตำนานของ Milotic ผ่านเกมที่เต็มไปด้วยความตื่นเต้นและความท้าทาย พร้อมทั้งเดินทางเข้าสู่วิหารโบราณลึกลับกลางทะเลสาบเพื่อค้นพบความลับของ Milotic...',
		talkContent_ph = 'Maligayang pagdating sa lahat sa Treasure Hunt ng Summer Festival! Tayo ngayon ay nasa isang napakagandang kapuluan, ang tahanan ni Milotic. Sa mga susunod na sandali, sasamahan ninyo kami sa pagtuklas ng alamat ni Milotic sa pamamagitan ng mga kapanapanabik at mapangahas na laro, at pagtungo sa sinaunang at mahiwagang templo sa lawa upang tuklasin ang mga lihim ni Milotic...',
		talkContent_in = 'Selamat datang semuanya di kegiatan Perburuan Harta Karun Festival Musim Panas! Kita sekarang berada di kepulauan yang indah, tempat tinggal Milotic. Dalam waktu dekat, kalian semua akan bergabung bersama kami untuk mengungkap legenda Milotic melalui permainan yang penuh tantangan dan keseruan, serta menjelajahi kuil kuno dan misterius di tengah danau untuk menemukan rahasia Milotic...'
	},
	[1002] = {
		id = 1002,
		stage = 2,
		showType = 2,
		useRoleFigure = __data_t__useRoleFigure[1002],
		-- {32}
		offPos = __data_t__offPos[1002],
		-- {['y'] = -150, ['x'] = 0, __size = 2}
		talkContent = 'Legend has it that Milotic resides beneath the lake temple at the heart of this stunning archipelago, and the clues to enter the temple are hidden in our intense game stages. In the end, only one team will earn the chance to enter the temple, where Milotic and the ultimate treasure of this event await you!',
		talkContent_vn = 'Truyền thuyết Milotic trú ngụ dưới đền thờ hồ nằm ngay trung tâm quần đảo xinh đẹp, và manh mối để vào đền thờ hồ ẩn giấu trong các màn chơi gay cấn của chúng ta. Cuối cùng, chỉ một đội duy nhất giành được cơ hội vào đền thờ hồ, nơi Milotic và kho báu cuối cùng của sự kiện lần này đang chờ đợi các bạn!',
		talkContent_ma = 'Menurut legenda, Milotic tinggal di bawah kuil tasik yang terletak di tengah-tengah kepulauan yang menakjubkan ini, dan petunjuk untuk masuk ke kuil itu tersembunyi dalam permainan mencabar kami. Akhirnya, hanya satu pasukan yang akan mendapat peluang untuk masuk ke kuil tersebut, di mana Milotic dan harta karun utama acara ini sedang menanti anda!',
		talkContent_en = 'Legend has it that Milotic resides beneath the lake temple at the heart of this stunning archipelago, and the clues to enter the temple are hidden in our intense game stages. In the end, only one team will earn the chance to enter the temple, where Milotic and the ultimate treasure of this event await you!',
		talkContent_th = 'ตำนานกล่าวว่า Milotic อาศัยอยู่ใต้เทวสถานในทะเลสาบ ซึ่งอยู่ใจกลางหมู่เกาะอันงดงามแห่งนี้ และเบาะแสในการเข้าสู่วิหารถูกซ่อนไว้ในด่านเกมที่ตื่นเต้นของเรา สุดท้ายแล้วจะมีเพียงทีมเดียวเท่านั้นที่จะได้เข้าสู่เทวสถาน ซึ่ง Milotic และขุมทรัพย์สุดท้ายของกิจกรรมครั้งนี้กำลังรอคุณอยู่!',
		talkContent_ph = 'Ayon sa alamat, naninirahan si Milotic sa ilalim ng templong nasa gitna ng lawa sa puso ng magandang kapuluan na ito, at ang mga pahiwatig upang makapasok sa templo ay nakatago sa mga hamon ng ating mga laro. Sa huli, iisang koponan lamang ang magkakaroon ng pagkakataong makapasok sa templo, kung saan naghihintay si Milotic at ang huling kayamanan ng kaganapan!',
		talkContent_in = 'Menurut legenda, Milotic tinggal di bawah kuil danau yang terletak di tengah-tengah kepulauan menakjubkan ini, dan petunjuk untuk masuk ke kuil tersembunyi dalam tahapan permainan kita yang menegangkan. Pada akhirnya, hanya satu tim yang akan mendapatkan kesempatan masuk ke kuil tersebut, di mana Milotic dan harta karun utama dari acara ini sedang menunggu kalian!'
	},
	[1003] = {
		id = 1003,
		stage = 2,
		showType = 2,
		useRoleFigure = __data_t__useRoleFigure[1003],
		-- {32}
		offPos = __data_t__offPos[1003],
		-- {['y'] = -150, ['x'] = 0, __size = 2}
		talkContent = 'Each team will receive a detailed expedition guide, including a map of our activity area and full details of the activities...',
		talkContent_vn = 'Mỗi đội sẽ nhận được một bản hướng dẫn thám hiểm chi tiết, bao gồm bản đồ khu vực hoạt động của chúng tôi và giới thiệu chi tiết về hoạt động...',
		talkContent_ma = 'Setiap pasukan akan menerima panduan ekspedisi terperinci, termasuk peta kawasan aktiviti kami dan maklumat lengkap tentang aktiviti...',
		talkContent_en = 'Each team will receive a detailed expedition guide, including a map of our activity area and full details of the activities...',
		talkContent_th = 'แต่ละทีมจะได้รับคู่มือสำรวจอย่างละเอียด ซึ่งประกอบด้วยแผนที่พื้นที่กิจกรรมของเราและรายละเอียดของกิจกรรม...',
		talkContent_ph = 'Bawat koponan ay makakatanggap ng detalyadong gabay sa ekspedisyon, kabilang ang mapa ng lugar ng aktibidad at kumpletong impormasyon tungkol sa mga aktibidad...',
		talkContent_in = 'Setiap tim akan menerima panduan ekspedisi lengkap, termasuk peta area kegiatan dan detail aktivitas...'
	},
	[1004] = {
		id = 1004,
		stage = 2,
		service = 1,
		showType = 2,
		force = 2,
		useRoleFigure = {0},
		talkContent = 'I can\'t wait any longer — let\'s get started!',
		talkContent_vn = 'Tôi nóng lòng lắm rồi, bắt đầu nhanh đi!',
		talkContent_ma = 'Saya tak sabar lagi — mari kita mulakan!',
		talkContent_en = 'I can\'t wait any longer — let\'s get started!',
		talkContent_th = 'ฉันตื่นเต้นมากแล้ว ไปเริ่มกันเลย!',
		talkContent_ph = 'Hindi ko na kayang maghintay — magsimula na tayo!',
		talkContent_in = 'Aku sudah tidak sabar — ayo kita mulai!'
	},

	__size = 9,
	__default = {
		__index = {
			startLevel = 1,
			startGate = 0,
			order = 0,
			service = 0,
			showAward = false,
			gotoScene = 0,
			showType = 1,
			force = 1,
			roleName_cn = '',
			roleName_tw = '',
			roleName_en = '',
			roleName_kr = '',
			talkContent = '',
			talkContent_vn = '',
			talkContent_ma = '',
			talkContent_en = '',
			talkContent_th = '',
			talkContent_ph = '',
			talkContent_in = '',
			tagName = __data_t__tagName["default"]	--[[ {}]],
			animateAngle = 0,
			anyPosCancel = false,
			choices = __data_t__choices["default"]	--[[ {}]]
		}
	}
}
return csv.new_guide_local