--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {1, 2}, 
	[4] = {2, 3}, 
	[6] = {3, 4}, 
	[8] = {4, 5}, 
	[10] = {5, 6}, 
	[12] = {6, 7}, 
	[14] = {7, 8}, 
	[16] = {8, 9}, 
	[18] = {9, 10}, 
	[20] = {10, 11}, 
	[22] = {11, 21}, 
	[24] = {21, 31}, 
	[26] = {31, 41}, 
	[28] = {41, 51}, 
	[30] = {51, 71}, 
	[32] = {71, 101}, 
	[34] = {101, 201}, 
	[36] = {201, 301}, 
	[38] = {301, 401}, 
	[40] = {401, 501}, 
	[42] = {501, 601}, 
	[44] = {601, 701}, 
	[46] = {701, 801}, 
	[48] = {801, 1001}, 
	[50] = {1001, 3001}, 
	[52] = {3001, 5001}, 
	[54] = {5001, 10001}, 
	[56] = {10001, 15001}, 
	[58] = {15001, 100000}, 
	[60] = {['gold'] = 150000, ['rmb'] = 700, ['coin1'] = 2700, __size = 3}, 
	[61] = {['gold'] = 145000, ['rmb'] = 640, ['coin1'] = 2400, __size = 3}, 
	[62] = {['gold'] = 140000, ['rmb'] = 600, ['coin1'] = 2100, __size = 3}, 
	[63] = {['gold'] = 135000, ['rmb'] = 560, ['coin1'] = 1900, __size = 3}, 
	[64] = {['gold'] = 130000, ['rmb'] = 520, ['coin1'] = 1800, __size = 3}, 
	[65] = {['gold'] = 125000, ['rmb'] = 500, ['coin1'] = 1740, __size = 3}, 
	[66] = {['gold'] = 120000, ['rmb'] = 480, ['coin1'] = 1680, __size = 3}, 
	[67] = {['gold'] = 115000, ['rmb'] = 460, ['coin1'] = 1620, __size = 3}, 
	[68] = {['gold'] = 110000, ['rmb'] = 440, ['coin1'] = 1560, __size = 3}, 
	[69] = {['gold'] = 105000, ['rmb'] = 420, ['coin1'] = 1500, __size = 3}, 
	[70] = {['gold'] = 100000, ['rmb'] = 400, ['coin1'] = 1400, __size = 3}, 
	[71] = {['gold'] = 95000, ['rmb'] = 380, ['coin1'] = 1340, __size = 3}, 
	[72] = {['gold'] = 90000, ['rmb'] = 360, ['coin1'] = 1280, __size = 3}, 
	[73] = {['gold'] = 85000, ['rmb'] = 340, ['coin1'] = 1220, __size = 3}, 
	[74] = {['gold'] = 80000, ['rmb'] = 320, ['coin1'] = 1160, __size = 3}, 
	[75] = {['gold'] = 78000, ['rmb'] = 280, ['coin1'] = 1100, __size = 3}, 
	[76] = {['gold'] = 76000, ['rmb'] = 240, ['coin1'] = 1060, __size = 3}, 
	[77] = {['gold'] = 74000, ['rmb'] = 200, ['coin1'] = 1020, __size = 3}, 
	[78] = {['gold'] = 72000, ['rmb'] = 180, ['coin1'] = 980, __size = 3}, 
	[79] = {['gold'] = 70000, ['rmb'] = 160, ['coin1'] = 940, __size = 3}, 
	[80] = {['gold'] = 68000, ['rmb'] = 150, ['coin1'] = 900, __size = 3}, 
	[81] = {['gold'] = 67000, ['rmb'] = 140, ['coin1'] = 860, __size = 3}, 
	[82] = {['gold'] = 66000, ['rmb'] = 130, ['coin1'] = 820, __size = 3}, 
	[83] = {['gold'] = 65000, ['rmb'] = 120, ['coin1'] = 780, __size = 3}, 
	[84] = {['gold'] = 64000, ['rmb'] = 110, ['coin1'] = 740, __size = 3}, 
	[85] = {['gold'] = 63000, ['rmb'] = 100, ['coin1'] = 700, __size = 3}, 
	[86] = {['gold'] = 62000, ['rmb'] = 90, ['coin1'] = 690, __size = 3}, 
	[87] = {['gold'] = 61000, ['rmb'] = 80, ['coin1'] = 680, __size = 3}, 
	[88] = {['gold'] = 60000, ['rmb'] = 80, ['coin1'] = 670, __size = 3}, __size = 58}
local __data_t__periodAward = {
	[216] = __predefine_t__[75],
	[217] = __predefine_t__[76],
	[214] = __predefine_t__[73],
	[215] = __predefine_t__[74],
	[212] = __predefine_t__[71],
	[213] = __predefine_t__[72],
	[210] = __predefine_t__[69],
	[211] = __predefine_t__[70],
	[228] = __predefine_t__[87],
	[218] = __predefine_t__[77],
	[219] = __predefine_t__[78],
	[115] = __predefine_t__[74],
	[114] = __predefine_t__[73],
	[117] = __predefine_t__[76],
	[116] = __predefine_t__[75],
	[111] = __predefine_t__[70],
	[110] = __predefine_t__[69],
	[113] = __predefine_t__[72],
	[112] = __predefine_t__[71],
	[119] = __predefine_t__[78],
	[118] = __predefine_t__[77],
	[229] = __predefine_t__[88],
	[224] = __predefine_t__[83],
	[223] = __predefine_t__[82],
	[226] = __predefine_t__[85],
	[222] = __predefine_t__[81],
	[129] = __predefine_t__[88],
	[221] = __predefine_t__[80],
	[227] = __predefine_t__[86],
	[128] = __predefine_t__[87],
	[220] = __predefine_t__[79],
	[201] = __predefine_t__[60],
	[203] = __predefine_t__[62],
	[202] = __predefine_t__[61],
	[205] = __predefine_t__[64],
	[204] = __predefine_t__[63],
	[207] = __predefine_t__[66],
	[206] = __predefine_t__[65],
	[209] = __predefine_t__[68],
	[208] = __predefine_t__[67],
	[120] = __predefine_t__[79],
	[121] = __predefine_t__[80],
	[122] = __predefine_t__[81],
	[109] = __predefine_t__[68],
	[124] = __predefine_t__[83],
	[125] = __predefine_t__[84],
	[126] = __predefine_t__[85],
	[127] = __predefine_t__[86],
	[102] = __predefine_t__[61],
	[103] = __predefine_t__[62],
	[225] = __predefine_t__[84],
	[101] = __predefine_t__[60],
	[106] = __predefine_t__[65],
	[107] = __predefine_t__[66],
	[104] = __predefine_t__[63],
	[105] = __predefine_t__[64],
	[108] = __predefine_t__[67],
	[123] = __predefine_t__[82]
}
local __data_t__range = {
	[216] = __predefine_t__[32],
	[217] = __predefine_t__[34],
	[214] = __predefine_t__[28],
	[215] = __predefine_t__[30],
	[212] = __predefine_t__[24],
	[213] = __predefine_t__[26],
	[210] = __predefine_t__[20],
	[211] = __predefine_t__[22],
	[218] = __predefine_t__[36],
	[219] = __predefine_t__[38],
	[24] = __predefine_t__[48],
	[25] = __predefine_t__[50],
	[26] = __predefine_t__[52],
	[27] = __predefine_t__[54],
	[20] = __predefine_t__[40],
	[21] = __predefine_t__[42],
	[22] = __predefine_t__[44],
	[23] = __predefine_t__[46],
	[28] = __predefine_t__[56],
	[29] = __predefine_t__[58],
	[4] = __predefine_t__[8],
	[8] = __predefine_t__[16],
	[120] = __predefine_t__[40],
	[121] = __predefine_t__[42],
	[122] = __predefine_t__[44],
	[123] = __predefine_t__[46],
	[124] = __predefine_t__[48],
	[125] = __predefine_t__[50],
	[126] = __predefine_t__[52],
	[127] = __predefine_t__[54],
	[128] = __predefine_t__[56],
	[129] = __predefine_t__[58],
	[115] = __predefine_t__[30],
	[114] = __predefine_t__[28],
	[117] = __predefine_t__[34],
	[116] = __predefine_t__[32],
	[111] = __predefine_t__[22],
	[110] = __predefine_t__[20],
	[113] = __predefine_t__[26],
	[112] = __predefine_t__[24],
	[119] = __predefine_t__[38],
	[118] = __predefine_t__[36],
	[3] = __predefine_t__[6],
	[7] = __predefine_t__[14],
	[108] = __predefine_t__[16],
	[109] = __predefine_t__[18],
	[102] = __predefine_t__[4],
	[103] = __predefine_t__[6],
	[101] = __predefine_t__[2],
	[106] = __predefine_t__[12],
	[107] = __predefine_t__[14],
	[104] = __predefine_t__[8],
	[105] = __predefine_t__[10],
	[2] = __predefine_t__[4],
	[6] = __predefine_t__[12],
	[229] = __predefine_t__[58],
	[228] = __predefine_t__[56],
	[227] = __predefine_t__[54],
	[226] = __predefine_t__[52],
	[225] = __predefine_t__[50],
	[224] = __predefine_t__[48],
	[223] = __predefine_t__[46],
	[222] = __predefine_t__[44],
	[221] = __predefine_t__[42],
	[220] = __predefine_t__[40],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[20],
	[13] = __predefine_t__[26],
	[12] = __predefine_t__[24],
	[15] = __predefine_t__[30],
	[14] = __predefine_t__[28],
	[17] = __predefine_t__[34],
	[16] = __predefine_t__[32],
	[19] = __predefine_t__[38],
	[18] = __predefine_t__[36],
	[1] = __predefine_t__[2],
	[5] = __predefine_t__[10],
	[9] = __predefine_t__[18],
	[201] = __predefine_t__[2],
	[203] = __predefine_t__[6],
	[202] = __predefine_t__[4],
	[205] = __predefine_t__[10],
	[204] = __predefine_t__[8],
	[207] = __predefine_t__[14],
	[206] = __predefine_t__[12],
	[209] = __predefine_t__[18],
	[208] = __predefine_t__[16]
}

csv['pwaward'] = {
	[1] = {
		id = 1,
		range = __data_t__range[1],
		-- {1, 2}
		periodAward = {['gold'] = 100000, ['rmb'] = 300, ['coin1'] = 1200, __size = 3}
	},
	[2] = {
		id = 2,
		range = __data_t__range[2],
		-- {2, 3}
		periodAward = {['gold'] = 95000, ['rmb'] = 280, ['coin1'] = 1050, __size = 3}
	},
	[3] = {
		id = 3,
		range = __data_t__range[3],
		-- {3, 4}
		periodAward = {['gold'] = 90000, ['rmb'] = 260, ['coin1'] = 900, __size = 3}
	},
	[4] = {
		id = 4,
		range = __data_t__range[4],
		-- {4, 5}
		periodAward = {['gold'] = 85000, ['rmb'] = 240, ['coin1'] = 800, __size = 3}
	},
	[5] = {
		id = 5,
		range = __data_t__range[5],
		-- {5, 6}
		periodAward = {['gold'] = 80000, ['rmb'] = 220, ['coin1'] = 750, __size = 3}
	},
	[6] = {
		id = 6,
		range = __data_t__range[6],
		-- {6, 7}
		periodAward = {['gold'] = 75000, ['rmb'] = 200, ['coin1'] = 720, __size = 3}
	},
	[7] = {
		id = 7,
		range = __data_t__range[7],
		-- {7, 8}
		periodAward = {['gold'] = 70000, ['rmb'] = 190, ['coin1'] = 690, __size = 3}
	},
	[8] = {
		id = 8,
		range = __data_t__range[8],
		-- {8, 9}
		periodAward = {['gold'] = 65000, ['rmb'] = 180, ['coin1'] = 660, __size = 3}
	},
	[9] = {
		id = 9,
		range = __data_t__range[9],
		-- {9, 10}
		periodAward = {['gold'] = 60000, ['rmb'] = 170, ['coin1'] = 630, __size = 3}
	},
	[10] = {
		id = 10,
		range = __data_t__range[10],
		-- {10, 11}
		periodAward = {['gold'] = 55000, ['rmb'] = 160, ['coin1'] = 600, __size = 3}
	},
	[11] = {
		id = 11,
		range = __data_t__range[11],
		-- {11, 21}
		periodAward = {['gold'] = 50000, ['rmb'] = 150, ['coin1'] = 550, __size = 3}
	},
	[12] = {
		id = 12,
		range = __data_t__range[12],
		-- {21, 31}
		periodAward = {['gold'] = 45000, ['rmb'] = 140, ['coin1'] = 510, __size = 3}
	},
	[13] = {
		id = 13,
		range = __data_t__range[13],
		-- {31, 41}
		periodAward = {['gold'] = 40000, ['rmb'] = 130, ['coin1'] = 490, __size = 3}
	},
	[14] = {
		id = 14,
		range = __data_t__range[14],
		-- {41, 51}
		periodAward = {['gold'] = 35000, ['rmb'] = 120, ['coin1'] = 460, __size = 3}
	},
	[15] = {
		id = 15,
		range = __data_t__range[15],
		-- {51, 71}
		periodAward = {['gold'] = 30000, ['rmb'] = 110, ['coin1'] = 430, __size = 3}
	},
	[16] = {
		id = 16,
		range = __data_t__range[16],
		-- {71, 101}
		periodAward = {['gold'] = 28000, ['rmb'] = 100, ['coin1'] = 400, __size = 3}
	},
	[17] = {
		id = 17,
		range = __data_t__range[17],
		-- {101, 201}
		periodAward = {['gold'] = 26000, ['rmb'] = 95, ['coin1'] = 380, __size = 3}
	},
	[18] = {
		id = 18,
		range = __data_t__range[18],
		-- {201, 301}
		periodAward = {['gold'] = 24000, ['rmb'] = 90, ['coin1'] = 360, __size = 3}
	},
	[19] = {
		id = 19,
		range = __data_t__range[19],
		-- {301, 401}
		periodAward = {['gold'] = 22000, ['rmb'] = 85, ['coin1'] = 340, __size = 3}
	},
	[20] = {
		id = 20,
		range = __data_t__range[20],
		-- {401, 501}
		periodAward = {['gold'] = 20000, ['rmb'] = 80, ['coin1'] = 320, __size = 3}
	},
	[21] = {
		id = 21,
		range = __data_t__range[21],
		-- {501, 601}
		periodAward = {['gold'] = 18000, ['rmb'] = 75, ['coin1'] = 300, __size = 3}
	},
	[22] = {
		id = 22,
		range = __data_t__range[22],
		-- {601, 701}
		periodAward = {['gold'] = 17000, ['rmb'] = 70, ['coin1'] = 280, __size = 3}
	},
	[23] = {
		id = 23,
		range = __data_t__range[23],
		-- {701, 801}
		periodAward = {['gold'] = 16000, ['rmb'] = 65, ['coin1'] = 260, __size = 3}
	},
	[24] = {
		id = 24,
		range = __data_t__range[24],
		-- {801, 1001}
		periodAward = {['gold'] = 15000, ['rmb'] = 60, ['coin1'] = 240, __size = 3}
	},
	[25] = {
		id = 25,
		range = __data_t__range[25],
		-- {1001, 3001}
		periodAward = {['gold'] = 14000, ['rmb'] = 55, ['coin1'] = 220, __size = 3}
	},
	[26] = {
		id = 26,
		range = __data_t__range[26],
		-- {3001, 5001}
		periodAward = {['gold'] = 13000, ['rmb'] = 50, ['coin1'] = 200, __size = 3}
	},
	[27] = {
		id = 27,
		range = __data_t__range[27],
		-- {5001, 10001}
		periodAward = {['gold'] = 12000, ['rmb'] = 45, ['coin1'] = 195, __size = 3}
	},
	[28] = {
		id = 28,
		range = __data_t__range[28],
		-- {10001, 15001}
		periodAward = {['gold'] = 11000, ['rmb'] = 40, ['coin1'] = 190, __size = 3}
	},
	[29] = {
		id = 29,
		range = __data_t__range[29],
		-- {15001, 100000}
		periodAward = {['gold'] = 10000, ['rmb'] = 40, ['coin1'] = 185, __size = 3}
	},
	[101] = {
		id = 101,
		range = __data_t__range[101],
		-- {1, 2}
		periodAward = __data_t__periodAward[101],
		-- {['gold'] = 150000, ['rmb'] = 700, ['coin1'] = 2700, __size = 3}
		version = 101
	},
	[102] = {
		id = 102,
		range = __data_t__range[102],
		-- {2, 3}
		periodAward = __data_t__periodAward[102],
		-- {['gold'] = 145000, ['rmb'] = 640, ['coin1'] = 2400, __size = 3}
		version = 101
	},
	[103] = {
		id = 103,
		range = __data_t__range[103],
		-- {3, 4}
		periodAward = __data_t__periodAward[103],
		-- {['gold'] = 140000, ['rmb'] = 600, ['coin1'] = 2100, __size = 3}
		version = 101
	},
	[104] = {
		id = 104,
		range = __data_t__range[104],
		-- {4, 5}
		periodAward = __data_t__periodAward[104],
		-- {['gold'] = 135000, ['rmb'] = 560, ['coin1'] = 1900, __size = 3}
		version = 101
	},
	[105] = {
		id = 105,
		range = __data_t__range[105],
		-- {5, 6}
		periodAward = __data_t__periodAward[105],
		-- {['gold'] = 130000, ['rmb'] = 520, ['coin1'] = 1800, __size = 3}
		version = 101
	},
	[106] = {
		id = 106,
		range = __data_t__range[106],
		-- {6, 7}
		periodAward = __data_t__periodAward[106],
		-- {['gold'] = 125000, ['rmb'] = 500, ['coin1'] = 1740, __size = 3}
		version = 101
	},
	[107] = {
		id = 107,
		range = __data_t__range[107],
		-- {7, 8}
		periodAward = __data_t__periodAward[107],
		-- {['gold'] = 120000, ['rmb'] = 480, ['coin1'] = 1680, __size = 3}
		version = 101
	},
	[108] = {
		id = 108,
		range = __data_t__range[108],
		-- {8, 9}
		periodAward = __data_t__periodAward[108],
		-- {['gold'] = 115000, ['rmb'] = 460, ['coin1'] = 1620, __size = 3}
		version = 101
	},
	[109] = {
		id = 109,
		range = __data_t__range[109],
		-- {9, 10}
		periodAward = __data_t__periodAward[109],
		-- {['gold'] = 110000, ['rmb'] = 440, ['coin1'] = 1560, __size = 3}
		version = 101
	},
	[110] = {
		id = 110,
		range = __data_t__range[110],
		-- {10, 11}
		periodAward = __data_t__periodAward[110],
		-- {['gold'] = 105000, ['rmb'] = 420, ['coin1'] = 1500, __size = 3}
		version = 101
	},
	[111] = {
		id = 111,
		range = __data_t__range[111],
		-- {11, 21}
		periodAward = __data_t__periodAward[111],
		-- {['gold'] = 100000, ['rmb'] = 400, ['coin1'] = 1400, __size = 3}
		version = 101
	},
	[112] = {
		id = 112,
		range = __data_t__range[112],
		-- {21, 31}
		periodAward = __data_t__periodAward[112],
		-- {['gold'] = 95000, ['rmb'] = 380, ['coin1'] = 1340, __size = 3}
		version = 101
	},
	[113] = {
		id = 113,
		range = __data_t__range[113],
		-- {31, 41}
		periodAward = __data_t__periodAward[113],
		-- {['gold'] = 90000, ['rmb'] = 360, ['coin1'] = 1280, __size = 3}
		version = 101
	},
	[114] = {
		id = 114,
		range = __data_t__range[114],
		-- {41, 51}
		periodAward = __data_t__periodAward[114],
		-- {['gold'] = 85000, ['rmb'] = 340, ['coin1'] = 1220, __size = 3}
		version = 101
	},
	[115] = {
		id = 115,
		range = __data_t__range[115],
		-- {51, 71}
		periodAward = __data_t__periodAward[115],
		-- {['gold'] = 80000, ['rmb'] = 320, ['coin1'] = 1160, __size = 3}
		version = 101
	},
	[116] = {
		id = 116,
		range = __data_t__range[116],
		-- {71, 101}
		periodAward = __data_t__periodAward[116],
		-- {['gold'] = 78000, ['rmb'] = 280, ['coin1'] = 1100, __size = 3}
		version = 101
	},
	[117] = {
		id = 117,
		range = __data_t__range[117],
		-- {101, 201}
		periodAward = __data_t__periodAward[117],
		-- {['gold'] = 76000, ['rmb'] = 240, ['coin1'] = 1060, __size = 3}
		version = 101
	},
	[118] = {
		id = 118,
		range = __data_t__range[118],
		-- {201, 301}
		periodAward = __data_t__periodAward[118],
		-- {['gold'] = 74000, ['rmb'] = 200, ['coin1'] = 1020, __size = 3}
		version = 101
	},
	[119] = {
		id = 119,
		range = __data_t__range[119],
		-- {301, 401}
		periodAward = __data_t__periodAward[119],
		-- {['gold'] = 72000, ['rmb'] = 180, ['coin1'] = 980, __size = 3}
		version = 101
	},
	[120] = {
		id = 120,
		range = __data_t__range[120],
		-- {401, 501}
		periodAward = __data_t__periodAward[120],
		-- {['gold'] = 70000, ['rmb'] = 160, ['coin1'] = 940, __size = 3}
		version = 101
	},
	[121] = {
		id = 121,
		range = __data_t__range[121],
		-- {501, 601}
		periodAward = __data_t__periodAward[121],
		-- {['gold'] = 68000, ['rmb'] = 150, ['coin1'] = 900, __size = 3}
		version = 101
	},
	[122] = {
		id = 122,
		range = __data_t__range[122],
		-- {601, 701}
		periodAward = __data_t__periodAward[122],
		-- {['gold'] = 67000, ['rmb'] = 140, ['coin1'] = 860, __size = 3}
		version = 101
	},
	[123] = {
		id = 123,
		range = __data_t__range[123],
		-- {701, 801}
		periodAward = __data_t__periodAward[123],
		-- {['gold'] = 66000, ['rmb'] = 130, ['coin1'] = 820, __size = 3}
		version = 101
	},
	[124] = {
		id = 124,
		range = __data_t__range[124],
		-- {801, 1001}
		periodAward = __data_t__periodAward[124],
		-- {['gold'] = 65000, ['rmb'] = 120, ['coin1'] = 780, __size = 3}
		version = 101
	},
	[125] = {
		id = 125,
		range = __data_t__range[125],
		-- {1001, 3001}
		periodAward = __data_t__periodAward[125],
		-- {['gold'] = 64000, ['rmb'] = 110, ['coin1'] = 740, __size = 3}
		version = 101
	},
	[126] = {
		id = 126,
		range = __data_t__range[126],
		-- {3001, 5001}
		periodAward = __data_t__periodAward[126],
		-- {['gold'] = 63000, ['rmb'] = 100, ['coin1'] = 700, __size = 3}
		version = 101
	},
	[127] = {
		id = 127,
		range = __data_t__range[127],
		-- {5001, 10001}
		periodAward = __data_t__periodAward[127],
		-- {['gold'] = 62000, ['rmb'] = 90, ['coin1'] = 690, __size = 3}
		version = 101
	},
	[128] = {
		id = 128,
		range = __data_t__range[128],
		-- {10001, 15001}
		periodAward = __data_t__periodAward[128],
		-- {['gold'] = 61000, ['rmb'] = 80, ['coin1'] = 680, __size = 3}
		version = 101
	},
	[129] = {
		id = 129,
		range = __data_t__range[129],
		-- {15001, 100000}
		periodAward = __data_t__periodAward[129],
		-- {['gold'] = 60000, ['rmb'] = 80, ['coin1'] = 670, __size = 3}
		version = 101
	},
	[201] = {
		id = 201,
		range = __data_t__range[201],
		-- {1, 2}
		periodAward = __data_t__periodAward[201],
		-- {['gold'] = 150000, ['rmb'] = 700, ['coin1'] = 2700, __size = 3}
		version = 102
	},
	[202] = {
		id = 202,
		range = __data_t__range[202],
		-- {2, 3}
		periodAward = __data_t__periodAward[202],
		-- {['gold'] = 145000, ['rmb'] = 640, ['coin1'] = 2400, __size = 3}
		version = 102
	},
	[203] = {
		id = 203,
		range = __data_t__range[203],
		-- {3, 4}
		periodAward = __data_t__periodAward[203],
		-- {['gold'] = 140000, ['rmb'] = 600, ['coin1'] = 2100, __size = 3}
		version = 102
	},
	[204] = {
		id = 204,
		range = __data_t__range[204],
		-- {4, 5}
		periodAward = __data_t__periodAward[204],
		-- {['gold'] = 135000, ['rmb'] = 560, ['coin1'] = 1900, __size = 3}
		version = 102
	},
	[205] = {
		id = 205,
		range = __data_t__range[205],
		-- {5, 6}
		periodAward = __data_t__periodAward[205],
		-- {['gold'] = 130000, ['rmb'] = 520, ['coin1'] = 1800, __size = 3}
		version = 102
	},
	[206] = {
		id = 206,
		range = __data_t__range[206],
		-- {6, 7}
		periodAward = __data_t__periodAward[206],
		-- {['gold'] = 125000, ['rmb'] = 500, ['coin1'] = 1740, __size = 3}
		version = 102
	},
	[207] = {
		id = 207,
		range = __data_t__range[207],
		-- {7, 8}
		periodAward = __data_t__periodAward[207],
		-- {['gold'] = 120000, ['rmb'] = 480, ['coin1'] = 1680, __size = 3}
		version = 102
	},
	[208] = {
		id = 208,
		range = __data_t__range[208],
		-- {8, 9}
		periodAward = __data_t__periodAward[208],
		-- {['gold'] = 115000, ['rmb'] = 460, ['coin1'] = 1620, __size = 3}
		version = 102
	},
	[209] = {
		id = 209,
		range = __data_t__range[209],
		-- {9, 10}
		periodAward = __data_t__periodAward[209],
		-- {['gold'] = 110000, ['rmb'] = 440, ['coin1'] = 1560, __size = 3}
		version = 102
	},
	[210] = {
		id = 210,
		range = __data_t__range[210],
		-- {10, 11}
		periodAward = __data_t__periodAward[210],
		-- {['gold'] = 105000, ['rmb'] = 420, ['coin1'] = 1500, __size = 3}
		version = 102
	},
	[211] = {
		id = 211,
		range = __data_t__range[211],
		-- {11, 21}
		periodAward = __data_t__periodAward[211],
		-- {['gold'] = 100000, ['rmb'] = 400, ['coin1'] = 1400, __size = 3}
		version = 102
	},
	[212] = {
		id = 212,
		range = __data_t__range[212],
		-- {21, 31}
		periodAward = __data_t__periodAward[212],
		-- {['gold'] = 95000, ['rmb'] = 380, ['coin1'] = 1340, __size = 3}
		version = 102
	},
	[213] = {
		id = 213,
		range = __data_t__range[213],
		-- {31, 41}
		periodAward = __data_t__periodAward[213],
		-- {['gold'] = 90000, ['rmb'] = 360, ['coin1'] = 1280, __size = 3}
		version = 102
	},
	[214] = {
		id = 214,
		range = __data_t__range[214],
		-- {41, 51}
		periodAward = __data_t__periodAward[214],
		-- {['gold'] = 85000, ['rmb'] = 340, ['coin1'] = 1220, __size = 3}
		version = 102
	},
	[215] = {
		id = 215,
		range = __data_t__range[215],
		-- {51, 71}
		periodAward = __data_t__periodAward[215],
		-- {['gold'] = 80000, ['rmb'] = 320, ['coin1'] = 1160, __size = 3}
		version = 102
	},
	[216] = {
		id = 216,
		range = __data_t__range[216],
		-- {71, 101}
		periodAward = __data_t__periodAward[216],
		-- {['gold'] = 78000, ['rmb'] = 280, ['coin1'] = 1100, __size = 3}
		version = 102
	},
	[217] = {
		id = 217,
		range = __data_t__range[217],
		-- {101, 201}
		periodAward = __data_t__periodAward[217],
		-- {['gold'] = 76000, ['rmb'] = 240, ['coin1'] = 1060, __size = 3}
		version = 102
	},
	[218] = {
		id = 218,
		range = __data_t__range[218],
		-- {201, 301}
		periodAward = __data_t__periodAward[218],
		-- {['gold'] = 74000, ['rmb'] = 200, ['coin1'] = 1020, __size = 3}
		version = 102
	},
	[219] = {
		id = 219,
		range = __data_t__range[219],
		-- {301, 401}
		periodAward = __data_t__periodAward[219],
		-- {['gold'] = 72000, ['rmb'] = 180, ['coin1'] = 980, __size = 3}
		version = 102
	},
	[220] = {
		id = 220,
		range = __data_t__range[220],
		-- {401, 501}
		periodAward = __data_t__periodAward[220],
		-- {['gold'] = 70000, ['rmb'] = 160, ['coin1'] = 940, __size = 3}
		version = 102
	},
	[221] = {
		id = 221,
		range = __data_t__range[221],
		-- {501, 601}
		periodAward = __data_t__periodAward[221],
		-- {['gold'] = 68000, ['rmb'] = 150, ['coin1'] = 900, __size = 3}
		version = 102
	},
	[222] = {
		id = 222,
		range = __data_t__range[222],
		-- {601, 701}
		periodAward = __data_t__periodAward[222],
		-- {['gold'] = 67000, ['rmb'] = 140, ['coin1'] = 860, __size = 3}
		version = 102
	},
	[223] = {
		id = 223,
		range = __data_t__range[223],
		-- {701, 801}
		periodAward = __data_t__periodAward[223],
		-- {['gold'] = 66000, ['rmb'] = 130, ['coin1'] = 820, __size = 3}
		version = 102
	},
	[224] = {
		id = 224,
		range = __data_t__range[224],
		-- {801, 1001}
		periodAward = __data_t__periodAward[224],
		-- {['gold'] = 65000, ['rmb'] = 120, ['coin1'] = 780, __size = 3}
		version = 102
	},
	[225] = {
		id = 225,
		range = __data_t__range[225],
		-- {1001, 3001}
		periodAward = __data_t__periodAward[225],
		-- {['gold'] = 64000, ['rmb'] = 110, ['coin1'] = 740, __size = 3}
		version = 102
	},
	[226] = {
		id = 226,
		range = __data_t__range[226],
		-- {3001, 5001}
		periodAward = __data_t__periodAward[226],
		-- {['gold'] = 63000, ['rmb'] = 100, ['coin1'] = 700, __size = 3}
		version = 102
	},
	[227] = {
		id = 227,
		range = __data_t__range[227],
		-- {5001, 10001}
		periodAward = __data_t__periodAward[227],
		-- {['gold'] = 62000, ['rmb'] = 90, ['coin1'] = 690, __size = 3}
		version = 102
	},
	[228] = {
		id = 228,
		range = __data_t__range[228],
		-- {10001, 15001}
		periodAward = __data_t__periodAward[228],
		-- {['gold'] = 61000, ['rmb'] = 80, ['coin1'] = 680, __size = 3}
		version = 102
	},
	[229] = {
		id = 229,
		range = __data_t__range[229],
		-- {15001, 100000}
		periodAward = __data_t__periodAward[229],
		-- {['gold'] = 60000, ['rmb'] = 80, ['coin1'] = 670, __size = 3}
		version = 102
	},

	__size = 87,
	__default = {
		__index = {
			periodAward = {__size = 0},
			version = 0
		}
	}
}
return csv.pwaward