--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {[66016] = 1, __size = 1}, 
	[3] = {[66017] = 1, __size = 1}, 
	[4] = {[66016] = 1, [66017] = 1, __size = 2}, __size = 3}
local __data_t__skills = {
	[11] = __predefine_t__[2],
	[21] = __predefine_t__[3],
	[31] = __predefine_t__[4],
	[1] = __predefine_t__[2],
	[3] = __predefine_t__[4],
	[2] = __predefine_t__[3]
}

csv['scene_story_choices'] = {
	[1] = {
		id = 1,
		text = 'Golden Apple',
		text_ma = 'Epal Emas',
		text_en = 'Golden Apple',
		text_th = 'แอปเปิ้ลทอง',
		text_in = 'Apel Emas',
		text_ph = 'Gintong Mansanas',
		text_vn = 'Táo vàng',
		startStoryID = 3000007,
		skills = __data_t__skills[1]
		-- {[66016] = 1, __size = 1}
	},
	[2] = {
		id = 2,
		text = 'Silver Apple',
		text_ma = 'Epal Perak',
		text_en = 'Silver Apple',
		text_th = 'แอปเปิ้ลเงิน',
		text_in = 'Apel Perak',
		text_ph = 'Pilak na Mansanas',
		text_vn = 'Táo bạc',
		startStoryID = 3000009,
		skills = __data_t__skills[2]
		-- {[66017] = 1, __size = 1}
	},
	[3] = {
		id = 3,
		text = 'Rotten Apple',
		text_ma = 'Epal Busuk',
		text_en = 'Rotten Apple',
		text_th = 'แอปเปิ้ลเน่า',
		text_in = 'Apel Busuk',
		text_ph = 'Bulok na Mansanas',
		text_vn = 'Táo hỏng',
		startStoryID = 3000011,
		skills = __data_t__skills[3]
		-- {[66016] = 1, [66017] = 1, __size = 2}
	},
	[11] = {
		id = 11,
		text = 'Golden Apple 2',
		text_ma = 'Epal Emas 2',
		text_en = 'Golden Apple 2',
		text_th = 'แอปเปิ้ลทอง 2',
		text_in = 'Apel Emas 2',
		text_ph = 'Gintong Mansanas 2',
		text_vn = 'Táo vàng 2',
		startStoryID = 11,
		skills = __data_t__skills[11]
		-- {[66016] = 1, __size = 1}
	},
	[21] = {
		id = 21,
		text = 'Silver Apple 2',
		text_ma = 'Epal Perak 2',
		text_en = 'Silver Apple 2',
		text_th = 'แอปเปิ้ลเงิน 2',
		text_in = 'Apel Perak 2',
		text_ph = 'Pilak na Mansanas 2',
		text_vn = 'Táo bạc 2',
		startStoryID = 21,
		skills = __data_t__skills[21]
		-- {[66017] = 1, __size = 1}
	},
	[31] = {
		id = 31,
		text = 'Rotten Apple 2',
		text_ma = 'Epal Busuk 2',
		text_en = 'Rotten Apple 2',
		text_th = 'แอปเปิ้ลเน่า 2',
		text_in = 'Apel Busuk 2',
		text_ph = 'Bulok na Mansanas 2',
		text_vn = 'Táo hỏng 2',
		startStoryID = 31,
		skills = __data_t__skills[31]
		-- {[66016] = 1, [66017] = 1, __size = 2}
	},
	[100001] = {
		id = 100001,
		text = 'Go left',
		text_ma = 'Pergi ke kiri',
		text_en = 'Go left',
		text_th = 'ไปทางซ้าย',
		text_in = 'Pergi ke kiri',
		text_ph = 'Pumunta sa kaliwa',
		text_vn = 'Đi bên trái',
		startStoryID = 100007,
		skills = {[50000001] = 1, __size = 1}
	},
	[100002] = {
		id = 100002,
		text = 'Go right',
		text_ma = 'Pergi ke kanan',
		text_en = 'Go right',
		text_th = 'ไปทางขวา',
		text_in = 'Pergi ke kanan',
		text_ph = 'Pumunta sa kanan',
		text_vn = 'Đi bên phải',
		startStoryID = 100009
	},
	[100101] = {
		id = 100101,
		text = 'Come out! Turtwig! Use water to melt!',
		text_ma = 'Keluar! Turtwig! Gunakan air untuk mencairkan!',
		text_en = 'Come out! Turtwig! Use water to melt!',
		text_th = 'ออกมา! Turtwig! ใช้น้ำทำให้ละลาย!',
		text_in = 'Keluar! Turtwig! Gunakan air untuk melelehkan!',
		text_ph = 'Lumabas ka! Turtwig! Gamitin ang tubig para tunawin!',
		text_vn = 'Ra đây đi! Turtwig! Dùng nước để làm tan!',
		startStoryID = 100105
	},
	[100102] = {
		id = 100102,
		text = 'Come out! Charmander! Use fire to melt!',
		text_ma = 'Keluar! Charmander! Gunakan api untuk mencairkan!',
		text_en = 'Come out! Charmander! Use fire to melt!',
		text_th = 'ออกมา! Charmander! ใช้ไฟทำให้ละลาย!',
		text_in = 'Keluar! Charmander! Gunakan api untuk melelehkan!',
		text_ph = 'Lumabas ka! Charmander! Gamitin ang apoy para tunawin!',
		text_vn = 'Ra đây đi! Charmander! Dùng lửa để làm tan!',
		startStoryID = 100107,
		skills = {[50000002] = 1, __size = 1}
	},
	[100601] = {
		id = 100601,
		text = 'Prioritize healing Magikarp',
		text_ma = 'Utamakan merawat Magikarp',
		text_en = 'Prioritize healing Magikarp',
		text_th = 'ให้ความสำคัญกับการรักษา Magikarp',
		text_in = 'Prioritaskan penyembuhan Magikarp',
		text_ph = 'Bigyang-priyoridad ang pagpapagaling kay Magikarp',
		text_vn = 'Ưu tiên chữa trị Magikarp',
		startStoryID = 100612,
		skills = {[50000011] = 1, __size = 1}
	},
	[100602] = {
		id = 100602,
		text = 'Prioritize driving out the bad guys',
		text_ma = 'Utamakan menghalau orang jahat',
		text_en = 'Prioritize driving out the bad guys',
		text_th = 'ให้ความสำคัญกับการขับไล่คนไม่ดีออกไป',
		text_in = 'Prioritaskan mengusir orang jahat',
		text_ph = 'Bigyang-priyoridad ang pagpapaalis sa mga masamang tao',
		text_vn = 'Ưu tiên đuổi kẻ xấu ra ngoài',
		startStoryID = 100614,
		skills = {[50000012] = 1, __size = 1}
	},

	__size = 12,
	__default = {
		__index = {
			text = '',
			text_ma = '',
			text_en = '',
			text_th = '',
			text_in = '',
			text_ph = '',
			text_vn = '',
			startStoryID = 0,
			skills = {__size = 0}
		}
	}
}
return csv.scene_story_choices