--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {[4932] = 1, [4933] = 1, __size = 2}, 
	[3] = {[823] = 1, [822] = 1, __size = 2}, __size = 2}
local __data_t__skills = {
	[9] = __predefine_t__[2],
	[8] = __predefine_t__[2],
	[12] = __predefine_t__[3],
	[7] = __predefine_t__[2],
	[10] = __predefine_t__[3]
}

csv['try_play_battle'] = {
	[2] = {
		id = 2,
		roleId = 0,
		roleForce = 1,
		classify = 3,
		mp2 = 1000,
		mp1Recover = 1000,
		mp2Recover = 1000,
		damage = 1000000,
		specialDamage = 1000000,
		defence = 3000,
		specialDefence = 3000,
		speed = 20,
		initMp1 = 1000
	},
	[7] = {
		id = 7,
		roleId = 60493,
		roleForce = 2,
		skills = __data_t__skills[7],
		-- {[4932] = 1, [4933] = 1, __size = 2}
		classify = 3,
		hp = 99999999,
		damage = 1000,
		specialDamage = 1000,
		defence = 3000,
		specialDefence = 3000,
		speed = 14
	},
	[8] = {
		id = 8,
		roleId = 60493,
		roleForce = 2,
		skills = __data_t__skills[8],
		-- {[4932] = 1, [4933] = 1, __size = 2}
		classify = 3,
		hp = 99999999,
		damage = 1000,
		specialDamage = 1000,
		defence = 3000,
		specialDefence = 3000,
		speed = 14
	},
	[9] = {
		id = 9,
		roleId = 60493,
		roleForce = 2,
		skills = __data_t__skills[9],
		-- {[4932] = 1, [4933] = 1, __size = 2}
		classify = 3,
		hp = 99999999,
		damage = 1000,
		specialDamage = 1000,
		defence = 3000,
		specialDefence = 3000,
		speed = 14
	},
	[10] = {
		id = 10,
		roleId = 60082,
		roleForce = 2,
		skills = __data_t__skills[10],
		-- {[823] = 1, [822] = 1, __size = 2}
		classify = 3,
		hp = 99999999,
		damage = 1000,
		specialDamage = 1000,
		defence = 3000,
		specialDefence = 3000,
		speed = 14
	},
	[11] = {
		id = 11,
		roleId = 60044,
		roleForce = 2,
		skills = {[443] = 1, [442] = 1, __size = 2},
		classify = 3,
		hp = 99999999,
		damage = 1000,
		specialDamage = 1000,
		defence = 3000,
		specialDefence = 3000,
		speed = 14
	},
	[12] = {
		id = 12,
		roleId = 60082,
		roleForce = 2,
		skills = __data_t__skills[12],
		-- {[823] = 1, [822] = 1, __size = 2}
		classify = 3,
		hp = 99999999,
		damage = 1000,
		specialDamage = 1000,
		defence = 3000,
		specialDefence = 3000,
		speed = 14
	},

	__size = 7,
	__default = {
		__index = {
			level = 100,
			skills = {__size = 0},
			star = 12,
			activeSkill = 0,
			classify = 0,
			hp = 1400000,
			mp1 = 1000,
			mp2 = 1,
			hpRecover = 1,
			mp1Recover = 1,
			mp2Recover = 1,
			damage = 1,
			specialDamage = 1,
			defence = 1,
			specialDefence = 1,
			defenceIgnore = 1,
			specialDefenceIgnore = 1,
			speed = 1,
			strike = 1,
			strikeDamage = 15000,
			strikeResistance = 1,
			block = 1,
			breakBlock = 1,
			blockPower = 1,
			dodge = 1,
			hit = 10000,
			damageAdd = 1,
			damageSub = 1,
			ultimateAdd = 0,
			ultimateSub = 0,
			damageDeepen = 1,
			damageReduce = 1,
			suckBlood = 0,
			suckBlood1 = 0,
			cure = 1,
			natureRestraint = 1,
			controlPer = 1,
			immuneControl = 1,
			initMp1 = 0
		}
	}
}
return csv.try_play_battle