--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['base_attribute']['nature_matrix'] = {
	[1] = {
		id = 1,
		ground = 0.7,
		super = 1.5,
		rock = 0.7,
		ghost = 1.5,
		evil = 1.5,
		steel = 0.7
	},
	[2] = {
		id = 2,
		water = 0.7,
		ice = 1.5,
		poison = 1.5,
		ground = 0.7,
		dragon = 0.7,
		steel = 1.5
	},
	[3] = {
		id = 3,
		fire = 1.5,
		electricity = 0.7,
		ice = 0.7,
		poison = 1.5,
		ground = 1.5,
		rock = 0.7
	},
	[4] = {
		id = 4,
		electricity = 1.5,
		combat = 0.7,
		poison = 0.7,
		ground = 1.5,
		fly = 1.5,
		ghost = 0.7
	},
	[5] = {
		id = 5,
		water = 1.5,
		grass = 0.7,
		ground = 0.7,
		rock = 0.7,
		ghost = 1.5,
		steel = 1.5
	},
	[6] = {
		id = 6,
		fire = 0.7,
		water = 1.5,
		combat = 1.5,
		rock = 1.5,
		ghost = 0.7,
		dragon = 0.7
	},
	[7] = {
		id = 7,
		grass = 1.5,
		ice = 0.7,
		fly = 0.7,
		worm = 0.7,
		rock = 1.5,
		dragon = 1.5
	},
	[8] = {
		id = 8,
		fire = 0.7,
		water = 0.7,
		grass = 1.5,
		super = 1.5,
		evil = 1.5,
		fairy = 0.7
	},
	[9] = {
		id = 9,
		normal = 1.5,
		fire = 1.5,
		water = 0.7,
		grass = 0.7,
		electricity = 1.5,
		evil = 0.7
	},
	[10] = {
		id = 10,
		grass = 0.7,
		combat = 1.5,
		worm = 1.5,
		dragon = 0.7,
		evil = 0.7,
		fairy = 1.5
	},
	[11] = {
		id = 11,
		normal = 0.7,
		poison = 0.7,
		worm = 1.5,
		dragon = 1.5,
		steel = 1.5,
		fairy = 0.7
	},
	[12] = {
		id = 12,
		combat = 1.5,
		fly = 0.7,
		super = 0.7,
		dragon = 1.5,
		evil = 0.7,
		fairy = 1.5
	},
	[13] = {
		id = 13,
		normal = 1.5,
		water = 1.5,
		electricity = 1.5,
		ice = 0.7,
		combat = 0.7,
		ghost = 0.7
	},
	[14] = {
		id = 14,
		normal = 0.7,
		grass = 1.5,
		electricity = 0.7,
		ice = 1.5,
		rock = 1.5,
		fairy = 0.7
	},
	[15] = {
		id = 15,
		fire = 1.5,
		ice = 1.5,
		combat = 0.7,
		fly = 1.5,
		super = 0.7,
		worm = 0.7,
		evil = 1.5,
		steel = 0.7
	},
	[16] = {
		id = 16,
		normal = 0.7,
		poison = 0.7,
		ground = 1.5,
		fly = 1.5,
		worm = 1.5,
		dragon = 0.7
	},
	[17] = {
		id = 17,
		normal = 1.5,
		fire = 0.7,
		electricity = 0.7,
		super = 0.7,
		dragon = 1.5,
		fairy = 1.5
	},
	[18] = {
		id = 18,
		poison = 1.5,
		fly = 0.7,
		super = 1.5,
		worm = 0.7,
		ghost = 1.5,
		steel = 0.7
	},

	__size = 18,
	__default = {
		__index = {
			normal = 1,
			fire = 1,
			water = 1,
			grass = 1,
			electricity = 1,
			ice = 1,
			combat = 1,
			poison = 1,
			ground = 1,
			fly = 1,
			super = 1,
			worm = 1,
			rock = 1,
			ghost = 1,
			dragon = 1,
			evil = 1,
			steel = 1,
			fairy = 1
		}
	}
}
return csv.base_attribute.nature_matrix