--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['skyscraper_tasks'] = {
	[1] = {
		id = 1,
		huodongID = 1,
		label = 'Built 25 floors today',
		label_th = 'จำนวนชั้นที่สร้างเสร็จในวันนี้ถึง 25 ชั้นแล้ว',
		label_en = 'Built 25 floors today',
		params = 25,
		award = {['gold'] = 100000, [5000] = 10, [850] = 100, __size = 3},
		points = 25
	},
	[2] = {
		id = 2,
		huodongID = 1,
		label = 'Built 75 floors today',
		label_th = 'จำนวนชั้นที่สร้างเสร็จในวันนี้ถึง 75 ชั้นแล้ว',
		label_en = 'Built 75 floors today',
		params = 75,
		award = {['gold'] = 150000, [930] = 10, [502] = 1, __size = 3},
		points = 25
	},
	[5] = {
		id = 5,
		huodongID = 1,
		type = 2,
		label = 'Achieved 800 pts in rating today',
		label_th = 'ได้รับคะแนนรวม 800 คะแนนในวันนี้',
		label_en = 'Achieved 800 pts in rating today',
		params = 800,
		award = {[451] = 100, ['gold'] = 100000, [5000] = 10, __size = 3},
		points = 25
	},
	[6] = {
		id = 6,
		huodongID = 1,
		type = 2,
		label = 'Achieved 1,600 pts in rating today',
		label_th = 'ได้รับคะแนนรวม 1,600 คะแนนในวันนี้',
		label_en = 'Achieved 1,600 pts in rating today',
		params = 1600,
		award = {['stamina'] = 30, ['gold'] = 150000, [930] = 10, __size = 3},
		points = 25
	},
	[9] = {
		id = 9,
		huodongID = 1,
		type = 3,
		label = 'Received Perfect Rank on Building 8 times today',
		label_th = 'ได้รับคะแนนการสร้างที่สมบูรณ์แบบทั้งหมด 8 คะแนนในวันนี้',
		label_en = 'Received Perfect Rank on Building 8 times today',
		params = 8,
		award = {[930] = 10, [850] = 50, [5000] = 10, __size = 3},
		points = 25
	},
	[10] = {
		id = 10,
		huodongID = 1,
		type = 3,
		label = 'Received Perfect Rank on Building 20 times today',
		label_th = 'ได้รับคะแนนการสร้างที่สมบูรณ์แบบทั้งหมด 20 คะแนนในวันนี้',
		label_en = 'Received Perfect Rank on Building 20 times today',
		params = 20,
		award = {[930] = 15, [850] = 50, [5000] = 15, __size = 3},
		points = 25
	},

	__size = 6,
	__default = {
		__index = {
			huodongID = 1001,
			type = 1,
			label = '',
			label_th = '',
			label_en = '',
			label_vn = '',
			params = 0,
			award = {__size = 0},
			points = 0
		}
	}
}
return csv.yunying.skyscraper_tasks