--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[10] = {['gold'] = 200000, ['rmb'] = 1000, [14] = 10, __size = 3}, 
	[11] = {['gold'] = 300000, ['rmb'] = 1200, [14] = 10, __size = 3}, __size = 2}
local __data_t__award = {
	[9] = __predefine_t__[10],
	[10] = __predefine_t__[10],
	[13] = __predefine_t__[11],
	[12] = __predefine_t__[11],
	[11] = __predefine_t__[11]
}

csv['yunying']['levelfund'] = {
	[1] = {
		id = 1,
		huodongID = 22001,
		needLevel = 15,
		desc = 'เลเวลถึง 15',
		award = {['gold'] = 100000, [12] = 10, ['rmb'] = 200, __size = 3}
	},
	[2] = {
		id = 2,
		huodongID = 22001,
		needLevel = 20,
		desc = 'เลเวลถึง 20',
		award = {['gold'] = 100000, [12] = 10, ['rmb'] = 300, __size = 3}
	},
	[3] = {
		id = 3,
		huodongID = 22001,
		needLevel = 25,
		desc = 'เลเวลถึง 25',
		award = {['gold'] = 100000, [12] = 10, ['rmb'] = 400, __size = 3}
	},
	[4] = {
		id = 4,
		huodongID = 22001,
		needLevel = 30,
		desc = 'เลเวลถึง 30',
		award = {['gold'] = 100000, ['rmb'] = 500, [13] = 10, __size = 3}
	},
	[5] = {
		id = 5,
		huodongID = 22001,
		needLevel = 35,
		desc = 'เลเวลถึง 35',
		award = {['gold'] = 100000, ['rmb'] = 600, [13] = 10, __size = 3}
	},
	[6] = {
		id = 6,
		huodongID = 22001,
		needLevel = 40,
		desc = 'เลเวลถึง 40',
		award = {['gold'] = 200000, ['rmb'] = 700, [13] = 10, __size = 3}
	},
	[7] = {
		id = 7,
		huodongID = 22001,
		needLevel = 45,
		desc = 'เลเวลถึง 45',
		award = {['gold'] = 200000, ['rmb'] = 800, [13] = 10, __size = 3}
	},
	[8] = {
		id = 8,
		huodongID = 22001,
		needLevel = 50,
		desc = 'เลเวลถึง 50',
		award = {['gold'] = 200000, ['rmb'] = 900, [13] = 10, __size = 3}
	},
	[9] = {
		id = 9,
		huodongID = 22001,
		needLevel = 55,
		desc = 'เลเวลถึง 55',
		award = __data_t__award[9]
		-- {['gold'] = 200000, ['rmb'] = 1000, [14] = 10, __size = 3}
	},
	[10] = {
		id = 10,
		huodongID = 22001,
		needLevel = 60,
		desc = 'เลเวลถึง 60',
		award = __data_t__award[10]
		-- {['gold'] = 200000, ['rmb'] = 1000, [14] = 10, __size = 3}
	},
	[11] = {
		id = 11,
		huodongID = 22001,
		needLevel = 70,
		desc = 'เลเวลถึง 70',
		award = __data_t__award[11]
		-- {['gold'] = 300000, ['rmb'] = 1200, [14] = 10, __size = 3}
	},
	[12] = {
		id = 12,
		huodongID = 22001,
		needLevel = 80,
		desc = 'เลเวลถึง 80',
		award = __data_t__award[12]
		-- {['gold'] = 300000, ['rmb'] = 1200, [14] = 10, __size = 3}
	},
	[13] = {
		id = 13,
		huodongID = 22001,
		needLevel = 90,
		desc = 'เลเวลถึง 90',
		award = __data_t__award[13]
		-- {['gold'] = 300000, ['rmb'] = 1200, [14] = 10, __size = 3}
	},

	__size = 13,
	__default = {
		__index = {
			huodongID = 0,
			needLevel = 1,
			desc = '',
			award = {__size = 0}
		}
	}
}
return csv.yunying.levelfund