--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['mid_autumn_draw_tasks'] = {
	[1] = {
		id = 1,
		huodongID = 1001,
		taskType = 17,
		taskParam = 1,
		desc = 'เข้าสู่เกมในวันนั้น',
		addTimes = 1
	},
	[2] = {
		id = 2,
		huodongID = 1001,
		taskType = 18,
		taskParam = 200,
		desc = 'สะสมสมบัติครบ 200 ครั้งในวันนั้น',
		addTimes = 1
	},
	[3] = {
		id = 3,
		huodongID = 1001,
		taskType = 41,
		taskParam = 10,
		desc = 'ท้าทายอารีน่า 10 ครั้งในวันนั้น',
		addTimes = 1
	},
	[11] = {
		id = 11,
		huodongID = 1001,
		taskType = 28,
		taskParam = 3000,
		desc = 'ใช้พลังงานครบ 3000 แต้มในวันนั้น',
		addTimes = 1
	},
	[12] = {
		id = 12,
		huodongID = 1001,
		taskType = 28,
		taskParam = 9000,
		desc = 'ใช้พลังงานครบ 9000 แต้มในวันนั้น',
		addTimes = 1
	},
	[13] = {
		id = 13,
		huodongID = 1001,
		taskType = 28,
		taskParam = 18000,
		desc = 'ใช้พลังงานครบ 18000 แต้มในวันนั้น',
		addTimes = 1
	},
	[14] = {
		id = 14,
		huodongID = 1001,
		taskType = 28,
		taskParam = 24000,
		desc = 'ใช้พลังงานครบ 24000 แต้มในวันนั้น',
		addTimes = 1
	},
	[15] = {
		id = 15,
		huodongID = 1001,
		taskType = 28,
		taskParam = 36000,
		desc = 'ใช้พลังงานครบ 360000 แต้มในวันนั้น',
		addTimes = 1
	},
	[16] = {
		id = 16,
		huodongID = 1001,
		taskType = 28,
		taskParam = 60000,
		desc = 'ใช้พลังงานครบ 60000 แต้มในวันนั้น',
		addTimes = 1
	},
	[17] = {
		id = 17,
		huodongID = 1001,
		taskType = 28,
		taskParam = 90000,
		desc = 'ใช้พลังงานครบ 90000 แต้มในวันนั้น',
		addTimes = 1
	},
	[18] = {
		id = 18,
		huodongID = 1001,
		taskType = 28,
		taskParam = 120000,
		desc = 'ใช้พลังงานครบ 120000 แต้มในวันนั้น',
		addTimes = 1
	},
	[21] = {
		id = 21,
		huodongID = 1001,
		taskType = 22,
		taskParam = 60,
		desc = 'เติมเงิน 60 เพชรในวันนั้น',
		addTimes = 1
	},
	[22] = {
		id = 22,
		huodongID = 1001,
		taskType = 22,
		taskParam = 300,
		desc = 'เติมเงิน 300 เพชรในวันนั้น',
		addTimes = 1
	},
	[23] = {
		id = 23,
		huodongID = 1001,
		taskType = 22,
		taskParam = 600,
		desc = 'เติมเงิน 600 เพชรในวันนั้น',
		addTimes = 1
	},
	[24] = {
		id = 24,
		huodongID = 1001,
		taskType = 22,
		taskParam = 1000,
		desc = 'เติมเงิน 1000 เพชรในวันนั้น',
		addTimes = 1
	},
	[25] = {
		id = 25,
		huodongID = 1001,
		taskType = 22,
		taskParam = 3000,
		desc = 'เติมเงิน 3000 เพชรในวันนั้น',
		addTimes = 1
	},
	[26] = {
		id = 26,
		huodongID = 1001,
		taskType = 22,
		taskParam = 5000,
		desc = 'เติมเงิน 5000 เพชรในวันนั้น',
		addTimes = 2
	},
	[27] = {
		id = 27,
		huodongID = 1001,
		taskType = 22,
		taskParam = 8000,
		desc = 'เติมเงิน 8000 เพชรในวันนั้น',
		addTimes = 3
	},
	[28] = {
		id = 28,
		huodongID = 1001,
		taskType = 22,
		taskParam = 10000,
		desc = 'เติมเงิน 10000 เพชรในวันนั้น',
		addTimes = 5
	},
	[31] = {
		id = 31,
		huodongID = 1001,
		taskType = 21,
		taskParam = 80000,
		desc = 'ใช้ 80000 เพชรในวันนั้น',
		addTimes = 1
	},
	[32] = {
		id = 32,
		huodongID = 1001,
		taskType = 21,
		taskParam = 150000,
		desc = 'ใช้ 150000 เพชรในวันนั้น',
		addTimes = 1
	},
	[33] = {
		id = 33,
		huodongID = 1001,
		taskType = 21,
		taskParam = 300000,
		desc = 'ใช้ 300000 เพชรในวันนั้น',
		addTimes = 1
	},
	[34] = {
		id = 34,
		huodongID = 1001,
		taskType = 21,
		taskParam = 500000,
		desc = 'ใช้ 500000 เพชรในวันนั้น',
		addTimes = 1
	},
	[35] = {
		id = 35,
		huodongID = 1001,
		taskType = 21,
		taskParam = 1000000,
		desc = 'ใช้ 1000000 เพชรในวันนั้น',
		addTimes = 1
	},

	__size = 24,
	__default = {
		__index = {
			huodongID = 0,
			taskType = 0,
			taskParam = 9999,
			taskSpecialParam = {__size = 0},
			desc = '',
			addTimes = 0
		}
	}
}
return csv.yunying.mid_autumn_draw_tasks