--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {['rmb'] = 6480, __size = 1}, 
	[3] = {['rmb'] = 3280, __size = 1}, 
	[4] = {['rmb'] = 1980, __size = 1}, 
	[5] = {['rmb'] = 980, __size = 1}, 
	[6] = {['rmb'] = 600, __size = 1}, 
	[7] = {['rmb'] = 300, __size = 1}, 
	[8] = {['rmb'] = 60, __size = 1}, __size = 7}
local __data_t__award = {
	[11] = __predefine_t__[2],
	[13] = __predefine_t__[4],
	[12] = __predefine_t__[3],
	[15] = __predefine_t__[6],
	[14] = __predefine_t__[5],
	[17] = __predefine_t__[8],
	[16] = __predefine_t__[7],
	[1] = __predefine_t__[2],
	[27] = __predefine_t__[8],
	[3] = __predefine_t__[4],
	[2] = __predefine_t__[3],
	[5] = __predefine_t__[6],
	[4] = __predefine_t__[5],
	[7] = __predefine_t__[8],
	[6] = __predefine_t__[7]
}

csv['yunying']['oncerechage'] = {
	[1] = {
		id = 1,
		huodongID = 3001,
		needRmb = 6480,
		desc = 'Single recharge 6580 diamond',
		award = __data_t__award[1],
		-- {['rmb'] = 6480, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz1.png'
	},
	[2] = {
		id = 2,
		huodongID = 3001,
		needRmb = 3280,
		desc = 'Single recharge 3380 diamond',
		award = __data_t__award[2],
		-- {['rmb'] = 3280, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz2.png'
	},
	[3] = {
		id = 3,
		huodongID = 3001,
		needRmb = 1980,
		desc = 'Single recharge 1980 diamond',
		award = __data_t__award[3],
		-- {['rmb'] = 1980, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz3.png'
	},
	[4] = {
		id = 4,
		huodongID = 3001,
		needRmb = 980,
		desc = 'Single recharge 980 diamond',
		award = __data_t__award[4],
		-- {['rmb'] = 980, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz4.png'
	},
	[5] = {
		id = 5,
		huodongID = 3001,
		needRmb = 600,
		desc = 'Single recharge 580 diamond',
		award = __data_t__award[5],
		-- {['rmb'] = 600, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz5.png'
	},
	[6] = {
		id = 6,
		huodongID = 3001,
		needRmb = 300,
		desc = 'Single recharge 340 diamond',
		award = __data_t__award[6],
		-- {['rmb'] = 300, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz6.png'
	},
	[7] = {
		id = 7,
		huodongID = 3001,
		needRmb = 60,
		desc = 'Single recharge 66 diamond',
		award = __data_t__award[7],
		-- {['rmb'] = 60, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz7.png'
	},
	[11] = {
		id = 11,
		huodongID = 3003,
		needRmb = 6480,
		desc = 'Single recharge 6580 diamond',
		award = __data_t__award[11],
		-- {['rmb'] = 6480, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz1.png'
	},
	[12] = {
		id = 12,
		huodongID = 3003,
		needRmb = 3280,
		desc = 'Single recharge 3380 diamond',
		award = __data_t__award[12],
		-- {['rmb'] = 3280, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz2.png'
	},
	[13] = {
		id = 13,
		huodongID = 3003,
		needRmb = 1980,
		desc = 'Single recharge 1980 diamond',
		award = __data_t__award[13],
		-- {['rmb'] = 1980, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz3.png'
	},
	[14] = {
		id = 14,
		huodongID = 3003,
		needRmb = 980,
		desc = 'Single recharge 980 diamond',
		award = __data_t__award[14],
		-- {['rmb'] = 980, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz4.png'
	},
	[15] = {
		id = 15,
		huodongID = 3003,
		needRmb = 600,
		desc = 'Single recharge 580 diamond',
		award = __data_t__award[15],
		-- {['rmb'] = 600, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz5.png'
	},
	[16] = {
		id = 16,
		huodongID = 3003,
		needRmb = 300,
		desc = 'Single recharge 340 diamond',
		award = __data_t__award[16],
		-- {['rmb'] = 300, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz6.png'
	},
	[17] = {
		id = 17,
		huodongID = 3003,
		needRmb = 60,
		desc = 'Single recharge 66 diamond',
		award = __data_t__award[17],
		-- {['rmb'] = 60, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz7.png'
	},
	[21] = {
		id = 21,
		huodongID = 3004,
		needRmb = 6480,
		desc = 'Single recharge 6580 diamond',
		award = {['rmb'] = 3880, __size = 1},
		icon = 'activity/once_recharge_award/icon_czfz1.png'
	},
	[22] = {
		id = 22,
		huodongID = 3004,
		needRmb = 3280,
		desc = 'Single recharge 3380 diamond',
		award = {['rmb'] = 2080, __size = 1},
		icon = 'activity/once_recharge_award/icon_czfz2.png'
	},
	[23] = {
		id = 23,
		huodongID = 3004,
		needRmb = 1980,
		desc = 'Single recharge 1980 diamond',
		award = {['rmb'] = 1280, __size = 1},
		icon = 'activity/once_recharge_award/icon_czfz3.png'
	},
	[24] = {
		id = 24,
		huodongID = 3004,
		needRmb = 980,
		desc = 'Single recharge 980 diamond',
		award = {['rmb'] = 680, __size = 1},
		icon = 'activity/once_recharge_award/icon_czfz4.png'
	},
	[25] = {
		id = 25,
		huodongID = 3004,
		needRmb = 600,
		desc = 'Single recharge 580 diamond',
		award = {['rmb'] = 460, __size = 1},
		icon = 'activity/once_recharge_award/icon_czfz5.png'
	},
	[26] = {
		id = 26,
		huodongID = 3004,
		needRmb = 300,
		desc = 'Single recharge 340 diamond',
		award = {['rmb'] = 280, __size = 1},
		icon = 'activity/once_recharge_award/icon_czfz6.png'
	},
	[27] = {
		id = 27,
		huodongID = 3004,
		needRmb = 60,
		desc = 'Single recharge 66 diamond',
		award = __data_t__award[27],
		-- {['rmb'] = 60, __size = 1}
		icon = 'activity/once_recharge_award/icon_czfz7.png'
	},

	__size = 21,
	__default = {
		__index = {
			huodongID = 0,
			needRmb = 1,
			desc = '',
			award = {__size = 0},
			icon = ''
		}
	}
}
return csv.yunying.oncerechage