--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['passport_recharge'] = {
	[1] = {
		id = 1,
		name = 'Adventure Pass',
		rechargeID = 114,
		type = 1,
		res = 'activity/passport/tips/kaitong.png',
		desc = '#L00100000##LOC0xFFFCED##LOS2##C0x72c1a1##F50#Activate #L00100000##LOC0xFFFCED##LOS2##C0x5b545b##F44#Master Passport \nUnlock #L00100000##LOC0xFFFCED##LOS2##C0xf76b45##F50#limited #L00100000##LOC0xFFFCED##LOS2##C0x5b545b##F44#quest',
		icon = 'activity/passport/icon_better.png'
	},
	[2] = {
		id = 2,
		name = 'Master Pass',
		rechargeID = 118,
		type = 1,
		level = 20,
		discountValue = 2,
		logo = 1,
		res = 'activity/passport/tips/maoxian.png',
		desc = '#L00100000##LOC0xFFFCED##LOS2##C0x72c1a1##F50#Activate #L00100000##LOC0xFFFCED##LOS2##C0x5b545b##F44#Golden Pack \n#L00100000##LOC0xFFFCED##LOS2##C0x5b545b##F44#Boost up #L00100000##LOC0xFFFCED##LOS2##C0xea5ec1##F44#20#L00100000##LOC0xFFFCED##LOS2##C0x5b545b##F44# passport level',
		icon = 'activity/passport/icon_lv.png'
	},
	[3] = {
		id = 3,
		name = '500EXP',
		rechargeID = 106,
		type = 2,
		exp = 500
	},
	[4] = {
		id = 4,
		name = '1000EXP',
		rechargeID = 108,
		type = 2,
		exp = 1000
	},
	[5] = {
		id = 5,
		name = '2000EXP',
		rechargeID = 111,
		type = 2,
		exp = 2000
	},
	[6] = {
		id = 6,
		name = '3000EXP',
		rechargeID = 113,
		type = 2,
		exp = 3000
	},

	__size = 6,
	__default = {
		__index = {
			level = 0,
			exp = 0,
			discountValue = 0,
			desc = '',
			icon = ''
		}
	}
}
return csv.yunying.passport_recharge