--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[5] = {['coin13'] = 100000, __size = 1}, 
	[6] = {210, 210}, 
	[7] = {'cn', 'en', 'tw', 'kr'}, 
	[15] = {['coin13'] = 75000, __size = 1}, 
	[18] = {['coin13'] = 60000, __size = 1}, 
	[28] = {['coin13'] = 20000, __size = 1}, 
	[34] = {'cn', 'kr'}, __size = 8}
local __data_t__languages = {
	[1141] = __predefine_t__[34],
	[1161] = __predefine_t__[7],
	[1081] = __predefine_t__[7],
	[211] = __predefine_t__[7],
	[1121] = __predefine_t__[7],
	[1261] = __predefine_t__[7],
	[1201] = __predefine_t__[7],
	[231] = __predefine_t__[7],
	[1231] = __predefine_t__[7],
	[1051] = __predefine_t__[7],
	[1221] = __predefine_t__[7],
	[1191] = __predefine_t__[7],
	[1071] = __predefine_t__[7],
	[1111] = __predefine_t__[7],
	[1251] = __predefine_t__[7],
	[1031] = __predefine_t__[7],
	[1011] = __predefine_t__[7],
	[201] = __predefine_t__[7],
	[1211] = __predefine_t__[7],
	[1091] = __predefine_t__[7],
	[1171] = __predefine_t__[7],
	[1271] = __predefine_t__[7],
	[1131] = __predefine_t__[34],
	[1151] = __predefine_t__[7],
	[241] = __predefine_t__[7],
	[221] = __predefine_t__[7],
	[1041] = __predefine_t__[7],
	[1021] = __predefine_t__[7],
	[1061] = __predefine_t__[7],
	[1181] = __predefine_t__[7],
	[1241] = __predefine_t__[7],
	[1101] = __predefine_t__[7],
	[1001] = __predefine_t__[7]
}
local __data_t__levelRange = {
	[201] = __predefine_t__[6],
	[241] = __predefine_t__[6],
	[231] = __predefine_t__[6],
	[221] = __predefine_t__[6],
	[211] = __predefine_t__[6]
}
local __data_t__costMap = {
	[1161] = __predefine_t__[5],
	[1221] = __predefine_t__[5],
	[211] = __predefine_t__[5],
	[1121] = __predefine_t__[28],
	[1261] = __predefine_t__[5],
	[1201] = __predefine_t__[5],
	["default"] = __predefine_t__[1],
	[231] = __predefine_t__[5],
	[1231] = __predefine_t__[5],
	[1051] = __predefine_t__[18],
	[1191] = __predefine_t__[5],
	[1251] = __predefine_t__[5],
	[1031] = __predefine_t__[18],
	[1011] = __predefine_t__[15],
	[201] = __predefine_t__[5],
	[1211] = __predefine_t__[5],
	[1091] = __predefine_t__[28],
	[1171] = __predefine_t__[5],
	[1271] = __predefine_t__[5],
	[1131] = __predefine_t__[28],
	[1151] = __predefine_t__[28],
	[241] = __predefine_t__[5],
	[221] = __predefine_t__[5],
	[1021] = __predefine_t__[15],
	[1061] = __predefine_t__[15],
	[1181] = __predefine_t__[5],
	[1241] = __predefine_t__[5],
	[1101] = __predefine_t__[28]
}
local __data_t__itemMap = {
	["default"] = __predefine_t__[1]
}

csv['cross']['mine']['shop'] = {
	[201] = {
		id = 201,
		itemMap = {[21901] = 5, __size = 1},
		costMap = __data_t__costMap[201],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		levelRange = __data_t__levelRange[201],
		-- {210, 210}
		languages = __data_t__languages[201]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[211] = {
		id = 211,
		itemMap = {[23001] = 5, __size = 1},
		costMap = __data_t__costMap[211],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		levelRange = __data_t__levelRange[211],
		-- {210, 210}
		languages = __data_t__languages[211]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[221] = {
		id = 221,
		itemMap = {[22231] = 5, __size = 1},
		costMap = __data_t__costMap[221],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		levelRange = __data_t__levelRange[221],
		-- {210, 210}
		languages = __data_t__languages[221]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[231] = {
		id = 231,
		itemMap = {[23141] = 5, __size = 1},
		costMap = __data_t__costMap[231],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		levelRange = __data_t__levelRange[231],
		-- {210, 210}
		languages = __data_t__languages[231]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[241] = {
		id = 241,
		itemMap = {[23411] = 5, __size = 1},
		costMap = __data_t__costMap[241],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		levelRange = __data_t__levelRange[241],
		-- {210, 210}
		languages = __data_t__languages[241]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1001] = {
		id = 1001,
		itemMap = {[21261] = 1, __size = 1},
		costMap = {['coin13'] = 120000, __size = 1},
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 1,
		languages = __data_t__languages[1001]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1011] = {
		id = 1011,
		itemMap = {[23151] = 3, __size = 1},
		costMap = __data_t__costMap[1011],
		-- {['coin13'] = 75000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 2,
		languages = __data_t__languages[1011]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1021] = {
		id = 1021,
		itemMap = {[502] = 1, __size = 1},
		costMap = __data_t__costMap[1021],
		-- {['coin13'] = 75000, __size = 1}
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 3,
		languages = __data_t__languages[1021]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1031] = {
		id = 1031,
		itemMap = {[21941] = 3, __size = 1},
		costMap = __data_t__costMap[1031],
		-- {['coin13'] = 60000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 4,
		languages = __data_t__languages[1031]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1041] = {
		id = 1041,
		itemMap = {[28504] = 1, __size = 1},
		costMap = {['coin13'] = 50000, __size = 1},
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 5,
		languages = __data_t__languages[1041]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1051] = {
		id = 1051,
		itemMap = {[21951] = 3, __size = 1},
		costMap = __data_t__costMap[1051],
		-- {['coin13'] = 60000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 6,
		languages = __data_t__languages[1051]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1061] = {
		id = 1061,
		itemMap = {['talent_point'] = 1, __size = 1},
		costMap = __data_t__costMap[1061],
		-- {['coin13'] = 75000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 7,
		languages = __data_t__languages[1061]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1071] = {
		id = 1071,
		itemMap = {[28505] = 1, __size = 1},
		costMap = {['coin13'] = 180000, __size = 1},
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 8,
		languages = __data_t__languages[1071]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1081] = {
		id = 1081,
		itemMap = {[529] = 500, __size = 1},
		costMap = {['coin13'] = 90000, __size = 1},
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 9,
		languages = __data_t__languages[1081]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1091] = {
		id = 1091,
		itemMap = {[514] = 60, __size = 1},
		costMap = __data_t__costMap[1091],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 10,
		languages = __data_t__languages[1091]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1101] = {
		id = 1101,
		itemMap = {[452] = 5, __size = 1},
		costMap = __data_t__costMap[1101],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 11,
		languages = __data_t__languages[1101]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1111] = {
		id = 1111,
		itemMap = {[15] = 10, __size = 1},
		costMap = {['coin13'] = 15000, __size = 1},
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 12,
		languages = __data_t__languages[1111]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1121] = {
		id = 1121,
		itemMap = {[453] = 5, __size = 1},
		costMap = __data_t__costMap[1121],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 13,
		languages = __data_t__languages[1121]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1131] = {
		id = 1131,
		itemMap = {[111] = 100, __size = 1},
		costMap = __data_t__costMap[1131],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 14,
		languages = __data_t__languages[1131]
		-- {'cn', 'kr'}
	},
	[1141] = {
		id = 1141,
		itemMap = {[112] = 20, __size = 1},
		costMap = {['coin13'] = 30000, __size = 1},
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 15,
		languages = __data_t__languages[1141]
		-- {'cn', 'kr'}
	},
	[1151] = {
		id = 1151,
		itemMap = {[5000] = 20, __size = 1},
		costMap = __data_t__costMap[1151],
		-- {['coin13'] = 20000, __size = 1}
		exchangeLimit = 20,
		regainHour = 12,
		sortValue = 16,
		languages = __data_t__languages[1151]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1161] = {
		id = 1161,
		itemMap = {[20971] = 2, __size = 1},
		costMap = __data_t__costMap[1161],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 17,
		languages = __data_t__languages[1161]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1171] = {
		id = 1171,
		itemMap = {[21031] = 2, __size = 1},
		costMap = __data_t__costMap[1171],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 18,
		languages = __data_t__languages[1171]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1181] = {
		id = 1181,
		itemMap = {[21771] = 2, __size = 1},
		costMap = __data_t__costMap[1181],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 19,
		languages = __data_t__languages[1181]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1191] = {
		id = 1191,
		itemMap = {[22021] = 2, __size = 1},
		costMap = __data_t__costMap[1191],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 20,
		languages = __data_t__languages[1191]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1201] = {
		id = 1201,
		itemMap = {[22371] = 2, __size = 1},
		costMap = __data_t__costMap[1201],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 21,
		languages = __data_t__languages[1201]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1211] = {
		id = 1211,
		itemMap = {[22411] = 2, __size = 1},
		costMap = __data_t__costMap[1211],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 22,
		languages = __data_t__languages[1211]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1221] = {
		id = 1221,
		itemMap = {[23161] = 2, __size = 1},
		costMap = __data_t__costMap[1221],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 23,
		languages = __data_t__languages[1221]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1231] = {
		id = 1231,
		itemMap = {[23171] = 2, __size = 1},
		costMap = __data_t__costMap[1231],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 24,
		languages = __data_t__languages[1231]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1241] = {
		id = 1241,
		itemMap = {[23181] = 2, __size = 1},
		costMap = __data_t__costMap[1241],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 25,
		languages = __data_t__languages[1241]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1251] = {
		id = 1251,
		itemMap = {[23191] = 2, __size = 1},
		costMap = __data_t__costMap[1251],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 26,
		languages = __data_t__languages[1251]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1261] = {
		id = 1261,
		itemMap = {[23201] = 2, __size = 1},
		costMap = __data_t__costMap[1261],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 27,
		languages = __data_t__languages[1261]
		-- {'cn', 'en', 'tw', 'kr'}
	},
	[1271] = {
		id = 1271,
		itemMap = {[23231] = 2, __size = 1},
		costMap = __data_t__costMap[1271],
		-- {['coin13'] = 100000, __size = 1}
		exchangeLimit = 20,
		regainHour = 24,
		sortValue = 28,
		languages = __data_t__languages[1271]
		-- {'cn', 'en', 'tw', 'kr'}
	},

	__size = 33,
	__default = {
		__index = {
			itemMap = __data_t__itemMap["default"]	--[[ {__size = 0}]],
			costMap = __data_t__costMap["default"]	--[[ {__size = 0}]],
			exchangeLimit = -1,
			regainHour = 0,
			beginDate = 0,
			endDate = 20990101,
			vipStart = 0,
			levelRange = {1, 150},
			limitType = 0,
			limitTimes = 0,
			showUnable = false,
			sortValue = 0,
			languages = {'cn'}
		}
	}
}
return csv.cross.mine.shop