--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['battle_card_halo'] = {
	[1] = {
		id = 1,
		icon = 'config/embattle/icon_gh1.png',
		desc = 'จัดทีมโปเกมอน 6 ตัวที่มีธาตุต่างกัน',
		type = 1,
		args = {1, 1, 1, 1, 1, 1},
		group = 10,
		autoPriority = 1,
		attrType1 = 1,
		attrValue1 = '10%',
		attrType2 = 7,
		attrValue2 = '10%',
		attrType3 = 8,
		attrValue3 = '10%'
	},
	[2] = {
		id = 2,
		icon = 'config/embattle/icon_gh2.png',
		desc = 'จัดทีมโปเกมอน 3 ตัวที่มีธาตุเดียวกัน',
		type = 1,
		args = {3},
		group = 20,
		autoPriority = 2,
		attrType1 = 1,
		attrValue1 = '15%',
		attrType2 = 7,
		attrValue2 = '10%',
		attrType3 = 8,
		attrValue3 = '10%'
	},
	[3] = {
		id = 3,
		icon = 'config/embattle/icon_gh3.png',
		desc = 'จัดทีมโปเกมอน 3 กลุ่ม กลุ่มละ 2 ตัวที่มีธาตุเดียวกัน',
		type = 1,
		args = {2, 2, 2},
		group = 30,
		autoPriority = 3,
		attrType1 = 1,
		attrValue1 = '15%',
		attrType2 = 7,
		attrValue2 = '15%',
		attrType3 = 8,
		attrValue3 = '15%'
	},
	[4] = {
		id = 4,
		icon = 'config/embattle/icon_gh4.png',
		desc = 'จัดทีมโปเกมอน 3 ตัวที่มีธาตุเดียวกัน พร้อมอีก 3 ตัวที่มีธาตุเดียวกันอีกกลุ่ม',
		type = 1,
		args = {3, 3},
		group = 20,
		priority = 49,
		autoPriority = 4,
		attrType1 = 1,
		attrValue1 = '20%',
		attrType2 = 7,
		attrValue2 = '15%',
		attrType3 = 8,
		attrValue3 = '15%'
	},
	[5] = {
		id = 5,
		icon = 'config/embattle/icon_gh5.png',
		desc = 'จัดทีมโปเกมอน 4 ตัวที่มีธาตุเดียวกัน พร้อมอีก 2 ตัวที่มีธาตุเดียวกันอีกกลุ่ม',
		type = 1,
		args = {4, 2},
		group = 20,
		priority = 79,
		autoPriority = 5,
		attrType1 = 1,
		attrValue1 = '20%',
		attrType2 = 7,
		attrValue2 = '15%',
		attrType3 = 8,
		attrValue3 = '15%'
	},
	[6] = {
		id = 6,
		icon = 'config/embattle/icon_gh6.png',
		desc = 'จัดทีมโปเกมอน 6 ตัวที่มีธาตุเดียวกัน',
		type = 1,
		args = {6},
		group = 20,
		priority = 99,
		autoPriority = 6,
		attrType1 = 1,
		attrValue1 = '25%',
		attrType2 = 7,
		attrValue2 = '20%',
		attrType3 = 8,
		attrValue3 = '20%'
	},

	__size = 6,
	__default = {
		__index = {
			icon = '',
			desc = '',
			type = 0,
			args = {},
			group = 0,
			priority = 0,
			autoPriority = 0,
			attrType1 = 0,
			attrValue1 = '',
			attrType2 = 0,
			attrValue2 = '',
			attrType3 = 0,
			attrValue3 = '',
			invalidScenes = {6, 7, 17}
		}
	}
}
return csv.battle_card_halo