--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['character'] = {
	[1] = {
		id = 1,
		name = 'Quirky'
	},
	[2] = {
		id = 2,
		name = 'Hardy'
	},
	[3] = {
		id = 3,
		name = 'Bashful'
	},
	[4] = {
		id = 4,
		name = 'Docile'
	},
	[5] = {
		id = 5,
		name = 'Serious'
	},
	[6] = {
		id = 6,
		name = 'Timid',
		attrMap = {[13] = '110%', [7] = '90%', __size = 2}
	},
	[7] = {
		id = 7,
		name = 'Hasty',
		attrMap = {[9] = '90%', [13] = '110%', __size = 2}
	},
	[8] = {
		id = 8,
		name = 'Jolly',
		attrMap = {[8] = '90%', [13] = '110%', __size = 2}
	},
	[9] = {
		id = 9,
		name = 'Naive',
		attrMap = {[10] = '90%', [13] = '110%', __size = 2}
	},
	[10] = {
		id = 10,
		name = 'Lonely',
		attrMap = {[9] = '90%', [7] = '110%', __size = 2}
	},
	[11] = {
		id = 11,
		name = 'Brave',
		attrMap = {[13] = '90%', [7] = '110%', __size = 2}
	},
	[12] = {
		id = 12,
		name = 'Adamant',
		attrMap = {[8] = '90%', [7] = '110%', __size = 2}
	},
	[13] = {
		id = 13,
		name = 'Naughty',
		attrMap = {[10] = '90%', [7] = '110%', __size = 2}
	},
	[14] = {
		id = 14,
		name = 'Bold',
		attrMap = {[9] = '110%', [7] = '90%', __size = 2}
	},
	[15] = {
		id = 15,
		name = 'Relaxed',
		attrMap = {[9] = '110%', [13] = '90%', __size = 2}
	},
	[16] = {
		id = 16,
		name = 'Impish',
		attrMap = {[9] = '110%', [8] = '90%', __size = 2}
	},
	[17] = {
		id = 17,
		name = 'Lax',
		attrMap = {[9] = '110%', [10] = '90%', __size = 2}
	},
	[18] = {
		id = 18,
		name = 'Modest',
		attrMap = {[8] = '110%', [7] = '90%', __size = 2}
	},
	[19] = {
		id = 19,
		name = 'Mild',
		attrMap = {[9] = '90%', [8] = '110%', __size = 2}
	},
	[20] = {
		id = 20,
		name = 'Quiet',
		attrMap = {[8] = '110%', [13] = '90%', __size = 2}
	},
	[21] = {
		id = 21,
		name = 'Rash',
		attrMap = {[8] = '110%', [10] = '90%', __size = 2}
	},
	[22] = {
		id = 22,
		name = 'Calm',
		attrMap = {[10] = '110%', [7] = '90%', __size = 2}
	},
	[23] = {
		id = 23,
		name = 'Gentle',
		attrMap = {[9] = '90%', [10] = '110%', __size = 2}
	},
	[24] = {
		id = 24,
		name = 'Sassy',
		attrMap = {[10] = '110%', [13] = '90%', __size = 2}
	},
	[25] = {
		id = 25,
		name = 'Careful',
		attrMap = {[8] = '90%', [10] = '110%', __size = 2}
	},

	__size = 25,
	__default = {
		__index = {
			name = '',
			attrMap = {__size = 0},
			res = ''
		}
	}
}
return csv.character