--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {['y'] = 0, ['x'] = 0, __size = 2}, 
	[5] = {['y'] = 80, ['x'] = 240, __size = 2}, 
	[13] = {['y'] = 60, ['x'] = -90, __size = 2}, 
	[16] = {100105}, 
	[19] = {['y'] = 50, ['x'] = -130, __size = 2}, 
	[21] = {['y'] = 40, ['x'] = -140, __size = 2}, 
	[31] = {['y'] = 0, ['x'] = -100, __size = 2}, 
	[34] = {2485}, 
	[38] = {['libs'] = {136}, __size = 1}, 
	[43] = {['height'] = 80, ['width'] = 70, __size = 2}, 
	[49] = {['height'] = 120, ['width'] = 80, __size = 2}, 
	[70] = {['height'] = 200, ['width'] = 200, __size = 2}, 
	[92] = {['height'] = 120, ['width'] = 120, __size = 2}, __size = 13}
local __data_t__activityPosition = {
	["default"] = __predefine_t__[1]
}
local __data_t__touchSize = {
	[25] = __predefine_t__[49],
	[26] = __predefine_t__[49],
	[27] = __predefine_t__[70],
	[20] = __predefine_t__[49],
	[21] = __predefine_t__[43],
	[18] = __predefine_t__[43],
	[28] = __predefine_t__[70],
	[29] = __predefine_t__[70],
	[43] = __predefine_t__[70],
	[32] = __predefine_t__[70],
	[1002] = __predefine_t__[92],
	[1001] = __predefine_t__[92]
}
local __data_t__offPos = {
	["default"] = __predefine_t__[1],
	[42] = __predefine_t__[31],
	[40] = __predefine_t__[31],
	[41] = __predefine_t__[31],
	[1] = __predefine_t__[5],
	[5] = __predefine_t__[13],
	[7] = __predefine_t__[19],
	[9] = __predefine_t__[21],
	[8] = __predefine_t__[21],
	[38] = __predefine_t__[31],
	[39] = __predefine_t__[31],
	[12] = __predefine_t__[19],
	[15] = __predefine_t__[13],
	[14] = __predefine_t__[31],
	[17] = __predefine_t__[5],
	[33] = __predefine_t__[31],
	[31] = __predefine_t__[31],
	[30] = __predefine_t__[31],
	[37] = __predefine_t__[31],
	[36] = __predefine_t__[31],
	[35] = __predefine_t__[31],
	[34] = __predefine_t__[31]
}
local __data_t__activityIds = {
	[24] = __predefine_t__[34],
	[10] = __predefine_t__[16],
	[15] = __predefine_t__[34],
	[22] = __predefine_t__[34],
	[23] = __predefine_t__[34],
	[6] = __predefine_t__[16]
}
local __data_t__position = {
	["default"] = __predefine_t__[1]
}
local __data_t__unfreezeAward = {
	[19] = __predefine_t__[38],
	[18] = __predefine_t__[38],
	[20] = __predefine_t__[38],
	[21] = __predefine_t__[38],
	[16] = __predefine_t__[38]
}

csv['city_sprites'] = {
	[1] = {
		id = 1,
		group = 11,
		res = 'zhuchangjing/zjm_kbs.skel',
		position = {['y'] = 380, ['x'] = 230, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'emmm',
		chattext2 = 'emmmm',
		chattext3 = 'Zzzzzzz',
		offPos = __data_t__offPos[1],
		-- {['y'] = 80, ['x'] = 240, __size = 2}
		overture = true,
		active = false
	},
	[2] = {
		id = 2,
		type = 2,
		group = 21,
		res = 'zhuchangjing/zjm_zdpp.skel',
		position = {['y'] = 355, ['x'] = 1095, __size = 2},
		zOrder = 15,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'bilibili！~',
		offPos = {['y'] = 30, ['x'] = -200, __size = 2},
		active = false
	},
	[3] = {
		id = 3,
		type = 2,
		group = 21,
		res = 'zhuchangjing/zjm_sb_br.skel',
		position = {['y'] = 360, ['x'] = 1495, __size = 2},
		zOrder = 12,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = {['y'] = 140, ['x'] = -180, __size = 2},
		active = false
	},
	[4] = {
		id = 4,
		type = 2,
		group = 21,
		res = 'zhuchangjing/zjm_fdpp.skel',
		position = {['y'] = 360, ['x'] = 1640, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'bilibili！~',
		offPos = {['y'] = 30, ['x'] = 180, __size = 2},
		overture = true,
		active = false
	},
	[5] = {
		id = 5,
		type = 2,
		group = 21,
		res = 'zhuchangjing/shadiao.skel',
		position = {['y'] = 370, ['x'] = 1265, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[5],
		-- {['y'] = 60, ['x'] = -90, __size = 2}
		active = false
	},
	[6] = {
		id = 6,
		type = 3,
		group = 31,
		res = 'zhuchangjing/zjm_kdy.skel',
		position = {['y'] = 540, ['x'] = 4360, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		chattext2 = '嘎？！！~',
		offPos = {['y'] = 0, ['x'] = 120, __size = 2},
		overture = true,
		activityIds = __data_t__activityIds[6],
		-- {100105}
		activityPosition = {['y'] = 620, ['x'] = 3400, __size = 2},
		activityScale = 3
	},
	[7] = {
		id = 7,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_qqhs.skel',
		position = {['y'] = 225, ['x'] = 2175, __size = 2},
		zOrder = 14,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'mua~',
		offPos = __data_t__offPos[7],
		-- {['y'] = 50, ['x'] = -130, __size = 2}
		active = false
	},
	[8] = {
		id = 8,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_pkq.skel',
		position = {['y'] = 230, ['x'] = 2005, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		chattext2 = '皮 皮卡丘~',
		chattext3 = '皮？~',
		offPos = __data_t__offPos[8],
		-- {['y'] = 40, ['x'] = -140, __size = 2}
		active = false
	},
	[9] = {
		id = 9,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_mmx.skel',
		position = {['y'] = 390, ['x'] = 2190, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[9],
		-- {['y'] = 40, ['x'] = -140, __size = 2}
		active = false
	},
	[10] = {
		id = 10,
		type = 4,
		group = 41,
		res = 'zhuchangjing/zjm_pqlz.skel',
		position = {['y'] = 235, ['x'] = 2350, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = {['y'] = 0, ['x'] = 80, __size = 2},
		overture = true,
		activityIds = __data_t__activityIds[10],
		-- {100105}
		activityPosition = {['y'] = 372, ['x'] = 3617, __size = 2},
		activityScale = 4,
		active = false
	},
	[11] = {
		id = 11,
		type = 5,
		group = 51,
		res = 'zhuchangjing/zjm_dds.skel',
		position = {['y'] = 300, ['x'] = 5145, __size = 2},
		zOrder = 12,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		active = false
	},
	[12] = {
		id = 12,
		type = 6,
		group = 61,
		res = 'zhuchangjing/zjm_scg.skel',
		position = {['y'] = 355, ['x'] = 930, __size = 2},
		zOrder = 12,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'wuso！！~',
		offPos = __data_t__offPos[12],
		-- {['y'] = 50, ['x'] = -130, __size = 2}
		active = false
	},
	[13] = {
		id = 13,
		type = 6,
		group = 61,
		res = 'zhuchangjing/zjm_trq.skel',
		position = {['y'] = 580, ['x'] = 1060, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = '(＠_＠;)',
		offPos = {['y'] = -100, ['x'] = -100, __size = 2},
		active = false
	},
	[14] = {
		id = 14,
		type = 6,
		group = 61,
		res = 'zhuchangjing/zjm_xbb.skel',
		position = {['y'] = 365, ['x'] = 760, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = '(≥﹃≤)',
		offPos = __data_t__offPos[14],
		-- {['y'] = 0, ['x'] = -100, __size = 2}
		active = false
	},
	[15] = {
		id = 15,
		type = 7,
		group = 71,
		res = 'zhuchangjing/bitixiong.skel',
		position = {['y'] = 280, ['x'] = 776, __size = 2},
		zOrder = 15,
		touchSize = {['height'] = 100, ['width'] = 80, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		chattext2 = '吸溜！--',
		offPos = __data_t__offPos[15],
		-- {['y'] = 60, ['x'] = -90, __size = 2}
		activityIds = __data_t__activityIds[15],
		-- {2485}
		activityPosition = {['y'] = 230, ['x'] = 2266, __size = 2},
		active = false
	},
	[16] = {
		id = 16,
		type = 8,
		group = 81,
		res = 'zhuchangjing/bojiaman.skel',
		position = {['y'] = 272, ['x'] = 2117, __size = 2},
		zOrder = 13,
		touchSize = {['height'] = 100, ['width'] = 90, __size = 2},
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[16],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		chattext1 = 'BoJia！',
		offPos = {['y'] = 80, ['x'] = 80, __size = 2},
		overture = true,
		active = false
	},
	[17] = {
		id = 17,
		type = 9,
		group = 91,
		res = 'zhuchangjing/chuanzhuoxiong.skel',
		position = {['y'] = 470, ['x'] = 190, __size = 2},
		touchSize = {['height'] = 150, ['width'] = 160, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'wuso！！~',
		offPos = __data_t__offPos[17],
		-- {['y'] = 80, ['x'] = 240, __size = 2}
		overture = true,
		active = false
	},
	[18] = {
		id = 18,
		type = 10,
		group = 101,
		res = 'zhuchangjing/daidaishou.skel',
		position = {['y'] = 340, ['x'] = 3456, __size = 2},
		zOrder = 11,
		touchSize = __data_t__touchSize[18],
		-- {['height'] = 80, ['width'] = 70, __size = 2}
		scale = 2.4,
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[18],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = {['y'] = 40, ['x'] = 130, __size = 2},
		overture = true,
		active = false
	},
	[19] = {
		id = 19,
		type = 8,
		group = 81,
		res = 'zhuchangjing/haibaoqiu.skel',
		position = {['y'] = 260, ['x'] = 1945, __size = 2},
		zOrder = 14,
		touchSize = {['height'] = 70, ['width'] = 70, __size = 2},
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[19],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		chattext1 = 'OwOw',
		offPos = {['y'] = 40, ['x'] = 126, __size = 2},
		overture = true,
		active = false
	},
	[20] = {
		id = 20,
		type = 8,
		group = 81,
		res = 'zhuchangjing/kabishou2.skel',
		position = {['y'] = 264, ['x'] = 1773, __size = 2},
		zOrder = 13,
		touchSize = __data_t__touchSize[20],
		-- {['height'] = 120, ['width'] = 80, __size = 2}
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[20],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		chattext1 = 'emmm',
		chattext2 = 'emmmm',
		chattext3 = 'emmm',
		offPos = {['y'] = 30, ['x'] = 170, __size = 2},
		overture = true,
		active = false
	},
	[21] = {
		id = 21,
		type = 10,
		group = 101,
		res = 'zhuchangjing/kedaya.skel',
		position = {['y'] = 360, ['x'] = 3276, __size = 2},
		zOrder = 12,
		touchSize = __data_t__touchSize[21],
		-- {['height'] = 80, ['width'] = 70, __size = 2}
		scale = 2.4,
		randLib = 130,
		unfreezeAward = __data_t__unfreezeAward[21],
		-- {['libs'] = {136}, __size = 1}
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		chattext2 = '嘎？！！~',
		offPos = {['y'] = 60, ['x'] = -74, __size = 2},
		active = false
	},
	[22] = {
		id = 22,
		type = 7,
		group = 71,
		res = 'zhuchangjing/minibing.skel',
		position = {['y'] = 531, ['x'] = 813, __size = 2},
		zOrder = 13,
		touchSize = {['height'] = 60, ['width'] = 60, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = '(≥﹃≤)',
		offPos = {['y'] = 44, ['x'] = -82, __size = 2},
		activityIds = __data_t__activityIds[22],
		-- {2485}
		activityPosition = {['y'] = 481, ['x'] = 2303, __size = 2},
		active = false
	},
	[23] = {
		id = 23,
		type = 7,
		group = 71,
		res = 'zhuchangjing/moqiangrenou.skel',
		position = {['y'] = 283, ['x'] = 1180, __size = 2},
		zOrder = 14,
		touchSize = {['height'] = 170, ['width'] = 100, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = '(＠_＠;)',
		offPos = {['y'] = 144, ['x'] = 56, __size = 2},
		overture = true,
		activityIds = __data_t__activityIds[23],
		-- {2485}
		activityPosition = {['y'] = 233, ['x'] = 2670, __size = 2},
		active = false
	},
	[24] = {
		id = 24,
		type = 7,
		group = 71,
		res = 'zhuchangjing/suannaixian.skel',
		position = {['y'] = 293, ['x'] = 945, __size = 2},
		zOrder = 13,
		touchSize = {['height'] = 130, ['width'] = 100, __size = 2},
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = {['y'] = 120, ['x'] = -90, __size = 2},
		activityIds = __data_t__activityIds[24],
		-- {2485}
		activityPosition = {['y'] = 243, ['x'] = 2435, __size = 2},
		active = false
	},
	[25] = {
		id = 25,
		type = 11,
		group = 111,
		res = 'zhuchangjing/pikaqiu.skel',
		position = {['y'] = 280, ['x'] = 3036, __size = 2},
		zOrder = 13,
		touchSize = __data_t__touchSize[25],
		-- {['height'] = 120, ['width'] = 80, __size = 2}
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = {['y'] = -20, ['x'] = -154, __size = 2},
		active = false
	},
	[26] = {
		id = 26,
		type = 11,
		group = 111,
		res = 'zhuchangjing/miaomiao.skel',
		position = {['y'] = 283, ['x'] = 3390, __size = 2},
		zOrder = 13,
		touchSize = __data_t__touchSize[26],
		-- {['height'] = 120, ['width'] = 80, __size = 2}
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = {['y'] = -40, ['x'] = -74, __size = 2},
		active = false
	},
	[27] = {
		id = 27,
		type = 12,
		group = 121,
		res = 'zhuchangjingpokmon/wsjzh.skel',
		position = {['y'] = 300, ['x'] = 130, __size = 2},
		touchSize = __data_t__touchSize[27],
		-- {['height'] = 200, ['width'] = 200, __size = 2}
		randLib = 130,
		shape_shifter = false,
		chattext1 = 'โลกแห่งโปเกมอนน',
		active = false
	},
	[28] = {
		id = 28,
		type = 13,
		group = 131,
		res = 'zhuchangjing/yiji/pokemon/zhengfupaipai.skel',
		position = {['y'] = 300, ['x'] = 160, __size = 2},
		touchSize = __data_t__touchSize[28],
		-- {['height'] = 200, ['width'] = 200, __size = 2}
		randLib = 130,
		shape_shifter = false,
		chattext1 = 'bilibili！~'
	},
	[29] = {
		id = 29,
		type = 14,
		group = 141,
		res = 'zhuchangjing/yiji/pokemon/miaomiao.skel',
		position = {['y'] = 475, ['x'] = 560, __size = 2},
		zOrder = 13,
		touchSize = __data_t__touchSize[29],
		-- {['height'] = 200, ['width'] = 200, __size = 2}
		randLib = 130,
		shape_shifter = false,
		chattext1 = 'โลกแห่งโปเกมอนน'
	},
	[30] = {
		id = 30,
		type = 15,
		group = 151,
		res = 'zhuchangjing/yiji/pokemon/mushougong.skel',
		position = {['y'] = 290, ['x'] = 1115, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'mus',
		offPos = __data_t__offPos[30]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[31] = {
		id = 31,
		type = 15,
		group = 151,
		res = 'zhuchangjing/yiji/pokemon/tengju.skel',
		position = {['y'] = 270, ['x'] = 1275, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = '(＠_＠;)',
		offPos = __data_t__offPos[31]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[32] = {
		id = 32,
		type = 15,
		group = 151,
		res = 'zhuchangjing/yiji/pokemon/shuiyueyu.skel',
		position = {['y'] = 750, ['x'] = 1080, __size = 2},
		zOrder = 13,
		touchSize = __data_t__touchSize[32],
		-- {['height'] = 200, ['width'] = 200, __size = 2}
		randLib = 130,
		shape_shifter = false,
		chattext1 = 'โลกแห่งโปเกมอนน'
	},
	[33] = {
		id = 33,
		type = 16,
		group = 161,
		res = 'zhuchangjing/yiji/pokemon/yiji_leiyanxi.skel',
		position = {['y'] = 230, ['x'] = 1640, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[33]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[34] = {
		id = 34,
		type = 16,
		group = 161,
		res = 'zhuchangjing/yiji/pokemon/yiji_yantuer.skel',
		position = {['y'] = 225, ['x'] = 1840, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = '(≥﹃≤)',
		offPos = __data_t__offPos[34]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[35] = {
		id = 35,
		type = 16,
		group = 161,
		res = 'zhuchangjing/yiji/pokemon/yj_qyh.skel',
		position = {['y'] = 980, ['x'] = 1820, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[35]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[36] = {
		id = 36,
		type = 17,
		group = 171,
		res = 'zhuchangjing/yiji/pokemon/butubo.skel',
		position = {['y'] = 750, ['x'] = 3850, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'OwOw',
		offPos = __data_t__offPos[36]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[37] = {
		id = 37,
		type = 17,
		group = 171,
		res = 'zhuchangjing/yiji/pokemon/zcyj_qyh2.skel',
		position = {['y'] = 275, ['x'] = 3640, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[37]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[38] = {
		id = 38,
		type = 18,
		group = 181,
		res = 'zhuchangjing/yiji/pokemon/rsy.skel',
		position = {['y'] = 265, ['x'] = 4645, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[38]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[39] = {
		id = 39,
		type = 18,
		group = 181,
		res = 'zhuchangjing/yiji/pokemon/dhe.skel',
		position = {['y'] = 285, ['x'] = 4815, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[39]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[40] = {
		id = 40,
		type = 18,
		group = 181,
		res = 'zhuchangjing/yiji/pokemon/xym.skel',
		position = {['y'] = 285, ['x'] = 4955, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[40]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[41] = {
		id = 41,
		type = 19,
		group = 191,
		res = 'zhuchangjing/yiji/pokemon/yijilioulu.skel',
		position = {['y'] = 390, ['x'] = 5585, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[41]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[42] = {
		id = 42,
		type = 19,
		group = 191,
		res = 'zhuchangjing/yiji/pokemon/lukaliou.skel',
		position = {['y'] = 390, ['x'] = 5685, __size = 2},
		zOrder = 13,
		randLib = 130,
		baibianRandLib = 131,
		chattext1 = 'โลกแห่งโปเกมอนน',
		offPos = __data_t__offPos[42]
		-- {['y'] = 0, ['x'] = -100, __size = 2}
	},
	[43] = {
		id = 43,
		type = 20,
		group = 201,
		res = 'zhuchangjing/yiji/pokemon/yijinuannuanzhu.skel',
		position = {['y'] = 500, ['x'] = 6045, __size = 2},
		zOrder = 13,
		touchSize = __data_t__touchSize[43],
		-- {['height'] = 200, ['width'] = 200, __size = 2}
		randLib = 130,
		shape_shifter = false,
		chattext1 = 'emmm',
		chattext2 = 'emmmm',
		chattext3 = 'emmm'
	},
	[1000] = {
		id = 1000,
		type = 1000,
		group = 10001,
		res = 'zhuchangjing/zjm_mnq1.skel',
		position = {['y'] = 570, ['x'] = 1280, __size = 2},
		zOrder = 2,
		touchSize = {['height'] = 80, ['width'] = 120, __size = 2},
		action = false,
		randLib = 132,
		activityIds = {2320},
		activityPosition = {['y'] = 551, ['x'] = 463, __size = 2}
	},
	[1001] = {
		id = 1001,
		type = 1000,
		group = 10002,
		res = 'zhuchangjing/zjm_mnq2.skel',
		position = {['y'] = 1150, ['x'] = 690, __size = 2},
		zOrder = 2,
		touchSize = __data_t__touchSize[1001],
		-- {['height'] = 120, ['width'] = 120, __size = 2}
		action = false,
		randLib = 132
	},
	[1002] = {
		id = 1002,
		weight = 0,
		type = 1000,
		group = 10003,
		res = 'zhuchangjing/zjm_mnq3.skel',
		position = {['y'] = 707, ['x'] = 3881, __size = 2},
		zOrder = 2,
		touchSize = __data_t__touchSize[1002],
		-- {['height'] = 120, ['width'] = 120, __size = 2}
		action = false,
		randLib = 132
	},
	[1003] = {
		id = 1003,
		type = 1000,
		group = 10004,
		res = 'zhuchangjing/zjm_mnq3.skel',
		position = {['y'] = 1195, ['x'] = 1000, __size = 2},
		zOrder = 2,
		touchSize = {['height'] = 200, ['width'] = 100, __size = 2},
		action = false,
		randLib = 132
	},

	__size = 47,
	__default = {
		__index = {
			weight = 10,
			type = 1,
			group = 1,
			res = '',
			position = __data_t__position["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			zOrder = 10,
			scale = 2,
			action = true,
			randLib = 0,
			unfreezeAward = {__size = 0},
			shape_shifter = true,
			baibianRandLib = 0,
			chattext1 = '',
			chattext2 = '',
			chattext3 = '',
			offPos = __data_t__offPos["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			overture = false,
			activityIds = {},
			activityPosition = __data_t__activityPosition["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			activityScale = 2,
			active = true
		}
	}
}
return csv.city_sprites