--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[2] = {__size = 0}, 
	[4] = {32}, 
	[5] = {['y'] = -150, ['x'] = 0, __size = 2}, __size = 4}
local __data_t__offPos = {
	[1003] = __predefine_t__[5],
	[1002] = __predefine_t__[5],
	[1001] = __predefine_t__[5]
}
local __data_t__choices = {
	["default"] = __predefine_t__[1]
}
local __data_t__useRoleFigure = {
	[1003] = __predefine_t__[4],
	[1002] = __predefine_t__[4],
	[1001] = __predefine_t__[4]
}
local __data_t__battleEnter = {
	[11] = __predefine_t__[2],
	[21] = __predefine_t__[2],
	[31] = __predefine_t__[2],
	[1] = __predefine_t__[2],
	[2] = __predefine_t__[2],
	[1004] = __predefine_t__[2],
	[1003] = __predefine_t__[2],
	[1002] = __predefine_t__[2],
	[1001] = __predefine_t__[2]
}
local __data_t__tagName = {
	["default"] = __predefine_t__[1]
}

csv['new_guide_local'] = {
	[1] = {
		id = 1,
		stage = 1,
		specialName = 'summerChallenge101',
		showType = 2,
		talkContent = 'พิคาจู! พิคาจู!',
		battleEnter = __data_t__battleEnter[1]
		-- {__size = 0}
	},
	[2] = {
		id = 2,
		stage = 1,
		service = 1,
		showType = 2,
		talkContent = 'พิคาจู, งั้นเรามาต่อสู้เคียงข้างกันเถอะ!',
		battleEnter = __data_t__battleEnter[2],
		-- {__size = 0}
		choices = {11, 21, 31}
	},
	[11] = {
		id = 11,
		stage = 1,
		showType = 2,
		talkContent = 'แอปเปิ้ลทอง 2',
		battleEnter = __data_t__battleEnter[11]
		-- {__size = 0}
	},
	[21] = {
		id = 21,
		stage = 1,
		showType = 2,
		talkContent = 'แอปเปิ้ลเงิน 2',
		battleEnter = __data_t__battleEnter[21]
		-- {__size = 0}
	},
	[31] = {
		id = 31,
		stage = 1,
		showType = 2,
		talkContent = 'แอปเปิ้ลเน่า 2',
		battleEnter = __data_t__battleEnter[31]
		-- {__size = 0}
	},
	[1001] = {
		id = 1001,
		stage = 2,
		specialName = 'summerChallenge1001',
		showType = 2,
		useRoleFigure = __data_t__useRoleFigure[1001],
		-- {32}
		offPos = __data_t__offPos[1001],
		-- {['y'] = -150, ['x'] = 0, __size = 2}
		roleName = 'Dr.Oak',
		talkContent = 'ยินดีต้อนรับทุกท่านมาร่วมกิจกรรมการผจญภัยขุมทรัพย์เทศกาลฤดูร้อนครั้งนี้ ตอนนี้เรากำลังอยู่ในหมู่เกาะที่สวยงาม ซึ่งเป็นที่อยู่อาศัยของมิไนอัส ในเวลาต่อไปทุกท่านจะได้ร่วมค้นหาตำนานของมิไนอัสในเกมที่เต็มไปด้วยความตื่นเต้นและท้าทาย เราจะไปยังวิหารในทะเลสาบโบราณและลึกลับเพื่อสำรวจความลับของมิไนอัส...',
		battleEnter = __data_t__battleEnter[1001]
		-- {__size = 0}
	},
	[1002] = {
		id = 1002,
		stage = 2,
		showType = 2,
		useRoleFigure = __data_t__useRoleFigure[1002],
		-- {32}
		offPos = __data_t__offPos[1002],
		-- {['y'] = -150, ['x'] = 0, __size = 2}
		roleName = 'Dr.Oak',
		talkContent = 'ตามตำนาน มิไนอัสอาศัยอยู่ในวิหารที่ตั้งอยู่กลางทะเลสาบของหมู่เกาะที่สวยงาม การเข้าไปในวิหารนั้นมีเบาะแสซ่อนอยู่ในด่านเกมสุดตื่นเต้นของเรา ซึ่งในที่สุดจะมีทีมเดียวที่จะสามารถคว้ารางวัลการเข้าไปในวิหารทะเลสาบได้ ทั้งมิไนอัสและขุมทรัพย์สุดท้ายของกิจกรรมรอคุณอยู่ที่นั่น!',
		battleEnter = __data_t__battleEnter[1002]
		-- {__size = 0}
	},
	[1003] = {
		id = 1003,
		stage = 2,
		showType = 2,
		useRoleFigure = __data_t__useRoleFigure[1003],
		-- {32}
		offPos = __data_t__offPos[1003],
		-- {['y'] = -150, ['x'] = 0, __size = 2}
		roleName = 'Dr.Oak',
		talkContent = 'ทุกทีมจะได้รับคู่มือการผจญภัยที่มีแผนที่ของพื้นที่กิจกรรมและรายละเอียดของกิจกรรมทั้งหมด...',
		battleEnter = __data_t__battleEnter[1003]
		-- {__size = 0}
	},
	[1004] = {
		id = 1004,
		stage = 2,
		service = 1,
		showType = 2,
		force = 2,
		useRoleFigure = {0},
		talkContent = 'ฉันไม่สามารถรอได้แล้ว รีบเริ่มกันเถอะ!',
		battleEnter = __data_t__battleEnter[1004]
		-- {__size = 0}
	},

	__size = 9,
	__default = {
		__index = {
			startLevel = 1,
			startGate = 0,
			order = 0,
			service = 0,
			showAward = false,
			gotoScene = 0,
			showType = 1,
			force = 1,
			roleName = '',
			talkContent = '',
			tagName = __data_t__tagName["default"]	--[[ {}]],
			animateAngle = 0,
			anyPosCancel = false,
			choices = __data_t__choices["default"]	--[[ {}]]
		}
	}
}
return csv.new_guide_local