--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[3] = {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}, 
	[4] = {'cn', 'kr', 'en', 'tw'}, 
	[5] = {'cn'}, 
	[6] = {'cn', 'kr'}, 
	[7] = {'cn', 'kr', 'tw', 'en'}, __size = 5}
local __data_t__servers = {
	[216] = __predefine_t__[3],
	[217] = __predefine_t__[3],
	[214] = __predefine_t__[3],
	[215] = __predefine_t__[3],
	[212] = __predefine_t__[3],
	[213] = __predefine_t__[3],
	[210] = __predefine_t__[3],
	[211] = __predefine_t__[3],
	[218] = __predefine_t__[3],
	[219] = __predefine_t__[3],
	[1] = __predefine_t__[3],
	[344] = __predefine_t__[3],
	[345] = __predefine_t__[3],
	[346] = __predefine_t__[3],
	[347] = __predefine_t__[3],
	[4] = __predefine_t__[3],
	[343] = __predefine_t__[3],
	[8] = __predefine_t__[3],
	[348] = __predefine_t__[3],
	[349] = __predefine_t__[3],
	[368] = __predefine_t__[3],
	[379] = __predefine_t__[3],
	[378] = __predefine_t__[3],
	[371] = __predefine_t__[3],
	[370] = __predefine_t__[3],
	[373] = __predefine_t__[3],
	[372] = __predefine_t__[3],
	[375] = __predefine_t__[3],
	[374] = __predefine_t__[3],
	[377] = __predefine_t__[3],
	[376] = __predefine_t__[3],
	[319] = __predefine_t__[3],
	[318] = __predefine_t__[3],
	[313] = __predefine_t__[3],
	[312] = __predefine_t__[3],
	[311] = __predefine_t__[3],
	[310] = __predefine_t__[3],
	[317] = __predefine_t__[3],
	[316] = __predefine_t__[3],
	[315] = __predefine_t__[3],
	[314] = __predefine_t__[3],
	[114] = __predefine_t__[3],
	[110] = __predefine_t__[3],
	[113] = __predefine_t__[3],
	[3] = __predefine_t__[3],
	[7] = __predefine_t__[3],
	[369] = __predefine_t__[3],
	[366] = __predefine_t__[3],
	[364] = __predefine_t__[3],
	[365] = __predefine_t__[3],
	[362] = __predefine_t__[3],
	[360] = __predefine_t__[3],
	[361] = __predefine_t__[3],
	[308] = __predefine_t__[3],
	[309] = __predefine_t__[3],
	[300] = __predefine_t__[3],
	[301] = __predefine_t__[3],
	[302] = __predefine_t__[3],
	[303] = __predefine_t__[3],
	[304] = __predefine_t__[3],
	[305] = __predefine_t__[3],
	[306] = __predefine_t__[3],
	[307] = __predefine_t__[3],
	[380] = __predefine_t__[3],
	[108] = __predefine_t__[3],
	[102] = __predefine_t__[3],
	[103] = __predefine_t__[3],
	[100] = __predefine_t__[3],
	[101] = __predefine_t__[3],
	[106] = __predefine_t__[3],
	[107] = __predefine_t__[3],
	[104] = __predefine_t__[3],
	[105] = __predefine_t__[3],
	[339] = __predefine_t__[3],
	[334] = __predefine_t__[3],
	[337] = __predefine_t__[3],
	[336] = __predefine_t__[3],
	[331] = __predefine_t__[3],
	[330] = __predefine_t__[3],
	[333] = __predefine_t__[3],
	[332] = __predefine_t__[3],
	[2] = __predefine_t__[3],
	[6] = __predefine_t__[3],
	[341] = __predefine_t__[3],
	[229] = __predefine_t__[3],
	[228] = __predefine_t__[3],
	[227] = __predefine_t__[3],
	[226] = __predefine_t__[3],
	[225] = __predefine_t__[3],
	[224] = __predefine_t__[3],
	[223] = __predefine_t__[3],
	[222] = __predefine_t__[3],
	[221] = __predefine_t__[3],
	[220] = __predefine_t__[3],
	[11] = __predefine_t__[3],
	[10] = __predefine_t__[3],
	[322] = __predefine_t__[3],
	[323] = __predefine_t__[3],
	[320] = __predefine_t__[3],
	[321] = __predefine_t__[3],
	[5] = __predefine_t__[3],
	[327] = __predefine_t__[3],
	[324] = __predefine_t__[3],
	[325] = __predefine_t__[3],
	[9] = __predefine_t__[3],
	[328] = __predefine_t__[3],
	[329] = __predefine_t__[3],
	[201] = __predefine_t__[3],
	[200] = __predefine_t__[3],
	[203] = __predefine_t__[3],
	[202] = __predefine_t__[3],
	[205] = __predefine_t__[3],
	[204] = __predefine_t__[3],
	[207] = __predefine_t__[3],
	[206] = __predefine_t__[3],
	[209] = __predefine_t__[3],
	[208] = __predefine_t__[3],
	[357] = __predefine_t__[3],
	[356] = __predefine_t__[3],
	[355] = __predefine_t__[3],
	[354] = __predefine_t__[3],
	[353] = __predefine_t__[3],
	[352] = __predefine_t__[3],
	[351] = __predefine_t__[3],
	[350] = __predefine_t__[3],
	[326] = __predefine_t__[3],
	[359] = __predefine_t__[3],
	[358] = __predefine_t__[3]
}
local __data_t__languages = {
	[372] = __predefine_t__[5],
	[339] = __predefine_t__[7],
	[334] = __predefine_t__[4],
	[337] = __predefine_t__[7],
	[380] = __predefine_t__[5],
	[333] = __predefine_t__[4],
	[332] = __predefine_t__[4],
	[114] = __predefine_t__[5],
	[378] = __predefine_t__[5],
	[379] = __predefine_t__[5],
	[224] = __predefine_t__[6],
	[345] = __predefine_t__[4],
	[344] = __predefine_t__[4],
	[323] = __predefine_t__[4],
	[346] = __predefine_t__[4],
	[347] = __predefine_t__[4],
	[327] = __predefine_t__[7],
	[324] = __predefine_t__[4],
	[343] = __predefine_t__[4],
	[9] = __predefine_t__[5],
	[8] = __predefine_t__[4],
	[364] = __predefine_t__[5],
	[329] = __predefine_t__[5],
	[348] = __predefine_t__[6],
	[349] = __predefine_t__[4],
	[360] = __predefine_t__[5],
	[341] = __predefine_t__[7],
	[369] = __predefine_t__[5],
	[376] = __predefine_t__[5],
	[366] = __predefine_t__[5],
	[229] = __predefine_t__[5],
	[228] = __predefine_t__[4],
	[227] = __predefine_t__[5],
	[226] = __predefine_t__[5],
	[225] = __predefine_t__[4],
	[314] = __predefine_t__[7],
	[222] = __predefine_t__[4],
	[221] = __predefine_t__[4],
	[220] = __predefine_t__[4],
	[11] = __predefine_t__[5],
	[10] = __predefine_t__[5],
	[377] = __predefine_t__[5],
	[365] = __predefine_t__[5],
	[362] = __predefine_t__[5],
	[357] = __predefine_t__[5],
	[356] = __predefine_t__[5],
	[355] = __predefine_t__[5],
	[354] = __predefine_t__[5],
	[353] = __predefine_t__[5],
	[352] = __predefine_t__[6],
	[351] = __predefine_t__[4],
	[371] = __predefine_t__[6],
	[370] = __predefine_t__[5],
	[373] = __predefine_t__[5],
	[361] = __predefine_t__[6],
	[375] = __predefine_t__[5],
	[374] = __predefine_t__[5],
	[359] = __predefine_t__[5],
	[358] = __predefine_t__[5]
}

csv['unlock'] = {
	[1] = {
		id = 1,
		name = 'การต่อสู้ในด่านอัตโนมัติ',
		feature = 'gateAuto',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		servers = __data_t__servers[1]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[2] = {
		id = 2,
		name = 'ความเร็ว 2 เท่าในด่าน',
		feature = 'gateSpeed2',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		servers = __data_t__servers[2]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[3] = {
		id = 3,
		name = 'หยุดพักในด่าน',
		feature = 'gatePause',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		servers = __data_t__servers[3]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[4] = {
		id = 4,
		name = 'ด่านยาก',
		feature = 'heroGate',
		desc = 'ซ่อน/แสดง',
		showLevel = 5,
		startLevel = 5,
		startGate = 10204,
		servers = __data_t__servers[4]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[5] = {
		id = 5,
		name = 'เร่งการใช้สกิลใหญ่',
		feature = 'ultraAcc',
		desc = 'ซ่อน/แสดง',
		showLevel = 12,
		startLevel = 20,
		servers = __data_t__servers[5]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[6] = {
		id = 6,
		name = 'ด่านฝันร้าย',
		feature = 'nightmareGate',
		desc = 'ซ่อน/แสดง',
		showLevel = 36,
		startLevel = 47,
		startGate = 20101,
		servers = __data_t__servers[6]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[7] = {
		id = 7,
		name = 'ความเร็ว 3 เท่าในด่าน',
		feature = 'gateSpeed3',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		showLevel = 15,
		startLevel = 20,
		startGate = 10102,
		servers = __data_t__servers[7]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[8] = {
		id = 8,
		name = 'สั่งล้างดันเจี้ยนอย่างรวดเร็ว',
		feature = 'quickSweep',
		desc = 'ซ่อน/แสดง',
		showLevel = 60,
		startLevel = 60,
		startGate = 10910,
		languages = __data_t__languages[8],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[8]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[9] = {
		id = 9,
		name = 'ข้ามการต่อสู้ของผู้เล่นใหม่',
		feature = 'skipNewbieBattle',
		showLevel = 50,
		startLevel = 50,
		languages = __data_t__languages[9],
		-- {'cn'}
		servers = __data_t__servers[9]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[10] = {
		id = 10,
		name = 'ข้ามการท้าทายองค์ประกอบ',
		feature = 'skipCloneBattle',
		desc = 'ซ่อน/แสดง',
		showLevel = 75,
		startLevel = 75,
		languages = __data_t__languages[10],
		-- {'cn'}
		servers = __data_t__servers[10]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[11] = {
		id = 11,
		name = 'สั่งล้างดันเจี้ยนของขวัญในด่านปัจจุบัน',
		feature = 'dailyGiftGate',
		desc = 'ซ่อน/แสดง',
		showLevel = 65,
		startLevel = 65,
		languages = __data_t__languages[11],
		-- {'cn'}
		servers = __data_t__servers[11]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[100] = {
		id = 100,
		name = 'ร้านค้าปกติ',
		feature = 'shop',
		desc = 'ล็อก',
		startLevel = 9,
		servers = __data_t__servers[100]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[101] = {
		id = 101,
		name = 'ร้านค้าอารีน่า',
		feature = 'arenaShop',
		desc = 'ซ่อน/แสดง',
		showLevel = 15,
		startLevel = 15,
		servers = __data_t__servers[101]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[102] = {
		id = 102,
		name = 'ร้านค้ากิลด์',
		feature = 'unionShop',
		desc = 'ซ่อน/แสดง',
		showLevel = 20,
		startLevel = 20,
		servers = __data_t__servers[102]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[103] = {
		id = 103,
		name = 'ร้านค้าชิ้นส่วน',
		feature = 'fragmentShop',
		desc = 'ซ่อน/แสดง',
		showLevel = 26,
		startLevel = 26,
		servers = __data_t__servers[103]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[104] = {
		id = 104,
		name = 'ประเภทของร้านค้า',
		feature = 'shopClassity',
		desc = 'ซ่อน/แสดง',
		showLevel = 55,
		startLevel = 55,
		servers = __data_t__servers[104]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[105] = {
		id = 105,
		name = 'การสุ่มอุปกรณ์',
		feature = 'drawEquip',
		desc = 'ซ่อน/แสดง',
		showLevel = 22,
		startLevel = 26,
		servers = __data_t__servers[105]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[106] = {
		id = 106,
		name = 'ฟังก์ชันกล่องสะสมการสุ่มแบบจำกัด',
		feature = 'timeLimitUpDrawSumBox',
		desc = 'ซ่อน/แสดง',
		showLevel = 6,
		startLevel = 6,
		servers = __data_t__servers[106]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[107] = {
		id = 107,
		name = 'ฟังก์ชันกล่องสะสมการสุ่ม',
		feature = 'drawSumBox',
		desc = 'ซ่อน/แสดง',
		showLevel = 6,
		startLevel = 6,
		servers = __data_t__servers[107]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[108] = {
		id = 108,
		name = 'การแจ้งเตือนการสุ่มเพชร',
		feature = 'diamondDrawTips',
		desc = 'ล็อก',
		startLevel = 40,
		servers = __data_t__servers[108]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[110] = {
		id = 110,
		name = 'การแจ้งเตือนการสุ่มแบบจำกัด',
		feature = 'diamondUpDrawTips',
		startLevel = 40,
		servers = __data_t__servers[110]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[113] = {
		id = 113,
		name = 'การแจ้งเตือนการสุ่มสัญลักษณ์',
		feature = 'gemDrawTips',
		showLevel = 66,
		startLevel = 66,
		servers = __data_t__servers[113]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[114] = {
		id = 114,
		name = 'สุ่มการสุ่มอุปกรณ์แบบจำกัด',
		feature = 'groupDrawCardUp',
		showLevel = 6,
		startLevel = 6,
		languages = __data_t__languages[114],
		-- {'cn'}
		servers = __data_t__servers[114]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[200] = {
		id = 200,
		name = 'รูปลักษณ์ส่วนบุคคล',
		feature = 'roleFigure',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		startLevel = 1,
		servers = __data_t__servers[200]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[201] = {
		id = 201,
		name = 'ตำแหน่ง',
		feature = 'title',
		desc = 'ล็อก',
		startLevel = 1,
		servers = __data_t__servers[201]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[202] = {
		id = 202,
		name = 'การล็อกการใช้สกิล',
		feature = 'cardUnlock',
		desc = 'ซ่อน/แสดง; เซิร์ฟเวอร์ไม่จำกัด',
		showLevel = 1,
		startLevel = 1,
		servers = __data_t__servers[202]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[203] = {
		id = 203,
		name = 'อุปกรณ์',
		feature = 'equip',
		desc = 'ล็อก',
		showLevel = 1,
		startLevel = 5,
		startGate = 10202,
		servers = __data_t__servers[203]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[204] = {
		id = 204,
		name = 'การอัพเกรดดาวของอุปกรณ์',
		feature = 'equipStarAdd',
		desc = 'ล็อก',
		showLevel = 22,
		startLevel = 26,
		servers = __data_t__servers[204]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[205] = {
		id = 205,
		name = 'การปลุกพลังอุปกรณ์',
		feature = 'equipAwak',
		desc = 'ล็อก',
		showLevel = 22,
		startLevel = 26,
		servers = __data_t__servers[205]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[206] = {
		id = 206,
		name = 'ไอเทมที่พกพา',
		feature = 'heldItem',
		desc = 'ซ่อน/แสดง',
		showLevel = 1,
		startLevel = 11,
		servers = __data_t__servers[206]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[207] = {
		id = 207,
		name = 'การปรับค่าคุณภาพส่วนบุคคล',
		feature = 'cardNValueRecast',
		desc = 'ซ่อน/แสดง',
		showLevel = 6,
		startLevel = 6,
		servers = __data_t__servers[207]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[208] = {
		id = 208,
		name = 'ความชอบของสปีริต',
		feature = 'cardLike',
		desc = 'ซ่อน/แสดง',
		startLevel = 25,
		servers = __data_t__servers[208]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[209] = {
		id = 209,
		name = 'การสืบทอดสปีริต',
		feature = 'cardSwap',
		desc = 'ซ่อน/แสดง',
		startLevel = 15,
		servers = __data_t__servers[209]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[210] = {
		id = 210,
		name = 'ค่าความพยายาม',
		feature = 'cardEffort',
		desc = 'ซ่อน/แสดง',
		showLevel = 15,
		startLevel = 24,
		servers = __data_t__servers[210]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[211] = {
		id = 211,
		name = 'การฝึกฝนค่าความพยายาม 10 ครั้ง',
		feature = 'effort10',
		desc = 'ซ่อน/แสดง; เซิร์ฟเวอร์ไม่จำกัด',
		showLevel = 24,
		startLevel = 24,
		servers = __data_t__servers[211]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[212] = {
		id = 212,
		name = 'การเกิดใหม่ของสปีริต',
		feature = 'cardReborn',
		desc = 'ซ่อน/แสดง',
		startLevel = 23,
		servers = __data_t__servers[212]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[213] = {
		id = 213,
		name = 'อัพเกรดอัตโนมัติ',
		feature = 'onekeyLevelup',
		desc = 'ซ่อน/แสดง; เซิร์ฟเวอร์ไม่จำกัด',
		showLevel = 28,
		startLevel = 28,
		servers = __data_t__servers[213]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[214] = {
		id = 214,
		name = 'ศักยภาพของสปีริต',
		feature = 'cardAbility',
		desc = 'ซ่อน/แสดง',
		showLevel = 40,
		startLevel = 45,
		servers = __data_t__servers[214]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[215] = {
		id = 215,
		name = 'อัพเกรดอย่างรวดเร็ว',
		feature = 'fastUpgrade',
		desc = 'ซ่อน/แสดง',
		showLevel = 35,
		startLevel = 35,
		servers = __data_t__servers[215]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[216] = {
		id = 216,
		name = 'เสริมพลังอย่างรวดเร็ว',
		feature = 'fastStrengthen',
		desc = 'ซ่อน/แสดง',
		showLevel = 40,
		startLevel = 40,
		servers = __data_t__servers[216]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[217] = {
		id = 217,
		name = 'แนะนำทีม',
		feature = 'battleRecommend',
		desc = 'ซ่อน/แสดง',
		showLevel = 20,
		startLevel = 20,
		servers = __data_t__servers[217]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[218] = {
		id = 218,
		name = 'ผลกระทบทักษะตามระดับดาว',
		feature = 'starEffect',
		desc = 'ซ่อน/แสดง',
		showLevel = 1,
		startLevel = 1,
		servers = __data_t__servers[218]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[219] = {
		id = 219,
		name = 'การฝึกฝนขั้นสูง',
		feature = 'extremityProperty',
		showLevel = 1,
		startLevel = 1,
		servers = __data_t__servers[219]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[220] = {
		id = 220,
		name = 'สัญลักษณ์',
		feature = 'gem',
		showLevel = 60,
		startLevel = 66,
		languages = __data_t__languages[220],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[220]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[221] = {
		id = 221,
		name = 'การเสริมพลังสัญลักษณ์อัตโนมัติ',
		feature = 'gemOnekeyStrengthen',
		showLevel = 75,
		startLevel = 75,
		languages = __data_t__languages[221],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[221]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[222] = {
		id = 222,
		name = 'การวิวัฒนาการสูงสุด',
		feature = 'mega',
		desc = 'ล็อก',
		showLevel = 65,
		startLevel = 70,
		languages = __data_t__languages[222],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[222]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[223] = {
		id = 223,
		name = 'การสลับสาขาของสปีริต',
		feature = 'cardSwitchBranch',
		showLevel = 10,
		startLevel = 10,
		servers = __data_t__servers[223]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[224] = {
		id = 224,
		name = 'การแกะสลักอุปกรณ์',
		feature = 'equipSignet',
		showLevel = 70,
		startLevel = 75,
		languages = __data_t__languages[224],
		-- {'cn', 'kr'}
		servers = __data_t__servers[224]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[225] = {
		id = 225,
		name = 'ศักยภาพดาวของอุปกรณ์',
		feature = 'equipAbility',
		showLevel = 75,
		startLevel = 75,
		languages = __data_t__languages[225],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[225]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[226] = {
		id = 226,
		name = 'การปรับค่าความพยายามที่กำหนดเอง',
		feature = 'customEffort',
		showLevel = 75,
		startLevel = 75,
		languages = __data_t__languages[226],
		-- {'cn'}
		servers = __data_t__servers[226]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[227] = {
		id = 227,
		name = 'เสริมพลังศักยภาพอัตโนมัติ',
		feature = 'potentialOneKey',
		showLevel = 65,
		startLevel = 65,
		languages = __data_t__languages[227],
		-- {'cn'}
		servers = __data_t__servers[227]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[228] = {
		id = 228,
		name = 'ศักยภาพการปลุกพลังอุปกรณ์',
		feature = 'equipAwakeAbility',
		showLevel = 80,
		startLevel = 80,
		languages = __data_t__languages[228],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[228]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[229] = {
		id = 229,
		name = 'การแกะสลักอัตโนมัติ',
		feature = 'oneKeySignet',
		desc = 'ล็อก',
		showLevel = 75,
		startLevel = 78,
		languages = __data_t__languages[229],
		-- {'cn'}
		servers = __data_t__servers[229]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[300] = {
		id = 300,
		name = 'ของขวัญออนไลน์',
		feature = 'onlineGift',
		desc = 'ซ่อน/แสดง',
		showLevel = 6,
		startLevel = 6,
		servers = __data_t__servers[300]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[301] = {
		id = 301,
		name = 'สมุดภาพ',
		feature = 'handbook',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		startLevel = 10,
		servers = __data_t__servers[301]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[302] = {
		id = 302,
		name = 'ภารกิจประจำวัน',
		feature = 'dailyTask',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		startLevel = 12,
		servers = __data_t__servers[302]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[303] = {
		id = 303,
		name = 'ใบอนุญาตการผจญภัย',
		feature = 'trainer',
		desc = 'ล็อก',
		startLevel = 12,
		servers = __data_t__servers[303]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[304] = {
		id = 304,
		name = 'อารีน่า',
		feature = 'arena',
		desc = 'ล็อก',
		startLevel = 15,
		servers = __data_t__servers[304]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[305] = {
		id = 305,
		name = 'ดันเจี้ยนประจำวัน',
		feature = 'activityGate',
		desc = 'ล็อก',
		startLevel = 18,
		servers = __data_t__servers[305]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[306] = {
		id = 306,
		name = 'อันดับ',
		feature = 'rank',
		desc = 'ล็อก',
		startLevel = 18,
		servers = __data_t__servers[306]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[307] = {
		id = 307,
		name = 'อั่งเปากิลด์',
		feature = 'unionRedpacket',
		desc = 'ล็อก; เซิร์ฟเวอร์ไม่จำกัด',
		startLevel = 20,
		servers = __data_t__servers[307]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[308] = {
		id = 308,
		name = 'กิลด์',
		feature = 'union',
		desc = 'ล็อก',
		startLevel = 20,
		servers = __data_t__servers[308]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[309] = {
		id = 309,
		name = 'เส้นทางการผจญภัย',
		feature = 'endlessTower',
		desc = 'ซ่อน/แสดง',
		startLevel = 24,
		servers = __data_t__servers[309]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[310] = {
		id = 310,
		name = 'พรสวรรค์',
		feature = 'talent',
		desc = 'ซ่อน/แสดง; เซิร์ฟเวอร์ไม่จำกัด',
		startLevel = 27,
		servers = __data_t__servers[310]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[311] = {
		id = 311,
		name = 'ภารกิจการส่ง',
		feature = 'dispatchTask',
		desc = 'ซ่อน/แสดง',
		startLevel = 30,
		servers = __data_t__servers[311]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[312] = {
		id = 312,
		name = 'เครื่องมือผจญภัย',
		feature = 'explorer',
		startLevel = 33,
		servers = __data_t__servers[312]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[313] = {
		id = 313,
		name = 'การแลกเปลี่ยนประสบการณ์ส่วนเกิน',
		feature = 'overflowExpExchange',
		desc = 'ซ่อน/แสดง',
		startLevel = 99,
		servers = __data_t__servers[313]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[314] = {
		id = 314,
		name = 'VIP 18',
		feature = 'vipLevel18',
		desc = 'ซ่อน/แสดง',
		startLevel = 1,
		languages = __data_t__languages[314],
		-- {'cn', 'kr', 'tw', 'en'}
		servers = __data_t__servers[314]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[315] = {
		id = 315,
		name = 'การแข่งขันควอตซ์',
		feature = 'craft',
		desc = 'ล็อก',
		startLevel = 40,
		servers = __data_t__servers[315]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[316] = {
		id = 316,
		name = 'การแชร์การ์ด',
		feature = 'cardShare',
		desc = 'ซ่อน/แสดง',
		startLevel = 10,
		servers = __data_t__servers[316]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[317] = {
		id = 317,
		name = 'การแชร์รายงานการต่อสู้',
		feature = 'battleShare',
		desc = 'ซ่อน/แสดง',
		startLevel = 10,
		servers = __data_t__servers[317]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[318] = {
		id = 318,
		name = 'สวนอีเธอร์',
		feature = 'randomTower',
		desc = 'ล็อก',
		startLevel = 33,
		servers = __data_t__servers[318]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[319] = {
		id = 319,
		name = 'การท้าทายองค์ประกอบ',
		feature = 'cloneBattle',
		desc = 'ล็อก',
		startLevel = 32,
		servers = __data_t__servers[319]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[320] = {
		id = 320,
		name = 'การจับจำกัดเวลา',
		feature = 'limitCapture',
		desc = 'ล็อก',
		showLevel = 33,
		startLevel = 36,
		servers = __data_t__servers[320]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[321] = {
		id = 321,
		name = 'ระบบความสำเร็จ',
		feature = 'achievement',
		desc = 'ล็อก',
		showLevel = 45,
		startLevel = 50,
		servers = __data_t__servers[321]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[322] = {
		id = 322,
		name = 'การจับในแผนที่',
		feature = 'gateCapture',
		desc = 'ซ่อน/แสดง',
		startLevel = 20,
		servers = __data_t__servers[322]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[323] = {
		id = 323,
		name = 'การแข่งขันควอตซ์ข้ามเซิร์ฟเวอร์',
		feature = 'crossCraft',
		desc = 'ล็อก',
		startLevel = 50,
		languages = __data_t__languages[323],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[323]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[324] = {
		id = 324,
		name = 'สงครามกิลด์',
		feature = 'unionFight',
		desc = 'ล็อก',
		startLevel = 40,
		languages = __data_t__languages[324],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[324]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[325] = {
		id = 325,
		name = 'แชทโลก',
		feature = 'worldChat',
		desc = 'ล็อก',
		startLevel = 50,
		startVip = 19,
		servers = __data_t__servers[325]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[326] = {
		id = 326,
		name = 'แชทส่วนตัว',
		feature = 'roleChat',
		desc = 'ล็อก',
		startLevel = 70,
		startVip = 19,
		servers = __data_t__servers[326]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[327] = {
		id = 327,
		name = 'การเข้าถึงระดับสูงในอีเธอร์',
		feature = 'randomTowerJump',
		desc = 'ล็อก',
		showLevel = 70,
		startLevel = 70,
		languages = __data_t__languages[327],
		-- {'cn', 'kr', 'tw', 'en'}
		servers = __data_t__servers[327]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[328] = {
		id = 328,
		name = 'อีเมลกิลด์',
		feature = 'unionMail',
		desc = 'ล็อก',
		startLevel = 25,
		servers = __data_t__servers[328]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[329] = {
		id = 329,
		name = 'คู่มือไอเทม',
		feature = 'propHandbook',
		desc = 'ซ่อน/แสดง',
		startLevel = 10,
		languages = __data_t__languages[329],
		-- {'cn'}
		servers = __data_t__servers[329]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[330] = {
		id = 330,
		name = 'การทำลายอารีน่าห้าครั้ง',
		feature = 'pvpPass',
		desc = 'ซ่อน/แสดง',
		showLevel = 65,
		startLevel = 65,
		servers = __data_t__servers[330]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[331] = {
		id = 331,
		name = 'การท้าทายดันเจี้ยนกิลด์สามครั้ง',
		feature = 'uinonGateThreeTimes',
		desc = 'ซ่อน/แสดง',
		showLevel = 60,
		startLevel = 60,
		servers = __data_t__servers[331]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[332] = {
		id = 332,
		name = 'อารีน่าข้ามเซิร์ฟเวอร์',
		feature = 'crossArena',
		desc = 'ล็อก',
		startLevel = 58,
		languages = __data_t__languages[332],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[332]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[333] = {
		id = 333,
		name = 'การต่อสู้ในอารีน่าข้ามเซิร์ฟเวอร์ห้าครั้ง',
		feature = 'crossArenaPass',
		desc = 'ซ่อน/แสดง',
		showLevel = 65,
		startLevel = 65,
		languages = __data_t__languages[333],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[333]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[334] = {
		id = 334,
		name = 'คู่มือการต่อสู้',
		feature = 'battleManuals',
		desc = 'ซ่อน/แสดง',
		showLevel = 1,
		startLevel = 15,
		languages = __data_t__languages[334],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[334]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[336] = {
		id = 336,
		name = 'VIP ผู้มีเกียรติ',
		feature = 'vipDistinguished',
		startLevel = 1,
		languages = {'cn', 'tw', 'kr', 'en'},
		servers = __data_t__servers[336]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[337] = {
		id = 337,
		name = 'การตกปลา',
		feature = 'fishing',
		startLevel = 65,
		languages = __data_t__languages[337],
		-- {'cn', 'kr', 'tw', 'en'}
		servers = __data_t__servers[337]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[339] = {
		id = 339,
		name = 'ตกปลาทันที',
		feature = 'autoFish',
		desc = 'ไม่สามารถคลิกได้',
		startLevel = 68,
		languages = __data_t__languages[339],
		-- {'cn', 'kr', 'tw', 'en'}
		servers = __data_t__servers[339]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[341] = {
		id = 341,
		name = 'อารีน่าการต่อสู้',
		feature = 'onlineFight',
		showLevel = 1,
		startLevel = 1,
		languages = __data_t__languages[341],
		-- {'cn', 'kr', 'tw', 'en'}
		servers = __data_t__servers[341]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[343] = {
		id = 343,
		name = 'ความคิดเห็นสปีริต',
		feature = 'cardComment',
		desc = 'ซ่อน/แสดง',
		showLevel = 35,
		startLevel = 35,
		languages = __data_t__languages[343],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[343]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[344] = {
		id = 344,
		name = 'การโพสต์ความคิดเห็นสปีริต',
		feature = 'cardPostComment',
		desc = 'ซ่อน/แสดง',
		showLevel = 50,
		startLevel = 50,
		languages = __data_t__languages[344],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[344]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[345] = {
		id = 345,
		name = 'ระดับโลก',
		feature = 'worldLevel',
		showLevel = 50,
		startLevel = 50,
		languages = __data_t__languages[345],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[345]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[346] = {
		id = 346,
		name = 'การท้าทายในยิม',
		feature = 'gym',
		startLevel = 68,
		languages = __data_t__languages[346],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[346]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[347] = {
		id = 347,
		name = 'เข็มขัด',
		feature = 'badge',
		showLevel = 65,
		startLevel = 68,
		languages = __data_t__languages[347],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[347]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[348] = {
		id = 348,
		name = 'ฟังก์ชันการเตะผู้เล่นออกจากการท้าทายองค์ประกอบ',
		feature = 'cloneBattleKick',
		desc = 'ล็อกไม่เปิดให้ใช้งาน',
		startLevel = 1,
		languages = __data_t__languages[348],
		-- {'cn', 'kr'}
		servers = __data_t__servers[348]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[349] = {
		id = 349,
		name = 'การรีเซ็ทพรสวรรค์เดี่ยว',
		feature = 'singleTalentReset',
		showLevel = 60,
		startLevel = 65,
		languages = __data_t__languages[349],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[349]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[350] = {
		id = 350,
		name = 'ทีมที่ตั้งไว้ล่วงหน้า',
		feature = 'readyTeam',
		showLevel = 35,
		startLevel = 40,
		languages = {'cn', 'tw'},
		servers = __data_t__servers[350]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[351] = {
		id = 351,
		name = 'สกิน',
		feature = 'skin',
		showLevel = 1,
		startLevel = 1,
		languages = __data_t__languages[351],
		-- {'cn', 'kr', 'en', 'tw'}
		servers = __data_t__servers[351]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[352] = {
		id = 352,
		name = 'ถนนการค้าข้ามเซิร์ฟเวอร์',
		feature = 'crossMine',
		desc = 'ล็อก',
		startLevel = 55,
		languages = __data_t__languages[352],
		-- {'cn', 'kr'}
		servers = __data_t__servers[352]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[353] = {
		id = 353,
		name = 'คำถามสปีริต',
		feature = 'unionQA',
		desc = 'ไม่สามารถคลิกได้',
		startLevel = 40,
		languages = __data_t__languages[353],
		-- {'cn'}
		servers = __data_t__servers[353]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[354] = {
		id = 354,
		name = 'ผู้ช่วยประจำวัน',
		feature = 'dailyAssistant',
		desc = 'ซ่อน/แสดง',
		showLevel = 80,
		startLevel = 80,
		languages = __data_t__languages[354],
		-- {'cn'}
		servers = __data_t__servers[354]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[355] = {
		id = 355,
		name = 'การจุดไฟเข็มขัดอย่างรวดเร็ว',
		feature = 'badgeOneKey',
		desc = 'ล็อก; เซิร์ฟเวอร์ก็จำกัด',
		showLevel = 72,
		startLevel = 75,
		languages = __data_t__languages[355],
		-- {'cn'}
		servers = __data_t__servers[355]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[356] = {
		id = 356,
		name = 'การแจ้งเตือนการป้องกันการฉ้อโกง',
		feature = 'preventFraud',
		desc = 'ซ่อน/แสดง',
		startLevel = 1,
		languages = __data_t__languages[356],
		-- {'cn'}
		servers = __data_t__servers[356]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[357] = {
		id = 357,
		name = 'การตื่นขึ้น Z',
		feature = 'zawake',
		showLevel = 78,
		startLevel = 85,
		languages = __data_t__languages[357],
		-- {'cn'}
		servers = __data_t__servers[357]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[358] = {
		id = 358,
		name = 'เขตล่าสัตว์',
		feature = 'hunting',
		showLevel = 70,
		startLevel = 80,
		languages = __data_t__languages[358],
		-- {'cn'}
		servers = __data_t__servers[358]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[359] = {
		id = 359,
		name = 'เส้นทางการพัฒนา',
		feature = 'specialHunting',
		showLevel = 70,
		startLevel = 83,
		languages = __data_t__languages[359],
		-- {'cn'}
		servers = __data_t__servers[359]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[360] = {
		id = 360,
		name = 'ชิป',
		feature = 'chip',
		desc = 'ซ่อน/แสดง',
		showLevel = 75,
		startLevel = 80,
		languages = __data_t__languages[360],
		-- {'cn'}
		servers = __data_t__servers[360]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[361] = {
		id = 361,
		name = 'การแจ้งเตือนการเก็บชิ้นส่วนเต็มดาวในร้านค้า',
		feature = 'fragShopMaxStar',
		desc = 'ซ่อน/แสดง',
		showLevel = 6,
		startLevel = 6,
		languages = __data_t__languages[361],
		-- {'cn', 'kr'}
		servers = __data_t__servers[361]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[362] = {
		id = 362,
		name = 'แผนชิป',
		feature = 'chipPlan',
		desc = 'ซ่อน/แสดง',
		showLevel = 80,
		startLevel = 85,
		languages = __data_t__languages[362],
		-- {'cn'}
		servers = __data_t__servers[362]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[364] = {
		id = 364,
		name = 'การอัพเกรดดาวอุปกรณ์อย่างรวดเร็ว',
		feature = 'starPotentialFast',
		desc = 'ซ่อน/แสดง',
		showLevel = 80,
		startLevel = 80,
		languages = __data_t__languages[364],
		-- {'cn'}
		servers = __data_t__servers[364]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[365] = {
		id = 365,
		name = 'การปลุกพลังอุปกรณ์อย่างรวดเร็ว',
		feature = 'awakePotentialFast',
		desc = 'ซ่อน/แสดง',
		showLevel = 80,
		startLevel = 80,
		languages = __data_t__languages[365],
		-- {'cn'}
		servers = __data_t__servers[365]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[366] = {
		id = 366,
		name = 'การชำระชิป',
		feature = 'chipAdvance',
		desc = 'ซ่อน/แสดง',
		showLevel = 80,
		startLevel = 85,
		languages = __data_t__languages[366],
		-- {'cn'}
		servers = __data_t__servers[366]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[368] = {
		id = 368,
		name = 'การแจ้งเตือนการสุ่มชิป',
		feature = 'ChipDrawTips',
		desc = 'คำแนะนำ/คำอธิบาย',
		showLevel = 75,
		startLevel = 75,
		servers = __data_t__servers[368]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[369] = {
		id = 369,
		name = 'โหมดขีดจำกัดทอง',
		feature = 'goldLimitMode',
		showLevel = 99,
		startLevel = 99,
		languages = __data_t__languages[369],
		-- {'cn'}
		servers = __data_t__servers[369]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[370] = {
		id = 370,
		name = 'โหมดขีดจำกัดประสบการณ์',
		feature = 'expLimitMode',
		showLevel = 99,
		startLevel = 99,
		languages = __data_t__languages[370],
		-- {'cn'}
		servers = __data_t__servers[370]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[371] = {
		id = 371,
		name = 'การเลือกสปีริตในหน้าจอการสลายที่มีดาวเต็ม',
		feature = 'decompositionMaxStar',
		showLevel = 23,
		startLevel = 23,
		languages = __data_t__languages[371],
		-- {'cn', 'kr'}
		servers = __data_t__servers[371]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[372] = {
		id = 372,
		name = 'การบดในเขตล่าสัตว์ปกติ',
		feature = 'huntingPass',
		showLevel = 85,
		startLevel = 85,
		languages = __data_t__languages[372],
		-- {'cn'}
		servers = __data_t__servers[372]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[373] = {
		id = 373,
		name = 'การบดในเขตล่าสัตว์ขั้นสูง',
		feature = 'specialHuntingPass',
		showLevel = 90,
		startLevel = 90,
		languages = __data_t__languages[373],
		-- {'cn'}
		servers = __data_t__servers[373]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[374] = {
		id = 374,
		name = 'การท้าทายความกล้าหาญปกติ',
		feature = 'normalBraveChallenge',
		showLevel = 85,
		startLevel = 85,
		languages = __data_t__languages[374],
		-- {'cn'}
		servers = __data_t__servers[374]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[375] = {
		id = 375,
		name = 'บ้าน',
		feature = 'town',
		showLevel = 199,
		startLevel = 199,
		languages = __data_t__languages[375],
		-- {'cn'}
		servers = __data_t__servers[375]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[376] = {
		id = 376,
		name = 'อัปเกรดอาคารบ้านเสร็จทันที',
		feature = 'buildingFinishAtOnce',
		languages = __data_t__languages[376],
		-- {'cn'}
		servers = __data_t__servers[376]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[377] = {
		id = 377,
		name = 'ข้อมูลอีเมล',
		feature = 'mailInfo',
		startLevel = 1,
		languages = __data_t__languages[377],
		-- {'cn'}
		servers = __data_t__servers[377]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[378] = {
		id = 378,
		name = 'สงครามห้อง',
		feature = 'crossunionfight',
		startLevel = 50,
		languages = __data_t__languages[378],
		-- {'cn'}
		servers = __data_t__servers[378]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[379] = {
		id = 379,
		name = 'การสั่งล้างดันเจี้ยนยิม',
		feature = 'gymPass',
		showLevel = 999,
		startLevel = 999,
		languages = __data_t__languages[379],
		-- {'cn'}
		servers = __data_t__servers[379]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},
	[380] = {
		id = 380,
		name = 'การแข่งขันชิงแชมป์โลก',
		feature = 'crossSupremacy',
		desc = 'ล็อก',
		showLevel = 999,
		startLevel = 999,
		languages = __data_t__languages[380],
		-- {'cn'}
		servers = __data_t__servers[380]
		-- {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
	},

	__size = 128,
	__default = {
		__index = {
			name = '',
			feature = '',
			desc = '',
			showLevel = 0,
			startLevel = 0,
			startGate = 0,
			startVip = 0,
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr'},
			servers = {['cn'] = {1, 999999}, ['cn_qd'] = {1, 999999}, ['xy'] = {1, 999999}, ['en'] = {1, 999999}, ['kr'] = {1, 999999}, ['dev'] = {1, 999999}, ['tw'] = {1, 999999}, __size = 7}
		}
	}
}
return csv.unlock