--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['union_qa']['role_rank'] = {
	[1] = {
		id = 1,
		rankMax = 1,
		award = {['gold'] = 9000000, [521] = 80, ['coin3'] = 10000, __size = 3}
	},
	[2] = {
		id = 2,
		rankMax = 2,
		award = {['gold'] = 7500000, [521] = 75, ['coin3'] = 8000, __size = 3}
	},
	[3] = {
		id = 3,
		rankMax = 3,
		award = {['gold'] = 6750000, [521] = 70, ['coin3'] = 6500, __size = 3}
	},
	[4] = {
		id = 4,
		rankMax = 4,
		award = {['gold'] = 6000000, [521] = 65, ['coin3'] = 5500, __size = 3}
	},
	[5] = {
		id = 5,
		rankMax = 8,
		award = {['gold'] = 5250000, [521] = 60, ['coin3'] = 4500, __size = 3}
	},
	[6] = {
		id = 6,
		rankMax = 16,
		award = {['gold'] = 4500000, [521] = 55, ['coin3'] = 4000, __size = 3}
	},
	[7] = {
		id = 7,
		rankMax = 32,
		award = {['gold'] = 4200000, [521] = 50, ['coin3'] = 3600, __size = 3}
	},
	[8] = {
		id = 8,
		rankMax = 64,
		award = {['gold'] = 3900000, [521] = 45, ['coin3'] = 3200, __size = 3}
	},
	[9] = {
		id = 9,
		rankMax = 100,
		award = {['gold'] = 3600000, [521] = 40, ['coin3'] = 2900, __size = 3}
	},
	[10] = {
		id = 10,
		rankMax = 200,
		award = {['gold'] = 3300000, [521] = 35, ['coin3'] = 2600, __size = 3}
	},
	[11] = {
		id = 11,
		rankMax = 300,
		award = {['gold'] = 3000000, [521] = 30, ['coin3'] = 2400, __size = 3}
	},
	[12] = {
		id = 12,
		rankMax = 500,
		award = {['gold'] = 2700000, [521] = 25, ['coin3'] = 2200, __size = 3}
	},
	[13] = {
		id = 13,
		rankMax = 1000,
		award = {['gold'] = 2550000, [521] = 20, ['coin3'] = 2000, __size = 3}
	},
	[14] = {
		id = 14,
		rankMax = 2000,
		award = {['gold'] = 2400000, [521] = 15, ['coin3'] = 1800, __size = 3}
	},
	[15] = {
		id = 15,
		rankMax = 9999,
		award = {['gold'] = 2250000, [521] = 10, ['coin3'] = 1600, __size = 3}
	},

	__size = 15,
	__default = {
		__index = {
			award = {__size = 0},
			version = 0
		}
	}
}
return csv.cross.union_qa.role_rank