--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['fishing']['rank'] = {
	[1] = {
		id = 1,
		rankMax = 1,
		award = {['gold'] = 2000000, ['rmb'] = 200, [535] = 4000, __size = 3}
	},
	[2] = {
		id = 2,
		rankMax = 2,
		award = {['gold'] = 1800000, ['rmb'] = 180, [535] = 3600, __size = 3}
	},
	[3] = {
		id = 3,
		rankMax = 3,
		award = {['gold'] = 1600000, ['rmb'] = 160, [535] = 3200, __size = 3}
	},
	[4] = {
		id = 4,
		rankMax = 4,
		award = {['gold'] = 1400000, ['rmb'] = 140, [535] = 2800, __size = 3}
	},
	[5] = {
		id = 5,
		rankMax = 8,
		award = {['gold'] = 1200000, ['rmb'] = 120, [535] = 2400, __size = 3}
	},
	[6] = {
		id = 6,
		rankMax = 16,
		award = {['gold'] = 1100000, ['rmb'] = 110, [535] = 2200, __size = 3}
	},
	[7] = {
		id = 7,
		rankMax = 32,
		award = {['gold'] = 1000000, ['rmb'] = 100, [535] = 2000, __size = 3}
	},
	[8] = {
		id = 8,
		rankMax = 64,
		award = {['gold'] = 900000, ['rmb'] = 90, [535] = 1800, __size = 3}
	},
	[9] = {
		id = 9,
		rankMax = 100,
		award = {['gold'] = 800000, ['rmb'] = 80, [535] = 1600, __size = 3}
	},
	[10] = {
		id = 10,
		rankMax = 200,
		award = {['gold'] = 700000, ['rmb'] = 70, [535] = 1400, __size = 3}
	},
	[11] = {
		id = 11,
		rankMax = 300,
		award = {['gold'] = 600000, ['rmb'] = 60, [535] = 1200, __size = 3}
	},
	[12] = {
		id = 12,
		rankMax = 500,
		award = {['gold'] = 550000, ['rmb'] = 55, [535] = 1100, __size = 3}
	},
	[13] = {
		id = 13,
		rankMax = 1000,
		award = {['gold'] = 500000, ['rmb'] = 50, [535] = 1000, __size = 3}
	},
	[14] = {
		id = 14,
		rankMax = 2000,
		award = {['gold'] = 450000, ['rmb'] = 45, [535] = 900, __size = 3}
	},
	[15] = {
		id = 15,
		rankMax = 99999,
		award = {['gold'] = 400000, ['rmb'] = 40, [535] = 800, __size = 3}
	},

	__size = 15,
	__default = {
		__index = {
			award = {__size = 0}
		}
	}
}
return csv.cross.fishing.rank