--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, __size = 1}
local __data_t__skills = {
	["default"] = __predefine_t__[1]
}
local __data_t__rarityLimit = {
	["default"] = __predefine_t__[1]
}

csv['cross']['online_fight']['theme'] = {
	[1] = {
		id = 1,
		desc = 'เริ่มต้นด้วยค่าโกรธเต็ม',
		skills = {[78001] = 1, __size = 1}
	},
	[2] = {
		id = 2,
		desc = 'ใช้สกิลพื้นฐานได้ไม่จำกัด',
		skills = {[78002] = 1, __size = 1}
	},
	[3] = {
		id = 3,
		desc = 'ฟื้นฟูค่าโกรธอย่างรวดเร็ว',
		skills = {[78003] = 1, __size = 1}
	},
	[4] = {
		id = 4,
		desc = 'เพิ่มความได้เปรียบของการแพ้-ชนะตามธาตุ',
		skills = {[78004] = 1, __size = 1}
	},
	[5] = {
		id = 5,
		desc = 'จำกัดให้ใช้ได้เฉพาะการ์ดระดับ A หรือต่ำกว่า',
		rarityLimit = {[3] = 0, [4] = 0, __size = 2}
	},
	[6] = {
		id = 6,
		desc = 'จำกัดให้ใช้ได้เฉพาะการ์ดระดับ S หรือต่ำกว่า',
		rarityLimit = {[4] = 0, __size = 1}
	},
	[7] = {
		id = 7,
		desc = 'จำกัดให้ใช้การ์ดระดับ S ได้เพียง 2 ใบ',
		rarityLimit = {[3] = 2, __size = 1}
	},

	__size = 7,
	__default = {
		__index = {
			desc = '',
			skills = __data_t__skills["default"]	--[[ {__size = 0}]],
			rarityLimit = __data_t__rarityLimit["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.cross.online_fight.theme